unpackaged/main/default/objects/Additional_GL_Transaction__c/Additional_GL_Transaction__c.object-meta.xml
<CustomObject>
    <label>Additional GL Transaction</label>
    <nameField>
        <displayFormat>AGLT-{0000}</displayFormat>
        <label>Additional GL Transactions Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Additional GL Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Additional_GL_Transaction__c/fields/Intercompany_Transaction__c.field-meta.xml
<CustomField>
    <fullName>Intercompany_Transaction__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Intercompany Transaction</label>
    <referenceTo>cmbls__Intercompany_Transaction__c</referenceTo>
    <relationshipLabel>Additional GL Transactions</relationshipLabel>
    <relationshipName>Additional_GL_Transactions</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Additional_GL_Transaction__c/fields/Posted_to_Accounting__c.field-meta.xml
<CustomField>
    <fullName>Posted_to_Accounting__c</fullName>
    <label>Posted to Accounting</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Additional_GL_Transaction__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Paid Intercompany Transaction</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/cmbls__Disbursement__c/cmbls__Disbursement__c.object-meta.xml
<CustomObject>
    <label>Disbursement</label>
    <nameField>
        <displayFormat>D-{0000}</displayFormat>
        <label>Disbursement Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Disbursements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/cmbls__Disbursement__c/fields/cmbls__Status__c.field-meta.xml
<CustomField>
    <fullName>cmbls__Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>Pre-Pending</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Settled</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Sent Error</fullName>
            </value>
            <value>
                <fullName>Staging</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/cmbls__Disbursement__c/fields/GL_Date__c.field-meta.xml
<CustomField>
    <fullName>GL_Date__c</fullName>
    <formula>IF(ISPICKVAL(cmbls__ACH_Processor__c, 'Wire'), cmbls__Effective_Date__c, DATEVALUE(cmbls__Disbursement_Batch__r.cmbls__Batch_Date_Time__c))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>GL Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/cmbls__Fund__c/cmbls__Fund__c.object-meta.xml
<CustomObject>
    <label>Fund</label>
    <nameField>
        <label>Fund Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Funds</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/cmbls__Intercompany_Transaction__c/cmbls__Intercompany_Transaction__c.object-meta.xml
<CustomObject>
    <label>Intercompany Transaction</label>
    <nameField>
        <displayFormat>ICT-{0000000}</displayFormat>
        <label>Intercompany Transaction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Intercompany Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/cmbls__Intercompany_Transaction__c/fields/Date_Paid__c.field-meta.xml
<CustomField>
    <fullName>Date_Paid__c</fullName>
    <label>Date Paid</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/cmbls__Intercompany_Transaction__c/fields/Date_Paid_Formula__c.field-meta.xml
<CustomField>
    <fullName>Date_Paid_Formula__c</fullName>
    <formula>NULLVALUE(Date_Paid__c, DATEVALUE(CreatedDate))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Date Paid Formula</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/cmbls__Intercompany_Transaction__c/fields/GL_Date__c.field-meta.xml
<CustomField>
    <fullName>GL_Date__c</fullName>
    <formula>IF( NOT(ISBLANK(Payment__c)),
 Payment__r.cmbls__Effective_Date__c  ,
 cmbls__Disbursement__r.cmbls__Date_Sent__c 
)</formula>
    <label>GL Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/cmbls__Intercompany_Transaction__c/fields/LoanNumber__c.field-meta.xml
<CustomField>
    <fullName>LoanNumber__c</fullName>
    <formula>IF( NOT(ISBLANK(Payment__c)),
     Payment__r.LoanNumber__c ,
      cmbls__Disbursement__r.Loan_Number__c 
)</formula>
    <label>LoanNumber</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/cmbls__Intercompany_Transaction__c/fields/NF_to_NFAS2_Transfer__c.field-meta.xml
<CustomField>
    <fullName>NF_to_NFAS2_Transfer__c</fullName>
    <formula>OR(
            AND(
                cmbls__Loan_Transfer_Summary__r.cmbls__Previous_Fund__r.Name = 'National Funding',
                cmbls__Loan_Transfer_Summary__r.cmbls__New_Fund__r.Name = 'NFAS2'
            ),
            AND(
                cmbls__Loan_Transfer_Summary__r.cmbls__Previous_Fund__r.Name = 'NFAS2',
                cmbls__Loan_Transfer_Summary__r.cmbls__New_Fund__r.Name = 'National Funding'
            )
        )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>NF to NFAS2 Transfer</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/cmbls__Intercompany_Transaction__c/fields/Notes__c.field-meta.xml
<CustomField>
    <fullName>Notes__c</fullName>
    <label>Notes</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/cmbls__Intercompany_Transaction__c/fields/Payee_Cash_GL__c.field-meta.xml
<CustomField>
    <fullName>Payee_Cash_GL__c</fullName>
    <label>Payee Cash GL #</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/cmbls__Intercompany_Transaction__c/fields/Payee_Cash_GL_NFAS2__c.field-meta.xml
<CustomField>
    <fullName>Payee_Cash_GL_NFAS2__c</fullName>
    <label>Payee Cash GL # (NFAS2 Transfer)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/cmbls__Intercompany_Transaction__c/fields/Payee_Intercompany__c.field-meta.xml
<CustomField>
    <fullName>Payee_Intercompany__c</fullName>
    <label>Payee Intercompany</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/cmbls__Intercompany_Transaction__c/fields/Payer_Cash_GL__c.field-meta.xml
<CustomField>
    <fullName>Payer_Cash_GL__c</fullName>
    <label>Payer Cash GL #</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/cmbls__Intercompany_Transaction__c/fields/Payer_Cash_GL_NFAS2__c.field-meta.xml
<CustomField>
    <fullName>Payer_Cash_GL_NFAS2__c</fullName>
    <label>Payer Cash GL # (NFAS2 Transfer)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/cmbls__Intercompany_Transaction__c/fields/Payer_Intercompany__c.field-meta.xml
<CustomField>
    <fullName>Payer_Intercompany__c</fullName>
    <label>Payer Intercompany</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/cmbls__Intercompany_Transaction__c/fields/Payment__c.field-meta.xml
<CustomField>
    <fullName>Payment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment</label>
    <referenceTo>cmbls__Payment__c</referenceTo>
    <relationshipLabel>Intercompany Transactions</relationshipLabel>
    <relationshipName>Intercompany_Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/cmbls__Intercompany_Transaction__c/fields/Posted_To_Accounting__c.field-meta.xml
<CustomField>
    <fullName>Posted_To_Accounting__c</fullName>
    <label>Posted to Accounting</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/cmbls__Intercompany_Transaction__c/fields/Repayment__c.field-meta.xml
<CustomField>
    <fullName>Repayment__c</fullName>
    <formula>IF( NOT(ISBLANK(Payment__c)), 
    Payment__r.cmbls__Repayment__c ,  
    cmbls__Disbursement__r.cmbls__Repayment__c 
)</formula>
    <label>Repayment</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/cmbls__Loan_Transfer_Summary__c/cmbls__Loan_Transfer_Summary__c.object-meta.xml
<CustomObject>
    <label>Loan Transfer Summary</label>
    <nameField>
        <displayFormat>LT Summary-{0000}</displayFormat>
        <label>Loan Transfer Summary Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Loan Transfer Summaries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/classes/IntercompanyTransactionHandler.cls
/**
 * IntercompanyTransactionHandler class
 * @author CloudMyBiz (r)
 * @date 2/13/2023
 * @description Follows the One Trigger Per Object design pattern, which allows for the control of execution order and recursion.
 * Ideally, business logic should not be included in this class. Trigger handlers are used to control recursion and order of execution and should delegate other work to service classes.
 * @group Trigger Handlers
 */
public inherited sharing class IntercompanyTransactionHandler{

    @TestVisible private static final String PAID_STATUS = 'Paid';
    @TestVisible private static final String PAID_TYPE = 'Paid Intercompany Transaction';
    @TestVisible private static final String NATIONAL_FUNDING = 'National Funding';

    public static void onAfterInsertUpdate(cmbls__Intercompany_Transaction__c[] records, Map<Id, cmbls__Intercompany_Transaction__c> oldRecords){
        Additional_GL_Transaction__c[] recordsToCreate = new Additional_GL_Transaction__c[]{};
        Map<Id, Additional_GL_Transaction__c> existingRecords = getAdditionalGLTransactionsByIntercompanyTransactionId(records);
        Map<Id, cmbls__Intercompany_Transaction__c> inTransactionMap = new Map<Id, cmbls__Intercompany_Transaction__c>(records);
        List<cmbls__Intercompany_Transaction__c> interCompanyToClone = new List<cmbls__Intercompany_Transaction__c>();
        List<cmbls__Intercompany_Transaction__c> interCompanyToInsert = new List<cmbls__Intercompany_Transaction__c>();
        List<cmbls__Intercompany_Transaction__c> interCompanyToUpdate = new List<cmbls__Intercompany_Transaction__c>();

        for(cmbls__Intercompany_Transaction__c record : [
                SELECT Name, cmbls__Amount__c, cmbls__Disbursement__c, cmbls__Loan_Transfer_Summary__c, cmbls__Payee__c,
                        cmbls__Payer__c, cmbls__Status__c, Payee_Cash_GL__c, Payee_Intercompany__c, Payer_Cash_GL__c,
                        Payer_Intercompany__c, Posted_To_Accounting__c, Payment__c, Date_Paid__c, NF_to_NFAS2_Transfer__c,
                        Payee_Cash_GL_NFAS2__c, Payer_Cash_GL_NFAS2__c, Date_Paid_Formula__c, GL_Date__c, LoanNumber__c,
                        Repayment__c,Notes__c, cmbls__Payer__r.Name, cmbls__Payee__r.Name
                FROM cmbls__Intercompany_Transaction__c WHERE Id IN: inTransactionMap.keySet()]
        ){

            if(oldRecords != null && shouldCreateAdditionalGLRecord(record, oldRecords.get(record.Id), existingRecords)){
                recordsToCreate.add(new Additional_GL_Transaction__c(
                        Intercompany_Transaction__c = record.Id,
                        Type__c = PAID_TYPE
                ));
            }
            if(oldRecords == null && record.cmbls__Payer__c != null && record.cmbls__Payee__c != null &&
                    record.cmbls__Payee__r.Name != NATIONAL_FUNDING && record.cmbls__Payer__r.Name != NATIONAL_FUNDING){
                interCompanyToClone.add(record);
            }
        }
        if(!interCompanyToClone.isEmpty()){
            List<cmbls__Fund__c> fundNational = [SELECT Id FROM cmbls__Fund__c WHERE Name = : NATIONAL_FUNDING LIMIT 1];
            Map<Id, cmbls__Intercompany_Transaction__c> clonedInterCompany = new Map<Id, cmbls__Intercompany_Transaction__c>();
            if(!fundNational.isEmpty()){
                for(cmbls__Intercompany_Transaction__c record : interCompanyToClone){
                    cmbls__Intercompany_Transaction__c nationalInterCompany = record.clone(false);
                    nationalInterCompany.Notes__c = 'Cloned ' + record.Id + ' to have National Funding as the intermediary Entity';
                    nationalInterCompany.cmbls__Payer__c = fundNational[0].Id;
                    interCompanyToInsert.add(nationalInterCompany);
                    clonedInterCompany.put(record.Id, nationalInterCompany);
                }
                insert interCompanyToInsert;

                for(cmbls__Intercompany_Transaction__c record : interCompanyToClone){
                    record.cmbls__Payee__c = fundNational[0].Id;
                    record.Notes__c = 'Updated Payee to have National Funding as the intermediary Entity and created ' + clonedInterCompany.get(record.Id).Id;
                    interCompanyToUpdate.add(record);
                }
            }
        }

        insert recordsToCreate;
        update interCompanyToClone;

    }

    private static Map<Id, Additional_GL_Transaction__c> getAdditionalGLTransactionsByIntercompanyTransactionId(cmbls__Intercompany_Transaction__c[] records){
        Set<Id> parentIds = new Map<Id, cmbls__Intercompany_Transaction__c>(records).keySet();
        Map<Id, Additional_GL_Transaction__c> output = new Map<Id, Additional_GL_Transaction__c>();
        for(Additional_GL_Transaction__c item :[SELECT Id, Intercompany_Transaction__c FROM Additional_GL_Transaction__c WHERE Intercompany_Transaction__c IN :parentIds AND Type__c = :PAID_TYPE]){
            output.put(item.Intercompany_Transaction__c, item);
        }
        return output;
    }

    private static Boolean shouldCreateAdditionalGLRecord(cmbls__Intercompany_Transaction__c record, cmbls__Intercompany_Transaction__c oldRecord, Map<Id, Additional_GL_Transaction__c> existingRecords){
        return  !existingRecords.containsKey(record.Id) &&
                oldRecord.cmbls__Status__c != record.cmbls__Status__c &&
                record.cmbls__Status__c == PAID_STATUS;

    }
}