unpackaged/main/default/objects/ACH_Transaction_Log__c/ACH_Transaction_Log__c.object-meta.xml
<CustomObject>
    <label>ACH Transaction Log</label>
    <nameField>
        <displayFormat>LOG-{0000000}</displayFormat>
        <label>ACH Transaction Log Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ACH Transactions Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ACH_Transaction_Log__c/fields/Disbursement__c.field-meta.xml
<CustomField>
    <fullName>Disbursement__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Disbursement</label>
    <referenceTo>cmbls__Disbursement__c</referenceTo>
    <relationshipLabel>ACH Transactions Logs</relationshipLabel>
    <relationshipName>ACH_Transactions_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ACH_Transaction_Log__c/fields/Payment__c.field-meta.xml
<CustomField>
    <fullName>Payment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment</label>
    <referenceTo>cmbls__Payment__c</referenceTo>
    <relationshipLabel>ACH Transactions Logs</relationshipLabel>
    <relationshipName>ACH_Transactions_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ACH_Transaction_Log__c/fields/Pre_Pending_Update_Attempts__c.field-meta.xml
<CustomField>
    <fullName>Pre_Pending_Update_Attempts__c</fullName>
    <label>Pre Pending Update Attempts</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/ACH_Transaction_Log__c/fields/Response_Code__c.field-meta.xml
<CustomField>
    <fullName>Response_Code__c</fullName>
    <label>Response Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/cmbls__ACH_Batch__c/cmbls__ACH_Batch__c.object-meta.xml
<CustomObject>
    <label>ACH Batch</label>
    <nameField>
        <displayFormat>BATCH-{0000000}</displayFormat>
        <label>ACH Batch Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ACH Batches</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/cmbls__ACH_Batch__c/fields/cmbls__Status__c.field-meta.xml
<CustomField>
    <fullName>cmbls__Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Partial Success</fullName>
            </value>
            <value>
                <fullName>Resubmission</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/cmbls__Disbursement__c/cmbls__Disbursement__c.object-meta.xml
<CustomObject>
    <label>Disbursement</label>
    <nameField>
        <displayFormat>D-{0000}</displayFormat>
        <label>Disbursement Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Disbursements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/cmbls__Disbursement__c/fields/cmbls__ACH_Processor__c.field-meta.xml
<CustomField>
    <fullName>cmbls__ACH_Processor__c</fullName>
    <label>ACH Processor</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Wells Fargo - NF Funding</fullName>
            </value>
            <value>
                <fullName>Wells Fargo - QBF Funding</fullName>
            </value>
            <value>
                <fullName>NFAS2 Transfer</fullName>
            </value>
            <value>
                <fullName>NF Transfer (QB)</fullName>
            </value>
            <value>
                <fullName>NFSPV1 Transfer</fullName>
            </value>
            <value>
                <fullName>Wire</fullName>
            </value>
            <value>
                <fullName>ACH Processing Co</fullName>
                <isActive>false</isActive>
                <label>ACH Processing Co</label>
            </value>
            <value>
                <fullName>ACH.com</fullName>
                <isActive>false</isActive>
                <label>ACH.com</label>
            </value>
            <value>
                <fullName>ACHWorks</fullName>
                <isActive>false</isActive>
                <label>ACHWorks</label>
            </value>
            <value>
                <fullName>ACHeck21</fullName>
                <isActive>false</isActive>
                <label>ACHeck21</label>
            </value>
            <value>
                <fullName>Forte</fullName>
                <isActive>false</isActive>
                <label>Forte</label>
            </value>
            <value>
                <fullName>PaySafe</fullName>
                <isActive>false</isActive>
                <label>PaySafe</label>
            </value>
            <value>
                <fullName>NFSPV2 Transfer</fullName>
            </value>
            <value>
                <fullName>NFAS3 Transfer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/cmbls__Disbursement__c/fields/cmbls__Disbursement_Batch__c.field-meta.xml
<CustomField>
    <fullName>cmbls__Disbursement_Batch__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Disbursement Batch</label>
    <referenceTo>cmbls__Disbursement_Batch__c</referenceTo>
    <relationshipLabel>Disbursements</relationshipLabel>
    <relationshipName>Disbursements</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/cmbls__Disbursement__c/fields/cmbls__Repayment__c.field-meta.xml
<CustomField>
    <fullName>cmbls__Repayment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Repayment</label>
    <referenceTo>cmbls__Repayment__c</referenceTo>
    <relationshipLabel>Disbursements</relationshipLabel>
    <relationshipName>Disbursements</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/cmbls__Payment__c/cmbls__Payment__c.object-meta.xml
<CustomObject>
    <label>Payment</label>
    <nameField>
        <displayFormat>PMT-{0000}</displayFormat>
        <label>Payment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/cmbls__Payment__c/fields/cmbls__ACH_Batch__c.field-meta.xml
<CustomField>
    <fullName>cmbls__ACH_Batch__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ACH Batch</label>
    <referenceTo>cmbls__ACH_Batch__c</referenceTo>
    <relationshipName>Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/cmbls__Payment__c/fields/cmbls__ACH_Processor__c.field-meta.xml
<CustomField>
    <fullName>cmbls__ACH_Processor__c</fullName>
    <label>ACH Processor</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Wells Fargo - NF Collections</fullName>
            </value>
            <value>
                <fullName>Wells Fargo - NFAS2 Collections</fullName>
            </value>
            <value>
                <fullName>Wells Fargo - NF Funding</fullName>
            </value>
            <value>
                <fullName>Wells Fargo - QBF Funding</fullName>
            </value>
            <value>
                <fullName>Wells Fargo - NFSPV1 Collections</fullName>
            </value>
            <value>
                <fullName>Wells Fargo - NFSPV2 Collections</fullName>
            </value>
            <value>
                <fullName>Wells Fargo - NFAS3 Collections</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/cmbls__Payment__c/fields/cmbls__Repayment__c.field-meta.xml
<CustomField>
    <fullName>cmbls__Repayment__c</fullName>
    <label>Repayment</label>
    <referenceTo>cmbls__Repayment__c</referenceTo>
    <relationshipLabel>Payments</relationshipLabel>
    <relationshipName>Payments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/cmbls__Payment__c/fields/cmbls__Transaction_Type__c.field-meta.xml
<CustomField>
    <fullName>cmbls__Transaction_Type__c</fullName>
    <description>This field indicates wether if it is a Fee or a Payment, and should be displayed in the page detail layout.</description>
    <inlineHelpText>This field indicates wether if it is a Fee or a Payment, and should be displayed in the page detail layout.</inlineHelpText>
    <label>Transaction Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Fee</fullName>
            </value>
            <value>
                <fullName>Payment</fullName>
            </value>
            <value>
                <fullName>Adjustment</fullName>
            </value>
            <value>
                <fullName>Distribution</fullName>
            </value>
            <value>
                <fullName>Fee Collection</fullName>
            </value>
            <value>
                <fullName>Reserve</fullName>
            </value>
            <value>
                <fullName>Interest</fullName>
            </value>
            <value>
                <fullName>Draw</fullName>
            </value>
            <value>
                <fullName>Draw Reserve</fullName>
            </value>
            <value>
                <fullName>Deferred Fee</fullName>
            </value>
            <value>
                <fullName>Lender Reimbursement</fullName>
            </value>
            <value>
                <fullName>Discount</fullName>
            </value>
            <value>
                <fullName>Payoff</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/cmbls__Payment__c/fields/Payment__c.field-meta.xml
<CustomField>
    <fullName>Payment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Rescheduled From</label>
    <referenceTo>cmbls__Payment__c</referenceTo>
    <relationshipLabel>Payments (Payment)</relationshipLabel>
    <relationshipName>Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/cmbls__Repayment__c/cmbls__Repayment__c.object-meta.xml
<CustomObject>
    <label>Repayment</label>
    <nameField>
        <displayFormat>RPMT-{0000000}</displayFormat>
        <label>Repayment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Repayments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/cmbls__Repayment__c/fields/cmbls__ACH_Processor__c.field-meta.xml
<CustomField>
    <fullName>cmbls__ACH_Processor__c</fullName>
    <description>The name of the processor being used</description>
    <inlineHelpText>The name of the processor being used</inlineHelpText>
    <label>ACH Processor</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Wells Fargo - NF Collections</fullName>
            </value>
            <value>
                <fullName>Wells Fargo - NFAS2 Collections</fullName>
            </value>
            <value>
                <fullName>Wells Fargo - NFSPV1 Collections</fullName>
            </value>
            <value>
                <fullName>Wells Fargo - NFSPV2 Collections</fullName>
            </value>
            <value>
                <fullName>Wells Fargo - NFAS3 Collections</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/cmbls__Repayment__c/fields/Merchant_Number__c.field-meta.xml
<CustomField>
    <fullName>Merchant_Number__c</fullName>
    <externalId>true</externalId>
    <label>LoanNumber</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/NF_ACH_Info__c/NF_ACH_Info__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>NF ACH Info</label>
</CustomObject>

unpackaged/main/default/objects/NF_ACH_Info__c/fields/Settlement_in_Business_day__c.field-meta.xml
<CustomField>
    <fullName>Settlement_in_Business_day__c</fullName>
    <defaultValue>0</defaultValue>
    <description>E.g. A settlement delay of “0” means the payments will settle on the effective date</description>
    <inlineHelpText>E.g. A settlement delay of “0” means the payments will settle on the effective date</inlineHelpText>
    <label>Settlement in Business day</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/classes/SentPaymentsProcessorBatchTest.cls
/**
 * SentPaymentsProcessorBatchTest class
 * @author CloudMyBiz (r)
 * @date 6/23/2023
 */

@IsTest
private class SentPaymentsProcessorBatchTest{
    
    @TestSetup static void setupMethod(){
        Test.startTest();
        Account acc = new Account(Name = 'Test account');
        insert acc;
        
        cmbls__Repayment__c repayment = TestDataFactory.createRepayment(acc.Id);
        repayment.cmbls__ACH_Processor__c = 'Wells Fargo - NF Collections';
        repayment.Merchant_Number__c = '123456';
        insert repayment;
        
        delete [SELECT Id FROM cmbls__Payment__c];
        
        cmbls__ACH_Batch__c achBatch = TestDataFactory.createACHBatch('Wells Fargo - NF Collections', 'Pending', DateTimeUtils.getNextValidDate(Date.today().addDays(1)));
        insert achBatch;
        
        cmbls__Payment__c[] payments = new cmbls__Payment__c[]{
            TestDataFactory.createPayment(repayment.Id,'Debit', 'Scheduled', 100.00, Date.today(), 'Wells Fargo - NF Collections'),
            TestDataFactory.createPayment(repayment.Id,'Debit', 'Scheduled', 100.00, Date.today(), 'Wells Fargo - NF Collections'),
            TestDataFactory.createPayment(repayment.Id,'Debit', 'Scheduled', 100.00, Date.today(), 'Wells Fargo - NF Collections'),
            TestDataFactory.createPayment(repayment.Id,'Debit', 'Scheduled', 100.00, Date.today(), 'Wells Fargo - NF Collections'),
            TestDataFactory.createPayment(repayment.Id,'Debit', 'Scheduled', 100.00, Date.today(), 'Wells Fargo - NF Collections')
        };
        for(cmbls__Payment__c item :payments){
            item.cmbls__ACH_Batch__c = achBatch.Id;
            item.cmbls__Transaction_Type__c = PaymentUtils.PAYMENT_TRANSACTION_TYPE_PAYMENT;
        }
        insert payments;
        
        delete [SELECT Id FROM cmbls__Disbursement_Batch__c];
        cmbls__Disbursement_Batch__c disBatch = TestDataFactory.createDisBatch(Constant.ACH_PROCESSOR_NF_FUNDING, 'Pending', DateTimeUtils.getNextValidDate(Date.today().addDays(1)));
        insert disBatch;
        
        cmbls__Disbursement__c[] disbursements = new cmbls__Disbursement__c[]{
            TestDataFactory.createDisbursement('Funding', Constant.STATUS_SCHEDULED, Constant.ACH_PROCESSOR_NF_FUNDING),
            TestDataFactory.createDisbursement('Funding', Constant.STATUS_SCHEDULED, Constant.ACH_PROCESSOR_NF_FUNDING),
            TestDataFactory.createDisbursement('Funding', Constant.STATUS_SCHEDULED, Constant.ACH_PROCESSOR_NF_FUNDING),
            TestDataFactory.createDisbursement('Funding', Constant.STATUS_SCHEDULED, Constant.ACH_PROCESSOR_NF_FUNDING),
            TestDataFactory.createDisbursement('Funding', Constant.STATUS_SCHEDULED, Constant.ACH_PROCESSOR_NF_FUNDING)
        };
        
        for(cmbls__Disbursement__c item :disbursements){
            item.cmbls__Repayment__c = repayment.Id;
            item.cmbls__Disbursement_Batch__c = disBatch.Id;
        }
        insert disbursements;
        
        delete [SELECT Id FROM ACH_Transaction_Log__c];
        ACH_Transaction_Log__c[] logs = new ACH_Transaction_Log__c[]{};
        SObject[] records = new SObject[]{};
        records.addAll(payments);
        records.addAll(disbursements);
        for(SObject item :records){
            ACH_Transaction_Log__c log = TestDataFactory.createACHTransactionLog(item.Id, Constant.ACH_TRANSACTION_LOG_WF_SENT);
            log.Response_Code__c = '201';
            logs.add(log);
        }
        insert logs;
        
        WF_Api_Settings__c wellsFargoAPiSettings = TestDataFactory.wfSettings();
        insert wellsFargoAPiSettings;
        
        NF_ACH_Info__c nfSettings = NF_ACH_Info__c.getInstance();
        nfSettings.Settlement_in_Business_day__c = 5;
        insert nfSettings;
        Test.stopTest();
    }
    
    @IsTest
    static void executePaymentsNoFailures(){
        Test.startTest();
        new SentPaymentsProcessorBatch().execute(null);
        Test.stopTest();
        
        for(ACH_Transaction_Log__c item :[SELECT Pre_Pending_Update_Attempts__c, Payment__r.cmbls__Status__c FROM ACH_Transaction_Log__c WHERE Payment__c != NULL]){
            Assert.areEqual(1, item.Pre_Pending_Update_Attempts__c);
            Assert.areEqual(PaymentUtils.PAYMENT_STATUS_PRE_PENDING, item.Payment__r.cmbls__Status__c);
        }
        
        Assert.areEqual(0, [SELECT COUNT() FROM cmbls__Debug_Log__c]);
    }
    
    @IsTest
    static void executeDisbursementNoFailures(){
        cmbls__Disbursement__c[] records = [SELECT Id, cmbls__Disbursement_Batch__c, cmbls__Disbursement_Batch__r.cmbls__Status__c FROM cmbls__Disbursement__c];
        cmbls__Loan_Servicing_Settings__c lsSetting = cmbls__Loan_Servicing_Settings__c.getOrgDefaults();
        lsSetting.cmbls__Disb_Status_Not_Assigned_to_Batch__c = PaymentUtils.PAYMENT_STATUS_PRE_PENDING;
        upsert lsSetting;
        
        Test.startTest();
        new SentPaymentsProcessorBatch().execute(null);
        Test.stopTest();
        
        Map<Id, cmbls__Disbursement__c> processedRecordsMap = new Map<Id, cmbls__Disbursement__c>([SELECT Id, cmbls__Disbursement_Batch__c FROM cmbls__Disbursement__c WHERE Id IN :records]);
        for(cmbls__Disbursement__c record :records){
            Assert.areEqual(record.cmbls__Disbursement_Batch__c, processedRecordsMap.get(record.Id).cmbls__Disbursement_Batch__c);
        }
        
        for(ACH_Transaction_Log__c item :[SELECT Pre_Pending_Update_Attempts__c, Disbursement__c, Disbursement__r.cmbls__Status__c FROM ACH_Transaction_Log__c WHERE Disbursement__c != NULL]){
            Assert.areEqual(1, item.Pre_Pending_Update_Attempts__c);
            Assert.areEqual(PaymentUtils.PAYMENT_STATUS_PRE_PENDING, item.Disbursement__r.cmbls__Status__c);
        }
        
        Assert.areEqual(0, [SELECT COUNT() FROM cmbls__Debug_Log__c]);
    }
    
    @IsTest
    static void executeDisbursementsNoFailures(){
        Test.startTest();
        new SentPaymentsProcessorBatch().execute(null);
        Test.stopTest();
        
        for(ACH_Transaction_Log__c item :[SELECT Pre_Pending_Update_Attempts__c, Disbursement__r.cmbls__Status__c FROM ACH_Transaction_Log__c WHERE Disbursement__c != NULL]){
            Assert.areEqual(1, item.Pre_Pending_Update_Attempts__c);
            Assert.areEqual(PaymentUtils.PAYMENT_STATUS_PRE_PENDING, item.Disbursement__r.cmbls__Status__c);
        }
        
        Assert.areEqual(0, [SELECT COUNT() FROM cmbls__Debug_Log__c]);
    }
    
    @IsTest
    static void executeMaxNumberOfAttempts(){
        WF_Api_Settings__c apiSettings = WF_Api_Settings__c.getInstance();
        
        ACH_Transaction_Log__c[] logs = [SELECT Id FROM ACH_Transaction_Log__c];
        for(ACH_Transaction_Log__c item :logs){
            item.Pre_Pending_Update_Attempts__c = apiSettings.Pre_Pending_Update_Max_Attempts__c;
        }
        update logs;
        
        Test.startTest();
        new SentPaymentsProcessorBatch().execute(null);
        Test.stopTest();
        
       
    }
    
    @IsTest
    static void executeRecordUpdateFailure(){
        cmbls__Payment__c[] records = [SELECT Id FROM cmbls__Payment__c];
        
        Test.startTest();
        SentPaymentsProcessorBatch.paymentFailureRecord = records[1];
        new SentPaymentsProcessorBatch().execute(null);
        Test.stopTest();

        for(ACH_Transaction_Log__c item :[SELECT Pre_Pending_Update_Attempts__c, Payment__c, Payment__r.cmbls__Status__c FROM ACH_Transaction_Log__c WHERE Payment__c != NULL]){
           // Assert.areEqual(1, item.Pre_Pending_Update_Attempts__c);
            if(item.Payment__c == records[1].Id){
                //Assert.areEqual(PaymentUtils.PAYMENT_STATUS_SCHEDULED, item.Payment__r.cmbls__Status__c);
            }else{
               // Assert.areEqual(PaymentUtils.PAYMENT_STATUS_PRE_PENDING, item.Payment__r.cmbls__Status__c);
            }
        }
        
        cmbls__Debug_Log__c debugLog = [SELECT cmbls__Subject__c, cmbls__Description__c, cmbls__Log__c FROM cmbls__Debug_Log__c];
        String objectName = cmbls__Payment__c.getSObjectType().getDescribe().getLabel();
        String expectedSubject = String.format(SentPaymentsProcessorBatch.DEBUG_LOG_FAILURE_SUBJECT, new String[]{SentPaymentsProcessorBatch.getJobName()});
        String expectedDescription = String.format(SentPaymentsProcessorBatch.DEBUG_LOG_FAILURE_DESCRIPTION, new String[]{objectName, PaymentUtils.PAYMENT_STATUS_PRE_PENDING, records[1].Id});

        
    }
}