unpackaged/main/default/objects/ACH_Transaction_Log__c/ACH_Transaction_Log__c.object-meta.xml
<CustomObject>
    <label>ACH Transaction Log</label>
    <nameField>
        <displayFormat>LOG-{0000000}</displayFormat>
        <label>ACH Transaction Log Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ACH Transactions Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ACH_Transaction_Log__c/fields/Disbursement__c.field-meta.xml
<CustomField>
    <fullName>Disbursement__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Disbursement</label>
    <referenceTo>cmbls__Disbursement__c</referenceTo>
    <relationshipLabel>ACH Transactions Logs</relationshipLabel>
    <relationshipName>ACH_Transactions_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ACH_Transaction_Log__c/fields/Payment__c.field-meta.xml
<CustomField>
    <fullName>Payment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment</label>
    <referenceTo>cmbls__Payment__c</referenceTo>
    <relationshipLabel>ACH Transactions Logs</relationshipLabel>
    <relationshipName>ACH_Transactions_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ACH_Transaction_Log__c/fields/Pre_Pending_Update_Attempts__c.field-meta.xml
<CustomField>
    <fullName>Pre_Pending_Update_Attempts__c</fullName>
    <label>Pre Pending Update Attempts</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/cmbls__Disbursement__c/cmbls__Disbursement__c.object-meta.xml
<CustomObject>
    <label>Disbursement</label>
    <nameField>
        <displayFormat>D-{0000}</displayFormat>
        <label>Disbursement Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Disbursements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/cmbls__Disbursement__c/fields/cmbls__Status__c.field-meta.xml
<CustomField>
    <fullName>cmbls__Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>Pre-Pending</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Settled</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Sent Error</fullName>
            </value>
            <value>
                <fullName>Staging</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/cmbls__Disbursement__c/fields/cmbls__Transaction_Amount__c.field-meta.xml
<CustomField>
    <fullName>cmbls__Transaction_Amount__c</fullName>
    <label>Transaction Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/cmbls__Payment__c/cmbls__Payment__c.object-meta.xml
<CustomObject>
    <label>Payment</label>
    <nameField>
        <displayFormat>PMT-{0000}</displayFormat>
        <label>Payment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/cmbls__Payment__c/fields/cmbls__Status__c.field-meta.xml
<CustomField>
    <fullName>cmbls__Status__c</fullName>
    <inlineHelpText>Scheduled: Created and not submitted
Pending: Submitted to the ACH provider, but not yet settled.
Settled: The ACH payment was pulled successfully from the customer's account
Failed: Returned a failed response from the ACH provider</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>cmbls__Transaction_Type__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>Pre-Pending</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Settled</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Fees Applied</fullName>
            </value>
            <value>
                <fullName>Fees Collected</fullName>
            </value>
            <value>
                <fullName>Fees Reversed</fullName>
            </value>
            <value>
                <fullName>Applied</fullName>
            </value>
            <value>
                <fullName>Sent Error</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/cmbls__Payment__c/fields/cmbls__Transaction_Amount__c.field-meta.xml
<CustomField>
    <fullName>cmbls__Transaction_Amount__c</fullName>
    <label>Transaction Amount</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/cmbls__Payment__c/fields/Payment__c.field-meta.xml
<CustomField>
    <fullName>Payment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Rescheduled From</label>
    <referenceTo>cmbls__Payment__c</referenceTo>
    <relationshipLabel>Payments (Payment)</relationshipLabel>
    <relationshipName>Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/SentPaymentsProcessorBatch.cls
global with sharing class SentPaymentsProcessorBatch implements Database.Batchable<SObject>, Schedulable{
    
    @TestVisible private static final String DEBUG_LOG_FAILURE_SUBJECT = '{0} Job failure';
    @TestVisible private static final String DEBUG_LOG_FAILURE_DESCRIPTION = '{0} record Status failed to update to {1} - {2}';
    @TestVisible private static cmbls__Payment__c paymentFailureRecord; //Used on UnitTest to throw an error on a specific record
    @TestVisible private static Boolean rescheduleFires; //Used on UnitTest to be sure this get rescheduled
    
    global Database.QueryLocator start(Database.BatchableContext bc){
        //Query to return no records, easy way is to query any record where Id = NULL
        String query = 'SELECT Id FROM ACH_Transaction_Log__c WHERE Id = NULL';
        
        //Check batch is not already running
        if(batchIsNotRunning(bc)) query = PaymentService.getSentToWellsFargoPendingPaymentsQuery();
        return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext bc, List<SObject> scope){
        Map<Id, SObject> recordsToUpdate = new Map<Id, SObject>();
        cmbls__Debug_Log__c[] debugLogsToInsert = new cmbls__Debug_Log__c[]{};
        Map<Id, ACH_Transaction_Log__c> logsToUpdateByParent = new Map<Id, ACH_Transaction_Log__c>();
        
        for(SObject item :scope){
            ACH_Transaction_Log__c log = (ACH_Transaction_Log__c)item;
            log.Pre_Pending_Update_Attempts__c = NumberUtils.getInteger(log.Pre_Pending_Update_Attempts__c) + 1;
            
            if(String.isNotBlank(log.Payment__c)){
                recordsToUpdate.put(log.Payment__c, new cmbls__Payment__c(
                    Id = log.Payment__c,
                    cmbls__Status__c = PaymentUtils.PAYMENT_STATUS_PRE_PENDING
                ));
                logsToUpdateByParent.put(log.Payment__c, log);
            }else if(String.isNotBlank(log.Disbursement__c)){
                recordsToUpdate.put(log.Disbursement__c, new cmbls__Disbursement__c(
                    Id = log.Disbursement__c,
                    cmbls__Date_Sent__c = log.CreatedDate.date(),
                    cmbls__Status__c = PaymentUtils.PAYMENT_STATUS_PRE_PENDING
                ));
                logsToUpdateByParent.put(log.Disbursement__c, log);
            }
        }
        
        if(Test.isRunningTest() && paymentFailureRecord != null){
            recordsToUpdate.get(paymentFailureRecord.Id).put('cmbls__Transaction_Amount__c', null);
            paymentFailureRecord = null;
        }
        
        SObject[] recordsToUpdateList = recordsToUpdate.values();
        Integer index = 0;
        for(Database.SaveResult result :Database.update(recordsToUpdateList, false)){
            if(!result.isSuccess()){
                Id recordId = recordsToUpdateList[index].Id;
                String objectName = recordId.getSobjectType().getDescribe().getLabel();
                cmbls__Debug_Log__c log = UtilityTools.getDebugLogForDMLFailure(null, recordsToUpdate.get(recordId), result);
                log.cmbls__Subject__c = String.format(DEBUG_LOG_FAILURE_SUBJECT, new String[]{getJobName()});
                log.cmbls__Description__c = String.format(DEBUG_LOG_FAILURE_DESCRIPTION, new String[]{objectName, PaymentUtils.PAYMENT_STATUS_PRE_PENDING, recordId});
                debugLogsToInsert.add(log);
            }
            index++;
        }
        
        update logsToUpdateByParent.values();
        insert debugLogsToInsert;
    }
    
    global void finish(Database.BatchableContext bc){
        if(PaymentService.getSentToWellsFargoPendingPaymentsCount() > 0){
            if(Test.isRunningTest()){
                rescheduleFires = true; //Set to true to let UnitTest know this is working as expected and tries to reschedule
                return;
            }
            Database.executeBatch(new SentPaymentsProcessorBatch(), PaymentsBatchProcessor.getBatchScope());
        }
    }
    
    global void execute(SchedulableContext sc){
        Database.executeBatch(new SentPaymentsProcessorBatch(), PaymentsBatchProcessor.getBatchScope());
    }
    
    public static Integer getPrePendingUpdateMaxAttempts(){
        return WellsFargoAPI.WF_Settings.Pre_Pending_Update_Max_Attempts__c != null ? NumberUtils.getInteger(WellsFargoAPI.WF_Settings.Pre_Pending_Update_Max_Attempts__c) : 10;
    }
    
    public static Boolean batchIsNotRunning(Database.BatchableContext bc){
        String[] statuses = new String[]{'Processing','Preparing','Holding'};
        if(Test.isRunningTest()) statuses.add('Queued');//Include Queued for Unittest
        String query =  'SELECT COUNT() FROM AsyncApexJob ' +
                        'WHERE ' +
                            'JobType = \'BatchApex\' AND ' +
                            'ApexClass.Name = \'SentPaymentsProcessorBatch\' AND ' +
                            'Status IN :statuses';
        if(bc != null) query += ' AND Id != \'' + bc.getJobId() + '\'';
        return Database.countQuery(query) == 0;
    }
    
    public static String getJobName(){
        String output = 'Update Pre-Pending Status ';
        return output;
    }
}