unpackaged/main/default/objects/ACH_Transaction_Log__c/ACH_Transaction_Log__c.object-meta.xml
<CustomObject>
    <label>ACH Transaction Log</label>
    <nameField>
        <displayFormat>LOG-{0000000}</displayFormat>
        <label>ACH Transaction Log Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ACH Transactions Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ACH_Transaction_Log__c/fields/Payment__c.field-meta.xml
<CustomField>
    <fullName>Payment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment</label>
    <referenceTo>cmbls__Payment__c</referenceTo>
    <relationshipLabel>ACH Transactions Logs</relationshipLabel>
    <relationshipName>ACH_Transactions_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/cmbls__ACH_Batch__c/cmbls__ACH_Batch__c.object-meta.xml
<CustomObject>
    <label>ACH Batch</label>
    <nameField>
        <displayFormat>BATCH-{0000000}</displayFormat>
        <label>ACH Batch Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ACH Batches</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/cmbls__ACH_Batch__c/fields/cmbls__Status__c.field-meta.xml
<CustomField>
    <fullName>cmbls__Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Partial Success</fullName>
            </value>
            <value>
                <fullName>Resubmission</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/cmbls__Disbursement__c/cmbls__Disbursement__c.object-meta.xml
<CustomObject>
    <label>Disbursement</label>
    <nameField>
        <displayFormat>D-{0000}</displayFormat>
        <label>Disbursement Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Disbursements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/cmbls__Disbursement__c/fields/cmbls__ACH_Processor__c.field-meta.xml
<CustomField>
    <fullName>cmbls__ACH_Processor__c</fullName>
    <label>ACH Processor</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Wells Fargo - NF Funding</fullName>
            </value>
            <value>
                <fullName>Wells Fargo - QBF Funding</fullName>
            </value>
            <value>
                <fullName>NFAS2 Transfer</fullName>
            </value>
            <value>
                <fullName>NF Transfer (QB)</fullName>
            </value>
            <value>
                <fullName>NFSPV1 Transfer</fullName>
            </value>
            <value>
                <fullName>Wire</fullName>
            </value>
            <value>
                <fullName>ACH Processing Co</fullName>
                <isActive>false</isActive>
                <label>ACH Processing Co</label>
            </value>
            <value>
                <fullName>ACH.com</fullName>
                <isActive>false</isActive>
                <label>ACH.com</label>
            </value>
            <value>
                <fullName>ACHWorks</fullName>
                <isActive>false</isActive>
                <label>ACHWorks</label>
            </value>
            <value>
                <fullName>ACHeck21</fullName>
                <isActive>false</isActive>
                <label>ACHeck21</label>
            </value>
            <value>
                <fullName>Forte</fullName>
                <isActive>false</isActive>
                <label>Forte</label>
            </value>
            <value>
                <fullName>PaySafe</fullName>
                <isActive>false</isActive>
                <label>PaySafe</label>
            </value>
            <value>
                <fullName>NFSPV2 Transfer</fullName>
            </value>
            <value>
                <fullName>NFAS3 Transfer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/cmbls__Disbursement__c/fields/cmbls__Disbursement_Batch__c.field-meta.xml
<CustomField>
    <fullName>cmbls__Disbursement_Batch__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Disbursement Batch</label>
    <referenceTo>cmbls__Disbursement_Batch__c</referenceTo>
    <relationshipLabel>Disbursements</relationshipLabel>
    <relationshipName>Disbursements</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/cmbls__Disbursement__c/fields/cmbls__Repayment__c.field-meta.xml
<CustomField>
    <fullName>cmbls__Repayment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Repayment</label>
    <referenceTo>cmbls__Repayment__c</referenceTo>
    <relationshipLabel>Disbursements</relationshipLabel>
    <relationshipName>Disbursements</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/cmbls__Disbursement__c/fields/cmbls__Status__c.field-meta.xml
<CustomField>
    <fullName>cmbls__Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>Pre-Pending</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Settled</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Sent Error</fullName>
            </value>
            <value>
                <fullName>Staging</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/cmbls__Disbursement_Batch__c/cmbls__Disbursement_Batch__c.object-meta.xml
<CustomObject>
    <label>Disbursement Batch</label>
    <nameField>
        <displayFormat>DB-{0000}</displayFormat>
        <label>Disbursement Batch Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Disbursement Batches</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/cmbls__Disbursement_Batch__c/fields/cmbls__Status__c.field-meta.xml
<CustomField>
    <fullName>cmbls__Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Partial Success</fullName>
            </value>
            <value>
                <fullName>Resubmission</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/cmbls__Payment__c/cmbls__Payment__c.object-meta.xml
<CustomObject>
    <label>Payment</label>
    <nameField>
        <displayFormat>PMT-{0000}</displayFormat>
        <label>Payment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/cmbls__Payment__c/fields/cmbls__ACH_Batch__c.field-meta.xml
<CustomField>
    <fullName>cmbls__ACH_Batch__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ACH Batch</label>
    <referenceTo>cmbls__ACH_Batch__c</referenceTo>
    <relationshipName>Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/cmbls__Payment__c/fields/cmbls__ACH_Processor__c.field-meta.xml
<CustomField>
    <fullName>cmbls__ACH_Processor__c</fullName>
    <label>ACH Processor</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Wells Fargo - NF Collections</fullName>
            </value>
            <value>
                <fullName>Wells Fargo - NFAS2 Collections</fullName>
            </value>
            <value>
                <fullName>Wells Fargo - NF Funding</fullName>
            </value>
            <value>
                <fullName>Wells Fargo - QBF Funding</fullName>
            </value>
            <value>
                <fullName>Wells Fargo - NFSPV1 Collections</fullName>
            </value>
            <value>
                <fullName>Wells Fargo - NFSPV2 Collections</fullName>
            </value>
            <value>
                <fullName>Wells Fargo - NFAS3 Collections</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/cmbls__Payment__c/fields/cmbls__Repayment__c.field-meta.xml
<CustomField>
    <fullName>cmbls__Repayment__c</fullName>
    <label>Repayment</label>
    <referenceTo>cmbls__Repayment__c</referenceTo>
    <relationshipLabel>Payments</relationshipLabel>
    <relationshipName>Payments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/cmbls__Payment__c/fields/cmbls__Transaction_Type__c.field-meta.xml
<CustomField>
    <fullName>cmbls__Transaction_Type__c</fullName>
    <description>This field indicates wether if it is a Fee or a Payment, and should be displayed in the page detail layout.</description>
    <inlineHelpText>This field indicates wether if it is a Fee or a Payment, and should be displayed in the page detail layout.</inlineHelpText>
    <label>Transaction Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Fee</fullName>
            </value>
            <value>
                <fullName>Payment</fullName>
            </value>
            <value>
                <fullName>Adjustment</fullName>
            </value>
            <value>
                <fullName>Distribution</fullName>
            </value>
            <value>
                <fullName>Fee Collection</fullName>
            </value>
            <value>
                <fullName>Reserve</fullName>
            </value>
            <value>
                <fullName>Interest</fullName>
            </value>
            <value>
                <fullName>Draw</fullName>
            </value>
            <value>
                <fullName>Draw Reserve</fullName>
            </value>
            <value>
                <fullName>Deferred Fee</fullName>
            </value>
            <value>
                <fullName>Lender Reimbursement</fullName>
            </value>
            <value>
                <fullName>Discount</fullName>
            </value>
            <value>
                <fullName>Payoff</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/cmbls__Payment__c/fields/Payment__c.field-meta.xml
<CustomField>
    <fullName>Payment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Rescheduled From</label>
    <referenceTo>cmbls__Payment__c</referenceTo>
    <relationshipLabel>Payments (Payment)</relationshipLabel>
    <relationshipName>Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/cmbls__Repayment__c/cmbls__Repayment__c.object-meta.xml
<CustomObject>
    <label>Repayment</label>
    <nameField>
        <displayFormat>RPMT-{0000000}</displayFormat>
        <label>Repayment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Repayments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/cmbls__Repayment__c/fields/cmbls__ACH_Processor__c.field-meta.xml
<CustomField>
    <fullName>cmbls__ACH_Processor__c</fullName>
    <description>The name of the processor being used</description>
    <inlineHelpText>The name of the processor being used</inlineHelpText>
    <label>ACH Processor</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Wells Fargo - NF Collections</fullName>
            </value>
            <value>
                <fullName>Wells Fargo - NFAS2 Collections</fullName>
            </value>
            <value>
                <fullName>Wells Fargo - NFSPV1 Collections</fullName>
            </value>
            <value>
                <fullName>Wells Fargo - NFSPV2 Collections</fullName>
            </value>
            <value>
                <fullName>Wells Fargo - NFAS3 Collections</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/cmbls__Repayment__c/fields/Merchant_Number__c.field-meta.xml
<CustomField>
    <fullName>Merchant_Number__c</fullName>
    <externalId>true</externalId>
    <label>LoanNumber</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/classes/BatchCheckACHTransactionStatusTest.cls
/**
 * BatchCheckACHTransactionStatusTest class
 * @author CloudMyBiz (r)
 * @date 08/02/2023
 * @description
 * @group 
 */

@IsTest
private class BatchCheckACHTransactionStatusTest {

    @TestSetup static void setupMethod(){
        Test.startTest();
        Account acc = new Account(Name = 'Test account');
        insert acc;

        List<cmbls__Repayment__c> repayments = new List<cmbls__Repayment__c>();
        cmbls__Repayment__c repayment1 = TestDataFactory.createRepayment(acc.Id);
        repayment1.cmbls__ACH_Processor__c = 'Wells Fargo Account';
        repayment1.Merchant_Number__c = '123456';
        repayments.add(repayment1);
        cmbls__Repayment__c repayment2 = TestDataFactory.createRepayment(acc.Id);
        repayment2.Merchant_Number__c = '123457';
        repayment2.cmbls__ACH_Processor__c = Constant.ACH_PROCESSOR_NF_FUNDING;
        repayments.add(repayment2);
        insert repayments;

        cmbls__ACH_Batch__c achBatch = TestDataFactory.createACHBatch('Wells Fargo Account', Constant.ACH_BATCH_STATUS_SUCCESS, DateTimeUtils.getNextValidDate(Date.today().addDays(1)));
        insert achBatch;

        cmbls__Payment__c payment = TestDataFactory.createPayment(repayment1.Id,'Debit', PaymentUtils.PAYMENT_STATUS_PRE_PENDING, 100.00, Date.today(), 'Wells Fargo Account');
        payment.cmbls__ACH_Batch__c = achBatch.Id;
        payment.cmbls__Transaction_Type__c = PaymentUtils.PAYMENT_TRANSACTION_TYPE_PAYMENT;
        insert payment;

        cmbls__Disbursement_Batch__c disBatch = TestDataFactory.createDisBatch(Constant.ACH_PROCESSOR_NF_FUNDING, 'Pending', DateTimeUtils.getNextValidDate(Date.today().addDays(1)));
        insert disBatch;

        cmbls__Disbursement__c dis = TestDataFactory.createDisbursement('Funding', Constant.STATUS_SCHEDULED, Constant.ACH_PROCESSOR_NF_FUNDING);
        dis.cmbls__Repayment__c = repayment2.Id;
        dis.cmbls__Disbursement_Batch__c = disBatch.Id;
        insert dis;

        WF_Api_Settings__c wellsFargoAPiSettings = TestDataFactory.wfSettings();
        insert wellsFargoAPiSettings;
        Test.stopTest();
    }

    @IsTest
    static void paymentProcessedStatusCheck(){
        cmbls__Payment__c payment = [SELECT Id FROM cmbls__Payment__c WHERE cmbls__Status__c = :PaymentUtils.PAYMENT_STATUS_PRE_PENDING];
        ACH_Transaction_Log__c achLog = TestDataFactory.createACHTransactionLog(payment.Id, Constant.ACH_TRANSACTION_LOG_WF_SENT);
        insert achLog;

        Test.startTest();
        String httpResp = '{"payment_status": "PROCESSED","payee_name": "JE Plumbing Services","payment_date": "20160617","payment_amount": 100.00,"trace_number": "001469807632881"}';
        Test.setMock(HttpCalloutMock.class, new ServiceConnectorMock(200, 'Status', httpResp, new Map<String,String>()));
        new BatchCheckACHTransactionStatus().execute(null);
        Test.stopTest();


        ACH_Transaction_Log__c achTransactionLog = [SELECT Id, Status__c, Response__c, Response_Code__c, ACH_Trace_Number__c FROM ACH_Transaction_Log__c WHERE Payment__c = :payment.Id AND Id !=: achLog.Id];
        System.assertEquals(achTransactionLog.Status__c, Constant.ACH_TRANSACTION_LOG_STATUS_COMPLETED);
        System.assertEquals(achTransactionLog.Response__c, httpResp);
        System.assertEquals(achTransactionLog.Response_Code__c, '200');
        System.assertEquals(achTransactionLog.ACH_Trace_Number__c, '001469807632881');

        Assert.areEqual(1, [SELECT COUNT() FROM ACH_Transaction_Log__c WHERE Status__c =: Constant.ACH_TRANSACTION_LOG_STATUS_PENDING AND Id =: achLog.Id]);
        Assert.areEqual(1, [SELECT COUNT() FROM cmbls__Payment__c WHERE cmbls__Status__c =: PaymentUtils.PAYMENT_STATUS_PRE_PENDING AND Id =: payment.Id]);
    }

    @IsTest
    static void paymentStatusPending(){

        cmbls__Payment__c payment = [SELECT Id FROM cmbls__Payment__c WHERE cmbls__Status__c = :PaymentUtils.PAYMENT_STATUS_PRE_PENDING];
        ACH_Transaction_Log__c achLog = TestDataFactory.createACHTransactionLog(payment.Id, Constant.ACH_TRANSACTION_LOG_WF_SENT);
        insert achLog;

        Test.startTest();
        String httpResp = '{"payment_status": "PENDING","payee_name": "JE Plumbing Services","payment_date": "20160617","payment_amount": 100.00}';
        Test.setMock(HttpCalloutMock.class, new ServiceConnectorMock(200, 'Status', httpResp, new Map<String,String>()));
        new BatchCheckACHTransactionStatus().execute(null);
        Test.stopTest();

        ACH_Transaction_Log__c achTransactionLog = [SELECT Id, Status__c, Response__c, Response_Code__c FROM ACH_Transaction_Log__c WHERE Payment__c = :payment.Id AND Id !=: achLog.Id];
        System.assertEquals(achTransactionLog.Status__c, Constant.ACH_TRANSACTION_LOG_STATUS_COMPLETED);
        System.assertEquals(achTransactionLog.Response__c, httpResp);
        System.assertEquals(achTransactionLog.Response_Code__c, '200');
    
        Assert.isTrue([SELECT COUNT() FROM ACH_Transaction_Log__c WHERE Status__c =: Constant.ACH_TRANSACTION_LOG_WF_SENT AND Id =: achLog.Id] == 1);
        Assert.isTrue([SELECT COUNT() FROM cmbls__Payment__c WHERE cmbls__Status__c =: PaymentUtils.PAYMENT_STATUS_PRE_PENDING AND Id =: payment.Id] == 1);
    }
    
    @IsTest
    static void paymentProcessedStatusToSettled(){
        cmbls__Payment__c payment = [SELECT Id FROM cmbls__Payment__c WHERE cmbls__Status__c = :PaymentUtils.PAYMENT_STATUS_PRE_PENDING];
        ACH_Transaction_Log__c achLog = TestDataFactory.createACHTransactionLog(payment.Id, Constant.ACH_TRANSACTION_LOG_WF_SENT);
        insert achLog;
    
        WF_Api_Settings__c settings = WF_Api_Settings__c.getInstance();
        settings.Pre_Pending_Payments_in_Settlement_Delay__c = true;
        upsert settings;
        
        Test.startTest();
        String httpResp = '{"payment_status": "PROCESSED","payee_name": "JE Plumbing Services","payment_date": "20160617","payment_amount": 100.00,"trace_number": "001469807632881"}';
        Test.setMock(HttpCalloutMock.class, new ServiceConnectorMock(200, 'Status', httpResp, new Map<String,String>()));
        new BatchCheckACHTransactionStatus().execute(null);
        Test.stopTest();
        
        ACH_Transaction_Log__c achTransactionLog = [SELECT Id, Status__c, Response__c, Response_Code__c FROM ACH_Transaction_Log__c WHERE Payment__c = :payment.Id AND Id !=: achLog.Id];
        System.assertEquals(achTransactionLog.Status__c, Constant.ACH_TRANSACTION_LOG_STATUS_COMPLETED);
        System.assertEquals(achTransactionLog.Response__c, httpResp);
        System.assertEquals(achTransactionLog.Response_Code__c, '200');
    
        Assert.isTrue([SELECT COUNT() FROM ACH_Transaction_Log__c WHERE Status__c =: Constant.ACH_TRANSACTION_LOG_STATUS_COMPLETED AND Id =: achLog.Id] == 1);
        Assert.isTrue([SELECT COUNT() FROM cmbls__Payment__c WHERE cmbls__Status__c =: PaymentUtils.PAYMENT_STATUS_SETTLED AND Id =: payment.Id] == 1);
    }

    @IsTest
    static void paymentStatusException(){

        cmbls__Payment__c payment = [SELECT Id FROM cmbls__Payment__c WHERE cmbls__Status__c = :PaymentUtils.PAYMENT_STATUS_PRE_PENDING];
        ACH_Transaction_Log__c achLog = TestDataFactory.createACHTransactionLog(payment.Id, Constant.ACH_TRANSACTION_LOG_WF_SENT);
        insert achLog;

        Test.startTest();
        String httpResp = '{"payment_status": "EXCEPTION","payee_name": "JE Plumbing Services","payment_date": "20160617","payment_amount": 100.00}';
        Test.setMock(HttpCalloutMock.class, new ServiceConnectorMock(200, 'Status', httpResp, new Map<String,String>()));
        new BatchCheckACHTransactionStatus().execute(null);
        Test.stopTest();

        ACH_Transaction_Log__c achTransactionLog = [SELECT Id, Status__c, Response__c, Response_Code__c FROM ACH_Transaction_Log__c WHERE Payment__c = :payment.Id AND Id !=: achLog.Id];
        System.assertEquals(achTransactionLog.Status__c, Constant.ACH_TRANSACTION_LOG_STATUS_FAILED);
        System.assertEquals(achTransactionLog.Response__c, httpResp);
        System.assertEquals(achTransactionLog.Response_Code__c, '200');
        
        System.debug([SELECT Status__c FROM ACH_Transaction_Log__c WHERE Id =: achLog.Id]);
    
        Assert.isTrue([SELECT COUNT() FROM ACH_Transaction_Log__c WHERE Status__c =: Constant.ACH_TRANSACTION_LOG_WF_SENT AND Id =: achLog.Id] == 1);
        Assert.isTrue([SELECT COUNT() FROM cmbls__Payment__c WHERE cmbls__Status__c =: PaymentUtils.PAYMENT_STATUS_PRE_PENDING AND Id =: payment.Id] == 1);
    }

    @IsTest
    static void calloutFailure(){

        cmbls__Payment__c payment = [SELECT Id FROM cmbls__Payment__c WHERE cmbls__Status__c = :PaymentUtils.PAYMENT_STATUS_PRE_PENDING];
        ACH_Transaction_Log__c achLog = TestDataFactory.createACHTransactionLog(payment.Id, Constant.ACH_TRANSACTION_LOG_WF_SENT);
        insert achLog;

        Test.startTest();
        String httpResp = '';
        Test.setMock(HttpCalloutMock.class, new ServiceConnectorMock(500, 'Status', httpResp, new Map<String,String>()));
        new BatchCheckACHTransactionStatus().execute(null);
        Test.stopTest();

        ACH_Transaction_Log__c achTransactionLog = [SELECT Id, Status__c, Response__c, Response_Code__c FROM ACH_Transaction_Log__c WHERE Payment__c = :payment.Id AND Id !=: achLog.Id];
        System.assertEquals(Constant.ACH_TRANSACTION_LOG_STATUS_COMPLETED, achTransactionLog.Status__c);
        System.assertEquals(achTransactionLog.Response_Code__c, '500');
    }

}