unpackaged/main/default/objects/ACH_Transaction_Log__c/ACH_Transaction_Log__c.object-meta.xml
<CustomObject>
    <label>ACH Transaction Log</label>
    <nameField>
        <displayFormat>LOG-{0000000}</displayFormat>
        <label>ACH Transaction Log Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ACH Transactions Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ACH_Transaction_Log__c/fields/Disbursement__c.field-meta.xml
<CustomField>
    <fullName>Disbursement__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Disbursement</label>
    <referenceTo>cmbls__Disbursement__c</referenceTo>
    <relationshipLabel>ACH Transactions Logs</relationshipLabel>
    <relationshipName>ACH_Transactions_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ACH_Transaction_Log__c/fields/Payment__c.field-meta.xml
<CustomField>
    <fullName>Payment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment</label>
    <referenceTo>cmbls__Payment__c</referenceTo>
    <relationshipLabel>ACH Transactions Logs</relationshipLabel>
    <relationshipName>ACH_Transactions_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/cmbls__Disbursement__c/cmbls__Disbursement__c.object-meta.xml
<CustomObject>
    <label>Disbursement</label>
    <nameField>
        <displayFormat>D-{0000}</displayFormat>
        <label>Disbursement Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Disbursements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/cmbls__Payment__c/cmbls__Payment__c.object-meta.xml
<CustomObject>
    <label>Payment</label>
    <nameField>
        <displayFormat>PMT-{0000}</displayFormat>
        <label>Payment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/cmbls__Payment__c/fields/Payment__c.field-meta.xml
<CustomField>
    <fullName>Payment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Rescheduled From</label>
    <referenceTo>cmbls__Payment__c</referenceTo>
    <relationshipLabel>Payments (Payment)</relationshipLabel>
    <relationshipName>Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/ACHTransactionLog.cls
/**
 * ACHTransactionLog class
 * @author CloudMyBiz (r)
 * @date 11/07/2022
 * @description
 * @group 
 */

public with sharing class ACHTransactionLog {

    public ACH_Transaction_Log__c log;

    public ACHTransactionLog(){
        this.log = new ACH_Transaction_Log__c();
        Database.DMLOptions dmlOptions = new Database.DMLOptions();
        dmlOptions.allowFieldTruncation = true;
        this.log.setOptions(dmlOptions);
    }

    public void setLookupField(Id recordId){
        if (recordId != null && this.log != null) {
            if (recordId.getSobjectType() == cmbls__Payment__c.getSObjectType()) {
                this.log.Payment__c = recordId;
            } else if (recordId.getSobjectType() == cmbls__Disbursement__c.getSObjectType()) {
                this.log.Disbursement__c = recordId;
            }
        }
    }

    public static List<ACH_Transaction_Log__c> getLogs(List<ACHTransactionLog> logs){
        List<ACH_Transaction_Log__c> ret = new List<ACH_Transaction_Log__c>();
        for(ACHTransactionLog achLog : logs){
            ret.add(achLog.log);
        }
        return ret;
    }

}