unpackaged/main/default/objects/ACH_Transaction_Log__c/ACH_Transaction_Log__c.object-meta.xml
<CustomObject>
    <label>ACH Transaction Log</label>
    <nameField>
        <displayFormat>LOG-{0000000}</displayFormat>
        <label>ACH Transaction Log Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ACH Transactions Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ACH_Transaction_Log__c/fields/ACH_Trace_Number__c.field-meta.xml
<CustomField>
    <fullName>ACH_Trace_Number__c</fullName>
    <description>ACH payment trace number assigned to the payment. The field only applies to PROCESSED payments.</description>
    <inlineHelpText>ACH payment trace number assigned to the payment. The field only applies to PROCESSED payments.</inlineHelpText>
    <label>ACH Trace Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ACH_Transaction_Log__c/fields/Disbursement__c.field-meta.xml
<CustomField>
    <fullName>Disbursement__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Disbursement</label>
    <referenceTo>cmbls__Disbursement__c</referenceTo>
    <relationshipLabel>ACH Transactions Logs</relationshipLabel>
    <relationshipName>ACH_Transactions_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ACH_Transaction_Log__c/fields/Payment__c.field-meta.xml
<CustomField>
    <fullName>Payment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment</label>
    <referenceTo>cmbls__Payment__c</referenceTo>
    <relationshipLabel>ACH Transactions Logs</relationshipLabel>
    <relationshipName>ACH_Transactions_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ACH_Transaction_Log__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Notification of Change</fullName>
            </value>
            <value>
                <fullName>Sent to Wells Fargo</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/cmbls__Disbursement__c/cmbls__Disbursement__c.object-meta.xml
<CustomObject>
    <label>Disbursement</label>
    <nameField>
        <displayFormat>D-{0000}</displayFormat>
        <label>Disbursement Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Disbursements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/cmbls__Disbursement__c/fields/cmbls__Effective_Date__c.field-meta.xml
<CustomField>
    <fullName>cmbls__Effective_Date__c</fullName>
    <label>Effective Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/cmbls__Disbursement__c/fields/cmbls__Status__c.field-meta.xml
<CustomField>
    <fullName>cmbls__Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>Pre-Pending</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Settled</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Sent Error</fullName>
            </value>
            <value>
                <fullName>Staging</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/cmbls__Disbursement__c/fields/Wells_Fargo_Disbursement_ID_Formula__c.field-meta.xml
<CustomField>
    <fullName>Wells_Fargo_Disbursement_ID_Formula__c</fullName>
    <description>Uses 'Record ID' if 'Wells Fargo Disbursement ID Override' is null</description>
    <formula>IF( ISBLANK( Wells_Fargo_Disbursement_ID_Override__c), Id ,  Wells_Fargo_Disbursement_ID_Override__c )</formula>
    <inlineHelpText>Uses 'Record ID' if 'Wells Fargo Disbursement ID Override' is null</inlineHelpText>
    <label>Wells Fargo Disbursement ID Formula</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/cmbls__Payment__c/cmbls__Payment__c.object-meta.xml
<CustomObject>
    <label>Payment</label>
    <nameField>
        <displayFormat>PMT-{0000}</displayFormat>
        <label>Payment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/cmbls__Payment__c/fields/cmbls__Effective_Date__c.field-meta.xml
<CustomField>
    <fullName>cmbls__Effective_Date__c</fullName>
    <inlineHelpText>Effective Date</inlineHelpText>
    <label>Effective Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/cmbls__Payment__c/fields/cmbls__Status__c.field-meta.xml
<CustomField>
    <fullName>cmbls__Status__c</fullName>
    <inlineHelpText>Scheduled: Created and not submitted
Pending: Submitted to the ACH provider, but not yet settled.
Settled: The ACH payment was pulled successfully from the customer's account
Failed: Returned a failed response from the ACH provider</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>cmbls__Transaction_Type__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>Pre-Pending</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Settled</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Fees Applied</fullName>
            </value>
            <value>
                <fullName>Fees Collected</fullName>
            </value>
            <value>
                <fullName>Fees Reversed</fullName>
            </value>
            <value>
                <fullName>Applied</fullName>
            </value>
            <value>
                <fullName>Sent Error</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/cmbls__Payment__c/fields/Payment__c.field-meta.xml
<CustomField>
    <fullName>Payment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Rescheduled From</label>
    <referenceTo>cmbls__Payment__c</referenceTo>
    <relationshipLabel>Payments (Payment)</relationshipLabel>
    <relationshipName>Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/cmbls__Payment__c/fields/Wells_Fargo_Payment_ID_Formula__c.field-meta.xml
<CustomField>
    <fullName>Wells_Fargo_Payment_ID_Formula__c</fullName>
    <description>Uses 'Record ID' if 'Wells Fargo Payment ID Override' is null</description>
    <formula>IF( ISBLANK( Wells_Fargo_Payment_ID_Override__c), Id , Wells_Fargo_Payment_ID_Override__c )</formula>
    <inlineHelpText>Uses 'Record ID' if 'Wells Fargo Payment ID Override' is null</inlineHelpText>
    <label>Wells Fargo Payment ID Formula</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/NF_ACH_Info__c/NF_ACH_Info__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>NF ACH Info</label>
</CustomObject>

unpackaged/main/default/objects/NF_ACH_Info__c/fields/Settlement_in_Business_day__c.field-meta.xml
<CustomField>
    <fullName>Settlement_in_Business_day__c</fullName>
    <defaultValue>0</defaultValue>
    <description>E.g. A settlement delay of “0” means the payments will settle on the effective date</description>
    <inlineHelpText>E.g. A settlement delay of “0” means the payments will settle on the effective date</inlineHelpText>
    <label>Settlement in Business day</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/WF_Api_Settings__c/WF_Api_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Wells Fargo API Settings</label>
</CustomObject>

unpackaged/main/default/objects/WF_Api_Settings__c/fields/Pre_Pending_Payments_in_Settlement_Delay__c.field-meta.xml
<CustomField>
    <fullName>Pre_Pending_Payments_in_Settlement_Delay__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If true, payments with a status of “Pre-Pending” will also be included in the settlement delay. If false, only payments with a status of “Pending” will be included in the settlement delay.</description>
    <inlineHelpText>If true, payments with a status of “Pre-Pending” will also be included in the settlement delay. If false, only payments with a status of “Pending” will be included in the settlement delay.</inlineHelpText>
    <label>Pre-Pending Payments in Settlement Delay</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/classes/BatchCheckACHTransactionStatus.cls
/**
 * BatchCheckACHTransactionStatus class
 * @author CloudMyBiz (r)
 * @date 07/02/2023
 * @info If you use a QueryLocator object, the governor limit for the total number of records retrieved by SOQL queries is bypassed
 * Use the iterable to create a complex scope for the batch job. You can also use the iterable to create your own custom process for iterating through the list.
  (If you use an iterable, the governor limit for the total number of records retrieved by SOQL queries is still enforced.)
 * @group Batch
 */
global class BatchCheckACHTransactionStatus implements Database.Batchable<SObject>, Schedulable, Database.AllowsCallouts{

    public static Integer batchSize = 5;
    private String objectType;
    private String accessToken;

    global BatchCheckACHTransactionStatus(){}

    global BatchCheckACHTransactionStatus(String objectType) {
        this.objectType = objectType;
    }

    global Iterable<SObject> start(Database.BatchableContext bc) {
        ACHTransactionIterator.queryType = ACHTransactionIterator.IteratorQueryType.SENT_TO_WF_ACH_TRANSACTIONS;
        return (Iterable<SObject>) new ACHTransactionIterator(this.objectType);
    }

    global void execute(Database.BatchableContext bc, List<ACH_Transaction_Log__c> scope) {

        this.accessToken = WellsFargoAPI.getAccessToken();
        WF_Api_Settings__c settings = WF_Api_Settings__c.getInstance();
        
        List<SObject> relatedRecordsForUpdate = new List<SObject>();
        List<ACH_Transaction_Log__c> logsForUpsert = new List<ACH_Transaction_Log__c>();
        for(ACH_Transaction_Log__c achOriginalLog : scope) {
            String transactionId = '';
            SObject relatedRecord;
            if (achOriginalLog.Payment__c != null) {
                relatedRecord = achOriginalLog.Payment__r;
                transactionId = achOriginalLog.Payment__r.Wells_Fargo_Payment_ID_Formula__c;
            } else if (achOriginalLog.Disbursement__c != null) {
                relatedRecord = achOriginalLog.Disbursement__r;
                transactionId = achOriginalLog.Disbursement__r.Wells_Fargo_Disbursement_ID_Formula__c;
            }

            WellsFargo achRequest = new WellsFargo();
            achRequest.record = relatedRecord;
            achRequest.token = this.accessToken;
            WellsFargoAPI.achPaymentStatusCheck(achRequest, transactionId);
            achRequest.achLog.setLookupField(achRequest.record.Id);
            logsForUpsert.add(achRequest.achLog.log);
    
            String recordStatus = (String)relatedRecord.get('cmbls__Status__c');
            Date recordEffectiveDate = (Date)relatedRecord.get('cmbls__Effective_Date__c');
            Date settlementDate = Date.today().addDays(NumberUtils.getInteger(NF_ACH_Info__c.getInstance().Settlement_in_Business_day__c));
            Boolean markAsSettled = settings.Pre_Pending_Payments_in_Settlement_Delay__c &&
                                    recordStatus == PaymentUtils.PAYMENT_STATUS_PRE_PENDING &&
                                    recordEffectiveDate != null && settlementDate <= recordEffectiveDate;
            
            // If we have an ACH Trace number means that payment was processed correctly.
            if(String.isNotBlank(achRequest.achLog?.log.ACH_Trace_Number__c) || markAsSettled){
                achOriginalLog.Status__c = Constant.ACH_TRANSACTION_LOG_STATUS_PENDING;
                if(markAsSettled){
                    relatedRecord.put('cmbls__Status__c', Constant.STATUS_SETTLED);
                    achOriginalLog.Status__c = Constant.ACH_TRANSACTION_LOG_STATUS_COMPLETED;
                    relatedRecordsForUpdate.add(relatedRecord);
                }
                logsForUpsert.add(achOriginalLog);
            }
        }
        upsert logsForUpsert;
        update relatedRecordsForUpdate;
    }

    global void finish(Database.BatchableContext bc) {

    }

    global void execute (SchedulableContext ctx) {
        Database.executeBatch(new BatchCheckACHTransactionStatus(cmbls__Disbursement__c.getSObjectType().getDescribe().getName()), BatchCheckACHTransactionStatus.batchSize);
        Database.executeBatch(new BatchCheckACHTransactionStatus(cmbls__Payment__c.getSObjectType().getDescribe().getName()), BatchCheckACHTransactionStatus.batchSize);
    }

}