unpackaged/main/default/objects/cmbls__Expense_Accrual__c/cmbls__Expense_Accrual__c.object-meta.xml
<CustomObject>
    <label>Expense Accrual</label>
    <nameField>
        <displayFormat>EA-{00000}</displayFormat>
        <label>Expense Accrual Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Expense Accruals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/cmbls__Expense_Accrual__c/fields/cmbls__Repayment__c.field-meta.xml
<CustomField>
    <fullName>cmbls__Repayment__c</fullName>
    <label>Repayment</label>
    <referenceTo>cmbls__Repayment__c</referenceTo>
    <relationshipLabel>Expense Accruals</relationshipLabel>
    <relationshipName>Expense_Accruals</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/cmbls__InterestAccrual__c/cmbls__InterestAccrual__c.object-meta.xml
<CustomObject>
    <label>Interest Accrual</label>
    <nameField>
        <displayFormat>Int-Accrual-{0000}</displayFormat>
        <label>Interest Accrual Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Interest Accruals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/cmbls__InterestAccrual__c/fields/cmbls__Repayment__c.field-meta.xml
<CustomField>
    <fullName>cmbls__Repayment__c</fullName>
    <inlineHelpText>Related Repayment ID</inlineHelpText>
    <label>Repayment</label>
    <referenceTo>cmbls__Repayment__c</referenceTo>
    <relationshipLabel>Interest Accruals</relationshipLabel>
    <relationshipName>Interest_Accruals</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/cmbls__Repayment__c/cmbls__Repayment__c.object-meta.xml
<CustomObject>
    <label>Repayment</label>
    <nameField>
        <displayFormat>RPMT-{0000000}</displayFormat>
        <label>Repayment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Repayments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/cmbls__Repayment__c/fields/Total_Broker_Fee_Expense__c.field-meta.xml
<CustomField>
    <fullName>Total_Broker_Fee_Expense__c</fullName>
    <label>Total Broker Fee Expense</label>
    <summarizedField>cmbls__Expense__c.cmbls__Amount__c</summarizedField>
    <summaryFilterItems>
        <field>cmbls__Expense__c.cmbls__Fee_Type__c</field>
        <operation>equals</operation>
        <value>Broker Fee</value>
    </summaryFilterItems>
    <summaryForeignKey>cmbls__Expense__c.cmbls__Repayment__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

unpackaged/main/default/objects/cmbls__Repayment__c/fields/Total_Fundera_RevShare__c.field-meta.xml
<CustomField>
    <fullName>Total_Fundera_RevShare__c</fullName>
    <label>Total Fundera RevShare</label>
    <summarizedField>cmbls__Expense__c.cmbls__Amount__c</summarizedField>
    <summaryFilterItems>
        <field>cmbls__Expense__c.cmbls__Fee_Type__c</field>
        <operation>equals</operation>
        <value>RevShare</value>
    </summaryFilterItems>
    <summaryFilterItems>
        <field>cmbls__Expense__c.Lead_Provider__c</field>
        <operation>equals</operation>
        <value>Fundera</value>
    </summaryFilterItems>
    <summaryForeignKey>cmbls__Expense__c.cmbls__Repayment__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

unpackaged/main/default/objects/cmbls__Repayment__c/fields/Total_LendingTree_RevShare__c.field-meta.xml
<CustomField>
    <fullName>Total_LendingTree_RevShare__c</fullName>
    <label>Total LendingTree RevShare</label>
    <summarizedField>cmbls__Expense__c.cmbls__Amount__c</summarizedField>
    <summaryFilterItems>
        <field>cmbls__Expense__c.cmbls__Fee_Type__c</field>
        <operation>equals</operation>
        <value>RevShare</value>
    </summaryFilterItems>
    <summaryFilterItems>
        <field>cmbls__Expense__c.Lead_Provider__c</field>
        <operation>equals</operation>
        <value>LendingTree</value>
    </summaryFilterItems>
    <summaryForeignKey>cmbls__Expense__c.cmbls__Repayment__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

unpackaged/main/default/objects/cmbls__Repayment__c/fields/Total_Origination_Fee_Expense__c.field-meta.xml
<CustomField>
    <fullName>Total_Origination_Fee_Expense__c</fullName>
    <label>Total Origination Fee Expense</label>
    <summarizedField>cmbls__Expense__c.cmbls__Amount__c</summarizedField>
    <summaryFilterItems>
        <field>cmbls__Expense__c.cmbls__Fee_Type__c</field>
        <operation>equals</operation>
        <value>Origination Fee</value>
    </summaryFilterItems>
    <summaryForeignKey>cmbls__Expense__c.cmbls__Repayment__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

unpackaged/main/default/objects/cmbls__Repayment__c/fields/Total_Strategic_Partner_RevShare__c.field-meta.xml
<CustomField>
    <fullName>Total_Strategic_Partner_RevShare__c</fullName>
    <label>Total Strategic Partner RevShare</label>
    <summarizedField>cmbls__Expense__c.cmbls__Amount__c</summarizedField>
    <summaryFilterItems>
        <field>cmbls__Expense__c.cmbls__Fee_Type__c</field>
        <operation>equals</operation>
        <value>RevShare</value>
    </summaryFilterItems>
    <summaryFilterItems>
        <field>cmbls__Expense__c.Lead_Provider__c</field>
        <operation>equals</operation>
        <value>Strategic Partner</value>
    </summaryFilterItems>
    <summaryForeignKey>cmbls__Expense__c.cmbls__Repayment__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

unpackaged/main/default/classes/PointInTimeCalculatedFormula.cls
/**
 * PointInTimeCalculatedFormula class
 * @author CloudMyBiz (r)
 * @date 11/25/2022
 * @description Service Class. Interface between business logic and specific apex contexts such as Trigger Handlers, Controllers, Batch Classes, API etc.
 * Services generally include static methods that implement business logic. Exceptions are generally thrown for the caller to handle.
 * @group Services
 */
global inherited sharing class PointInTimeCalculatedFormula extends cmbls.PointInTimeCalculatedField{

    public static final String INTEREST_ACCRUAL_TOTAL_ACCRUED_FIELD = 'Interest_Accrual_Total_Accrued';
    public static final String ORIGINATION_EXPENSE_TOTAL_ACCRUED_FIELD = 'Origination_Expense_Total_Accrued';
    public static final String BROKER_EXPENSE_TOTAL_ACCRUED_FIELD = 'Broker_Expense_Total_Accrued';
    public static final String REV_SHARE_EXPENSE_TOTAL_ACCRUED_FIELD = 'RevShare_Expense_Total_Accrued';
    public static final String INTEREST_ACCRUAL_REMAINING_FIELD = 'Interest_Accrual_Remaining';
    public static final String ORIGINATION_EXPENSE_REMAINING_FIELD = 'Origination_Expense_Remaining';
    public static final String BROKER_EXPENSE_REMAINING_FIELD = 'Broker_Expense_Remaining';
    public static final String REV_SHARE_EXPENSE_REMAINING_FIELD = 'RevShare_Expense_Remaining';

    global override Object execute(Map<String, Object> context, SObject record, String fieldApiName){
        if(isRepayment(record)){
            cmbls__Repayment__c repayment = (cmbls__Repayment__c)record;
            if(INTEREST_ACCRUAL_REMAINING_FIELD.equalsIgnoreCase(fieldApiName)){
                return NumberUtils.getDecimal(repayment.cmbls__Interest__c) - NumberUtils.getDecimal((Decimal)context.get(INTEREST_ACCRUAL_TOTAL_ACCRUED_FIELD));
            }else if(ORIGINATION_EXPENSE_REMAINING_FIELD.equalsIgnoreCase(fieldApiName)){
                return NumberUtils.getDecimal(repayment.Total_Origination_Fee_Expense__c) - NumberUtils.getDecimal((Decimal)context.get(ORIGINATION_EXPENSE_TOTAL_ACCRUED_FIELD)).setScale(2);
            }else if(BROKER_EXPENSE_REMAINING_FIELD.equalsIgnoreCase(fieldApiName)){
                return NumberUtils.getDecimal(repayment.Total_Broker_Fee_Expense__c) - NumberUtils.getDecimal((Decimal)context.get(BROKER_EXPENSE_TOTAL_ACCRUED_FIELD)).setScale(2);
            }else if(REV_SHARE_EXPENSE_REMAINING_FIELD.equalsIgnoreCase(fieldApiName)){
                Decimal revShare =  NumberUtils.getDecimal(repayment.Total_Fundera_RevShare__c) +
                        NumberUtils.getDecimal(repayment.Total_LendingTree_RevShare__c) +
                        NumberUtils.getDecimal(repayment.Total_Strategic_Partner_RevShare__c);

                return revShare - NumberUtils.getDecimal((Decimal)context.get(REV_SHARE_EXPENSE_TOTAL_ACCRUED_FIELD)).setScale(2);
            }
        }
        return null;
    }

    global override Boolean filter(SObject record, String fieldApiName){
        Boolean result = false;
        if(!isValidObject(record)) return result;
        if(isInterestAccrual(record)){
            if(INTEREST_ACCRUAL_TOTAL_ACCRUED_FIELD.equalsIgnoreCase(fieldApiName)){
                result = true;
            }
        }else if(isExpenseAccrual(record)){
            cmbls__Expense_Accrual__c expenseAccrual = (cmbls__Expense_Accrual__c)record;
            if(ORIGINATION_EXPENSE_TOTAL_ACCRUED_FIELD.equalsIgnoreCase(fieldApiName)){
                result = expenseAccrual.cmbls__Expense__r.cmbls__Fee_Type__c == RepaymentUtils.ORIGINATION_FEE;
            }else if(BROKER_EXPENSE_TOTAL_ACCRUED_FIELD.equalsIgnoreCase(fieldApiName)){
                result = expenseAccrual.cmbls__Expense__r.cmbls__Fee_Type__c == RepaymentUtils.BROKER_FEE;
            }else if(REV_SHARE_EXPENSE_TOTAL_ACCRUED_FIELD.equalsIgnoreCase(fieldApiName)){
                result = expenseAccrual.cmbls__Expense__r.cmbls__Fee_Type__c == RepaymentUtils.REV_SHARE_FEE;
            }
        }
        return result;
    }

    private static Boolean isValidObject(SObject record){
        return  record != null && (isExpenseAccrual(record) || isInterestAccrual(record));
    }

    private static Boolean isExpenseAccrual(SObject record){
        return record.Id.getSobjectType() == cmbls__Expense_Accrual__c.getSObjectType();
    }

    private static Boolean isInterestAccrual(SObject record){
        return record.Id.getSobjectType() == cmbls__InterestAccrual__c.getSObjectType();
    }

    private static Boolean isRepayment(SObject record){
        return record.Id.getSobjectType() == cmbls__Repayment__c.getSObjectType();
    }
}