unpackaged/main/default/objects/Bank_Data__c/Bank_Data__c.object-meta.xml
<CustomObject>
    <label>Bank Data</label>
    <nameField>
        <displayFormat>BD-{0}</displayFormat>
        <label>Bank_Data</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bank Data</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Bank_Data__c/fields/Encrypted_Email_String__c.field-meta.xml
<CustomField>
    <fullName>Encrypted_Email_String__c</fullName>
    <label>Encrypted Email String</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/DLP_Email_Status__c.field-meta.xml
<CustomField>
    <fullName>DLP_Email_Status__c</fullName>
    <description>Status of DLP Emails - can be automatic or single end.</description>
    <label>DLP Email Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Prequal DocuSign Complete</fullName>
            </value>
            <value>
                <fullName>Prequal Bank Statements Uploaded</fullName>
            </value>
            <value>
                <fullName>Driver's License Uploaded</fullName>
            </value>
            <value>
                <fullName>Voided Check Uploaded</fullName>
            </value>
            <value>
                <fullName>Drip Campaign Started</fullName>
            </value>
            <value>
                <fullName>DLP Drip Activated</fullName>
            </value>
            <value>
                <fullName>DLP Email Sent</fullName>
            </value>
            <value>
                <fullName>DLP Drip Deactivated</fullName>
            </value>
            <value>
                <fullName>DLP Drip Campaign Ended</fullName>
            </value>
            <value>
                <fullName>Prequal Application Signing Complete</fullName>
            </value>
            <value>
                <fullName>DLP Page 1 Complete</fullName>
            </value>
            <value>
                <fullName>DLP Page 2 Complete</fullName>
            </value>
            <value>
                <fullName>Email Link Clicked</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Encrypted_Email_String__c.field-meta.xml
<CustomField>
    <fullName>Encrypted_Email_String__c</fullName>
    <label>Encrypted Email String</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Encrypted_Email_String_Refresh_Date__c.field-meta.xml
<CustomField>
    <fullName>Encrypted_Email_String_Refresh_Date__c</fullName>
    <label>Encrypted Email String Refresh Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Lead/fields/DLP_Email_Status__c.field-meta.xml
<CustomField>
    <fullName>DLP_Email_Status__c</fullName>
    <label>DLP Email Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Prequal DocuSign Complete</fullName>
            </value>
            <value>
                <fullName>Prequal Bank Statements Uploaded</fullName>
            </value>
            <value>
                <fullName>Driver's License Uploaded</fullName>
            </value>
            <value>
                <fullName>Voided Check Uploaded</fullName>
            </value>
            <value>
                <fullName>Drip Campaign Started</fullName>
            </value>
            <value>
                <fullName>DLP Drip Activated</fullName>
            </value>
            <value>
                <fullName>DLP Email Sent</fullName>
            </value>
            <value>
                <fullName>DLP Drip Deactivated</fullName>
            </value>
            <value>
                <fullName>DLP Drip Campaign Ended</fullName>
            </value>
            <value>
                <fullName>Prequal Application Signing Complete</fullName>
            </value>
            <value>
                <fullName>DLP Page 1 Complete</fullName>
            </value>
            <value>
                <fullName>DLP Page 2 Complete</fullName>
            </value>
            <value>
                <fullName>Email Link Clicked</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Lead/fields/National_Funding_WebId__c.field-meta.xml
<CustomField>
    <fullName>National_Funding_WebId__c</fullName>
    <displayFormat>NFS-{000000}</displayFormat>
    <externalId>true</externalId>
    <label>National Funding WebId</label>
    <type>AutoNumber</type>
</CustomField>

unpackaged/main/default/objects/Lead/fields/Originating_Brand__c.field-meta.xml
<CustomField>
    <fullName>Originating_Brand__c</fullName>
    <description>Introduced as part of the Quick Bridge to National Funding migration project to capture which brand the response originally came from. Inserted by LeadGen.</description>
    <inlineHelpText>Displays which brand this lead was originally sourced from</inlineHelpText>
    <label>Originating Brand</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Originating_Brand</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Lead/fields/Web_Id_NatFund__c.field-meta.xml
<CustomField>
    <fullName>Web_Id_NatFund__c</fullName>
    <description>This field will be the unique record identifier for leads that are created from nationalfunding.com.  This field will be populated on create and subsequently when the customer completes steps of the application. For de-duping, the field in the new lead should overwrite the existing value.</description>
    <externalId>true</externalId>
    <inlineHelpText>This field should not be edited.</inlineHelpText>
    <label>Web Id NatFund</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/User/fields/Available_Brands__c.field-meta.xml
<CustomField>
    <fullName>Available_Brands__c</fullName>
    <description>Introduced as part of the Quick Bridge to National Funding migration project to capture which brands this user works for. Originally all users will have one available brand but this is being created as a multi select picklist with the possibility that reps can work under multiple brands in the future.</description>
    <inlineHelpText>Which brand does this user work under?</inlineHelpText>
    <label>Available Brands</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>National Funding</fullName>
                <default>true</default>
                <label>National Funding</label>
            </value>
            <value>
                <fullName>Quick Bridge</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/globalValueSets/Originating_Brand.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>National Funding</fullName>
    </customValue>
    <customValue>
        <fullName>Quick Bridge</fullName>
    </customValue>
    <customValue>
        <fullName>National Funding XPRS</fullName>
    </customValue>
    <description>Introduced as part of the Quick Bridge to National Funding migration project to capture which brand the response originally came from. Inserted by LeadGen.</description>
    <masterLabel>Originating Brand</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/SendDLPRequestLead.cls
public with sharing class SendDLPRequestLead {

    private Apexpages.StandardController con;
    private Apexpages.StandardController ld;
    public List<LeadWrapper> Leads { get; set; }
    private Map<Id, Lead> contactsWithoutEmail;
    private transient List<Messaging.SingleEmailMessage> emails;
    public Id leadId;
    private Id templateId;
    private Id templateId2;
    public Id pLead;
    public String pName;
    public String nfId;
    public String encId;
    public String data {get;set;}
    
    public SendDLPRequestLead(Apexpages.StandardController con){
        this.con = con;
        leadId = this.con.getId();
        System.debug('Nat_Fund_WebId__c =======> ' + ApexPages.currentPage().getParameters().get('webId'));
        if(ApexPages.currentPage().getParameters().get('webId') == ''){ throw new GenericException('Missing NF Web ID Please Update for LeadId: ' + leadId); }
        Init();
    }

    private void Init(){
        Leads = new List<LeadWrapper>();
        contactsWithoutEmail = new Map<Id, Lead>();

        for(Lead c : [Select Id, Name, Email, Encrypted_Email_String__c, Web_Id_NatFund__c, National_Funding_WebId__c, DLP_Email_Status__c, HasOptedOutOfEmail  From Lead Where Id =: leadId]){
            System.debug('test c.iD ==>' + c.Id);
            pLead = c.Id;
            if(c.Web_Id_NatFund__c != NULL){
                nfId = c.Web_Id_NatFund__c;
                encId = c.Web_Id_NatFund__c;
            }
            else{
                nfId = c.National_Funding_WebId__c;
                encId = c.National_Funding_WebId__c;
            }
            Leads.Add(new LeadWrapper(c, (c.Email != null)));
        }
    }

    public List<SelectOption> getItems() {
        String e = [Select Id, DLP_Email_Status__c From Lead Where Id=: pLead].DLP_Email_Status__c;
        if(e == NULL  || e == 'DLP Email Sent' ){
            List<SelectOption> options = new List<SelectOption>();
            options.add(new SelectOption('DLP Email Sent','Not Active'));
            options.add(new SelectOption('DLP Drip Activated','Start'));
            return options;
        }
        if(e == 'DLP Drip Activated'){
            List<SelectOption> options = new List<SelectOption>();
            options.add(new SelectOption('DLP Drip Activated','Activated'));
            options.add(new SelectOption('DLP Drip Deactivated','Stop'));

            return options;
        }
        else{
            List<SelectOption> options = new List<SelectOption>();
            options.add(new SelectOption('DLP Drip Deactivated','Deactivated'));
            options.add(new SelectOption('DLP Drip Activated','Start'));
            return options;
        }
    }

    public pageReference SendEmail(){
        try {
            emails = new List<Messaging.SingleEmailMessage>();
            List<EmailTemplate> et = [SELECT id FROM EmailTemplate WHERE developerName IN('Automated_Yodlee_Email', 'Loan_Modification_Request') Order By NAME asc];
            if(et.size() > 0){
                templateId = et[0].Id;
                System.debug('I am supposed to be new application' + templateId);
                templateId2 = et[1].Id;
            }

            integer selectedLeads = 0;
            //list for the contacts that didn't had email previously and user has just provided.
            List<Lead> contactEmailsToUpdate = new List<Lead>();

            string activityDescription = '--- Automated Yodlee Email ---';
            activityDescription += '\nSent to: ';
            for(LeadWrapper c : Leads){
                System.debug('contact y ' + c.Lead.Id);

                if(c.IsSelected == true){
                    if(c.Lead.HasOptedOutOfEmail) { throw new GenericException(c.Lead.Name + ' has opted out of email at this time'); }
                    pLead = c.Lead.Id;
                    pName = c.Lead.Name;

                    if(c.Lead.Email == null){
                        throw new GenericException('Please provide email address for: '+c.Lead.Name);
                        if(nfId == null){
                            throw new GenericException('Missing NF Web ID Please Update for: ' + c.Lead.Name);
                        }
                    } else if(!c.HasEmail) {
                        contactEmailsToUpdate.Add(c.Lead);
                    }
                    selectedLeads++;
                }
            }

            if(selectedLeads == 0){
                throw new GenericException('Please select atleast 1 lead');
            }

            //need to update these contacts, else the send email will not work with template targetId of contactId.
            if(contactEmailsToUpdate.size() > 0){
                update contactEmailsToUpdate;
            }

            List<Bank_Data__c> bankDataToUpdate = new List<Bank_Data__c>();
            integer selectedBanks = 0;
            activityDescription += '\nBank Accounts requested access to: ';

            String tokenCred;
            String qbTokenCred;
            String nfTokenCred;
            String brand;
            String sourceOrg = 'National Funding';
            Boolean userHasBothBrands = false;
            User userInfo = new User();

            Lead leadRec = [SELECT Id, OwnerId, Web_Id_NatFund__c, Originating_Brand__c, Encrypted_Email_String_Refresh_Date__c FROM LEAD WHERE Id =: pLead];
            if(leadRec == null) { throw new GenericException('Lead record cannot be found.'); }

            if(leadRec.ownerId != null) {
                //owned by a user
                if (leadRec.OwnerId.getSObjectType() == Schema.User.SObjectType) {
                    userInfo = [Select Id, Available_Brands__c From User Where Id =:leadRec.OwnerId];
                    if(userInfo?.Available_Brands__c != null) {
                        if(userInfo.Available_Brands__c.contains('Quick Bridge') && userInfo.Available_Brands__c.contains('National Funding')) {
                            userHasBothBrands = true;
                        }
                        else if(userInfo.Available_Brands__c.contains('Quick Bridge')) {
                            brand = 'Quick Bridge';
                        }
                        else if(userInfo.Available_Brands__c.contains('National Funding')) {
                            brand = 'National Funding';
                        }
                    } else {
                        brand = 'National Funding';
                    }
                }
                else {
                    //if not owned by a user, we are checking the originating brand field on lead and if that is null, we are defaulting to generating both tokens
                    if(leadRec.Originating_Brand__c != null) {
                         brand = leadRec.Originating_Brand__c;
                    } else {
                        userHasBothBrands = true;
                    }
                }
            }

            if(userHasBothBrands) {
                qbTokenCred = ConsoleApplicationLinkController.getShortenedLink(pLead, nfId, sourceOrg, 'Quick Bridge');
                nfTokenCred = ConsoleApplicationLinkController.getShortenedLink(pLead, nfId, sourceOrg, 'National Funding');
                if(qbTokenCred.startsWith('This service is temporarily unavailable.') || nfTokenCred.startsWith('This service is temporarily unavailable.')){
                    throw new GenericException('This service is temporarily unavailable.');
                }
                HelperClass.upsertDFPToken(pLead, 'Quick Bridge', qbTokenCred);
                HelperClass.upsertDFPToken(pLead, 'National Funding', nfTokenCred);
                return new pageReference('/apex/DLPEmailLinkUpdateSvc?id='+pLead+'&tokencred='+nfTokenCred+'&data='+data+'&ptype=lead');
            }
            else {
                tokencred = ConsoleApplicationLinkController.getShortenedLink(pLead, nfId, sourceOrg, brand); 
                if(tokencred == 'This service is temporarily unavailable.') {
                    throw new GenericException('This service is temporarily unavailable. ');
                }
                HelperClass.upsertDFPToken(pLead, brand, tokencred);
                return new pageReference('/apex/DLPEmailLinkUpdateSvc?id='+pLead+'&tokencred='+tokencred+'&data='+data+'&ptype=lead');
            }
        } catch (Exception ex) {
            Apexpages.addMessages(ex);
            return null;
        }
    }

    //********************************************************************************************
    public class LeadWrapper {
        public boolean IsSelected { get; set; }
        public Lead Lead { get; set; }
        public boolean HasEmail { get; set; }

        public LeadWrapper(Lead c, boolean hasEmail){
            Lead = c;
            IsSelected = true;
            this.HasEmail = hasEmail;
        }
    }
}