unpackaged/main/default/objects/cmbls__Loan_Servicing_Settings__c/cmbls__Loan_Servicing_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Loan Servicing Settings</label>
</CustomObject>

unpackaged/main/default/objects/cmbls__Loan_Servicing_Settings__c/fields/RSNextPaymentDateBatch_Size__c.field-meta.xml
<CustomField>
    <fullName>RSNextPaymentDateBatch_Size__c</fullName>
    <label>RSNextPaymentDateBatch Size</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/cmbls__Loan_Servicing_Triggers__c/cmbls__Loan_Servicing_Triggers__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Loan Servicing Triggers</label>
</CustomObject>

unpackaged/main/default/objects/cmbls__Repayment__c/cmbls__Repayment__c.object-meta.xml
<CustomObject>
    <label>Repayment</label>
    <nameField>
        <displayFormat>RPMT-{0000000}</displayFormat>
        <label>Repayment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Repayments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/cmbls__Repayment__c/fields/cmbls__Status__c.field-meta.xml
<CustomField>
    <fullName>cmbls__Status__c</fullName>
    <description>Active, pause, complete, and new</description>
    <inlineHelpText>Active, pause, complete, and new</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Temporary Pause</fullName>
            </value>
            <value>
                <fullName>Pause</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Write Off</fullName>
            </value>
            <value>
                <fullName>Recovery</fullName>
            </value>
            <value>
                <fullName>Unwind</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/cmbls__Repayment_Schedule__c/cmbls__Repayment_Schedule__c.object-meta.xml
<CustomObject>
    <label>Repayment Schedule</label>
    <nameField>
        <displayFormat>RS-{000000}</displayFormat>
        <label>Repayment Schedule</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Repayment Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/cmbls__Repayment_Schedule__c/fields/cmbls__Next_Payment_Date__c.field-meta.xml
<CustomField>
    <fullName>cmbls__Next_Payment_Date__c</fullName>
    <inlineHelpText>This is the Effective Date of the next ACH payment that will be created by the Repayment Schedule. This field is populated and updated by the system based on the current values in the Repayment Schedule. Note: This will always roll forward to the next valid business day if it falls on a holiday or weekend.</inlineHelpText>
    <label>Next Payment Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/cmbls__Repayment_Schedule__c/fields/cmbls__Payment_Amount_Method__c.field-meta.xml
<CustomField>
    <fullName>cmbls__Payment_Amount_Method__c</fullName>
    <inlineHelpText>Loans in Recovery - Use "Remaining Settlement Balance", otherwise use "Fixed Amount"</inlineHelpText>
    <label>Payment Amount Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Fixed Amount</fullName>
                <default>true</default>
                <label>Fixed Amount</label>
            </value>
            <value>
                <fullName>Active Invoice Balance</fullName>
            </value>
            <value>
                <fullName>Remaining Settlement Balance</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/cmbls__Repayment_Schedule__c/fields/cmbls__Repayment__c.field-meta.xml
<CustomField>
    <fullName>cmbls__Repayment__c</fullName>
    <label>Repayment</label>
    <referenceTo>cmbls__Repayment__c</referenceTo>
    <relationshipLabel>Repayment Schedules</relationshipLabel>
    <relationshipName>Repayment_Schedules</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/cmbls__Repayment_Schedule__c/fields/cmbls__Start_Date__c.field-meta.xml
<CustomField>
    <fullName>cmbls__Start_Date__c</fullName>
    <inlineHelpText>This is the first date the system will start evaluating this Repayment Schedule to begin creating ACH payments. NOTE: This must be at least one day before the Next Payment Date and should also be a business day</inlineHelpText>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/classes/RepaymentScheduleTriggerTest.cls
/**
 * RepaymentScheduleTriggerTest class
 * @author CloudMyBiz (r)
 * @date 8/15/2023
 */

@IsTest
private class RepaymentScheduleTriggerTest{
    
    @TestSetup static void setupMethod(){
        cmbls__Loan_Servicing_Settings__c settings = new cmbls__Loan_Servicing_Settings__c();
        settings.RSNextPaymentDateBatch_Size__c = 100;
        settings.cmbls__Allow_Multi_Schedule__c = true;
        insert settings;
        
        cmbls__Loan_Servicing_Triggers__c triggerSettings = cmbls__Loan_Servicing_Triggers__c.getOrgDefaults();
        triggerSettings.cmbls__Disable_Repayment_Schedule_Trigger__c = true;
        upsert triggerSettings;
        
        Account acc = TestDataFactory.createAccount();
        insert acc;
        
        cmbls__Repayment__c repayment = TestDataFactory.createRepayment(acc.Id);
        insert repayment;
        
        delete [SELECT Id FROM cmbls__Repayment_Schedule__c];
    }
    
    @IsTest
    static void insertOneRecord(){
        cmbls__Repayment__c repayment = [SELECT Id, RecordType.Name FROM cmbls__Repayment__c];
        repayment.cmbls__Status__c = RepaymentUtils.STATUS_WRITE_OFF;
        update repayment;
        cmbls__Repayment_Schedule__c record = TestDataFactory.createRepaymentSchedule(repayment.Id);
        record.cmbls__Start_Date__c = Date.newInstance(2023,1,1);
        record.cmbls__Next_Payment_Date__c = Date.newInstance(2023,8,5); //Saturday
        record.cmbls__Payment_Amount_Method__c = 'Fixed Amount';

        Test.startTest();
        Database.insert(record);
        Test.stopTest();
        
        record = [SELECT Id, cmbls__Next_Payment_Date__c, cmbls__Payment_Amount_Method__c FROM cmbls__Repayment_Schedule__c WHERE Id = :record.Id];
        Assert.areEqual(Date.newInstance(2023,8,7), record.cmbls__Next_Payment_Date__c);
        Assert.areEqual(RepaymentUtils.PAYMENT_AMOUNT_METHOD_REMAINING, record.cmbls__Payment_Amount_Method__c);

        repayment = [SELECT Id, cmbls__Status__c FROM cmbls__Repayment__c WHERE Id = :repayment.Id];
        Assert.areEqual(RepaymentUtils.STATUS_RECOVERY, repayment.cmbls__Status__c);
    }
    
    @IsTest
    static void insertMultipleRecords(){
        cmbls__Repayment__c repayment = [SELECT Id, RecordType.Name FROM cmbls__Repayment__c];
        cmbls__Repayment_Schedule__c[] records = new cmbls__Repayment_Schedule__c[]{};
        for(Integer i = 0; i < 100;i++){
            cmbls__Repayment_Schedule__c record = TestDataFactory.createRepaymentSchedule(repayment.Id);
            record.cmbls__Start_Date__c = Date.newInstance(2023,1,1);
            record.cmbls__Next_Payment_Date__c = Date.newInstance(2023,8,5); //Saturday
            records.add(record);
        }
        
        Test.startTest();
        Database.insert(records);
        Test.stopTest();
        
        for(cmbls__Repayment_Schedule__c record :[SELECT cmbls__Next_Payment_Date__c FROM cmbls__Repayment_Schedule__c]){
            Assert.areEqual(Date.newInstance(2023,8,7), record.cmbls__Next_Payment_Date__c);
        }
    }
    
    @IsTest
    static void updateOneRecord(){
        cmbls__Repayment__c repayment = [SELECT Id, RecordType.Name FROM cmbls__Repayment__c];
        cmbls__Repayment_Schedule__c record = TestDataFactory.createRepaymentSchedule(repayment.Id);
        record.cmbls__Start_Date__c = Date.newInstance(2023,1,1);
        record.cmbls__Next_Payment_Date__c = Date.newInstance(2023,8,4); //Friday
        RepaymentScheduleTriggerHandler.RUN_NEXT_PAYMENT_DATE_VALIDATION = false;
        Database.insert(record);
        
        Test.startTest();
        RepaymentScheduleTriggerHandler.RUN_NEXT_PAYMENT_DATE_VALIDATION = true;
        record.cmbls__Next_Payment_Date__c = Date.newInstance(2023,8,5); //Saturday
        update record;
        Test.stopTest();
        
        record = [SELECT Id, cmbls__Next_Payment_Date__c FROM cmbls__Repayment_Schedule__c WHERE Id = :record.Id];
        Assert.areEqual(Date.newInstance(2023,8,7), record.cmbls__Next_Payment_Date__c);
    }
    
    @IsTest
    static void updateMultipleRecords(){
        cmbls__Repayment__c repayment = [SELECT Id, RecordType.Name FROM cmbls__Repayment__c];
        cmbls__Repayment_Schedule__c[] records = new cmbls__Repayment_Schedule__c[]{};
        for(Integer i = 0; i < 100;i++){
            cmbls__Repayment_Schedule__c record = TestDataFactory.createRepaymentSchedule(repayment.Id);
            record.cmbls__Start_Date__c = Date.newInstance(2023,1,1);
            record.cmbls__Next_Payment_Date__c = Date.newInstance(2023,8,4); //Friday
            records.add(record);
        }
        Database.insert(records);
        
        Test.startTest();
        RepaymentScheduleTriggerHandler.RUN_NEXT_PAYMENT_DATE_VALIDATION = true;
        for(cmbls__Repayment_Schedule__c record :records){
            record.cmbls__Next_Payment_Date__c = Date.newInstance(2023,8,5); //Saturday
        }
        Database.update(records);
        Test.stopTest();
        
        for(cmbls__Repayment_Schedule__c record :[SELECT cmbls__Next_Payment_Date__c FROM cmbls__Repayment_Schedule__c]){
            Assert.areEqual(Date.newInstance(2023,8,7), record.cmbls__Next_Payment_Date__c);
        }
    }
    
    @IsTest
    static void flagOnFalse(){
        cmbls__Repayment__c repayment = [SELECT Id, RecordType.Name FROM cmbls__Repayment__c];
        cmbls__Repayment_Schedule__c record = TestDataFactory.createRepaymentSchedule(repayment.Id);
        record.cmbls__Start_Date__c = Date.newInstance(2023,1,1);
        record.cmbls__Next_Payment_Date__c = Date.newInstance(2023,8,5); //Saturday
        
        Test.startTest();
        RepaymentScheduleTriggerHandler.RUN_NEXT_PAYMENT_DATE_VALIDATION = false;
        Database.insert(record);
        Test.stopTest();
        
        record = [SELECT Id, cmbls__Next_Payment_Date__c FROM cmbls__Repayment_Schedule__c WHERE Id = :record.Id];
        Assert.areEqual(Date.newInstance(2023,8,5), record.cmbls__Next_Payment_Date__c);
    }
}