unpackaged/main/default/objects/cmbls__Loan_Servicing_Settings__c/cmbls__Loan_Servicing_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Loan Servicing Settings</label>
</CustomObject>

unpackaged/main/default/objects/cmbls__Loan_Servicing_Settings__c/fields/RSNextPaymentDateBatch_Size__c.field-meta.xml
<CustomField>
    <fullName>RSNextPaymentDateBatch_Size__c</fullName>
    <label>RSNextPaymentDateBatch Size</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/cmbls__Loan_Servicing_Triggers__c/cmbls__Loan_Servicing_Triggers__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Loan Servicing Triggers</label>
</CustomObject>

unpackaged/main/default/objects/cmbls__Repayment__c/cmbls__Repayment__c.object-meta.xml
<CustomObject>
    <label>Repayment</label>
    <nameField>
        <displayFormat>RPMT-{0000000}</displayFormat>
        <label>Repayment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Repayments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/cmbls__Repayment_Schedule__c/cmbls__Repayment_Schedule__c.object-meta.xml
<CustomObject>
    <label>Repayment Schedule</label>
    <nameField>
        <displayFormat>RS-{000000}</displayFormat>
        <label>Repayment Schedule</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Repayment Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/cmbls__Repayment_Schedule__c/fields/cmbls__Next_Payment_Date__c.field-meta.xml
<CustomField>
    <fullName>cmbls__Next_Payment_Date__c</fullName>
    <inlineHelpText>This is the Effective Date of the next ACH payment that will be created by the Repayment Schedule. This field is populated and updated by the system based on the current values in the Repayment Schedule. Note: This will always roll forward to the next valid business day if it falls on a holiday or weekend.</inlineHelpText>
    <label>Next Payment Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/cmbls__Repayment_Schedule__c/fields/cmbls__Repayment__c.field-meta.xml
<CustomField>
    <fullName>cmbls__Repayment__c</fullName>
    <label>Repayment</label>
    <referenceTo>cmbls__Repayment__c</referenceTo>
    <relationshipLabel>Repayment Schedules</relationshipLabel>
    <relationshipName>Repayment_Schedules</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/cmbls__Repayment_Schedule__c/fields/cmbls__Start_Date__c.field-meta.xml
<CustomField>
    <fullName>cmbls__Start_Date__c</fullName>
    <inlineHelpText>This is the first date the system will start evaluating this Repayment Schedule to begin creating ACH payments. NOTE: This must be at least one day before the Next Payment Date and should also be a business day</inlineHelpText>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/classes/RSNextPaymentDateBatchTest.cls
/**
 * RSNextPaymentDateBatchTest class
 * @author CloudMyBiz (r)
 * @date 8/15/2023
 */

@IsTest
private class RSNextPaymentDateBatchTest{
    
    @TestSetup static void setupMethod(){
        cmbls__Loan_Servicing_Settings__c settings = new cmbls__Loan_Servicing_Settings__c();
        settings.cmbls__Allow_Multi_Schedule__c = true;
        settings.RSNextPaymentDateBatch_Size__c = 100;
        insert settings;
        
        cmbls__Loan_Servicing_Triggers__c triggerSettings = cmbls__Loan_Servicing_Triggers__c.getOrgDefaults();
        triggerSettings.cmbls__Disable_Repayment_Schedule_Trigger__c = true;
        upsert triggerSettings;
        
        Account acc = TestDataFactory.createAccount();
        insert acc;
        
        cmbls__Repayment__c repayment = TestDataFactory.createRepayment(acc.Id);
        insert repayment;
        
        delete [SELECT Id FROM cmbls__Repayment_Schedule__c];
    }
    
    @IsTest
    static void behavior(){
        cmbls__Repayment__c repayment = [SELECT Id, RecordType.Name FROM cmbls__Repayment__c];
        cmbls__Repayment_Schedule__c[] records = new cmbls__Repayment_Schedule__c[]{};
        for(Integer i = 0; i < 100;i++){
            cmbls__Repayment_Schedule__c record = TestDataFactory.createRepaymentSchedule(repayment.Id);
            record.cmbls__Start_Date__c = Date.newInstance(2023,1,1);
            record.cmbls__Next_Payment_Date__c = Date.newInstance(2023,8,5); //Saturday
            records.add(record);
        }
        
        RepaymentScheduleTriggerHandler.RUN_NEXT_PAYMENT_DATE_VALIDATION = false;
        Database.insert(records);
        Set<Id> recordIds = new Set<Id>();
        for(cmbls__Repayment_Schedule__c record :[SELECT Id, cmbls__Next_Payment_Date__c FROM cmbls__Repayment_Schedule__c]){
            recordIds.add(record.Id);
            Assert.areEqual(Date.newInstance(2023,8,5), record.cmbls__Next_Payment_Date__c);
        }
        
        Test.startTest();
        Database.executeBatch(new RSNextPaymentDateBatch(recordIds), RSNextPaymentDateBatch.getBatchSize());
        Test.stopTest();
        
        for(cmbls__Repayment_Schedule__c record :[SELECT cmbls__Next_Payment_Date__c FROM cmbls__Repayment_Schedule__c]){
            Assert.areEqual(Date.newInstance(2023,8,7), record.cmbls__Next_Payment_Date__c);
        }
    }
}