unpackaged/main/default/objects/cmbls__Loan_Servicing_Settings__c/cmbls__Loan_Servicing_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Loan Servicing Settings</label>
</CustomObject>

unpackaged/main/default/objects/cmbls__Payment__c/cmbls__Payment__c.object-meta.xml
<CustomObject>
    <label>Payment</label>
    <nameField>
        <displayFormat>PMT-{0000}</displayFormat>
        <label>Payment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/cmbls__Payment__c/fields/cmbls__Effective_Date__c.field-meta.xml
<CustomField>
    <fullName>cmbls__Effective_Date__c</fullName>
    <inlineHelpText>Effective Date</inlineHelpText>
    <label>Effective Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/cmbls__Payment__c/fields/cmbls__Repayment__c.field-meta.xml
<CustomField>
    <fullName>cmbls__Repayment__c</fullName>
    <label>Repayment</label>
    <referenceTo>cmbls__Repayment__c</referenceTo>
    <relationshipLabel>Payments</relationshipLabel>
    <relationshipName>Payments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/cmbls__Payment__c/fields/cmbls__Status__c.field-meta.xml
<CustomField>
    <fullName>cmbls__Status__c</fullName>
    <inlineHelpText>Scheduled: Created and not submitted
Pending: Submitted to the ACH provider, but not yet settled.
Settled: The ACH payment was pulled successfully from the customer's account
Failed: Returned a failed response from the ACH provider</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>cmbls__Transaction_Type__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>Pre-Pending</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Settled</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Fees Applied</fullName>
            </value>
            <value>
                <fullName>Fees Collected</fullName>
            </value>
            <value>
                <fullName>Fees Reversed</fullName>
            </value>
            <value>
                <fullName>Applied</fullName>
            </value>
            <value>
                <fullName>Sent Error</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/cmbls__Payment__c/fields/cmbls__Transaction_Amount__c.field-meta.xml
<CustomField>
    <fullName>cmbls__Transaction_Amount__c</fullName>
    <label>Transaction Amount</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/cmbls__Payment__c/fields/cmbls__Transaction_Type__c.field-meta.xml
<CustomField>
    <fullName>cmbls__Transaction_Type__c</fullName>
    <description>This field indicates wether if it is a Fee or a Payment, and should be displayed in the page detail layout.</description>
    <inlineHelpText>This field indicates wether if it is a Fee or a Payment, and should be displayed in the page detail layout.</inlineHelpText>
    <label>Transaction Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Fee</fullName>
            </value>
            <value>
                <fullName>Payment</fullName>
            </value>
            <value>
                <fullName>Adjustment</fullName>
            </value>
            <value>
                <fullName>Distribution</fullName>
            </value>
            <value>
                <fullName>Fee Collection</fullName>
            </value>
            <value>
                <fullName>Reserve</fullName>
            </value>
            <value>
                <fullName>Interest</fullName>
            </value>
            <value>
                <fullName>Draw</fullName>
            </value>
            <value>
                <fullName>Draw Reserve</fullName>
            </value>
            <value>
                <fullName>Deferred Fee</fullName>
            </value>
            <value>
                <fullName>Lender Reimbursement</fullName>
            </value>
            <value>
                <fullName>Discount</fullName>
            </value>
            <value>
                <fullName>Payoff</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/cmbls__Repayment__c/cmbls__Repayment__c.object-meta.xml
<CustomObject>
    <label>Repayment</label>
    <nameField>
        <displayFormat>RPMT-{0000000}</displayFormat>
        <label>Repayment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Repayments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/cmbls__Repayment__c/fields/cmbls__Bank_Account_Number__c.field-meta.xml
<CustomField>
    <fullName>cmbls__Bank_Account_Number__c</fullName>
    <label>Bank Account Number</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/cmbls__Repayment__c/fields/cmbls__Bank_Routing_Number__c.field-meta.xml
<CustomField>
    <fullName>cmbls__Bank_Routing_Number__c</fullName>
    <label>Bank Routing Number</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/cmbls__Repayment__c/fields/cmbls__Status__c.field-meta.xml
<CustomField>
    <fullName>cmbls__Status__c</fullName>
    <description>Active, pause, complete, and new</description>
    <inlineHelpText>Active, pause, complete, and new</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Temporary Pause</fullName>
            </value>
            <value>
                <fullName>Pause</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Write Off</fullName>
            </value>
            <value>
                <fullName>Recovery</fullName>
            </value>
            <value>
                <fullName>Unwind</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/cmbls__Repayment__c/fields/Notes__c.field-meta.xml
<CustomField>
    <fullName>Notes__c</fullName>
    <label>Notes</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/cmbls__Repayment_Schedule__c/cmbls__Repayment_Schedule__c.object-meta.xml
<CustomObject>
    <label>Repayment Schedule</label>
    <nameField>
        <displayFormat>RS-{000000}</displayFormat>
        <label>Repayment Schedule</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Repayment Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/cmbls__Repayment_Schedule__c/fields/cmbls__Active__c.field-meta.xml
<CustomField>
    <fullName>cmbls__Active__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/cmbls__Repayment_Schedule__c/fields/cmbls__Bank_Account_Number__c.field-meta.xml
<CustomField>
    <fullName>cmbls__Bank_Account_Number__c</fullName>
    <label>Bank Account Number</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/cmbls__Repayment_Schedule__c/fields/cmbls__Bank_Routing_Number__c.field-meta.xml
<CustomField>
    <fullName>cmbls__Bank_Routing_Number__c</fullName>
    <label>Bank Routing Number</label>
    <length>9</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/cmbls__Repayment_Schedule__c/fields/cmbls__Notes__c.field-meta.xml
<CustomField>
    <fullName>cmbls__Notes__c</fullName>
    <label>Notes</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/cmbls__Repayment_Schedule__c/fields/cmbls__Repayment__c.field-meta.xml
<CustomField>
    <fullName>cmbls__Repayment__c</fullName>
    <label>Repayment</label>
    <referenceTo>cmbls__Repayment__c</referenceTo>
    <relationshipLabel>Repayment Schedules</relationshipLabel>
    <relationshipName>Repayment_Schedules</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/classes/UpdateBankingInformationTest.cls
/**
 * UpdateBankingInformationTest class
 * @author CloudMyBiz (r)
 * @date 3/25/2022
 * @description
 * @group 
 */

@IsTest
private class UpdateBankingInformationTest{
    
    @TestSetup static void setupMethod(){
        cmbls__Loan_Servicing_Settings__c settings = new cmbls__Loan_Servicing_Settings__c();
        settings.cmbls__Allow_Multi_Schedule__c = true;
        insert settings;
        
        Account acc = TestDataFactory.createAccount();
        insert acc;
        
        cmbls__Repayment__c repayment = TestDataFactory.createRepayment(acc.Id);
        insert repayment;
        delete [SELECT Id FROM cmbls__Payment__c];
    
        cmbls__Repayment_Schedule__c[] schedules = new cmbls__Repayment_Schedule__c[]{
            TestDataFactory.createRepaymentSchedule(repayment.Id),
            TestDataFactory.createRepaymentSchedule(repayment.Id)
        };
        schedules[0].cmbls__Active__c = true;
        schedules[0].cmbls__Bank_Account_Number__c = '1212';
        schedules[0].cmbls__Bank_Routing_Number__c = '999999963';

        schedules[1].cmbls__Bank_Account_Number__c = '1212';
        schedules[1].cmbls__Bank_Routing_Number__c = '999999963';
        insert schedules;
        
        cmbls__Payment__c[] payments = new cmbls__Payment__c[]{
            new cmbls__Payment__c(
                cmbls__Repayment__c = repayment.Id,
                RecordTypeId = PaymentUtils.PAYMENT_RECORD_TYPE_CREDIT_ID,
                cmbls__Effective_Date__c = System.today().addDays(1),
                cmbls__Transaction_Type__c = PaymentUtils.PAYMENT_TRANSACTION_TYPE_PAYMENT,
                cmbls__Transaction_Amount__c = 4000,
                cmbls__Status__c = PaymentUtils.PAYMENT_STATUS_SCHEDULED
            ),
            new cmbls__Payment__c(
                cmbls__Repayment__c = repayment.Id,
                RecordTypeId = PaymentUtils.PAYMENT_RECORD_TYPE_CREDIT_ID,
                cmbls__Effective_Date__c = System.today().addDays(1),
                cmbls__Transaction_Type__c = PaymentUtils.PAYMENT_TRANSACTION_TYPE_PAYMENT,
                cmbls__Transaction_Amount__c = 4000,
                cmbls__Status__c = PaymentUtils.PAYMENT_STATUS_CANCELED
            )
        };
        insert payments;
    }
    
    @IsTest
    static void mainInvocableMethod(){
        cmbls__Repayment__c repayment = [SELECT Id, cmbls__Bank_Routing_Number__c, cmbls__Bank_Account_Number__c, cmbls__Bank_Name__c FROM cmbls__Repayment__c];
        UpdateBankingInformation.UpdateRequest mainRequest = new UpdateBankingInformation.UpdateRequest();
        mainRequest.repaymentId = repayment.Id;
        mainRequest.fromRecord = 'Case: #000987';
        mainRequest.notes = 'TEST NOTES';
        mainRequest.bankName = 'WELLS FARGO';
        mainRequest.bankAccountType = 'Checking';
        mainRequest.bankAccountNumber = '456456456';
        mainRequest.bankRoutingNumber = '999999763';
        mainRequest.updateRepaymentSchedules = true;
        mainRequest.updateScheduledPayments = true;
    
        String notes = String.format(UpdateBankingInformation.NOTE, new String[]{
            System.now().format('MM/dd/YYYY HH:mm'),
            (String.isNotBlank(mainRequest.fromRecord) ? ' from ' + mainRequest.fromRecord : ''),
            repayment.cmbls__Bank_Name__c, repayment.cmbls__Bank_Routing_Number__c, repayment.cmbls__Bank_Account_Number__c,
            mainRequest.bankName, mainRequest.bankRoutingNumber, mainRequest.bankAccountNumber
        }) + mainRequest.notes;
    
        Test.startTest();
        UpdateBankingInformation.UpdateResult[] results = UpdateBankingInformation.mainInvocableMethod(new UpdateBankingInformation.UpdateRequest[]{mainRequest});
        System.assertEquals(1, results.size());
        System.assertEquals(true, results[0].success);
        Test.stopTest();
        
        repayment = [SELECT Id, cmbls__Bank_Routing_Number__c, cmbls__Bank_Account_Number__c, cmbls__Bank_Name__c, Notes__c, cmbls__Type_of_Account__c FROM cmbls__Repayment__c];
        System.assertEquals(notes, repayment.Notes__c);
        System.assertEquals(mainRequest.bankAccountNumber, repayment.cmbls__Bank_Account_Number__c);
        System.assertEquals(mainRequest.bankRoutingNumber, repayment.cmbls__Bank_Routing_Number__c);
        System.assertEquals(mainRequest.bankAccountType, repayment.cmbls__Type_of_Account__c);
        
        cmbls__Payment__c[] payments = [SELECT Id, cmbls__Bank_Account_Number__c, cmbls__Bank_Routing_Number__c, cmbls__Status__c, cmbls__Notes__c, cmbls__Type_of_Account__c FROM cmbls__Payment__c];
        for(cmbls__Payment__c item :payments){
            if(item.cmbls__Status__c == PaymentUtils.PAYMENT_STATUS_CANCELED){
                System.assertEquals(null, item.cmbls__Notes__c);
                System.assertEquals(null, item.cmbls__Bank_Account_Number__c);
                System.assertEquals(null, item.cmbls__Bank_Routing_Number__c);
                System.assertEquals(null, item.cmbls__Type_of_Account__c);
            }else if(item.cmbls__Status__c == PaymentUtils.PAYMENT_STATUS_SCHEDULED){
                System.assertEquals(notes, item.cmbls__Notes__c);
                System.assertEquals(mainRequest.bankAccountNumber, item.cmbls__Bank_Account_Number__c);
                System.assertEquals(mainRequest.bankRoutingNumber, item.cmbls__Bank_Routing_Number__c);
                System.assertEquals(mainRequest.bankAccountType, item.cmbls__Type_of_Account__c);
            }
        }
        
        cmbls__Repayment_Schedule__c[] schedules = [SELECT Id, cmbls__Bank_Account_Number__c, cmbls__Bank_Routing_Number__c, cmbls__Active__c, cmbls__Notes__c FROM cmbls__Repayment_Schedule__c];
        for(cmbls__Repayment_Schedule__c item :schedules){
            if(!item.cmbls__Active__c){
                System.assertEquals(null, item.cmbls__Notes__c);
                System.assertEquals('1212', item.cmbls__Bank_Account_Number__c);
                System.assertEquals('999999963', item.cmbls__Bank_Routing_Number__c);
            }else{
                System.assertEquals(mainRequest.bankAccountNumber, item.cmbls__Bank_Account_Number__c);
                System.assertEquals(mainRequest.bankRoutingNumber, item.cmbls__Bank_Routing_Number__c);
            }
        }
    }
    
    @IsTest
    static void mainInvocableMethod2(){
        cmbls__Repayment__c repayment = [SELECT Id, cmbls__Bank_Routing_Number__c, cmbls__Bank_Account_Number__c, cmbls__Bank_Name__c FROM cmbls__Repayment__c];
        UpdateBankingInformation.UpdateRequest mainRequest = new UpdateBankingInformation.UpdateRequest();
        mainRequest.repaymentId = repayment.Id;
        mainRequest.fromRecord = 'Case: #000987';
        mainRequest.notes = 'TEST NOTES';
        mainRequest.bankName = 'WELLS FARGO';
        mainRequest.bankAccountType = 'Checking';
        mainRequest.bankAccountNumber = '456456456';
        mainRequest.bankRoutingNumber = '999999763';
        mainRequest.updateRepaymentSchedules = false;
        mainRequest.updateScheduledPayments = false;
    
        String notes = String.format(UpdateBankingInformation.NOTE, new String[]{
            System.now().format('MM/dd/YYYY HH:mm'),
            (String.isNotBlank(mainRequest.fromRecord) ? ' from ' + mainRequest.fromRecord : ''),
            repayment.cmbls__Bank_Name__c, repayment.cmbls__Bank_Routing_Number__c, repayment.cmbls__Bank_Account_Number__c,
            mainRequest.bankName, mainRequest.bankRoutingNumber, mainRequest.bankAccountNumber
        }) + mainRequest.notes;
    
        Test.startTest();
        UpdateBankingInformation.UpdateResult[] results = UpdateBankingInformation.mainInvocableMethod(new UpdateBankingInformation.UpdateRequest[]{mainRequest});
        System.assertEquals(1, results.size());
        System.assertEquals(true, results[0].success);
        Test.stopTest();
    
        repayment = [SELECT Id, cmbls__Bank_Routing_Number__c, cmbls__Bank_Account_Number__c, cmbls__Bank_Name__c, Notes__c, cmbls__Type_of_Account__c FROM cmbls__Repayment__c];
        System.assertEquals(notes, repayment.Notes__c);
        System.assertEquals(mainRequest.bankAccountNumber, repayment.cmbls__Bank_Account_Number__c);
        System.assertEquals(mainRequest.bankRoutingNumber, repayment.cmbls__Bank_Routing_Number__c);
        System.assertEquals(mainRequest.bankAccountType, repayment.cmbls__Type_of_Account__c);
        
        System.assertEquals(0, [SELECT COUNT() FROM cmbls__Payment__c WHERE cmbls__Bank_Account_Number__c = :mainRequest.bankAccountNumber OR cmbls__Bank_Routing_Number__c = :mainRequest.bankRoutingNumber]);
        System.assertEquals(0, [SELECT COUNT() FROM cmbls__Repayment_Schedule__c WHERE cmbls__Bank_Account_Number__c = :mainRequest.bankAccountNumber OR cmbls__Bank_Routing_Number__c = :mainRequest.bankRoutingNumber]);
    }
    
    @IsTest
    static void mainInvocableMethod3(){
        UpdateBankingInformation.UpdateRequest mainRequest = new UpdateBankingInformation.UpdateRequest();
        mainRequest.repaymentId = 'a6x040000004G89';
        mainRequest.fromRecord = 'Case: #000987';
        mainRequest.notes = 'TEST NOTES';
        mainRequest.bankName = 'WELLS FARGO';
        mainRequest.bankAccountType = 'Checking';
        mainRequest.bankAccountNumber = '456456456';
        mainRequest.bankRoutingNumber = '999999763';
        mainRequest.updateRepaymentSchedules = true;
        mainRequest.updateScheduledPayments = true;
        
        Test.startTest();
        UpdateBankingInformation.UpdateResult[] results = UpdateBankingInformation.mainInvocableMethod(new UpdateBankingInformation.UpdateRequest[]{mainRequest});
        System.assertEquals(1, results.size());
        System.assertEquals(false, results[0].success);
        Test.stopTest();
    
        cmbls__Repayment__c repayment = [SELECT Id, cmbls__Bank_Routing_Number__c, cmbls__Bank_Account_Number__c, cmbls__Bank_Name__c, Notes__c, cmbls__Type_of_Account__c FROM cmbls__Repayment__c];
        System.assertEquals(null, repayment.Notes__c);
        System.assertNotEquals(mainRequest.bankAccountNumber, repayment.cmbls__Bank_Account_Number__c);
        System.assertNotEquals(mainRequest.bankRoutingNumber, repayment.cmbls__Bank_Routing_Number__c);
        System.assertNotEquals(mainRequest.bankAccountType, repayment.cmbls__Type_of_Account__c);
        
        System.assertEquals(0, [SELECT COUNT() FROM cmbls__Payment__c WHERE cmbls__Bank_Account_Number__c = :mainRequest.bankAccountNumber OR cmbls__Bank_Routing_Number__c = :mainRequest.bankRoutingNumber]);
        System.assertEquals(0, [SELECT COUNT() FROM cmbls__Repayment_Schedule__c WHERE cmbls__Bank_Account_Number__c = :mainRequest.bankAccountNumber OR cmbls__Bank_Routing_Number__c = :mainRequest.bankRoutingNumber]);
    }
}