unpackaged/main/default/objects/cmbls__Loan_Servicing_Settings__c/cmbls__Loan_Servicing_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Loan Servicing Settings</label>
</CustomObject>

unpackaged/main/default/objects/cmbls__Repayment__c/cmbls__Repayment__c.object-meta.xml
<CustomObject>
    <label>Repayment</label>
    <nameField>
        <displayFormat>RPMT-{0000000}</displayFormat>
        <label>Repayment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Repayments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/cmbls__Repayment__c/fields/cmbls__Status__c.field-meta.xml
<CustomField>
    <fullName>cmbls__Status__c</fullName>
    <description>Active, pause, complete, and new</description>
    <inlineHelpText>Active, pause, complete, and new</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Temporary Pause</fullName>
            </value>
            <value>
                <fullName>Pause</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Write Off</fullName>
            </value>
            <value>
                <fullName>Recovery</fullName>
            </value>
            <value>
                <fullName>Unwind</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/cmbls__Repayment__c/fields/Pause_Date__c.field-meta.xml
<CustomField>
    <fullName>Pause_Date__c</fullName>
    <label>Pause Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/cmbls__Repayment__c/fields/Resume_Date__c.field-meta.xml
<CustomField>
    <fullName>Resume_Date__c</fullName>
    <label>Resume Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/cmbls__Repayment_Schedule__c/cmbls__Repayment_Schedule__c.object-meta.xml
<CustomObject>
    <label>Repayment Schedule</label>
    <nameField>
        <displayFormat>RS-{000000}</displayFormat>
        <label>Repayment Schedule</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Repayment Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/cmbls__Repayment_Schedule__c/fields/cmbls__Next_Payment_Date__c.field-meta.xml
<CustomField>
    <fullName>cmbls__Next_Payment_Date__c</fullName>
    <inlineHelpText>This is the Effective Date of the next ACH payment that will be created by the Repayment Schedule. This field is populated and updated by the system based on the current values in the Repayment Schedule. Note: This will always roll forward to the next valid business day if it falls on a holiday or weekend.</inlineHelpText>
    <label>Next Payment Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/cmbls__Repayment_Schedule__c/fields/cmbls__Repayment__c.field-meta.xml
<CustomField>
    <fullName>cmbls__Repayment__c</fullName>
    <label>Repayment</label>
    <referenceTo>cmbls__Repayment__c</referenceTo>
    <relationshipLabel>Repayment Schedules</relationshipLabel>
    <relationshipName>Repayment_Schedules</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/classes/RepaymentStatusBatchTest.cls
/**
 * RepaymentStatusBatchTest class
 * @author CloudMyBiz (r)
 * @date 3/22/2022
 * @description
 * @group 
 */

@IsTest
private class RepaymentStatusBatchTest{
    
    @TestSetup static void setupMethod(){
        cmbls__Loan_Servicing_Settings__c settings = new cmbls__Loan_Servicing_Settings__c();
        settings.cmbls__Allow_Multi_Schedule__c = true;
        insert settings;
        
        Account acc = TestDataFactory.createAccount();
        insert acc;
    }
    
    @IsTest
    static void executeResume(){
        Account acc = [SELECT Id FROM Account];
        cmbls__Repayment__c repayment = TestDataFactory.createRepayment(acc.Id);
        repayment.cmbls__Status__c = RepaymentUtils.STATUS_TEMPORARY_PAUSE;
        repayment.Resume_Date__c = System.today();
        insert repayment;
    
        cmbls__Repayment_Schedule__c[] schedules = new cmbls__Repayment_Schedule__c[]{
            TestDataFactory.createRepaymentSchedule(repayment.Id),
            TestDataFactory.createRepaymentSchedule(repayment.Id)
        };
        schedules[0].cmbls__Next_Payment_Date__c = cmbls.DatetimeUtils.getNextValidDate(System.today().addDays(1));
        schedules[1].cmbls__Next_Payment_Date__c = cmbls.DatetimeUtils.getNextValidDate(System.today().addDays(1));
        insert schedules;
        
        Test.startTest();
        Database.executeBatch(new RepaymentStatusBatch());
        Test.stopTest();
        
        repayment = [SELECT Id, Resume_Date__c, cmbls__Status__c, (SELECT Id, cmbls__Next_Payment_Date__c FROM cmbls__Repayment_Schedules__r) FROM cmbls__Repayment__c];
        System.assertEquals(RepaymentUtils.STATUS_ACTIVE, repayment.cmbls__Status__c);
        for(cmbls__Repayment_Schedule__c item :repayment.cmbls__Repayment_Schedules__r){
            System.assert(item.cmbls__Next_Payment_Date__c >= System.today());
        }
    
        String CRON_EXP = '0 0 23 * * ?';
        System.schedule('RepaymentStatusBatch TEST', CRON_EXP, new RepaymentStatusBatch());
    }
    
    @IsTest
    static void executePause(){
        Account acc = [SELECT Id FROM Account];
        cmbls__Repayment__c repayment = TestDataFactory.createRepayment(acc.Id);
        repayment.cmbls__Status__c = RepaymentUtils.STATUS_ACTIVE;
        repayment.Pause_Date__c = System.today();
        insert repayment;
        
        cmbls__Repayment_Schedule__c[] schedules = new cmbls__Repayment_Schedule__c[]{
            TestDataFactory.createRepaymentSchedule(repayment.Id),
            TestDataFactory.createRepaymentSchedule(repayment.Id)
        };
        schedules[0].cmbls__Next_Payment_Date__c = cmbls.DatetimeUtils.getNextValidDate(System.today().addDays(1));
        schedules[1].cmbls__Next_Payment_Date__c = cmbls.DatetimeUtils.getNextValidDate(System.today().addDays(1));
        insert schedules;
        
        Test.startTest();
        Database.executeBatch(new RepaymentStatusBatch());
        Test.stopTest();
        
        repayment = [SELECT Id, Pause_Date__c, cmbls__Status__c, (SELECT Id, cmbls__Next_Payment_Date__c FROM cmbls__Repayment_Schedules__r) FROM cmbls__Repayment__c];
        System.assertEquals(RepaymentUtils.STATUS_TEMPORARY_PAUSE, repayment.cmbls__Status__c);
        for(cmbls__Repayment_Schedule__c item :repayment.cmbls__Repayment_Schedules__r){
            System.assertEquals(cmbls.DatetimeUtils.getNextValidDate(repayment.Pause_Date__c.addDays(1)), item.cmbls__Next_Payment_Date__c);
        }
    }
}