unpackaged/main/default/objects/cmbls__Loan_Servicing_Settings__c/cmbls__Loan_Servicing_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Loan Servicing Settings</label>
</CustomObject>

unpackaged/main/default/objects/cmbls__Repayment__c/cmbls__Repayment__c.object-meta.xml
<CustomObject>
    <label>Repayment</label>
    <nameField>
        <displayFormat>RPMT-{0000000}</displayFormat>
        <label>Repayment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Repayments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/cmbls__Repayment__c/fields/cmbls__Bank_Account_Number__c.field-meta.xml
<CustomField>
    <fullName>cmbls__Bank_Account_Number__c</fullName>
    <label>Bank Account Number</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/cmbls__Repayment__c/fields/cmbls__Bank_Routing_Number__c.field-meta.xml
<CustomField>
    <fullName>cmbls__Bank_Routing_Number__c</fullName>
    <label>Bank Routing Number</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/cmbls__Repayment__c/fields/cmbls__Status__c.field-meta.xml
<CustomField>
    <fullName>cmbls__Status__c</fullName>
    <description>Active, pause, complete, and new</description>
    <inlineHelpText>Active, pause, complete, and new</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Temporary Pause</fullName>
            </value>
            <value>
                <fullName>Pause</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Write Off</fullName>
            </value>
            <value>
                <fullName>Recovery</fullName>
            </value>
            <value>
                <fullName>Unwind</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/cmbls__Repayment__c/fields/Notes__c.field-meta.xml
<CustomField>
    <fullName>Notes__c</fullName>
    <label>Notes</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/cmbls__Repayment_Schedule__c/cmbls__Repayment_Schedule__c.object-meta.xml
<CustomObject>
    <label>Repayment Schedule</label>
    <nameField>
        <displayFormat>RS-{000000}</displayFormat>
        <label>Repayment Schedule</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Repayment Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/cmbls__Repayment_Schedule__c/fields/cmbls__Active__c.field-meta.xml
<CustomField>
    <fullName>cmbls__Active__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/cmbls__Repayment_Schedule__c/fields/cmbls__Bank_Account_Number__c.field-meta.xml
<CustomField>
    <fullName>cmbls__Bank_Account_Number__c</fullName>
    <label>Bank Account Number</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/cmbls__Repayment_Schedule__c/fields/cmbls__Bank_Routing_Number__c.field-meta.xml
<CustomField>
    <fullName>cmbls__Bank_Routing_Number__c</fullName>
    <label>Bank Routing Number</label>
    <length>9</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/cmbls__Repayment_Schedule__c/fields/cmbls__Next_Payment_Date__c.field-meta.xml
<CustomField>
    <fullName>cmbls__Next_Payment_Date__c</fullName>
    <inlineHelpText>This is the Effective Date of the next ACH payment that will be created by the Repayment Schedule. This field is populated and updated by the system based on the current values in the Repayment Schedule. Note: This will always roll forward to the next valid business day if it falls on a holiday or weekend.</inlineHelpText>
    <label>Next Payment Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/cmbls__Repayment_Schedule__c/fields/cmbls__Notes__c.field-meta.xml
<CustomField>
    <fullName>cmbls__Notes__c</fullName>
    <label>Notes</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/cmbls__Repayment_Schedule__c/fields/cmbls__Repayment__c.field-meta.xml
<CustomField>
    <fullName>cmbls__Repayment__c</fullName>
    <label>Repayment</label>
    <referenceTo>cmbls__Repayment__c</referenceTo>
    <relationshipLabel>Repayment Schedules</relationshipLabel>
    <relationshipName>Repayment_Schedules</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/classes/ReactivateRepaymentTest.cls
/**
 * ReactivateRepaymentTest class
 * @author CloudMyBiz (r)
 * @date 3/25/2022
 * @description
 * @group 
 */

@IsTest
private class ReactivateRepaymentTest{
    
    @TestSetup static void setupMethod(){
        cmbls__Loan_Servicing_Settings__c settings = new cmbls__Loan_Servicing_Settings__c();
        settings.cmbls__Allow_Multi_Schedule__c = true;
        insert settings;
        
        Account acc = TestDataFactory.createAccount();
        insert acc;
        
        cmbls__Repayment__c repayment = TestDataFactory.createRepayment(acc.Id);
        repayment.cmbls__Status__c = RepaymentUtils.STATUS_TEMPORARY_PAUSE;
        insert repayment;
        
        cmbls__Repayment_Schedule__c[] schedules = new cmbls__Repayment_Schedule__c[]{
            TestDataFactory.createRepaymentSchedule(repayment.Id),
            TestDataFactory.createRepaymentSchedule(repayment.Id)
        };
        schedules[0].cmbls__Active__c = true;
        schedules[0].cmbls__Next_Payment_Date__c = cmbls.DatetimeUtils.getNextValidDate(System.today().addDays(10));
        
        schedules[1].cmbls__Next_Payment_Date__c = cmbls.DatetimeUtils.getNextValidDate(System.today().addDays(10));
        insert schedules;
    }
    
    @IsTest
    static void mainInvocableMethod(){
        cmbls__Repayment__c repayment = [SELECT Id, cmbls__Bank_Routing_Number__c, cmbls__Bank_Account_Number__c, cmbls__Bank_Name__c FROM cmbls__Repayment__c];
        ReactivateRepayment.ReactivateRequest mainRequest = new ReactivateRepayment.ReactivateRequest();
        mainRequest.repaymentId = repayment.Id;
        mainRequest.fromRecord = 'Case: #000987';
        mainRequest.notes = 'TEST NOTES';
        
        Test.startTest();
        ReactivateRepayment.ReactivateResult[] results = ReactivateRepayment.mainInvocableMethod(new ReactivateRepayment.ReactivateRequest[]{mainRequest});
        System.assertEquals(1, results.size());
        System.assertEquals(true, results[0].success);
        Test.stopTest();
        
        repayment = [SELECT Id, cmbls__Status__c, Notes__c FROM cmbls__Repayment__c];
        System.assert(repayment.Notes__c.startsWith('Repayment status updated to Active on '));
        System.assertEquals(RepaymentUtils.STATUS_ACTIVE, repayment.cmbls__Status__c);
        
        cmbls__Repayment_Schedule__c[] schedules = [SELECT Id, cmbls__Next_Payment_Date__c, cmbls__Notes__c, cmbls__Active__c FROM cmbls__Repayment_Schedule__c];
        for(cmbls__Repayment_Schedule__c item :schedules){
            if(!item.cmbls__Active__c){
                System.assertEquals(null, item.cmbls__Notes__c);
                System.assertEquals(cmbls.DatetimeUtils.getNextValidDate(System.today().addDays(10)), item.cmbls__Next_Payment_Date__c);
            }else{
                System.assert(item.cmbls__Notes__c.startsWith('"Next Payment Date" reset after Repayment status updating to Active on '));
                System.assertNotEquals(cmbls.DatetimeUtils.getNextValidDate(System.today().addDays(10)), item.cmbls__Next_Payment_Date__c);
            }
        }
    }
    
    @IsTest
    static void mainInvocableMethod2(){
        ReactivateRepayment.ReactivateRequest mainRequest = new ReactivateRepayment.ReactivateRequest();
        mainRequest.repaymentId = 'a6x040000004G89';
        mainRequest.fromRecord = 'Case: #000987';
        mainRequest.notes = 'TEST NOTES';
        
        Test.startTest();
        ReactivateRepayment.ReactivateResult[] results = ReactivateRepayment.mainInvocableMethod(new ReactivateRepayment.ReactivateRequest[]{mainRequest});
        System.assertEquals(1, results.size());
        System.assertEquals(false, results[0].success);
        Test.stopTest();
    
        cmbls__Repayment__c repayment = [SELECT Id, cmbls__Status__c, Notes__c FROM cmbls__Repayment__c];
        System.assertEquals(null, repayment.Notes__c);
        System.assertEquals(RepaymentUtils.STATUS_TEMPORARY_PAUSE, repayment.cmbls__Status__c);
        System.assertEquals(0, [SELECT COUNT() FROM cmbls__Repayment_Schedule__c WHERE cmbls__Next_Payment_Date__c != :cmbls.DatetimeUtils.getNextValidDate(System.today().addDays(10))]);
    }
}