unpackaged/main/default/objects/cmbls__Loan_Servicing_Settings__c/cmbls__Loan_Servicing_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Loan Servicing Settings</label>
</CustomObject>

unpackaged/main/default/objects/cmbls__Repayment__c/cmbls__Repayment__c.object-meta.xml
<CustomObject>
    <label>Repayment</label>
    <nameField>
        <displayFormat>RPMT-{0000000}</displayFormat>
        <label>Repayment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Repayments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/cmbls__Repayment_Schedule__c/cmbls__Repayment_Schedule__c.object-meta.xml
<CustomObject>
    <label>Repayment Schedule</label>
    <nameField>
        <displayFormat>RS-{000000}</displayFormat>
        <label>Repayment Schedule</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Repayment Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/cmbls__Repayment_Schedule__c/fields/cmbls__Active__c.field-meta.xml
<CustomField>
    <fullName>cmbls__Active__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/cmbls__Repayment_Schedule__c/fields/cmbls__Days__c.field-meta.xml
<CustomField>
    <fullName>cmbls__Days__c</fullName>
    <inlineHelpText>Specifies the day/date of the payment frequency</inlineHelpText>
    <label>Days</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <controllingField>cmbls__Preset__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Monday</fullName>
            </value>
            <value>
                <fullName>Tuesday</fullName>
            </value>
            <value>
                <fullName>Wednesday</fullName>
            </value>
            <value>
                <fullName>Thursday</fullName>
            </value>
            <value>
                <fullName>Friday</fullName>
            </value>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>9</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
            <value>
                <fullName>11</fullName>
            </value>
            <value>
                <fullName>12</fullName>
            </value>
            <value>
                <fullName>13</fullName>
            </value>
            <value>
                <fullName>14</fullName>
            </value>
            <value>
                <fullName>15</fullName>
            </value>
            <value>
                <fullName>16</fullName>
            </value>
            <value>
                <fullName>17</fullName>
            </value>
            <value>
                <fullName>18</fullName>
            </value>
            <value>
                <fullName>19</fullName>
            </value>
            <value>
                <fullName>20</fullName>
            </value>
            <value>
                <fullName>21</fullName>
            </value>
            <value>
                <fullName>22</fullName>
            </value>
            <value>
                <fullName>23</fullName>
            </value>
            <value>
                <fullName>24</fullName>
            </value>
            <value>
                <fullName>25</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/cmbls__Repayment_Schedule__c/fields/cmbls__Default__c.field-meta.xml
<CustomField>
    <fullName>cmbls__Default__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Default</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/cmbls__Repayment_Schedule__c/fields/cmbls__End_Date__c.field-meta.xml
<CustomField>
    <fullName>cmbls__End_Date__c</fullName>
    <inlineHelpText>This will be the final payment pulled. If populated, the system will no longer schedule payments for an Effective Date that is after this date. Note: An End Date is not required. If null, the system will continue to create payments until there is no longer a balance.</inlineHelpText>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/cmbls__Repayment_Schedule__c/fields/cmbls__Installment_Amount__c.field-meta.xml
<CustomField>
    <fullName>cmbls__Installment_Amount__c</fullName>
    <inlineHelpText>Note: If the remaining balance is less than the scheduled payment, the system will create a payment for the lesser amount</inlineHelpText>
    <label>Transaction Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/cmbls__Repayment_Schedule__c/fields/cmbls__Next_Payment_Date__c.field-meta.xml
<CustomField>
    <fullName>cmbls__Next_Payment_Date__c</fullName>
    <inlineHelpText>This is the Effective Date of the next ACH payment that will be created by the Repayment Schedule. This field is populated and updated by the system based on the current values in the Repayment Schedule. Note: This will always roll forward to the next valid business day if it falls on a holiday or weekend.</inlineHelpText>
    <label>Next Payment Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/cmbls__Repayment_Schedule__c/fields/cmbls__Notes__c.field-meta.xml
<CustomField>
    <fullName>cmbls__Notes__c</fullName>
    <label>Notes</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/cmbls__Repayment_Schedule__c/fields/cmbls__Preset__c.field-meta.xml
<CustomField>
    <fullName>cmbls__Preset__c</fullName>
    <inlineHelpText>Payment frequency</inlineHelpText>
    <label>Preset</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Weekly</fullName>
            </value>
            <value>
                <fullName>Bi-Weekly</fullName>
            </value>
            <value>
                <fullName>Monthly</fullName>
            </value>
            <value>
                <fullName>Pause</fullName>
            </value>
            <value>
                <fullName>Daily</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/cmbls__Repayment_Schedule__c/fields/cmbls__Repayment__c.field-meta.xml
<CustomField>
    <fullName>cmbls__Repayment__c</fullName>
    <label>Repayment</label>
    <referenceTo>cmbls__Repayment__c</referenceTo>
    <relationshipLabel>Repayment Schedules</relationshipLabel>
    <relationshipName>Repayment_Schedules</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/cmbls__Repayment_Schedule__c/fields/cmbls__Start_Date__c.field-meta.xml
<CustomField>
    <fullName>cmbls__Start_Date__c</fullName>
    <inlineHelpText>This is the first date the system will start evaluating this Repayment Schedule to begin creating ACH payments. NOTE: This must be at least one day before the Next Payment Date and should also be a business day</inlineHelpText>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/classes/CreateRepaymentScheduleTest.cls
/**
 * CreateRepaymentScheduleTest class
 * @author CloudMyBiz (r)
 * @date 3/23/2022
 * @description
 * @group 
 */

@IsTest
private class CreateRepaymentScheduleTest{
    
    @TestSetup static void setupMethod(){
        cmbls__Loan_Servicing_Settings__c settings = new cmbls__Loan_Servicing_Settings__c();
        settings.cmbls__Allow_Multi_Schedule__c = true;
        insert settings;
        
        Account acc = TestDataFactory.createAccount();
        insert acc;
    
        cmbls__Repayment__c repayment = TestDataFactory.createRepayment(acc.Id);
        insert repayment;
    }
    
    @IsTest
    static void mainInvocableMethod(){
        cmbls__Repayment__c repayment = [SELECT Id FROM cmbls__Repayment__c];
        delete [SELECT Id FROM cmbls__Repayment_Schedule__c];
        CreateRepaymentSchedule.CreateRequest mainRequest = new CreateRepaymentSchedule.CreateRequest();
        mainRequest.repaymentId = repayment.Id;
        mainRequest.expectedFirstPaymentDate = System.today().addDays(15);
        mainRequest.paymentAmount = 2000;
        mainRequest.endDate = System.today().addMonths(2);
        mainRequest.paymentFrequency = 'Monthly';
        mainRequest.day = '1';
        mainRequest.isDefault = false;
        mainRequest.bankAccountNumber = '1212';
        mainRequest.bankRoutingNumber = '999999963';
        mainRequest.notes = 'Test Notes';
        
        Test.startTest();
        CreateRepaymentSchedule.CreateResult[] results = CreateRepaymentSchedule.mainInvocableMethod(new CreateRepaymentSchedule.CreateRequest[]{mainRequest});
        System.assertEquals(1, results.size());
        System.assertEquals(true, results[0].success);
        Test.stopTest();
        
        cmbls__Repayment_Schedule__c record = [SELECT Id, cmbls__Notes__c, cmbls__Installment_Amount__c, cmbls__Start_Date__c, cmbls__Next_Payment_Date__c, cmbls__End_Date__c, cmbls__Preset__c, cmbls__Days__c, cmbls__Active__c, cmbls__Default__c FROM cmbls__Repayment_Schedule__c WHERE cmbls__Repayment__c = :repayment.Id];
        System.assertEquals(record.Id, results[0].output);
        System.assertEquals(cmbls.DatetimeUtils.getNextValidDate(mainRequest.expectedFirstPaymentDate), record.cmbls__Next_Payment_Date__c);
        System.assertEquals(mainRequest.paymentAmount, record.cmbls__Installment_Amount__c);
        System.assertEquals(mainRequest.endDate, record.cmbls__End_Date__c);
        System.assertEquals(mainRequest.paymentFrequency, record.cmbls__Preset__c);
        System.assertEquals(mainRequest.day, record.cmbls__Days__c);
        System.assertEquals(true, record.cmbls__Active__c);
        System.assertEquals(mainRequest.isDefault, record.cmbls__Default__c);
        System.assertEquals(mainRequest.notes, record.cmbls__Notes__c);
    
        Set<Date> holidays = cmbls.DatetimeUtils.getAllHolidays();
        Date startDate = RepaymentScheduleService.getPreviousValidDate(mainRequest.expectedFirstPaymentDate, holidays);
        System.assertEquals(startDate, record.cmbls__Start_Date__c);
    }
    
    @IsTest
    static void mainInvocableMethodError(){
        cmbls__Repayment__c repayment = [SELECT Id FROM cmbls__Repayment__c];
        CreateRepaymentSchedule.CreateRequest mainRequest = new CreateRepaymentSchedule.CreateRequest();
        mainRequest.repaymentId = repayment.Id;
        mainRequest.expectedFirstPaymentDate = System.today().addDays(15);
        mainRequest.paymentAmount = 2000;
        mainRequest.endDate = System.today().addMonths(2);
        mainRequest.paymentFrequency = 'Unsupported';
        mainRequest.day = '1';
        mainRequest.isDefault = false;
        mainRequest.bankAccountNumber = '1212';
        mainRequest.bankRoutingNumber = '999999963';
        mainRequest.notes = 'Test Notes';
        
        Test.startTest();
        CreateRepaymentSchedule.CreateResult[] results = CreateRepaymentSchedule.mainInvocableMethod(new CreateRepaymentSchedule.CreateRequest[]{mainRequest});
        System.assertEquals(1, results.size());
        System.assert(results[0].output.contains('INVALID_OR_NULL_FOR_RESTRICTED_PICKLIST'));
        System.assertEquals(false, results[0].success);
        Test.stopTest();
        
        System.assertEquals(0, [SELECT COUNT() FROM cmbls__Repayment_Schedule__c WHERE cmbls__Repayment__c = :repayment.Id]);
    }
}