unpackaged/main/default/objects/Account/fields/Account_Number__c.field-meta.xml
<CustomField>
    <fullName>Account_Number__c</fullName>
    <description>The 16 digit account number associated with this account.</description>
    <inlineHelpText>The 16 digit account number associated with this account.</inlineHelpText>
    <label>Account Number</label>
    <length>16</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Bank_Name__c.field-meta.xml
<CustomField>
    <fullName>Bank_Name__c</fullName>
    <description>Bank Name</description>
    <inlineHelpText>Enter Name of Bank</inlineHelpText>
    <label>Bank Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/recordTypes/Customer.recordType-meta.xml
<RecordType>
    <fullName>Customer</fullName>
    <active>true</active>
    <label>Customer</label>
</RecordType>

unpackaged/main/default/objects/Bank_Data__c/Bank_Data__c.object-meta.xml
<CustomObject>
    <label>Bank Data</label>
    <nameField>
        <displayFormat>BD-{0}</displayFormat>
        <label>Bank_Data</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bank Data</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Bank_Data__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Bank Data</relationshipLabel>
    <relationshipName>Bank_Data</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Bank_Data__c/fields/Account_Number__c.field-meta.xml
<CustomField>
    <fullName>Account_Number__c</fullName>
    <description>Field to initially capture and compare bank account number data to ensure we are not pulling duplicate bank accounts.</description>
    <inlineHelpText>Field to initially capture and compare bank account number data to ensure we are not pulling duplicate bank accounts.</inlineHelpText>
    <label>Account Number</label>
    <length>175</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Bank_Data__c/fields/Bank_Name__c.field-meta.xml
<CustomField>
    <fullName>Bank_Name__c</fullName>
    <description>This field will collect the Name of the bank that the rep has collected.</description>
    <inlineHelpText>Enter the name of the customer's bank account.</inlineHelpText>
    <label>Bank Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Bank_Data__c/fields/Routing_Number__c.field-meta.xml
<CustomField>
    <fullName>Routing_Number__c</fullName>
    <label>Routing Number</label>
    <length>9</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Bank_Data__c/fields/Yodlee_Banks__c.field-meta.xml
<CustomField>
    <fullName>Yodlee_Banks__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Yodlee Banks</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2) OR 3</booleanFilter>
        <filterItems>
            <field>$Profile.Name</field>
            <operation>equals</operation>
            <value>FPC - WC - Renewal Sales, NF Renewal Manager Profile</value>
        </filterItems>
        <filterItems>
            <field>Yodlee_Banks__c.Transaction_Depth__c</field>
            <operation>greaterOrEqual</operation>
            <value>90</value>
        </filterItems>
        <filterItems>
            <field>$Profile.Name</field>
            <operation>notEqual</operation>
            <value>FPC - WC - Renewal Sales, NF Renewal Manager Profile</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Yodlee_Banks__c</referenceTo>
    <relationshipLabel>Bank Data</relationshipLabel>
    <relationshipName>Bank_Data</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Yodlee_Banks__c/Yodlee_Banks__c.object-meta.xml
<CustomObject>
    <label>Yodlee Banks</label>
    <nameField>
        <label>Yodlee FI Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Yodlee Banks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/classes/SendLoanModificationControllerTest.cls
@isTest
public class SendLoanModificationControllerTest { 

    public class ContactWrapper {
        public boolean IsSelected { get; set; }
        public Contact Contact { get; set; }
        public boolean HasEmail { get; set; }
        public String cType {get; set;}
        
        public ContactWrapper(Contact c, boolean hasEmail){
            Contact = c;
            IsSelected = false;
            this.HasEmail = hasEmail;
        }
    }
    
    private static testmethod void Test_SendLoanModRequestExtension(){
        createTestData();

        Account acc = new Account(Name = 'unit test account', Phone = '+1 300 2011231', Type = 'Customer');
        insert acc;
        
        Contact c = new Contact(LastName = 'harry1', Email='bkravitz@nationalfunding.com', AccountId = acc.Id);
        Contact c1 = new Contact(LastName = 'harry', Email='oporter@nationalfunding.com', AccountId = acc.Id);
        insert c;
        insert c1;
        
        Test.startTest();
            PageReference pageRef = Page.SendLoanModification;
            Test.setCurrentPage(pageRef);
            
            HttpMockGenerator mock = new HttpMockGenerator('[{"Id":"' + c.Id+ '","Token":"bxofefoHG9wLuWDiynV4"}]', 200);
            Test.setMock(HttpCalloutMock.class, mock);
            
            SendLoanModificationController ext = new SendLoanModificationController(new Apexpages.StandardController(acc));
            List<SendLoanModificationController.ContactWrapper> contacts = ext.Contacts;
            
            //testing without selecting any contact
            ext.SendEmail();
            SendLoanModificationController.getItems('DLP Drip Activated');
            SendLoanModificationController.getItems('DLP Drip Deactivated');
            SendLoanModificationController.getItems('test');
            
            boolean foundDesiredMsg = false;
            for(ApexPages.Message msg :  ApexPages.getMessages()) {
                if(msg.getSummary() == 'Please select atleast 1 contact'){
                    foundDesiredMsg = true;
                }
            }
            System.assertEquals(true, foundDesiredMsg, 'Atlease 1 Contact validation did not worked');
            
            ext.Contacts[0].IsSelected = True;
            system.debug('------------>' + ext.Contacts[0]);
            ext.Contacts[1].IsSelected = False;
            //testing without selecting any bank
            ext.SendEmail();
        Test.stopTest();
        foundDesiredMsg = false;
        for(ApexPages.Message msg :  ApexPages.getMessages()) {
            if(msg.getSummary() == 'Please select atleast 1 bank'){
                foundDesiredMsg = true;
            }
        }
        System.assertEquals(false, foundDesiredMsg, 'Atlease 1 Bank validation did not worked');
    }
    
    private static testmethod void createTestData(){
        Account acc = new Account(Name = 'unit test account', Phone = '+1 300 2011231', Type = 'Customer');
        insert acc;
        
        List<Contact> contacts = new List<Contact>();
        for(integer i=0; i<20; i++){
            contacts.add(new Contact(AccountId = acc.Id, LastName = 'unit test contact'+i, Email = 'test'+i+'@gmail.com'));
        }
        insert contacts;
        Yodlee_Banks__c ybank = new Yodlee_Banks__c(Name = 'worst bank ever');
        insert ybank;
        List<Bank_Data__c> bankAccounts = new List<Bank_Data__c>();
        integer bankAccountNo = 123456789;
        for(integer i=0; i<20; i++){
            bankAccountNo++;
            system.debug('bank account number'+i+': '+bankAccountNo);
            bankAccounts.add(new Bank_Data__c(Yodlee_Banks__c = ybank.id, Account__c = acc.Id, Bank_Name__c = 'unit test bank '+i, Account_Number__c = bankAccountNo+'', Routing_Number__c = '1231231'+i));
        }
        insert bankAccounts;
    }
    
    private static testmethod void createTestData2(){
        Account acc = new Account(Name = 'unit test account', Phone = '+1 300 2011231', Type = 'Customer');
        insert acc;
        
        List<Contact> contacts = new List<Contact>();
        for(integer i=0; i<20; i++){
            contacts.add(new Contact(AccountId = acc.Id, LastName = 'unit test contact'+i, Email = 'test'+i+'@gmail.com'));
        }
        insert contacts;
        Yodlee_Banks__c ybank = new Yodlee_Banks__c(Name = 'worst bank ever');
        insert ybank;
        List<Bank_Data__c> bankAccounts = new List<Bank_Data__c>();
        integer bankAccountNo = 123456789;
        for(integer i=0; i<20; i++){
            bankAccountNo++;
            system.debug('bank account number'+i+': '+bankAccountNo);
            bankAccounts.add(new Bank_Data__c(Yodlee_Banks__c = ybank.id, Account__c = acc.Id, Bank_Name__c = 'unit test bank '+i, Account_Number__c = bankAccountNo+'', Routing_Number__c = '1231231'+i));
        }
        insert bankAccounts;
    }
    
    private static testmethod void createTestData3() {
        Id accountId = '001S000000nfn6YIAQ';
		List<ContactWrapper> Contacts;
        Map<Id, Contact> contactsWithoutEmail;
        Contacts = new List<ContactWrapper>();
        contactsWithoutEmail = new Map<Id, Contact>();
        for(Contact c : [Select Id, Name, Email, AccountId From Contact Where AccountId =: accountId]){
            Contacts.Add(new ContactWrapper(c, (c.Email != null)));
        }
        
    } 
}