unpackaged/main/default/objects/Account/fields/Account_Number__c.field-meta.xml
<CustomField>
    <fullName>Account_Number__c</fullName>
    <description>The 16 digit account number associated with this account.</description>
    <inlineHelpText>The 16 digit account number associated with this account.</inlineHelpText>
    <label>Account Number</label>
    <length>16</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Response_Channel__c.field-meta.xml
<CustomField>
    <fullName>Response_Channel__c</fullName>
    <description>The channel customer used to contact with FPC</description>
    <inlineHelpText>Select the method contact was made with the account</inlineHelpText>
    <label>Response Channel</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Email</fullName>
            </value>
            <value>
                <fullName>Fax</fullName>
            </value>
            <value>
                <fullName>Inbound Call</fullName>
            </value>
            <value>
                <fullName>Internet</fullName>
            </value>
            <value>
                <fullName>Internet Activation</fullName>
            </value>
            <value>
                <fullName>Internet Application</fullName>
            </value>
            <value>
                <fullName>Internet- Lead Aggregator</fullName>
            </value>
            <value>
                <fullName>Outbound Call</fullName>
            </value>
            <value>
                <fullName>Overflow</fullName>
            </value>
            <value>
                <fullName>After Hours Voice Mail</fullName>
            </value>
            <value>
                <fullName>Facebook</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/Short_Account_Number__c.field-meta.xml
<CustomField>
    <fullName>Short_Account_Number__c</fullName>
    <description>The last 8 digits of the customer's 16 digit account number.</description>
    <inlineHelpText>Type in the last 8 digits of the customer's 16 digit account number.</inlineHelpText>
    <label>Short Account Number</label>
    <length>9</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Web_Id_NatFund__c.field-meta.xml
<CustomField>
    <fullName>Web_Id_NatFund__c</fullName>
    <description>This field will be the unique record identifier for leads that are created from nationalfunding.com. This field will be populated on create and subsequently when the customer completes steps of the application. For de-duping, the field in the new lead should overwrite the existing value.</description>
    <externalId>true</externalId>
    <inlineHelpText>This field should not be edited</inlineHelpText>
    <label>Web Id NatFund</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Lead/fields/Account_Number__c.field-meta.xml
<CustomField>
    <fullName>Account_Number__c</fullName>
    <description>The 16 digit account number assigned to this account.</description>
    <inlineHelpText>The 16 digit account number assigned to this account.</inlineHelpText>
    <label>Account Number</label>
    <length>16</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Lead/fields/Buyer_Zone_Id__c.field-meta.xml
<CustomField>
    <fullName>Buyer_Zone_Id__c</fullName>
    <label>Buyerzone Id</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Lead/fields/Lending_Tree_Id__c.field-meta.xml
<CustomField>
    <fullName>Lending_Tree_Id__c</fullName>
    <description>Lending Tree Id for reporting.</description>
    <label>Lending Tree Id</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Lead/fields/Response_Channel__c.field-meta.xml
<CustomField>
    <fullName>Response_Channel__c</fullName>
    <description>Indicate the response channel used to reach this Lead</description>
    <inlineHelpText>Select the response channel used to reach this Lead</inlineHelpText>
    <label>Response Channel</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Email</fullName>
            </value>
            <value>
                <fullName>Fax</fullName>
            </value>
            <value>
                <fullName>Inbound Call</fullName>
            </value>
            <value>
                <fullName>Internet</fullName>
            </value>
            <value>
                <fullName>Internet Activation</fullName>
            </value>
            <value>
                <fullName>Internet Application</fullName>
            </value>
            <value>
                <fullName>Internet- Lead Aggregator</fullName>
            </value>
            <value>
                <fullName>Outbound Call</fullName>
            </value>
            <value>
                <fullName>Overflow</fullName>
            </value>
            <value>
                <fullName>After Hours Voice Mail</fullName>
            </value>
            <value>
                <fullName>Dev Site</fullName>
            </value>
            <value>
                <fullName>Facebook</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Lead/fields/Short_Account_Number__c.field-meta.xml
<CustomField>
    <fullName>Short_Account_Number__c</fullName>
    <description>A calculated field that is that last 8 digits of the account number.  Used for many lookups.</description>
    <inlineHelpText>A calculated field that is that last 8 digits of the account number.  Used for many lookups.</inlineHelpText>
    <label>Short Account Number</label>
    <length>9</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Lead/fields/Web_Id_NatFund__c.field-meta.xml
<CustomField>
    <fullName>Web_Id_NatFund__c</fullName>
    <description>This field will be the unique record identifier for leads that are created from nationalfunding.com.  This field will be populated on create and subsequently when the customer completes steps of the application. For de-duping, the field in the new lead should overwrite the existing value.</description>
    <externalId>true</externalId>
    <inlineHelpText>This field should not be edited.</inlineHelpText>
    <label>Web Id NatFund</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Lending_Tree_Id__c.field-meta.xml
<CustomField>
    <fullName>Lending_Tree_Id__c</fullName>
    <description>Lending Tree Id for reporting. Updated via workflow rule.</description>
    <label>Lending Tree Id</label>
    <length>9</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Signor_Phone__c.field-meta.xml
<CustomField>
    <fullName>Signor_Phone__c</fullName>
    <label>Signor Phone</label>
    <type>Phone</type>
</CustomField>

unpackaged/main/default/classes/TestConsoleApplicationLinkController.cls
@isTest(SeeAllData=true)
public class TestConsoleApplicationLinkController {

    static testMethod void myUnitTest()
    {
        Account acct = new Account();
        acct.Name = 'test';
        acct.Web_Id_NatFund__c = '11111111';
        insert acct;

        Opportunity o = new Opportunity();
        o.Name = 'test';
        o.StageName = 'New';
        o.CloseDate = Date.today();
        o.AccountId = acct.id;
        o.Signor_Phone__c = '111111111';
        insert o;

        Contact cont = new Contact();
        cont.AccountId = acct.Id;
        cont.FirstName='Test';
        cont.LastName='Test';
        insert cont;

        Lead l = new Lead();
        l.Company = 'test';
        l.FirstName='Test';
        l.LastName='Test';
        l.Web_Id_NatFund__c = '1111111';
        l.Account_Number__c = '1234567890';
        l.Short_Account_Number__c = '098765432';
        l.PostalCode = '12345';
        l.Lending_Tree_Id__c = '1111';
        l.Buyer_Zone_Id__c= '2222';
        l.Status = 'House'; // can't do this in the initial run.
        l.IsConverted = FALSE;
        l.Response_Channel__c = 'Internet';
        insert l;

        Test.startTest();
        ConsoleApplicationLinkController k = new ConsoleApplicationLinkController();
        HttpMockGenerator mock = new HttpMockGenerator('[{"Id":"' + l.Id+ '","Token":"bxofefoHG9wLuWDiynV4"}]', 200);
        Test.setMock(HttpCalloutMock.class, mock);
        String value1= cont.id + ',' + acct.Web_Id_NatFund__c;
        String value2= l.id + ',' + + l.Web_Id_NatFund__c;
        String value3 = 'error';
        ConsoleApplicationLinkController.getShortenedLink(l.id, l.Web_Id_NatFund__c, 'National Funding', 'Quick Bridge');
        ConsoleApplicationLinkController.getShortenedLinkOneParam(value2, 'National Funding', 'Quick Bridge');
        ConsoleApplicationLinkController.getShortenedLinkLT(value2, 'National Funding', 'Quick Bridge');
        //ConsoleApplicationLinkController.getShortenedLinkLoanMod(value2, 'National Funding', 'Quick Bridge');
        //ConsoleApplicationLinkController.getShortenedLinkSecondDML(value2, 'National Funding', 'Quick Bridge');
        
        ConsoleApplicationLinkController.returnURL(cont.id);
        Test.stopTest();
    }
    
     static testMethod void myUnitTest2()
    {
        Account acct = new Account();
        acct.Name = 'test';
        acct.Web_Id_NatFund__c = '11111111';
        insert acct;

        Opportunity o = new Opportunity();
        o.Name = 'test';
        o.StageName = 'New';
        o.CloseDate = Date.today();
        o.AccountId = acct.id;
        o.Signor_Phone__c = '111111111';
        insert o;

        Contact cont = new Contact();
        cont.AccountId = acct.Id;
        cont.FirstName='Test';
        cont.LastName='Test';
        insert cont;

        Lead l = new Lead();
        l.Company = 'test';
        l.FirstName='Test';
        l.LastName='Test';
        l.Web_Id_NatFund__c = '1111111';
        l.Account_Number__c = '1234567890';
        l.Short_Account_Number__c = '098765432';
        l.PostalCode = '12345';
        l.Lending_Tree_Id__c = '1111';
        l.Buyer_Zone_Id__c= '2222';
        l.Status = 'House'; // can't do this in the initial run.
        l.IsConverted = FALSE;
        l.Response_Channel__c = 'Internet';
        insert l;

        Test.startTest();
        ConsoleApplicationLinkController k = new ConsoleApplicationLinkController();
        HttpMockGenerator mock = new HttpMockGenerator('[{"Id":"' + l.Id+ '","Token":"bxofefoHG9wLuWDiynV4"}]', 200);
        Test.setMock(HttpCalloutMock.class, mock);
        String value1= cont.id + ',' + acct.Web_Id_NatFund__c;
        String value2= l.id + ',' + + l.Web_Id_NatFund__c;
        String value3 = 'error';
        //ConsoleApplicationLinkController.getShortenedLink(l.id, l.Web_Id_NatFund__c, 'National Funding', 'Quick Bridge');
        //ConsoleApplicationLinkController.getShortenedLinkOneParam(value2, 'National Funding', 'Quick Bridge');
        //ConsoleApplicationLinkController.getShortenedLinkLT(value2, 'National Funding', 'Quick Bridge');
        ConsoleApplicationLinkController.getShortenedLinkLoanMod(value2, 'National Funding', 'Quick Bridge');
        ConsoleApplicationLinkController.getShortenedLinkSecondDML(value2, 'National Funding', 'Quick Bridge');
        
        ConsoleApplicationLinkController.returnURL(cont.id);
        Test.stopTest();
    }
    
    static testMethod void bulkContactTest()
    {
        Account a = new Account( Web_Id_NatFund__c= '123456789', Name = 'Test');
        insert a;

        Contact c = new Contact();
        c.AccountId = a.Id;
        c.LastName = 'lastname';
        c.FirstName = 'firstname';
        insert c;

        Test.startTest();
        ConsoleApplicationLinkController k = new ConsoleApplicationLinkController();
        HttpMockGenerator mock = new HttpMockGenerator('[{"Id":"1","Token":"t0"},{"Id":"2","Token":"t1"},{"Id":"3","Token":"t2"},{"Id":"4","Token":"t3"}]', 200);
        Test.setMock(HttpCalloutMock.class, mock);
        String valContacts = '{"ID":"' + c.Id+'","Properties":{"NFD":"11111111", "ContactId":"' +c.id+'","GeneratingTime":"' + Date.today().format() + '"}}';
        String valLeads = null;
        ConsoleApplicationLinkController.getShortenedLinkBULK(valContacts, valLeads);
        ConsoleApplicationLinkController.getShortenedLinkBULKNOTFUTURE(valContacts, valLeads);
        Test.stopTest();
    }
    static testMethod void bulkLeadTest()
    {
        Lead l = new Lead();
        l.IsConverted = FALSE;
        l.LastName = 'test lead 1';
        l.Company = 'Test Company';
        insert l;

        Test.startTest();
        ConsoleApplicationLinkController k = new ConsoleApplicationLinkController();
        HttpMockGenerator mock = new HttpMockGenerator('[{"Id":"1","Token":"t0"},{"Id":"2","Token":"t1"},{"Id":"3","Token":"t2"},{"Id":"4","Token":"t3"}]', 200);
        Test.setMock(HttpCalloutMock.class, mock);
        String valContacts = null;
        String valLeads = '{"ID":"' + l.Id+'","Properties":{"NFD":"11111111", "LeadId":"' +l.id+'","GeneratingTime":"' + Date.today().format() + '"}}';
        ConsoleApplicationLinkController.getShortenedLinkBULK(valContacts, valLeads);
        ConsoleApplicationLinkController.getShortenedLinkBULKNOTFUTURE(valContacts, valLeads);
        Test.stopTest();
    }

}