unpackaged/main/default/objects/Account/fields/Account_Number__c.field-meta.xml
<CustomField>
    <fullName>Account_Number__c</fullName>
    <description>The 16 digit account number associated with this account.</description>
    <inlineHelpText>The 16 digit account number associated with this account.</inlineHelpText>
    <label>Account Number</label>
    <length>16</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Bank_Name__c.field-meta.xml
<CustomField>
    <fullName>Bank_Name__c</fullName>
    <description>Bank Name</description>
    <inlineHelpText>Enter Name of Bank</inlineHelpText>
    <label>Bank Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/recordTypes/Customer.recordType-meta.xml
<RecordType>
    <fullName>Customer</fullName>
    <active>true</active>
    <label>Customer</label>
</RecordType>

unpackaged/main/default/objects/Bank_Data__c/Bank_Data__c.object-meta.xml
<CustomObject>
    <label>Bank Data</label>
    <nameField>
        <displayFormat>BD-{0}</displayFormat>
        <label>Bank_Data</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bank Data</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Bank_Data__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Bank Data</relationshipLabel>
    <relationshipName>Bank_Data</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Bank_Data__c/fields/Account_Number__c.field-meta.xml
<CustomField>
    <fullName>Account_Number__c</fullName>
    <description>Field to initially capture and compare bank account number data to ensure we are not pulling duplicate bank accounts.</description>
    <inlineHelpText>Field to initially capture and compare bank account number data to ensure we are not pulling duplicate bank accounts.</inlineHelpText>
    <label>Account Number</label>
    <length>175</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Bank_Data__c/fields/Bank_Name__c.field-meta.xml
<CustomField>
    <fullName>Bank_Name__c</fullName>
    <description>This field will collect the Name of the bank that the rep has collected.</description>
    <inlineHelpText>Enter the name of the customer's bank account.</inlineHelpText>
    <label>Bank Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Bank_Data__c/fields/Routing_Number__c.field-meta.xml
<CustomField>
    <fullName>Routing_Number__c</fullName>
    <label>Routing Number</label>
    <length>9</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Bank_Data__c/fields/Yodlee_Banks__c.field-meta.xml
<CustomField>
    <fullName>Yodlee_Banks__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Yodlee Banks</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2) OR 3</booleanFilter>
        <filterItems>
            <field>$Profile.Name</field>
            <operation>equals</operation>
            <value>FPC - WC - Renewal Sales, NF Renewal Manager Profile</value>
        </filterItems>
        <filterItems>
            <field>Yodlee_Banks__c.Transaction_Depth__c</field>
            <operation>greaterOrEqual</operation>
            <value>90</value>
        </filterItems>
        <filterItems>
            <field>$Profile.Name</field>
            <operation>notEqual</operation>
            <value>FPC - WC - Renewal Sales, NF Renewal Manager Profile</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Yodlee_Banks__c</referenceTo>
    <relationshipLabel>Bank Data</relationshipLabel>
    <relationshipName>Bank_Data</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/DLP_Email_Status__c.field-meta.xml
<CustomField>
    <fullName>DLP_Email_Status__c</fullName>
    <description>Status of DLP Emails - can be automatic or single end.</description>
    <label>DLP Email Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Prequal DocuSign Complete</fullName>
            </value>
            <value>
                <fullName>Prequal Bank Statements Uploaded</fullName>
            </value>
            <value>
                <fullName>Driver's License Uploaded</fullName>
            </value>
            <value>
                <fullName>Voided Check Uploaded</fullName>
            </value>
            <value>
                <fullName>Drip Campaign Started</fullName>
            </value>
            <value>
                <fullName>DLP Drip Activated</fullName>
            </value>
            <value>
                <fullName>DLP Email Sent</fullName>
            </value>
            <value>
                <fullName>DLP Drip Deactivated</fullName>
            </value>
            <value>
                <fullName>DLP Drip Campaign Ended</fullName>
            </value>
            <value>
                <fullName>Prequal Application Signing Complete</fullName>
            </value>
            <value>
                <fullName>DLP Page 1 Complete</fullName>
            </value>
            <value>
                <fullName>DLP Page 2 Complete</fullName>
            </value>
            <value>
                <fullName>Email Link Clicked</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Lead/fields/Account_Number__c.field-meta.xml
<CustomField>
    <fullName>Account_Number__c</fullName>
    <description>The 16 digit account number assigned to this account.</description>
    <inlineHelpText>The 16 digit account number assigned to this account.</inlineHelpText>
    <label>Account Number</label>
    <length>16</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Lead/fields/Bank_Name__c.field-meta.xml
<CustomField>
    <fullName>Bank_Name__c</fullName>
    <description>The name of the customer's bank.</description>
    <inlineHelpText>Enter the name of the customer's bank.</inlineHelpText>
    <label>Bank Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Lead/fields/DLP_Email_Status__c.field-meta.xml
<CustomField>
    <fullName>DLP_Email_Status__c</fullName>
    <label>DLP Email Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Prequal DocuSign Complete</fullName>
            </value>
            <value>
                <fullName>Prequal Bank Statements Uploaded</fullName>
            </value>
            <value>
                <fullName>Driver's License Uploaded</fullName>
            </value>
            <value>
                <fullName>Voided Check Uploaded</fullName>
            </value>
            <value>
                <fullName>Drip Campaign Started</fullName>
            </value>
            <value>
                <fullName>DLP Drip Activated</fullName>
            </value>
            <value>
                <fullName>DLP Email Sent</fullName>
            </value>
            <value>
                <fullName>DLP Drip Deactivated</fullName>
            </value>
            <value>
                <fullName>DLP Drip Campaign Ended</fullName>
            </value>
            <value>
                <fullName>Prequal Application Signing Complete</fullName>
            </value>
            <value>
                <fullName>DLP Page 1 Complete</fullName>
            </value>
            <value>
                <fullName>DLP Page 2 Complete</fullName>
            </value>
            <value>
                <fullName>Email Link Clicked</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/User/fields/Available_Brands__c.field-meta.xml
<CustomField>
    <fullName>Available_Brands__c</fullName>
    <description>Introduced as part of the Quick Bridge to National Funding migration project to capture which brands this user works for. Originally all users will have one available brand but this is being created as a multi select picklist with the possibility that reps can work under multiple brands in the future.</description>
    <inlineHelpText>Which brand does this user work under?</inlineHelpText>
    <label>Available Brands</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>National Funding</fullName>
                <default>true</default>
                <label>National Funding</label>
            </value>
            <value>
                <fullName>Quick Bridge</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Yodlee_Banks__c/Yodlee_Banks__c.object-meta.xml
<CustomObject>
    <label>Yodlee Banks</label>
    <nameField>
        <label>Yodlee FI Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Yodlee Banks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/classes/TestSendDLPRequestLead.cls
@isTest
public class TestSendDLPRequestLead {

    public class LeadWrapper {
        public boolean IsSelected { get; set; }
        public Lead Lead { get; set; }
        public boolean HasEmail { get; set; }
        public String cType {get; set;}
        
        public LeadWrapper(Lead c, boolean hasEmail){
            Lead = c;
            IsSelected = false;
            this.HasEmail = hasEmail;
        }
    }
    
    @isTest
    static  void Test_SendDLPRequestLeadExtension(){
        createTestData();

        Account acc = new Account(Name = 'unit test account', Phone = '+1 300 2011231', Type = 'Customer');
        insert acc;

        Lead c = new Lead(LastName = 'harry1', Email='bkravitz@nationalfunding.com', Company='NF', DLP_Email_Status__c = 'DLP Email Sent');
        Lead c1 = new Lead(LastName = 'harry', Email='oporter@nationalfunding.com', Company='NF', DLP_Email_Status__c = 'DLP Drip Activated');
        insert c;
        insert c1;
        
        Test.startTest();
            PageReference pageRef = Page.SendDLPLead;
            Test.setCurrentPage(pageRef);

            HttpMockGenerator mock = new HttpMockGenerator('[{"Id":"' + c.Id+ '","Token":"bxofefoHG9wLuWDiynV4"}]', 200);
            Test.setMock(HttpCalloutMock.class, mock);
            SendDLPRequestLead ext = new SendDLPRequestLead(new Apexpages.StandardController(c1));
            ext.getItems();
            //testing without selecting any contact
            ext.SendEmail();
        Test.stopTest();
        boolean foundDesiredMsg = false;
        for(ApexPages.Message msg :  ApexPages.getMessages()) {
            if(msg.getSummary() == 'Please select atleast 1 contact'){
                foundDesiredMsg = true;
            }
        }
        System.assertEquals(false, foundDesiredMsg, 'Atlease 1 Lead validation did not worked');
    }

    @isTest
    static  void Test_SendDLPRequestLeadExtension2(){
        createTestData();

        Profile p = [SELECT Id FROM Profile WHERE Name='Standard User']; 
        User u = new User(Alias = 'standt', Email='standarduser@testorg.com.nf',EmailEncodingKey='UTF-8', 
                        LastName='Testing', LanguageLocaleKey='en_US',LocaleSidKey='en_US', ProfileId = p.Id, 
                        TimeZoneSidKey='America/Los_Angeles', UserName='standardus@testorg.com.nf', Available_Brands__c = 'Quick Bridge;National Funding');
        insert u;

        Lead c = new Lead(LastName = 'harry1', Email='bkravitz@nationalfunding.com', Company='NF', DLP_Email_Status__c = 'DLP Email Sent', OwnerId = u.Id);
        Lead c1 = new Lead(LastName = 'harry', Email='oporter@nationalfunding.com', Company='NF', DLP_Email_Status__c = '', OwnerId = u.Id);
        insert c;
        insert c1;
        
        Test.startTest();
            PageReference pageRef = Page.SendDLPLead;
            Test.setCurrentPage(pageRef);

            HttpMockGenerator mock = new HttpMockGenerator('[{"Id":"' + c.Id+ '","Token":"bxofefoHG9wLuWDiynV4"}]', 200);
            Test.setMock(HttpCalloutMock.class, mock);
            SendDLPRequestLead ext = new SendDLPRequestLead(new Apexpages.StandardController(c1));
            ext.getItems();           
            //testing without selecting any contact
            ext.SendEmail();
        Test.stopTest();
        boolean foundDesiredMsg = false;
        for(ApexPages.Message msg :  ApexPages.getMessages()) {
            if(msg.getSummary() == 'Please select atleast 1 contact'){
                foundDesiredMsg = true;
            }
        }
        System.assertEquals(false, foundDesiredMsg, 'Atlease 1 Lead validation did not worked');
    }

    @isTest
    static void Test_SendDLPRequestLeadExtension3(){
        createTestData();

        Account acc = new Account(Name = 'unit test account', Phone = '+1 300 2011231', Type = 'Customer');
        insert acc;

        Lead c = new Lead(LastName = 'harry1', Email='bkravitz@nationalfunding.com', Company='NF', DLP_Email_Status__c = 'DLP Email Sent');
        Lead c1 = new Lead(LastName = 'harry', Email='oporter@nationalfunding.com', Company='NF', DLP_Email_Status__c = 'DLP Drip Activated');
        insert c;
        insert c1;
        
        Test.startTest();
            PageReference pageRef = Page.SendDLPLead;
            Test.setCurrentPage(pageRef);
            
            HttpMockGenerator mock = new HttpMockGenerator('[{"Id":"' + c.Id+ '","Token":"bxofefoHG9wLuWDiynV4"}]', 200);
            Test.setMock(HttpCalloutMock.class, mock);
            SendDLPRequestLead ext = new SendDLPRequestLead(new Apexpages.StandardController(c));
            ext.getItems();
            List<SendDLPRequestLead.LeadWrapper> contacts = ext.Leads;
            
            //testing without selecting any contact
            ext.SendEmail();
        Test.stopTest();
        boolean foundDesiredMsg = false;
        for(ApexPages.Message msg :  ApexPages.getMessages()) {
            if(msg.getSummary() == 'Please select atleast 1 contact'){
                foundDesiredMsg = true;
            }
        }
        System.assertEquals(false, foundDesiredMsg, 'Atlease 1 Lead validation did not worked');
    }

    @isTest
    static void createTestData(){
        Account acc = new Account(Name = 'unit test account', Phone = '+1 300 2011231', Type = 'Customer');
        insert acc;
        
        HttpMockGenerator mock = new HttpMockGenerator('[{"Id":"' + acc.Id+ '","Token":"bxofefoHG9wLuWDiynV4"}]', 200);
        Test.setMock(HttpCalloutMock.class, mock);

        List<Lead> leadRecs = new List<Lead>();
        for(integer i=0; i<20; i++){
            leadRecs.add(new Lead( LastName = 'unit test contact'+i, Email = 'test'+i+'@gmail.com', Company='NF'));
        }
        insert leadRecs;

        Yodlee_Banks__c ybank = new Yodlee_Banks__c(Name = 'worst bank ever');
        insert ybank;

        List<Bank_Data__c> bankAccounts = new List<Bank_Data__c>();
        integer bankAccountNo = 123456789;
        for(integer i=0; i<20; i++){
            bankAccountNo++;
            system.debug('bank account number'+i+': '+bankAccountNo);
            bankAccounts.add(new Bank_Data__c(Yodlee_Banks__c = ybank.id, Account__c = acc.Id, Bank_Name__c = 'unit test bank '+i, Account_Number__c = bankAccountNo+'', Routing_Number__c = '1231231'+i));
        }
        insert bankAccounts;
    }
    
    @isTest
    static void createTestData2(){
        
        Account acc = new Account(Name = 'unit test account', Phone = '+1 300 2011231', Type = 'Customer');
        insert acc;
        
        HttpMockGenerator mock = new HttpMockGenerator('[{"Id":"' + acc.Id+ '","Token":"bxofefoHG9wLuWDiynV4"}]', 200);
        Test.setMock(HttpCalloutMock.class, mock);

        List<Lead> leadRecs = new List<Lead>();
        for(integer i=0; i<20; i++){
            leadRecs.add(new Lead(LastName = 'unit test contact'+i, Email = 'test'+i+'@gmail.com', Company='NF'));
        }
        insert leadRecs;

        Yodlee_Banks__c ybank = new Yodlee_Banks__c(Name = 'worst bank ever');
        insert ybank;

        List<Bank_Data__c> bankAccounts = new List<Bank_Data__c>();
        integer bankAccountNo = 123456789;
        for(integer i=0; i<20; i++){
            bankAccountNo++;
            system.debug('bank account number'+i+': '+bankAccountNo);
            bankAccounts.add(new Bank_Data__c(Yodlee_Banks__c = ybank.id, Account__c = acc.Id, Bank_Name__c = 'unit test bank '+i, Account_Number__c = bankAccountNo+'', Routing_Number__c = '1231231'+i));
        }
        insert bankAccounts;
    }       
    
    @isTest
    static void Test_SendDLPRequestLeadExtension4(){
        Lead c = new Lead(LastName = 'harry1', Email='bkravitz@nationalfunding.com', Company='NF', DLP_Email_Status__c = '');
        insert c;
        
        PageReference pageRef = Page.SendDLPLead;
        Test.setCurrentPage(pageRef);
        
        HttpMockGenerator mock = new HttpMockGenerator('[{"Id":"' + c.Id+ '","Token":"bxofefoHG9wLuWDiynV4"}]', 200);
        Test.setMock(HttpCalloutMock.class, mock);
        SendDLPRequestLead ext = new SendDLPRequestLead(new Apexpages.StandardController(c));
        ext.getItems();
    }
}