unpackaged/main/default/objects/Account/fields/Account_Number__c.field-meta.xml
<CustomField>
    <fullName>Account_Number__c</fullName>
    <description>The 16 digit account number associated with this account.</description>
    <inlineHelpText>The 16 digit account number associated with this account.</inlineHelpText>
    <label>Account Number</label>
    <length>16</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Activation_Code__c.field-meta.xml
<CustomField>
    <fullName>Activation_Code__c</fullName>
    <label>Activation Code</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Activation_Date__c.field-meta.xml
<CustomField>
    <fullName>Activation_Date__c</fullName>
    <description>The date the card was "activated"</description>
    <inlineHelpText>The date the card was "activated"</inlineHelpText>
    <label>Activation Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Initial_Lead_Source__c.field-meta.xml
<CustomField>
    <fullName>Initial_Lead_Source__c</fullName>
    <description>This field will be a record of what type of campaign a customer responded to first.</description>
    <inlineHelpText>This field will be a record of what type of campaign a customer responded to first. ***Do Not Change***</inlineHelpText>
    <label>Initial Lead Source</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Initial_Product_Response__c.field-meta.xml
<CustomField>
    <fullName>Initial_Product_Response__c</fullName>
    <description>This field will capture what product a campaign targeted that a customer responded to for the first time.</description>
    <inlineHelpText>This field will capture what product a campaign targeted that a customer responded to for the first time.</inlineHelpText>
    <label>Initial Product Response</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Initial_Response_Channel__c.field-meta.xml
<CustomField>
    <fullName>Initial_Response_Channel__c</fullName>
    <description>This field will be a record of how the customer responded.</description>
    <inlineHelpText>This field will be a record of how the customer responded.  ***Do Not Change***</inlineHelpText>
    <label>Initial Response Channel</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Response_Channel__c.field-meta.xml
<CustomField>
    <fullName>Response_Channel__c</fullName>
    <description>The channel customer used to contact with FPC</description>
    <inlineHelpText>Select the method contact was made with the account</inlineHelpText>
    <label>Response Channel</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Email</fullName>
            </value>
            <value>
                <fullName>Fax</fullName>
            </value>
            <value>
                <fullName>Inbound Call</fullName>
            </value>
            <value>
                <fullName>Internet</fullName>
            </value>
            <value>
                <fullName>Internet Activation</fullName>
            </value>
            <value>
                <fullName>Internet Application</fullName>
            </value>
            <value>
                <fullName>Internet- Lead Aggregator</fullName>
            </value>
            <value>
                <fullName>Outbound Call</fullName>
            </value>
            <value>
                <fullName>Overflow</fullName>
            </value>
            <value>
                <fullName>After Hours Voice Mail</fullName>
            </value>
            <value>
                <fullName>Facebook</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/Short_Account_Number__c.field-meta.xml
<CustomField>
    <fullName>Short_Account_Number__c</fullName>
    <description>The last 8 digits of the customer's 16 digit account number.</description>
    <inlineHelpText>Type in the last 8 digits of the customer's 16 digit account number.</inlineHelpText>
    <label>Short Account Number</label>
    <length>9</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Status_MCA__c.field-meta.xml
<CustomField>
    <fullName>Status_MCA__c</fullName>
    <description>The status of this account regarding Merchant Cash Advance.</description>
    <inlineHelpText>The status of this account regarding Merchant Cash Advance.</inlineHelpText>
    <label>Status MCA</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Interested</fullName>
            </value>
            <value>
                <fullName>Not Qualified</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Campaign/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <label>Brand</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>National Funding</fullName>
                <default>true</default>
                <label>National Funding</label>
            </value>
            <value>
                <fullName>Edge Funding</fullName>
            </value>
            <value>
                <fullName>Finova</fullName>
            </value>
            <value>
                <fullName>Quick Bridge</fullName>
            </value>
            <value>
                <fullName>SBL</fullName>
                <isActive>false</isActive>
                <label>SBL</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Campaign/fields/Product_Target__c.field-meta.xml
<CustomField>
    <fullName>Product_Target__c</fullName>
    <description>This field will capture the Product Target of each campaign. It will also allow for better segmentation for reporting.</description>
    <inlineHelpText>Select the Product Target that this campaign is targeting.</inlineHelpText>
    <label>Product Target</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Lease</fullName>
            </value>
            <value>
                <fullName>Merchant</fullName>
            </value>
            <value>
                <fullName>EPP</fullName>
            </value>
            <value>
                <fullName>Generic</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/CampaignMember/fields/Account_Number__c.field-meta.xml
<CustomField>
    <fullName>Account_Number__c</fullName>
    <externalId>true</externalId>
    <label>Account Number</label>
    <length>16</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/CampaignMember/fields/Activation_Code__c.field-meta.xml
<CustomField>
    <fullName>Activation_Code__c</fullName>
    <label>Activation Code</label>
    <length>16</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/CampaignMember/fields/Campaign_Type__c.field-meta.xml
<CustomField>
    <fullName>Campaign_Type__c</fullName>
    <description>This field will indicate the type of campaign that the campaign member is a part of.</description>
    <formula>TEXT(Campaign.Type)</formula>
    <inlineHelpText>This field will indicate the type of campaign that the campaign member is a part of.</inlineHelpText>
    <label>Campaign Type</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/CampaignMember/fields/Response_Channel__c.field-meta.xml
<CustomField>
    <fullName>Response_Channel__c</fullName>
    <label>Response Channel</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Internet</fullName>
            </value>
            <value>
                <fullName>Inbound Call</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/CampaignMember/fields/Short_Account_Number__c.field-meta.xml
<CustomField>
    <fullName>Short_Account_Number__c</fullName>
    <description>The last 8 of the account number field.</description>
    <externalId>true</externalId>
    <inlineHelpText>The last 8 of the account number field.</inlineHelpText>
    <label>Short Account Number</label>
    <length>9</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Lead/fields/Account_Number__c.field-meta.xml
<CustomField>
    <fullName>Account_Number__c</fullName>
    <description>The 16 digit account number assigned to this account.</description>
    <inlineHelpText>The 16 digit account number assigned to this account.</inlineHelpText>
    <label>Account Number</label>
    <length>16</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Lead/fields/Activation_Code__c.field-meta.xml
<CustomField>
    <fullName>Activation_Code__c</fullName>
    <label>Activation Code</label>
    <length>16</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Lead/fields/Activation_Date__c.field-meta.xml
<CustomField>
    <fullName>Activation_Date__c</fullName>
    <description>The date the card was activated.</description>
    <inlineHelpText>The date the card was activated.</inlineHelpText>
    <label>Activation Date</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Lead/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <label>Brand</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>National Funding</fullName>
            </value>
            <value>
                <fullName>Edge Funding</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Lead/fields/Initial_Lead_Source__c.field-meta.xml
<CustomField>
    <fullName>Initial_Lead_Source__c</fullName>
    <description>This field will be a record of what type of campaign a customer responded to first.</description>
    <inlineHelpText>This field will be a record of what type of campaign a customer responded to first. 
***Do Not Change***</inlineHelpText>
    <label>Initial Lead Source</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Lead/fields/Initial_Response_Channel__c.field-meta.xml
<CustomField>
    <fullName>Initial_Response_Channel__c</fullName>
    <description>This field will be a record of how the customer responded.</description>
    <inlineHelpText>This field will be a record of how the customer responded. 
***Do Not Change***</inlineHelpText>
    <label>Initial Response Channel</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Lead/fields/Initial_Response_Rep__c.field-meta.xml
<CustomField>
    <fullName>Initial_Response_Rep__c</fullName>
    <description>This field will capture the rep that took the initial call from the customer.  This field will be updated by workflow.</description>
    <inlineHelpText>This field will capture the rep that took the initial call from the customer.  This field will be updated by workflow.</inlineHelpText>
    <label>Initial Response Rep</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Lead/fields/Initial_Response_User__c.field-meta.xml
<CustomField>
    <fullName>Initial_Response_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field will capture the user that initially worked with the customer.</description>
    <inlineHelpText>This field will capture the user that initially worked with the customer.</inlineHelpText>
    <label>Initial Response User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Lead/fields/Last_Campaign_Response_Date__c.field-meta.xml
<CustomField>
    <fullName>Last_Campaign_Response_Date__c</fullName>
    <description>This field will indicate when the last response to a campaign occurred.</description>
    <inlineHelpText>This field will indicate when the last response to a campaign occurred.</inlineHelpText>
    <label>Last Campaign Response Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Lead/fields/Rep_Ownership_Date__c.field-meta.xml
<CustomField>
    <fullName>Rep_Ownership_Date__c</fullName>
    <description>This field will indicate the date that a rep took ownership of the lead.</description>
    <inlineHelpText>This field will indicate the date that a rep took ownership of the lead.</inlineHelpText>
    <label>Rep Ownership Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Lead/fields/Response_Channel__c.field-meta.xml
<CustomField>
    <fullName>Response_Channel__c</fullName>
    <description>Indicate the response channel used to reach this Lead</description>
    <inlineHelpText>Select the response channel used to reach this Lead</inlineHelpText>
    <label>Response Channel</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Email</fullName>
            </value>
            <value>
                <fullName>Fax</fullName>
            </value>
            <value>
                <fullName>Inbound Call</fullName>
            </value>
            <value>
                <fullName>Internet</fullName>
            </value>
            <value>
                <fullName>Internet Activation</fullName>
            </value>
            <value>
                <fullName>Internet Application</fullName>
            </value>
            <value>
                <fullName>Internet- Lead Aggregator</fullName>
            </value>
            <value>
                <fullName>Outbound Call</fullName>
            </value>
            <value>
                <fullName>Overflow</fullName>
            </value>
            <value>
                <fullName>After Hours Voice Mail</fullName>
            </value>
            <value>
                <fullName>Dev Site</fullName>
            </value>
            <value>
                <fullName>Facebook</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Lead/fields/Short_Account_Number__c.field-meta.xml
<CustomField>
    <fullName>Short_Account_Number__c</fullName>
    <description>A calculated field that is that last 8 digits of the account number.  Used for many lookups.</description>
    <inlineHelpText>A calculated field that is that last 8 digits of the account number.  Used for many lookups.</inlineHelpText>
    <label>Short Account Number</label>
    <length>9</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Lead/fields/Status_MCA__c.field-meta.xml
<CustomField>
    <fullName>Status_MCA__c</fullName>
    <label>Status MCA</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Interested</fullName>
            </value>
            <value>
                <fullName>Not Qualified</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/cardSearchActivation.cls
public with sharing class cardSearchActivation {

    // Modified for National Funding Lightning Transition
    // Original Code: https://nf.lightning.force.com/lightning/setup/ApexClasses/page?address=%2F01p8000000041Ej

    // Lead Activation
    @AuraEnabled
    public static object activateLead(String cmId, String leadId, String userId){

        system.debug('Lead Id: ' + leadId);
        system.debug('CM Id: ' + cmId);
        system.debug('UserId: ' + userId);

        CampaignMember[] cm = [Select Status,Short_Account_Number__c,Account_Number__c,Activation_Code__c,Campaign_Type__c,Campaign.Product_Target__c, Campaign.Brand__c From CampaignMember where id = :cmId];

        system.debug('Campaign Member:');
        system.debug(cm);
        
        if (cm.size() > 0){
            cm[0].Status = 'Responded';
            upsert cm;
        }

        Lead theLead = [Select Id,Last_Campaign_Response_Date__c,Activation_Date__c,Rep_Ownership_Date__c,Initial_Lead_Source__c,Response_Channel__c,LeadSource,Account_Number__c,Status,Status_MCA__c,OwnerId,IsConverted, Brand__c,Initial_Response_Channel__c,Initial_Response_Rep__c, Initial_Response_User__c, Initial_Product_Response__c from Lead where Id = :leadId];
        Boolean ownedByQueue = String.valueOf(theLead.OwnerId).startsWith('00G');
        User leadOwner;
        
        if (!ownedByQueue){
            leadOwner = [SELECT Sales_User__c FROM User WHERE Id = :theLead.OwnerId];
        }

            
        if (theLead != null && theLead.Status != 'Qualified/Converted'){
            
            Boolean hasActivationDate = false;

            if(theLead.Activation_Date__c == null) {
                theLead.Activation_Date__c = System.now();
            } else{
                hasActivationDate = true;
            }

            if(cm.size() > 0){
                theLead.Short_Account_Number__c = cm[0].Short_Account_Number__c;
                theLead.Account_Number__c = cm[0].Account_Number__c;
                theLead.Activation_Code__c = cm[0].Activation_Code__c;            
                theLead.LeadSource = cm[0].Campaign_Type__c;
            }

            theLead.Response_Channel__c = 'Inbound Call';
            theLead.Last_Card_Search_Date__c = Date.today();
            
            if((ownedByQueue || leadOwner.Sales_User__c == false) && (theLead.status != 'House' || !hasActivationDate)){

                system.debug('lead owner is House account or DB Amp, reassigning to current user...');

                theLead.OwnerId = userId;
                User usr = [SELECT Name, Id FROM User WHERE Id = :theLead.ownerId];

                theLead.Rep_Ownership_Date__c = Date.today();
                theLead.Card_Search_Used__c = true;
                theLead.Last_Campaign_Response_Date__c = Date.today();

                if (!hasActivationDate) {
                    if (theLead.Initial_Response_Channel__c == null){
                        theLead.Initial_Response_Channel__c = 'Inbound Call';
                    }
                    if (theLead.Initial_Response_Rep__c == null){
                        theLead.Initial_Response_Rep__c = usr.Name;
                    }
                    if (theLead.Initial_Response_User__c == null){
                        theLead.Initial_Response_User__c = usr.id;
                    }
                    if (theLead.Initial_Lead_Source__c == null){
                        theLead.Initial_Lead_Source__c = theLead.LeadSource;
                    }
                    if (theLead.Initial_Product_Response__c == null && cm.size() > 0){
                        theLead.Initial_Product_Response__c = cm[0].Campaign.Product_Target__c;
                    }
                }
            }
            
           string lst = theLead.Status;
           system.debug('the lead status is... '+lst);

            if((lst == 'House' || lst == 'Open' || lst == 'Pursuing' || lst == 'Contacted') && (lst != 'Prospect' && lst != 'Activator' && lst != 'Remove from List')){ 
                theLead.Status = 'Prospect';
                system.debug('changing the lead status to... '+theLead.Status);

                if(cm.size() > 0){
                    theLead.Brand__c = cm[0].Campaign.Brand__c;
                }
            }
    
            update theLead;
        }
        
        Map<String,String> valueReturn = new Map<String,String>();
        valueReturn.put('RedirectRecord', leadId);
        valueReturn.put('RedirectObject', 'Lead');
               
        return valueReturn;

    }


    // Contact Activation
    @AuraEnabled
    public static object activateContact(String cmId, String contactId, String userId){

        system.debug('cmId: ' + cmId);
        system.debug('ContactId: ' + contactId);
        system.debug('UserId: ' + userId);

        Contact cont = [Select Account.Owner.Sales_User__c, AccountId, LeadSource From Contact WHERE Id = :contactId];
        CampaignMember[] cm = [Select Status,Short_Account_Number__c,Account_Number__c,Activation_Code__c,Campaign_Type__c,Campaign.Product_Target__c From CampaignMember where id = :cmId];
        User currentUser = [SELECT Sales_User__c FROM User WHERE Id = : userId];

        system.debug('Contact:');
        system.debug(cont);

        system.debug('Campaign Member:');
        system.debug(cm);

        system.debug('currentUser:');
        system.debug(currentUser);



        if(cm.size() > 0)
        {
            system.debug('Updaing CM');

            cm[0].Status = 'Responded';
            upsert cm;

            cont.LeadSource = cm[0].Campaign_Type__c;
            upsert cont;
        }
            
        Account acct = new Account(id = cont.accountId);
        acct.Response_Channel__c = 'Inbound Call';
        acct.Last_Card_Search_Date__c = Date.today();
            
        if (cont.Account.Owner.Sales_User__c == false) {
            acct.OwnerId = userId;
            acct.Rep_Ownership_Date__c = Date.today();
            acct.Card_Search_Used__c = true;
            acct.Last_Campaign_Response_Date__c = Date.today();

            if (acct.Initial_Response_Channel__c == null)
                acct.Initial_Response_Channel__c = acct.Response_Channel__c;
            if (acct.Initial_Lead_Source__c == null)
                 acct.Initial_Lead_Source__c = cont.LeadSource;
            if (acct.Initial_Product_Response__c == null && cm.size() > 0)
                acct.Initial_Product_Response__c = cm[0].Campaign.Product_Target__c;
        }

        upsert acct;

        Map<String,String> valueReturn = new Map<String,String>();
        valueReturn.put('RedirectRecord', cont.accountId);
        valueReturn.put('RedirectObject', 'Account');
               
        return valueReturn;

    }

}