unpackaged/main/default/objects/Account/fields/Account_Number__c.field-meta.xml
<CustomField>
    <fullName>Account_Number__c</fullName>
    <description>The 16 digit account number associated with this account.</description>
    <inlineHelpText>The 16 digit account number associated with this account.</inlineHelpText>
    <label>Account Number</label>
    <length>16</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Bank_Name__c.field-meta.xml
<CustomField>
    <fullName>Bank_Name__c</fullName>
    <description>Bank Name</description>
    <inlineHelpText>Enter Name of Bank</inlineHelpText>
    <label>Bank Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/NF_Renewal_Rep__c.field-meta.xml
<CustomField>
    <fullName>NF_Renewal_Rep__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Previously was “NF Renewal Rep” but the “NF” was removed to make this field generic enough to support Quick Bridge renewals with working out of National Funding Salesforce.</description>
    <inlineHelpText>The renewal rep's name is entered in this field.</inlineHelpText>
    <label>Renewal Rep</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Accounts4</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Account/recordTypes/Customer.recordType-meta.xml
<RecordType>
    <fullName>Customer</fullName>
    <active>true</active>
    <label>Customer</label>
</RecordType>

unpackaged/main/default/objects/Bank_Data__c/Bank_Data__c.object-meta.xml
<CustomObject>
    <label>Bank Data</label>
    <nameField>
        <displayFormat>BD-{0}</displayFormat>
        <label>Bank_Data</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bank Data</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Bank_Data__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Bank Data</relationshipLabel>
    <relationshipName>Bank_Data</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Bank_Data__c/fields/Account_Number__c.field-meta.xml
<CustomField>
    <fullName>Account_Number__c</fullName>
    <description>Field to initially capture and compare bank account number data to ensure we are not pulling duplicate bank accounts.</description>
    <inlineHelpText>Field to initially capture and compare bank account number data to ensure we are not pulling duplicate bank accounts.</inlineHelpText>
    <label>Account Number</label>
    <length>175</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Bank_Data__c/fields/Bank_Name__c.field-meta.xml
<CustomField>
    <fullName>Bank_Name__c</fullName>
    <description>This field will collect the Name of the bank that the rep has collected.</description>
    <inlineHelpText>Enter the name of the customer's bank account.</inlineHelpText>
    <label>Bank Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Bank_Data__c/fields/Routing_Number__c.field-meta.xml
<CustomField>
    <fullName>Routing_Number__c</fullName>
    <label>Routing Number</label>
    <length>9</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Bank_Data__c/fields/Yodlee_Banks__c.field-meta.xml
<CustomField>
    <fullName>Yodlee_Banks__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Yodlee Banks</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2) OR 3</booleanFilter>
        <filterItems>
            <field>$Profile.Name</field>
            <operation>equals</operation>
            <value>FPC - WC - Renewal Sales, NF Renewal Manager Profile</value>
        </filterItems>
        <filterItems>
            <field>Yodlee_Banks__c.Transaction_Depth__c</field>
            <operation>greaterOrEqual</operation>
            <value>90</value>
        </filterItems>
        <filterItems>
            <field>$Profile.Name</field>
            <operation>notEqual</operation>
            <value>FPC - WC - Renewal Sales, NF Renewal Manager Profile</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Yodlee_Banks__c</referenceTo>
    <relationshipLabel>Bank Data</relationshipLabel>
    <relationshipName>Bank_Data</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Bank_Name__c.field-meta.xml
<CustomField>
    <fullName>Bank_Name__c</fullName>
    <description>Bank Name</description>
    <inlineHelpText>Enter name of Bank</inlineHelpText>
    <label>Bank Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/NF_Renewal_Rep__c.field-meta.xml
<CustomField>
    <fullName>NF_Renewal_Rep__c</fullName>
    <formula>Account.NF_Renewal_Rep__r.Full_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>NF Renewal Rep</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/User/fields/Available_Brands__c.field-meta.xml
<CustomField>
    <fullName>Available_Brands__c</fullName>
    <description>Introduced as part of the Quick Bridge to National Funding migration project to capture which brands this user works for. Originally all users will have one available brand but this is being created as a multi select picklist with the possibility that reps can work under multiple brands in the future.</description>
    <inlineHelpText>Which brand does this user work under?</inlineHelpText>
    <label>Available Brands</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>National Funding</fullName>
                <default>true</default>
                <label>National Funding</label>
            </value>
            <value>
                <fullName>Quick Bridge</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Yodlee_Banks__c/Yodlee_Banks__c.object-meta.xml
<CustomObject>
    <label>Yodlee Banks</label>
    <nameField>
        <label>Yodlee FI Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Yodlee Banks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/classes/SendFundingOptionsControllerTest.cls
//Created by Olivia Porter on 8/17/18

@isTest
private class SendFundingOptionsControllerTest{

    public class ContactWrapper {
        public boolean IsSelected { get; set; }
        public Contact Contact { get; set; }
        public boolean HasEmail { get; set; }
        public String cType {get; set;}

        public ContactWrapper(Contact c, boolean hasEmail){
            Contact = c;
            IsSelected = false;
            this.HasEmail = hasEmail;
        }
    }

    @isTest
    static void Test_SendFundingOptions(){
        createTestData();
        Account acc = new Account(Name = 'unit test account', Phone = '+1 300 2011231', Type = 'Customer');
        insert acc;

        Contact c = new Contact(LastName = 'harry1', Email='test@nationalfunding.com', AccountId = acc.Id);
        Contact c1 = new Contact(LastName = 'harry', Email='test2@nationalfunding.com', AccountId = acc.Id);
        insert c;
        insert c1;

        Opportunity opp = new Opportunity(Name = 'TestOpp', Account = acc, AccountId = acc.Id, StageName = 'Approved - MCA', CloseDate = Date.today());
        insert opp;

        Test.startTest();
            PageReference pageRef = Page.SendFundingOptions;
            Test.setCurrentPage(pageRef);

            HttpMockGenerator mock = new HttpMockGenerator('[{"Id":"' + c.Id+ '","Token":"bxofefoHG9wLuWDiynV4"}]', 200);
            Test.setMock(HttpCalloutMock.class, mock);

            SendFundingOptionsController ext = new SendFundingOptionsController(new Apexpages.StandardController(opp));
            //testing without selecting any contact
            ext.SendEmail();
            boolean foundDesiredMsg = false;
            for(ApexPages.Message msg :  ApexPages.getMessages()) {
                if(msg.getSummary() == 'Please select at least 1 contact'){
                    foundDesiredMsg = true;
                }
            }
            System.assertEquals(true, foundDesiredMsg, 'At lease 1 Contact validation did not worked');

            ext.contactList[0].IsSelected = True;
            system.debug('------------>' + ext.contactList[0]);
            ext.contactList[1].IsSelected = False;
            //testing without selecting any bank
            ext.SendEmail();
            foundDesiredMsg = false;
        Test.stopTest();
        for(ApexPages.Message msg :  ApexPages.getMessages()) {
            if(msg.getSummary() == 'Please select at least 1 bank'){
                foundDesiredMsg = true;
            }
        }
        System.assertEquals(false, foundDesiredMsg, 'At lease 1 Bank validation did not worked');
    }

    @isTest
    static void Test_SendFundingOptions2(){
        createTestData();

        Profile p = [SELECT Id FROM Profile WHERE Name='Standard User']; 
        User u = new User(Alias = 'standt', Email='standarduser@testorg.com.nf',EmailEncodingKey='UTF-8', 
                        LastName='Testing', LanguageLocaleKey='en_US',LocaleSidKey='en_US', ProfileId = p.Id, 
                        TimeZoneSidKey='America/Los_Angeles', UserName='standardus@testorg.com.nf', Available_Brands__c = 'Quick Bridge;National Funding');
        insert u;

        Account acc = new Account(Name = 'unit test account', Phone = '+1 300 2011231', Type = 'Customer', NF_Renewal_Rep__c = u.Id);
        insert acc;

        Contact c = new Contact(LastName = 'harry1', Email='bkravitz@nationalfunding.com', AccountId = acc.Id);
        Contact c1 = new Contact(LastName = 'harry', Email='oporter@nationalfunding.com', AccountId = acc.Id);
        insert c;
        insert c1;

        Opportunity opp = new Opportunity(Name = 'TestOpp', Account = acc, AccountId = acc.Id, StageName = 'Approved - MCA', CloseDate = Date.today());
        insert opp;

        Test.startTest();
            PageReference pageRef = Page.SendFundingOptions;
            Test.setCurrentPage(pageRef);

            HttpMockGenerator mock = new HttpMockGenerator('[{"Id":"' + c.Id+ '","Token":"bxofefoHG9wLuWDiynV4"}]', 200);
            Test.setMock(HttpCalloutMock.class, mock);

            SendFundingOptionsController ext = new SendFundingOptionsController(new Apexpages.StandardController(opp));
            List<SendFundingOptionsController.ContactWrapper> contacts = ext.contactList;

            //testing without selecting any contact
            ext.SendEmail();
            boolean foundDesiredMsg = false;
            for(ApexPages.Message msg :  ApexPages.getMessages()) {
                if(msg.getSummary() == 'Please select at least 1 contact'){
                    foundDesiredMsg = true;
                }
            }
            System.assertEquals(true, foundDesiredMsg, 'At lease 1 Contact validation did not worked');

            ext.contactList[0].IsSelected = True;
            system.debug('------------>' + ext.contactList[0]);
            ext.contactList[1].IsSelected = False;
            //testing without selecting any bank
            ext.SendEmail();
        Test.stopTest();
        foundDesiredMsg = false;
        for(ApexPages.Message msg :  ApexPages.getMessages()) {
            if(msg.getSummary() == 'Please select at least 1 bank'){
                foundDesiredMsg = true;
            }
        }
        System.assertEquals(false, foundDesiredMsg, 'At lease 1 Bank validation did not worked');
    }

    @isTest
    static void createTestData(){
        Account acc = new Account(Name = 'unit test account', Phone = '+1 300 2011231', Type = 'Customer');
        insert acc;

        List<Contact> contacts = new List<Contact>();
        for(integer i=0; i<20; i++){
            contacts.add(new Contact(AccountId = acc.Id, LastName = 'unit test contact'+i, Email = 'test'+i+'@gmail.com'));
        }
        insert contacts;
        Yodlee_Banks__c ybank = new Yodlee_Banks__c(Name = 'Test Bank Name');
        insert ybank;
        List<Bank_Data__c> bankAccounts = new List<Bank_Data__c>();
        integer bankAccountNo = 123456789;
        for(integer i=0; i<20; i++){
            bankAccountNo++;
            system.debug('bank account number'+i+': '+bankAccountNo);
            bankAccounts.add(new Bank_Data__c(Yodlee_Banks__c = ybank.id, Account__c = acc.Id, Bank_Name__c = 'unit test bank '+i, Account_Number__c = bankAccountNo+'', Routing_Number__c = '1231231'+i));
        }
        insert bankAccounts;
    }

    @isTest
    static void createTestData2(){
        Account acc = new Account(Name = 'unit test account', Phone = '+1 300 2011231', Type = 'Customer');
        insert acc;

        List<Contact> contacts = new List<Contact>();
        for(integer i=0; i<20; i++){
            contacts.add(new Contact(AccountId = acc.Id, LastName = 'unit test contact'+i, Email = 'test'+i+'@gmail.com'));
        }
        insert contacts;

        Yodlee_Banks__c ybank = new Yodlee_Banks__c(Name = 'test bank name');
        insert ybank;

        List<Bank_Data__c> bankAccounts = new List<Bank_Data__c>();
        integer bankAccountNo = 123456789;

        for(integer i=0; i<20; i++){
            bankAccountNo++;
            system.debug('bank account number'+i+': '+bankAccountNo);
            bankAccounts.add(new Bank_Data__c(Yodlee_Banks__c = ybank.id, Account__c = acc.Id, Bank_Name__c = 'unit test bank '+i, Account_Number__c = bankAccountNo+'', Routing_Number__c = '1231231'+i));
        }
        insert bankAccounts;
    }

    @isTest
    static void createTestData3() {
        Id accountId = '001S000000nfn6YIAQ';
        List<ContactWrapper> contactList;
        Map<Id, Contact> contactsWithoutEmail;
        contactList = new List<ContactWrapper>();
        contactsWithoutEmail = new Map<Id, Contact>();
        for(Contact c : [Select Id, Name, Email, AccountId From Contact Where AccountId =: accountId]){
            contactList.Add(new ContactWrapper(c, (c.Email != null)));
        }
    }
}