unpackaged/main/default/objects/Account/fields/Bank_Name__c.field-meta.xml
<CustomField>
    <fullName>Bank_Name__c</fullName>
    <description>Bank Name</description>
    <inlineHelpText>Enter Name of Bank</inlineHelpText>
    <label>Bank Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Fed_Tax_ID__c.field-meta.xml
<CustomField>
    <fullName>Fed_Tax_ID__c</fullName>
    <description>The federal Tax ID of the account</description>
    <externalId>true</externalId>
    <inlineHelpText>The federal Tax ID of the account</inlineHelpText>
    <label>Fed Tax ID</label>
    <length>16</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ACH_Payment__c/ACH_Payment__c.object-meta.xml
<CustomObject>
    <description>This object will be a repository for all ACH payments recorded for lease vendors and working capital customers.</description>
    <label>ACH Payment</label>
    <nameField>
        <displayFormat>ACH # {0}</displayFormat>
        <label>ACH Payment #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ACH Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ACH_Payment__c/fields/ACH_File_Generated__c.field-meta.xml
<CustomField>
    <fullName>ACH_File_Generated__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field will indicate that an ACH file was generated for a specific customer and/or other ACH payment recipients.</description>
    <inlineHelpText>This field will indicate that an ACH file was generated for a specific customer and/or other ACH payment recipients.</inlineHelpText>
    <label>ACH File Generated</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/ACH_Payment__c/fields/ACH_File_Generated_Date__c.field-meta.xml
<CustomField>
    <fullName>ACH_File_Generated_Date__c</fullName>
    <description>This field will indicate what date an ACH file was generated for the customer and/or other ACH payment recipients.</description>
    <inlineHelpText>This field will indicate what date an ACH file was generated for the customer and/or other ACH payment recipients.</inlineHelpText>
    <label>ACH File Generated Date</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/ACH_Payment__c/fields/ACH_Payment__c.field-meta.xml
<CustomField>
    <fullName>ACH_Payment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ACH Payment</label>
    <referenceTo>ACH_Payment__c</referenceTo>
    <relationshipLabel>ACH Payments</relationshipLabel>
    <relationshipName>ACH_Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ACH_Payment__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/ACH_Payment__c/fields/Create_ACH_File_Date__c.field-meta.xml
<CustomField>
    <fullName>Create_ACH_File_Date__c</fullName>
    <label>Create ACH File Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/ACH_Payment__c/fields/NF_Lease_Loan_Number__c.field-meta.xml
<CustomField>
    <fullName>NF_Lease_Loan_Number__c</fullName>
    <description>This field will correspond to CCD Entry Detail Record Field 7 (Company Discretionary Data) in the NACHA File.  It will contain the Lease or Loan Number that the ACH payment is being generated for.</description>
    <inlineHelpText>Please enter the associated customer's Lease or Loan Number.</inlineHelpText>
    <label>NF Lease/Loan Number</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ACH_Payment__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <description>This field will indicate the opportunity that the ACH payments are associated with.</description>
    <inlineHelpText>This field will indicate the opportunity that the ACH payments are associated with.</inlineHelpText>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>ACH Payments</relationshipLabel>
    <relationshipName>ACH_Payments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/ACH_Payment__c/fields/Organization_s_Bank_Account__c.field-meta.xml
<CustomField>
    <fullName>Organization_s_Bank_Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Organization's Bank Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Bank_Account__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Organization</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Bank_Account__c</referenceTo>
    <relationshipLabel>ACH Payments (Organization's Bank Account)</relationshipLabel>
    <relationshipName>ACH_Payments1</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ACH_Payment__c/fields/Pay_On_This_Date__c.field-meta.xml
<CustomField>
    <fullName>Pay_On_This_Date__c</fullName>
    <label>Pay On This Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/ACH_Payment__c/fields/Payee_s_Account_Type__c.field-meta.xml
<CustomField>
    <fullName>Payee_s_Account_Type__c</fullName>
    <description>This field will contain the type of account the funds will be deposited into.</description>
    <inlineHelpText>This field will contain the type of account the funds will be deposited into.</inlineHelpText>
    <label>Payee's Account Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Checking</fullName>
                <default>true</default>
                <label>Checking</label>
            </value>
            <value>
                <fullName>Savings</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ACH_Payment__c/fields/Payee_s_Bank_Account_Number__c.field-meta.xml
<CustomField>
    <fullName>Payee_s_Bank_Account_Number__c</fullName>
    <description>This field will contain the Bank Account Number for the payee.</description>
    <inlineHelpText>This field will contain the Bank Account Number for the payee.</inlineHelpText>
    <label>Payee's Bank Account Number</label>
    <length>17</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ACH_Payment__c/fields/Payee_s_Bank_Name__c.field-meta.xml
<CustomField>
    <fullName>Payee_s_Bank_Name__c</fullName>
    <description>This field will contain the name of the Payee's bank.</description>
    <inlineHelpText>This field will contain the name of the Payee's bank.</inlineHelpText>
    <label>Payee's Bank Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ACH_Payment__c/fields/Payee_s_Name__c.field-meta.xml
<CustomField>
    <fullName>Payee_s_Name__c</fullName>
    <description>This field will contain the name of the company/person that will be receiving the funds.</description>
    <inlineHelpText>This field will contain the name of the company/person that will be receiving the funds.</inlineHelpText>
    <label>Payee's Name</label>
    <length>22</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ACH_Payment__c/fields/Payee_s_Routing_Number__c.field-meta.xml
<CustomField>
    <fullName>Payee_s_Routing_Number__c</fullName>
    <description>This field will contain the routing number for the payee.</description>
    <inlineHelpText>This field will contain the routing number for the payee.</inlineHelpText>
    <label>Payee's Routing Number</label>
    <length>9</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ACH_Payment__c/fields/Receiving_Company_Name__c.field-meta.xml
<CustomField>
    <fullName>Receiving_Company_Name__c</fullName>
    <description>This field will correspond to CCD Entry Detail Record field #8.  This will field should contain the name of the recipient of the payment.  (A maximum of 22 characters are allowed)</description>
    <inlineHelpText>This will field should contain the name of the recipient of the payment.  (A maximum of 22 characters are allowed)</inlineHelpText>
    <label>Receiving Company Name</label>
    <length>22</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Bank_Account__c/Bank_Account__c.object-meta.xml
<CustomObject>
    <label>Bank Account</label>
    <nameField>
        <label>Bank Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bank Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Bank_Account__c/fields/ACH_ID__c.field-meta.xml
<CustomField>
    <fullName>ACH_ID__c</fullName>
    <label>ACH ID</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Bank_Account__c/fields/Bank_ACH_Code__c.field-meta.xml
<CustomField>
    <fullName>Bank_ACH_Code__c</fullName>
    <label>Bank ACH Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Bank_Account__c/fields/Bank_Name__c.field-meta.xml
<CustomField>
    <fullName>Bank_Name__c</fullName>
    <label>Bank Name</label>
    <length>23</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Bank_Account__c/fields/Company_Name__c.field-meta.xml
<CustomField>
    <fullName>Company_Name__c</fullName>
    <label>Company Name</label>
    <length>16</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Bank_Account__c/fields/Fed_Tax_Id__c.field-meta.xml
<CustomField>
    <fullName>Fed_Tax_Id__c</fullName>
    <label>Fed Tax Id</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Bank_Account__c/fields/Folder_Name__c.field-meta.xml
<CustomField>
    <fullName>Folder_Name__c</fullName>
    <label>Folder Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Bank_Account__c/fields/National_Funding_Account__c.field-meta.xml
<CustomField>
    <fullName>National_Funding_Account__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This check box will indicate if this account is a National Funding Account.</description>
    <label>National Funding Account</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Bank_Account__c/fields/Payee_s_Name__c.field-meta.xml
<CustomField>
    <fullName>Payee_s_Name__c</fullName>
    <label>Payee's Name</label>
    <length>22</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Bank_Account__c/fields/Receiving_Company_Name__c.field-meta.xml
<CustomField>
    <fullName>Receiving_Company_Name__c</fullName>
    <label>Receiving Company Name</label>
    <length>22</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Bank_Account__c/fields/Standard_Entry_Class__c.field-meta.xml
<CustomField>
    <fullName>Standard_Entry_Class__c</fullName>
    <label>Standard Entry Class</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Bank_Account__c/recordTypes/Organization.recordType-meta.xml
<RecordType>
    <fullName>Organization</fullName>
    <active>true</active>
    <label>Organization</label>
</RecordType>

unpackaged/main/default/classes/ACHPaymentProcessController.cls
public with sharing class ACHPaymentProcessController {
    
    private ApexPages.StandardSetController standardController;
    public Boolean fileStatus{get;set;}
    List <String> fileNames = new List<String>();
    Date createdDate{get;set;}
    
    public ACHPaymentProcessController(ApexPages.StandardSetController controller) {
        this.standardController = controller;
    }
    
    public PageReference processACHPayments() {
        Set<Id> paymentIds = new Set<Id>();
        for(SObject payment : standardController.getSelected()){
            paymentIds.add(payment.id);
        }
        if (paymentIds.size()>0) {
            List<Ach_payment__c> paymentsWithNoOrgBankAccounts = [select Id,Organization_s_Bank_Account__c from Ach_Payment__c where Organization_s_Bank_Account__c=null and Id in:paymentIds ];
            
            if(paymentsWithNoOrgBankAccounts.size()>0){
                ApexPages.addMessage(new ApexPages.message(ApexPages.Severity.Error,
                                    'Some of the ACH Payment Objects are not having Organization bank account.Please assign them the appropriate organization Bank Account.'));
            }
            AggregateResult[] createdDateCount = [select count(Id),Create_ACH_File_Date__c from ACH_Payment__c 
                                                where Id in:paymentIds 
                                                and Create_ACH_File_Date__c != null 
                                                group by Create_ACH_File_Date__c ];
            if(createdDateCount.size() > 1){
                ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR,
                            'For the selected records, the Create ACH File Date is different. All records must have the same Create ACH File Date.'));  
                return null;
            }else if((Date)createdDateCount[0].get('Create_ACH_File_Date__c') != Date.Today()){
                ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR,'For the selected records to process,the Create ACH File Date should be today\'s Date. '));  
                return null;
            }else if(createdDateCount.size()==1){
                createdDate = (Date)createdDateCount[0].get('Create_ACH_File_Date__c');
            }
            List<Bank_Account__c> orgBanks = [select Id,ACH_ID__c,Bank_ACH_Code__c,Bank_Name__c,National_Funding_Account__c
                                            ,Company_Name__c,Fed_Tax_Id__c,Folder_Name__c,
                                            Routing_Number__c,Standard_Entry_Class__c from Bank_Account__c where RecordType.Name='Organization'];
            for(Bank_Account__c bank:orgBanks){
                AggregateResult[] payOnThisDateCount = [select count(Id),Pay_On_This_Date__c from ACH_Payment__c 
                                                where Id in : paymentIds and Pay_On_This_Date__c != null 
                                                and Create_ACH_File_Date__c != null and Organization_s_Bank_Account__c=:bank.Id
                                                group by Pay_On_This_Date__c ];
                Map<Date,List<ACH_Payment__c>> paymentsMap = new Map<Date,List<ACH_Payment__c>>();
                if(payOnThisDateCount.size() > 0){
                    for(Integer i = 0; i < payOnThisDateCount.size() ; i++){
                        paymentsMap.put((Date)payOnThisDateCount[i].get('Pay_On_This_Date__c'),
                                            [select Id ,Name,
                                            ACH_File_Generated__c,
                                            ACH_File_Generated_Date__c,
                                            Amount__c,
                                            Create_ACH_File_Date__c,
                                            Pay_On_This_Date__c,
                                            NF_Lease_Loan_Number__c,
                                            Opportunity__c,
                                            Payee_s_Account_Type__c,
                                            Payee_s_Bank_Account_Number__c,
                                            Payee_s_Bank_Name__c,
                                            Payee_s_Name__c,
                                            Payee_s_Routing_Number__c,
                                            Receiving_Company_Name__c
                                            from ACH_Payment__c
                                            where Id in : paymentIds 
                                            and Pay_On_This_Date__c =:(Date)payOnThisDateCount[i].get('Pay_On_This_Date__c')   
                                            and ACH_File_Generated__c = false and Organization_s_Bank_Account__c=:bank.Id]);
                    }
                }
                try {
                    for(Date payDate:paymentsMap.keySet()){
                        ACHFileGenerator ach = new ACHFileGenerator(paymentsMap.get(payDate),payDate,createdDate,bank);
                        Document d = [select Id,Name from Document where Id=:ach.generateACH() limit 1];
                        String fileName = '<a href="' + URL.getSalesforceBaseUrl().toExternalForm() + '/'+d.id+'">'+d.Name+'</a>';
                        system.debug(fileName);
                        fileNames.add(fileName);
                    }
                    
                    ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.INFO,'ACH files generated are:'));
                    for(Integer i=0 ; i < fileNames.size() ; i++){
                        ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.INFO,'&nbsp;' + fileNames[i]));
                    }
                }catch(Exception e){
                    system.debug('Message:'+e.getMessage()+'line number:'+e.getLineNumber());
                    ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR,'ACH file could not be generated.'));
                }
            }
            
        }else{
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR,'No ACH payment records were selected.'));
        }
        return null;
    }

}