unpackaged/main/default/objects/Account/fields/Bank_Account_Number__c.field-meta.xml
<CustomField>
    <fullName>Bank_Account_Number__c</fullName>
    <description>The customer's bank account number.</description>
    <inlineHelpText>Enter the customer's bank account number.</inlineHelpText>
    <label>Bank Account Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Bank_Name__c.field-meta.xml
<CustomField>
    <fullName>Bank_Name__c</fullName>
    <description>Bank Name</description>
    <inlineHelpText>Enter Name of Bank</inlineHelpText>
    <label>Bank Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ACH_Payment__c/ACH_Payment__c.object-meta.xml
<CustomObject>
    <description>This object will be a repository for all ACH payments recorded for lease vendors and working capital customers.</description>
    <label>ACH Payment</label>
    <nameField>
        <displayFormat>ACH # {0}</displayFormat>
        <label>ACH Payment #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ACH Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ACH_Payment__c/fields/ACH_Payment__c.field-meta.xml
<CustomField>
    <fullName>ACH_Payment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ACH Payment</label>
    <referenceTo>ACH_Payment__c</referenceTo>
    <relationshipLabel>ACH Payments</relationshipLabel>
    <relationshipName>ACH_Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ACH_Payment__c/fields/ACH_Rejected__c.field-meta.xml
<CustomField>
    <fullName>ACH_Rejected__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field will indicate if an ACH payment is rejected and needs to be re-processed by creating a New ACH Payment.</description>
    <inlineHelpText>This field will indicate if an ACH payment is rejected and needs to be re-processed by creating a New ACH Payment.</inlineHelpText>
    <label>ACH Rejected</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/ACH_Payment__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/ACH_Payment__c/fields/Create_ACH_File_Date__c.field-meta.xml
<CustomField>
    <fullName>Create_ACH_File_Date__c</fullName>
    <label>Create ACH File Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/ACH_Payment__c/fields/Lease_or_Loan__c.field-meta.xml
<CustomField>
    <fullName>Lease_or_Loan__c</fullName>
    <description>This will indicate if the payments are being made for a lease or working capital transaction.</description>
    <inlineHelpText>This will indicate if the payments are being made for a lease or working capital transaction.</inlineHelpText>
    <label>Lease or Working Capital</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Lease</fullName>
            </value>
            <value>
                <fullName>Working Capital</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ACH_Payment__c/fields/NF_Lease_Loan_Number__c.field-meta.xml
<CustomField>
    <fullName>NF_Lease_Loan_Number__c</fullName>
    <description>This field will correspond to CCD Entry Detail Record Field 7 (Company Discretionary Data) in the NACHA File.  It will contain the Lease or Loan Number that the ACH payment is being generated for.</description>
    <inlineHelpText>Please enter the associated customer's Lease or Loan Number.</inlineHelpText>
    <label>NF Lease/Loan Number</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ACH_Payment__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <description>This field will indicate the opportunity that the ACH payments are associated with.</description>
    <inlineHelpText>This field will indicate the opportunity that the ACH payments are associated with.</inlineHelpText>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>ACH Payments</relationshipLabel>
    <relationshipName>ACH_Payments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/ACH_Payment__c/fields/Organization_s_Bank_Account__c.field-meta.xml
<CustomField>
    <fullName>Organization_s_Bank_Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Organization's Bank Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Bank_Account__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Organization</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Bank_Account__c</referenceTo>
    <relationshipLabel>ACH Payments (Organization's Bank Account)</relationshipLabel>
    <relationshipName>ACH_Payments1</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ACH_Payment__c/fields/Pay_On_This_Date__c.field-meta.xml
<CustomField>
    <fullName>Pay_On_This_Date__c</fullName>
    <label>Pay On This Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/ACH_Payment__c/fields/Payee_Bank_Account__c.field-meta.xml
<CustomField>
    <fullName>Payee_Bank_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payee's Bank Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Bank_Account__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Broker, Organization</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Bank_Account__c</referenceTo>
    <relationshipLabel>ACH Payments</relationshipLabel>
    <relationshipName>ACH_Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ACH_Payment__c/fields/Payee_s_Account_Type__c.field-meta.xml
<CustomField>
    <fullName>Payee_s_Account_Type__c</fullName>
    <description>This field will contain the type of account the funds will be deposited into.</description>
    <inlineHelpText>This field will contain the type of account the funds will be deposited into.</inlineHelpText>
    <label>Payee's Account Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Checking</fullName>
                <default>true</default>
                <label>Checking</label>
            </value>
            <value>
                <fullName>Savings</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ACH_Payment__c/fields/Payee_s_Bank_Account_Number__c.field-meta.xml
<CustomField>
    <fullName>Payee_s_Bank_Account_Number__c</fullName>
    <description>This field will contain the Bank Account Number for the payee.</description>
    <inlineHelpText>This field will contain the Bank Account Number for the payee.</inlineHelpText>
    <label>Payee's Bank Account Number</label>
    <length>17</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ACH_Payment__c/fields/Payee_s_Bank_Name__c.field-meta.xml
<CustomField>
    <fullName>Payee_s_Bank_Name__c</fullName>
    <description>This field will contain the name of the Payee's bank.</description>
    <inlineHelpText>This field will contain the name of the Payee's bank.</inlineHelpText>
    <label>Payee's Bank Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ACH_Payment__c/fields/Payee_s_Name__c.field-meta.xml
<CustomField>
    <fullName>Payee_s_Name__c</fullName>
    <description>This field will contain the name of the company/person that will be receiving the funds.</description>
    <inlineHelpText>This field will contain the name of the company/person that will be receiving the funds.</inlineHelpText>
    <label>Payee's Name</label>
    <length>22</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ACH_Payment__c/fields/Payee_s_Routing_Number__c.field-meta.xml
<CustomField>
    <fullName>Payee_s_Routing_Number__c</fullName>
    <description>This field will contain the routing number for the payee.</description>
    <inlineHelpText>This field will contain the routing number for the payee.</inlineHelpText>
    <label>Payee's Routing Number</label>
    <length>9</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ACH_Payment__c/fields/Receiving_Company_Name__c.field-meta.xml
<CustomField>
    <fullName>Receiving_Company_Name__c</fullName>
    <description>This field will correspond to CCD Entry Detail Record field #8.  This will field should contain the name of the recipient of the payment.  (A maximum of 22 characters are allowed)</description>
    <inlineHelpText>This will field should contain the name of the recipient of the payment.  (A maximum of 22 characters are allowed)</inlineHelpText>
    <label>Receiving Company Name</label>
    <length>22</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Bank_Account__c/Bank_Account__c.object-meta.xml
<CustomObject>
    <label>Bank Account</label>
    <nameField>
        <label>Bank Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bank Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Bank_Account__c/fields/Bank_Account_Number__c.field-meta.xml
<CustomField>
    <fullName>Bank_Account_Number__c</fullName>
    <label>Bank Account Number</label>
    <length>17</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Bank_Account__c/fields/Bank_Account_Type__c.field-meta.xml
<CustomField>
    <fullName>Bank_Account_Type__c</fullName>
    <description>This field will contain the type of account the funds will be deposited into.</description>
    <inlineHelpText>This field will contain the type of account the funds will be deposited into.</inlineHelpText>
    <label>Bank Account Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Checking</fullName>
            </value>
            <value>
                <fullName>Savings</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Bank_Account__c/fields/Bank_Name__c.field-meta.xml
<CustomField>
    <fullName>Bank_Name__c</fullName>
    <label>Bank Name</label>
    <length>23</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Bank_Account__c/fields/National_Funding_Account__c.field-meta.xml
<CustomField>
    <fullName>National_Funding_Account__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This check box will indicate if this account is a National Funding Account.</description>
    <label>National Funding Account</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Bank_Account__c/fields/Payee_s_Name__c.field-meta.xml
<CustomField>
    <fullName>Payee_s_Name__c</fullName>
    <label>Payee's Name</label>
    <length>22</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Bank_Account__c/fields/Receiving_Company_Name__c.field-meta.xml
<CustomField>
    <fullName>Receiving_Company_Name__c</fullName>
    <label>Receiving Company Name</label>
    <length>22</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Bank_Account__c/recordTypes/Broker.recordType-meta.xml
<RecordType>
    <fullName>Broker</fullName>
    <active>true</active>
    <label>Broker</label>
</RecordType>

unpackaged/main/default/objects/cmbls__Disbursement__c/cmbls__Disbursement__c.object-meta.xml
<CustomObject>
    <label>Disbursement</label>
    <nameField>
        <displayFormat>D-{0000}</displayFormat>
        <label>Disbursement Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Disbursements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/cmbls__Disbursement__c/fields/Bank_Name__c.field-meta.xml
<CustomField>
    <fullName>Bank_Name__c</fullName>
    <label>Bank Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/cmbls__Disbursement__c/fields/cmbls__Status__c.field-meta.xml
<CustomField>
    <fullName>cmbls__Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>Pre-Pending</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Settled</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Sent Error</fullName>
            </value>
            <value>
                <fullName>Staging</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/cmbls__Disbursement__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Disbursements</relationshipLabel>
    <relationshipName>Disbursements</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Bank_Account_Number__c.field-meta.xml
<CustomField>
    <fullName>Bank_Account_Number__c</fullName>
    <description>Customer's Bank account number.</description>
    <inlineHelpText>Type in the customer's bank account number.</inlineHelpText>
    <label>Bank Account Number</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Bank_Name__c.field-meta.xml
<CustomField>
    <fullName>Bank_Name__c</fullName>
    <description>Bank Name</description>
    <inlineHelpText>Enter name of Bank</inlineHelpText>
    <label>Bank Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/ACHPaymentTriggerHandler.cls
public class ACHPaymentTriggerHandler{
    
    private List<ACH_Payment__c> achPayments;
    private Map<Id,ACH_Payment__c> oldMap;
    Set<Id> bankIds = new Set<Id>();
    Set<Id> orgBankIds  = new Set<Id>();
    
    public ACHPaymentTriggerHandler(List<ACH_Payment__c> achPayments,Map<Id,ACH_Payment__c> oldMap){
        this.achPayments = achPayments;
        this.oldMap = oldMap;
        
        if(achPayments.size()>0){
            for(ACH_Payment__c payment:achPayments){
                if(payment.Payee_Bank_Account__c != null){
                    bankIds.add(payment.Payee_Bank_Account__c);
                }
                if(payment.Organization_s_Bank_Account__c!=null){
                    orgBankIds.add(payment.Organization_s_Bank_Account__c);
                }
            }
        } 
    }
    
    /************************************************************************************************************************************************
    COMMENTED LEGACY CODE DUE TO AN INACTIVE TRIGGER
    CMB IS ACTIVATING THIS TRIGGER AGAIN TO ADD LOGIC ON PAYMENT CREATION AS PART OF FUNDINGO
    !!! THIS CODE IS THROWING ERRORS !!!!
    ************************************************************************************************************************************************
    public void updateACHPaymentFields(){
        Map<Id, Bank_Account__c> bankMap = new Map<Id, Bank_Account__c>([
            select Id, Bank_Account_Number__c, Bank_Account_Type__c
                , Bank_Name__c, Routing_Number__c, Receiving_Company_Name__c
                , Payee_s_Name__c
            from Bank_Account__c
            where Id in :bankIds
        ]);
        List<RecordType> pmtRecordTypes = [select Id, Name, SObjectType from RecordType where SObjectType = 'ACH_Payment__c'];
        Map<String, Id> recordTypeIdMap = new Map<String, Id>();
        for(RecordType rt : pmtrecordTypes){
            recordTypeIdMap.put(rt.Name, rt.Id);
        }


        for(ACH_Payment__c payment : achPayments){
            system.debug(payment.RecordType.Name);
            if(payment.RecordTypeId != null){
                if(String.valueOf(payment.RecordTypeId).equalsIgnoreCase(recordTypeIdMap.get('Broker/Internal'))){
                    if(payment.Payee_Bank_Account__c != null){
                        Bank_Account__c paymentBank = bankMap.get(payment.Payee_Bank_Account__c);
                        payment.Payee_s_Account_Type__c = (paymentBank.Bank_Account_Type__c != null ? paymentBank.Bank_Account_Type__c : '');
                        payment.Payee_s_Bank_Account_Number__c = (paymentBank.Bank_Account_Number__c != null ? paymentBank.Bank_Account_Number__c : '');
                        payment.Payee_s_Bank_Name__c = (paymentBank.Bank_Name__c != null ? paymentBank.Bank_Name__c : '');
                        payment.Payee_s_Routing_Number__c = (paymentBank.Routing_Number__c != null ? paymentBank.Routing_Number__c : '');
                        payment.Payee_s_Name__c = (paymentBank.Payee_s_Name__c != null ? paymentBank.Payee_s_Name__c : '');
                        payment.Receiving_Company_Name__c = (paymentBank.Receiving_Company_Name__c != null ? paymentBank.Receiving_Company_Name__c : '');
                    }
                }
            }
        }
    }
    public void afterInsertHandler(){
        Id brokerRecType = [select Id from RecordType where Name = 'Broker/Internal' and SObjectType = 'ACH_Payment__c' limit 1].Id;
        Map<Id, Bank_Account__c> orgBankMap = new Map<Id, Bank_Account__c>([
            select Id, Bank_Account_Number__c, Bank_Account_Type__c
                , Bank_Name__c, Routing_Number__c, National_Funding_Account__c
            from Bank_Account__c
            where Id in :orgBankIds
        ]);
        List<Bank_Account__c> nfBankAcc = [select Id from Bank_Account__c where National_Funding_Account__c = true limit 1];
        List<ACH_Payment__c> newACHPayments = new List<ACH_Payment__c>();
        if(nfBankAcc.size() == 1){
            for(ACH_Payment__c payment : achPayments){
                if(orgBankMap.get(payment.Organization_s_Bank_Account__c).National_Funding_Account__c == false){
                    ACH_Payment__c newPmt = new ACH_Payment__c();
                    newPmt.Amount__c = payment.Amount__c;
                    newPmt.Opportunity__c = payment.Opportunity__c;
                    newPmt.Organization_s_Bank_Account__c = nfBankAcc[0].Id;
                    newPmt.RecordTypeId = brokerRecType;
                    newPmt.Payee_Bank_Account__c = payment.Organization_s_Bank_Account__c;
                    newPmt.Create_ACH_File_Date__c = payment.Pay_On_This_Date__c;
                    newPmt.Pay_On_This_Date__c = HolidayUtil.INSTANCE.getNextWorkingDate(payment.Pay_On_This_Date__c);
                    newPmt.ACH_Payment__c = payment.Id;
                    newPmt.NF_Lease_Loan_Number__c = payment.NF_Lease_Loan_Number__c;
                    newPmt.Lease_or_Loan__c = payment.Lease_or_Loan__c;
                    newACHPayments.add(newPmt);
                }
            }
        }

        if(newACHPayments.size() > 0){
            insert newACHPayments;
        }
    }
    */
    
    public void autoCreateDisbursements(Map<Id,ACH_Payment__c> newMap){
        List<cmbls__Disbursement__c> disToCreate = new List<cmbls__Disbursement__c>();
        List<ACH_Payment__c> newPayments = getACHPaymentById(newMap.keySet());
        for(ACH_Payment__c pay : newPayments){
            cmbls__Disbursement__c dis = new cmbls__Disbursement__c();
            dis.cmbls__Status__c = DisbursementUtils.DISBURSEMENT_STATUS_STAGING;
            if(pay.ACH_Rejected__c){
                if(pay.ACH_Rejected_Reason__c == DisbursementUtils.DISBURSEMENT_REASON_CANCELED){
                    dis.cmbls__ACH_Processor__c = DisbursementUtils.DISBURSEMENT_PROCESSOR_WIRE;
                }else{
                    dis.cmbls__ACH_Processor__c = null;
                    dis.cmbls__Status__c = DisbursementUtils.DISBURSEMENT_PROCESSOR_REJECTED;
                    dis.ACH_Rejected_Reason__c = pay.ACH_Rejected_Reason__c;
                }
            }else{
                dis.cmbls__ACH_Processor__c = pay.Organization_s_Bank_Account__r.ACH_Processor__c;
            }
            
            dis.RecordTypeId =  DisbursementUtils.PAYMENT_RECORD_TYPE_FUNDING;
            
            if(pay.Payment_Type__c != null){
                if(pay.Payment_Type__c.contains(DisbursementUtils.DISBURSEMENT_PAYMENT_TYPE_FUNDING)){
                    dis.RecordTypeId =  DisbursementUtils.PAYMENT_RECORD_TYPE_FUNDING;
                }else if(pay.Payment_Type__c.contains(DisbursementUtils.DISBURSEMENT_PAYMENT_TYPE_COMMISSION)){
                    dis.RecordTypeId =  DisbursementUtils.PAYMENT_RECORD_TYPE_COMMISSION;
                }else if(pay.Payment_Type__c.contains(DisbursementUtils.DISBURSEMENT_PAYMENT_TYPE_PAYOFF)){
                    dis.RecordTypeId =  DisbursementUtils.PAYMENT_RECORD_TYPE_PAYOFF;
                }
            }
            
            dis.cmbls__Effective_Date__c = pay.Pay_On_This_Date__c;
            dis.cmbls__Addenda__c = pay.Opportunity__r.Account.Company_DBA__c;
            dis.Opportunity__c = pay.Opportunity__c;
            dis.cmbls__Transaction_Amount__c = pay.Amount__c;
            dis.cmbls__Bank_Account_Number__c = pay.Payee_s_Bank_Account_Number__c;
            dis.cmbls__Bank_Routing_Number__c = pay.Payee_s_Routing_Number__c;
            dis.cmbls__Bank_Account_Type__c = pay.Payee_s_Account_Type__c;
            dis.Bank_Name__c = pay.Payee_s_Bank_Name__c;
            dis.cmbls__Payee_Name__c = pay.Receiving_Company_Name__c;
            
            disToCreate.add(dis);
        }
        insert disToCreate;
    }
    
    private static ACH_Payment__c[] getACHPaymentById(Set<Id> recordIds){
        return [
            SELECT
                Id, Receiving_Company_Name__c,ACH_Rejected__c,ACH_Rejected_Reason__c,Organization_s_Bank_Account__r.ACH_Processor__c, Payment_Type__c,
                Pay_On_This_Date__c, Opportunity__r.Account.Company_DBA__c, Amount__c,Payee_s_Bank_Name__c, Payee_s_Bank_Account_Number__c,
                Payee_s_Routing_Number__c,Payee_s_Account_Type__c
            FROM ACH_Payment__c WHERE Id IN :recordIds];
    }
}