unpackaged/main/default/objects/Account/fields/Bank_Account_Number__c.field-meta.xml
<CustomField>
    <fullName>Bank_Account_Number__c</fullName>
    <description>The customer's bank account number.</description>
    <inlineHelpText>Enter the customer's bank account number.</inlineHelpText>
    <label>Bank Account Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Bank_Name__c.field-meta.xml
<CustomField>
    <fullName>Bank_Name__c</fullName>
    <description>Bank Name</description>
    <inlineHelpText>Enter Name of Bank</inlineHelpText>
    <label>Bank Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Fed_Tax_ID__c.field-meta.xml
<CustomField>
    <fullName>Fed_Tax_ID__c</fullName>
    <description>The federal Tax ID of the account</description>
    <externalId>true</externalId>
    <inlineHelpText>The federal Tax ID of the account</inlineHelpText>
    <label>Fed Tax ID</label>
    <length>16</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/recordTypes/Customer.recordType-meta.xml
<RecordType>
    <fullName>Customer</fullName>
    <active>true</active>
    <label>Customer</label>
</RecordType>

unpackaged/main/default/objects/ACH_Payment__c/ACH_Payment__c.object-meta.xml
<CustomObject>
    <description>This object will be a repository for all ACH payments recorded for lease vendors and working capital customers.</description>
    <label>ACH Payment</label>
    <nameField>
        <displayFormat>ACH # {0}</displayFormat>
        <label>ACH Payment #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ACH Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ACH_Payment__c/fields/ACH_Payment__c.field-meta.xml
<CustomField>
    <fullName>ACH_Payment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ACH Payment</label>
    <referenceTo>ACH_Payment__c</referenceTo>
    <relationshipLabel>ACH Payments</relationshipLabel>
    <relationshipName>ACH_Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ACH_Payment__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/ACH_Payment__c/fields/NF_Lease_Loan_Number__c.field-meta.xml
<CustomField>
    <fullName>NF_Lease_Loan_Number__c</fullName>
    <description>This field will correspond to CCD Entry Detail Record Field 7 (Company Discretionary Data) in the NACHA File.  It will contain the Lease or Loan Number that the ACH payment is being generated for.</description>
    <inlineHelpText>Please enter the associated customer's Lease or Loan Number.</inlineHelpText>
    <label>NF Lease/Loan Number</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ACH_Payment__c/fields/Organization_s_Bank_Account__c.field-meta.xml
<CustomField>
    <fullName>Organization_s_Bank_Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Organization's Bank Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Bank_Account__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Organization</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Bank_Account__c</referenceTo>
    <relationshipLabel>ACH Payments (Organization's Bank Account)</relationshipLabel>
    <relationshipName>ACH_Payments1</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ACH_Payment__c/fields/Payee_s_Account_Type__c.field-meta.xml
<CustomField>
    <fullName>Payee_s_Account_Type__c</fullName>
    <description>This field will contain the type of account the funds will be deposited into.</description>
    <inlineHelpText>This field will contain the type of account the funds will be deposited into.</inlineHelpText>
    <label>Payee's Account Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Checking</fullName>
                <default>true</default>
                <label>Checking</label>
            </value>
            <value>
                <fullName>Savings</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ACH_Payment__c/fields/Payee_s_Bank_Account_Number__c.field-meta.xml
<CustomField>
    <fullName>Payee_s_Bank_Account_Number__c</fullName>
    <description>This field will contain the Bank Account Number for the payee.</description>
    <inlineHelpText>This field will contain the Bank Account Number for the payee.</inlineHelpText>
    <label>Payee's Bank Account Number</label>
    <length>17</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ACH_Payment__c/fields/Payee_s_Bank_Name__c.field-meta.xml
<CustomField>
    <fullName>Payee_s_Bank_Name__c</fullName>
    <description>This field will contain the name of the Payee's bank.</description>
    <inlineHelpText>This field will contain the name of the Payee's bank.</inlineHelpText>
    <label>Payee's Bank Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ACH_Payment__c/fields/Payee_s_Name__c.field-meta.xml
<CustomField>
    <fullName>Payee_s_Name__c</fullName>
    <description>This field will contain the name of the company/person that will be receiving the funds.</description>
    <inlineHelpText>This field will contain the name of the company/person that will be receiving the funds.</inlineHelpText>
    <label>Payee's Name</label>
    <length>22</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ACH_Payment__c/fields/Payee_s_Routing_Number__c.field-meta.xml
<CustomField>
    <fullName>Payee_s_Routing_Number__c</fullName>
    <description>This field will contain the routing number for the payee.</description>
    <inlineHelpText>This field will contain the routing number for the payee.</inlineHelpText>
    <label>Payee's Routing Number</label>
    <length>9</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ACH_Payment__c/fields/Receiving_Company_Name__c.field-meta.xml
<CustomField>
    <fullName>Receiving_Company_Name__c</fullName>
    <description>This field will correspond to CCD Entry Detail Record field #8.  This will field should contain the name of the recipient of the payment.  (A maximum of 22 characters are allowed)</description>
    <inlineHelpText>This will field should contain the name of the recipient of the payment.  (A maximum of 22 characters are allowed)</inlineHelpText>
    <label>Receiving Company Name</label>
    <length>22</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ACH_Payment__c/recordTypes/Default.recordType-meta.xml
<RecordType>
    <fullName>Default</fullName>
    <active>true</active>
    <label>Default</label>
</RecordType>

unpackaged/main/default/objects/Bank_Account__c/Bank_Account__c.object-meta.xml
<CustomObject>
    <label>Bank Account</label>
    <nameField>
        <label>Bank Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bank Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Bank_Account__c/fields/ACH_ID__c.field-meta.xml
<CustomField>
    <fullName>ACH_ID__c</fullName>
    <label>ACH ID</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Bank_Account__c/fields/Bank_Account_Number__c.field-meta.xml
<CustomField>
    <fullName>Bank_Account_Number__c</fullName>
    <label>Bank Account Number</label>
    <length>17</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Bank_Account__c/fields/Bank_Account_Type__c.field-meta.xml
<CustomField>
    <fullName>Bank_Account_Type__c</fullName>
    <description>This field will contain the type of account the funds will be deposited into.</description>
    <inlineHelpText>This field will contain the type of account the funds will be deposited into.</inlineHelpText>
    <label>Bank Account Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Checking</fullName>
            </value>
            <value>
                <fullName>Savings</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Bank_Account__c/fields/Bank_ACH_Code__c.field-meta.xml
<CustomField>
    <fullName>Bank_ACH_Code__c</fullName>
    <label>Bank ACH Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Bank_Account__c/fields/Bank_Name__c.field-meta.xml
<CustomField>
    <fullName>Bank_Name__c</fullName>
    <label>Bank Name</label>
    <length>23</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Bank_Account__c/fields/Company_Entry_Description__c.field-meta.xml
<CustomField>
    <fullName>Company_Entry_Description__c</fullName>
    <label>Company Entry Description</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Bank_Account__c/fields/Company_Name__c.field-meta.xml
<CustomField>
    <fullName>Company_Name__c</fullName>
    <label>Company Name</label>
    <length>16</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Bank_Account__c/fields/Fed_Tax_Id__c.field-meta.xml
<CustomField>
    <fullName>Fed_Tax_Id__c</fullName>
    <label>Fed Tax Id</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Bank_Account__c/fields/Folder_Name__c.field-meta.xml
<CustomField>
    <fullName>Folder_Name__c</fullName>
    <label>Folder Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Bank_Account__c/fields/National_Funding_Account__c.field-meta.xml
<CustomField>
    <fullName>National_Funding_Account__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This check box will indicate if this account is a National Funding Account.</description>
    <label>National Funding Account</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Bank_Account__c/fields/Payee_s_Name__c.field-meta.xml
<CustomField>
    <fullName>Payee_s_Name__c</fullName>
    <label>Payee's Name</label>
    <length>22</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Bank_Account__c/fields/Receiving_Company_Name__c.field-meta.xml
<CustomField>
    <fullName>Receiving_Company_Name__c</fullName>
    <label>Receiving Company Name</label>
    <length>22</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Bank_Account__c/fields/Standard_Entry_Class__c.field-meta.xml
<CustomField>
    <fullName>Standard_Entry_Class__c</fullName>
    <label>Standard Entry Class</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Bank_Account__c/recordTypes/Broker.recordType-meta.xml
<RecordType>
    <fullName>Broker</fullName>
    <active>true</active>
    <label>Broker</label>
</RecordType>

unpackaged/main/default/objects/Bank_Account__c/recordTypes/Organization.recordType-meta.xml
<RecordType>
    <fullName>Organization</fullName>
    <active>true</active>
    <label>Organization</label>
</RecordType>

unpackaged/main/default/objects/NF_ACH_Info__c/NF_ACH_Info__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>NF ACH Info</label>
</CustomObject>

unpackaged/main/default/objects/NF_ACH_Info__c/fields/ACH_ID__c.field-meta.xml
<CustomField>
    <fullName>ACH_ID__c</fullName>
    <description>Field 7(Company Identification) in the Batch Control Record.</description>
    <inlineHelpText>Field 7(Company Identification) in the Batch Control Record.</inlineHelpText>
    <label>ACH ID</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/NF_ACH_Info__c/fields/Bank_Account_Number__c.field-meta.xml
<CustomField>
    <fullName>Bank_Account_Number__c</fullName>
    <label>Bank Account Number</label>
    <length>17</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/NF_ACH_Info__c/fields/Bank_ACH_Code__c.field-meta.xml
<CustomField>
    <fullName>Bank_ACH_Code__c</fullName>
    <description>This field corresponds to the Field 5(Company Identification) in the Batch Header Record.</description>
    <label>Bank ACH Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/NF_ACH_Info__c/fields/Bank_Name__c.field-meta.xml
<CustomField>
    <fullName>Bank_Name__c</fullName>
    <label>Bank Name</label>
    <length>23</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/NF_ACH_Info__c/fields/Company_Entry_Description__c.field-meta.xml
<CustomField>
    <fullName>Company_Entry_Description__c</fullName>
    <description>This field will contain a description of the ACH transaction.</description>
    <inlineHelpText>This field will contain a description of the ACH transaction.</inlineHelpText>
    <label>Company Entry Description</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/NF_ACH_Info__c/fields/Company_Name__c.field-meta.xml
<CustomField>
    <fullName>Company_Name__c</fullName>
    <label>Company Name</label>
    <length>16</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/NF_ACH_Info__c/fields/Fed_Tax_Id__c.field-meta.xml
<CustomField>
    <fullName>Fed_Tax_Id__c</fullName>
    <description>This field corresponds to the Field 4(Immediate Origin) in the File Header Record</description>
    <label>Fed Tax Id</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/NF_ACH_Info__c/fields/Folder_Name__c.field-meta.xml
<CustomField>
    <fullName>Folder_Name__c</fullName>
    <label>Folder Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/NF_ACH_Info__c/fields/Routing_Number__c.field-meta.xml
<CustomField>
    <fullName>Routing_Number__c</fullName>
    <label>Routing_Number</label>
    <length>9</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/NF_ACH_Info__c/fields/Standard_Entry_Class__c.field-meta.xml
<CustomField>
    <fullName>Standard_Entry_Class__c</fullName>
    <label>Standard Entry Class</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Bank_Account_Number__c.field-meta.xml
<CustomField>
    <fullName>Bank_Account_Number__c</fullName>
    <description>Customer's Bank account number.</description>
    <inlineHelpText>Type in the customer's bank account number.</inlineHelpText>
    <label>Bank Account Number</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Bank_Name__c.field-meta.xml
<CustomField>
    <fullName>Bank_Name__c</fullName>
    <description>Bank Name</description>
    <inlineHelpText>Enter name of Bank</inlineHelpText>
    <label>Bank Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Fed_Tax_Id__c.field-meta.xml
<CustomField>
    <fullName>Fed_Tax_Id__c</fullName>
    <description>This is a formula field for Federal Tax Id number for an Account.  This field will carry it through to the Opportunity to verify that the field is populated.  It mirrors the Doc Formula field for Fed Tax Id.  This will be in the documentation section for each product.</description>
    <formula>Account.Fed_Tax_ID__c</formula>
    <inlineHelpText>This is a read only field.  If this field is blank please check the Fed Tax Id field on the Account record.</inlineHelpText>
    <label>Fed Tax Id</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/TestHelper.cls
public class TestHelper{

    public static void createCustomSettings(){
        List<filegen__Metadata_Segments__c> segments = filegen__Metadata_Segments__c.getAll().values();
        segments.add(new filegen__Metadata_Segments__c(Name='Addenda',filegen__Segment__c='filegen__Addenda_Record__c'));
        segments.add(new filegen__Metadata_Segments__c(Name='Batch Control Record',filegen__Segment__c='filegen__Batch_Control_Record__c'));
        segments.add(new filegen__Metadata_Segments__c(Name='Batch Header Record',filegen__Segment__c='filegen__Batch_Header_Record__c'));
        segments.add(new filegen__Metadata_Segments__c(Name='Entry Detail Record',filegen__Segment__c='filegen__Entry_Detail_Record__c'));
        segments.add(new filegen__Metadata_Segments__c(Name='File Control Record',filegen__Segment__c='filegen__File_Control_Record__c'));
        segments.add(new filegen__Metadata_Segments__c(Name='File Header Record',filegen__Segment__c='filegen__File_Header_Record__c'));
        
        insert segments;
        /*
        NF_ACH_Info__c param = NF_ACH_Info__c.getInstance();
        param.ACH_ID__c = '4TGD2211';
        param.Bank_Account_Number__c = '33333';
        param.Bank_ACH_Code__c = 'BOFACHCD';
        param.Bank_Name__c = 'Bank of America';
        param.Company_Entry_Description__c = 'PAYMENT';
        param.Company_Name__c = 'National Funding';
        param.Fed_Tax_Id__c = '4TGD2211';
        param.Folder_Name__c='Shared Folder for ACH';
        param.Routing_Number__c='823291211';
        param.Standard_Entry_Class__c='PPD';
        
        insert param;*/
    }
    public static Bank_Account__c createBankAccount(){
        RecordType rt = [select id ,Name from RecordType where SObjectType = 'Bank_Account__c' and Name = 'Organization'];
        Bank_Account__c bank = new Bank_Account__c();
        bank.ACH_ID__c = '4TGD2211';
        bank.Bank_Account_Number__c = '33333';
        bank.Bank_ACH_Code__c = 'BOFACHCD';
        bank.Bank_Name__c = 'Bank of America';
        bank.Company_Entry_Description__c = 'PAYMENT';
        bank.Company_Name__c = 'National Funding';
        bank.Fed_Tax_Id__c = '4TGD2211';
        bank.Folder_Name__c='Shared Folder for ACH';
        bank.Routing_Number__c='823291211';
        bank.Standard_Entry_Class__c='PPD';
        bank.recordTypeId = rt.Id;
		bank.Payee_s_Name__c = 'test';
        bank.Receiving_Company_Name__c = 'test';
        bank.Bank_Account_Type__c = 'Checking';
        insert bank;
        return bank;
    }
    
    public static Bank_Account__c createPayeeBankAccount(){
        RecordType rt = [select id ,Name from RecordType where SObjectType = 'Bank_Account__c' and Name = 'Broker'];
        Bank_Account__c bank = new Bank_Account__c();
        bank.ACH_ID__c = '4TGD2211';
        bank.Bank_Account_Number__c = '33333';
        bank.Bank_ACH_Code__c = 'BOFACHCD';
        bank.Bank_Name__c = 'Bank of America';
        bank.Company_Entry_Description__c = 'PAYMENT';
        bank.Company_Name__c = 'National Funding';
        bank.Fed_Tax_Id__c = '4TGD2211';
        bank.Folder_Name__c='Shared Folder for ACH';
        bank.Routing_Number__c='823291211';
        bank.Standard_Entry_Class__c='PPD';
        bank.recordTypeId = rt.Id;
        bank.Payee_s_Name__c = 'test';
        bank.Receiving_Company_Name__c = 'test';
        bank.Bank_Account_Type__c = 'Checking';
        insert bank;
        return bank;
    }
    
    public static Bank_Account__c createNFBankAccount(){
        RecordType rt = [select id ,Name from RecordType where SObjectType = 'Bank_Account__c' and Name = 'Organization'];
        Bank_Account__c bank = new Bank_Account__c();
        bank.ACH_ID__c = '4TGD2211';
        bank.Bank_Account_Number__c = '33333';
        bank.Bank_ACH_Code__c = 'BOFACHCD';
        bank.Bank_Name__c = 'Bank of America';
        bank.Company_Entry_Description__c = 'PAYMENT';
        bank.Company_Name__c = 'National Funding';
        bank.Fed_Tax_Id__c = '4TGD2211';
        bank.Folder_Name__c='Shared Folder for ACH';
        bank.Routing_Number__c='823291211';
        bank.Standard_Entry_Class__c='PPD';
        bank.recordTypeId = rt.Id;
        bank.National_Funding_Account__c = true;
        bank.Payee_s_Name__c = 'test';
        bank.Receiving_Company_Name__c = 'test';
        bank.Bank_Account_Type__c = 'Checking';
        insert bank;
        return bank;
    }
    
    public static ACH_Payment__c createDefaultACHPaymentRecord(){
        RecordType rt = [select id ,Name from RecordType where SObjectType = 'ACH_Payment__c' and Name = 'Default'];
        ACH_Payment__c payment = new ACH_Payment__c();
        payment.Organization_s_Bank_Account__c =  createBankAccount().id;
        payment.NF_Lease_Loan_Number__c = 'Test #1';
        payment.Receiving_Company_Name__c = 'Bill\'s Bobcats';
        payment.Payee_s_Routing_Number__c = '515151155';
        payment.Payee_s_Bank_Account_Number__c = '65465465464654654';
        payment.Payee_s_Bank_Name__c = 'Wells Fargo';
        payment.Payee_s_Account_Type__c = 'Checking';
        payment.Payee_s_Name__c = 'Bill Brasky';
        payment.Amount__c = 1000;
        payment.Pay_On_This_Date__c = Date.Today();
        payment.Create_ACH_File_Date__c = Date.today();
        payment.Payee_Bank_Account__c = createPayeeBankAccount().id;
        payment.Opportunity__c = createOpportunity().Id;
        payment.recordTypeId = rt.Id;
        
        insert payment;
        return payment;
    }
    
    
    public static ACH_Payment__c createBrokerACHPaymentRecord(){
        RecordType rt = [select id ,Name from RecordType where SObjectType = 'ACH_Payment__c' and Name = 'Broker/Internal'];
        ACH_Payment__c payment = new ACH_Payment__c();
        payment.Organization_s_Bank_Account__c =  createNFBankAccount().id;
        payment.NF_Lease_Loan_Number__c = 'Test #1';
        payment.Receiving_Company_Name__c = 'Bill\'s Bobcats';
        payment.Payee_s_Routing_Number__c = '515151155';
        payment.Payee_s_Bank_Account_Number__c = '65465465464654654';
        payment.Payee_s_Bank_Name__c = 'Wells Fargo';
        payment.Payee_s_Account_Type__c = 'Checking';
        payment.Payee_s_Name__c = 'Bill Brasky';
        payment.Amount__c = 1000;
        payment.Pay_On_This_Date__c = Date.Today();
        payment.Create_ACH_File_Date__c = Date.today();
        payment.Payee_Bank_Account__c = createBankAccount().id;
        payment.Opportunity__c = createOpportunity().Id;
        payment.recordTypeId = rt.Id;
        
        insert payment;
        return payment;
    }
    public static Opportunity createOpportunity(){
        Opportunity oppt = new Opportunity();
        oppt.Account = createAccount();
        oppt.Name = 'Ach Testing Account 2 Lease Oppty Deal #4';
        oppt.Type = 'NEW';
        oppt.Amount = 10000;
        oppt.StageName = 'Funded';
        oppt.Probability = 100;
        oppt.CloseDate = Date.Today();
        oppt.Use_of_Funds__c = 'Equipment Purchase';
        oppt.Lender_Doc_Fee_For_Actual__c = 0;
        oppt.Residual_Assigned_To__c = 'No Residual';
        
        insert oppt;
        return oppt;
    }
    
    public static Account createAccount(){
        Account acct = new Account();
        acct.Name='Ach Testing Account 3';
        acct.Type='Customer';
        insert acct;
        return acct;    
    }
    
}