unpackaged/main/default/objects/Account/fields/Company_DBA__c.field-meta.xml
<CustomField>
    <fullName>Company_DBA__c</fullName>
    <description>The company's "Doing Business As" Name</description>
    <inlineHelpText>The company's "Doing Business As" Name</inlineHelpText>
    <label>Company DBA</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ACH_Payment__c/ACH_Payment__c.object-meta.xml
<CustomObject>
    <description>This object will be a repository for all ACH payments recorded for lease vendors and working capital customers.</description>
    <label>ACH Payment</label>
    <nameField>
        <displayFormat>ACH # {0}</displayFormat>
        <label>ACH Payment #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ACH Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ACH_Payment__c/fields/ACH_Payment__c.field-meta.xml
<CustomField>
    <fullName>ACH_Payment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ACH Payment</label>
    <referenceTo>ACH_Payment__c</referenceTo>
    <relationshipLabel>ACH Payments</relationshipLabel>
    <relationshipName>ACH_Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ACH_Payment__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/ACH_Payment__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <description>This field will indicate the opportunity that the ACH payments are associated with.</description>
    <inlineHelpText>This field will indicate the opportunity that the ACH payments are associated with.</inlineHelpText>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>ACH Payments</relationshipLabel>
    <relationshipName>ACH_Payments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/ACH_Payment__c/fields/Pay_On_This_Date__c.field-meta.xml
<CustomField>
    <fullName>Pay_On_This_Date__c</fullName>
    <label>Pay On This Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/ACH_Payment__c/fields/Payee_s_Account_Type__c.field-meta.xml
<CustomField>
    <fullName>Payee_s_Account_Type__c</fullName>
    <description>This field will contain the type of account the funds will be deposited into.</description>
    <inlineHelpText>This field will contain the type of account the funds will be deposited into.</inlineHelpText>
    <label>Payee's Account Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Checking</fullName>
                <default>true</default>
                <label>Checking</label>
            </value>
            <value>
                <fullName>Savings</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ACH_Payment__c/fields/Payee_s_Bank_Account_Number__c.field-meta.xml
<CustomField>
    <fullName>Payee_s_Bank_Account_Number__c</fullName>
    <description>This field will contain the Bank Account Number for the payee.</description>
    <inlineHelpText>This field will contain the Bank Account Number for the payee.</inlineHelpText>
    <label>Payee's Bank Account Number</label>
    <length>17</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ACH_Payment__c/fields/Payee_s_Routing_Number__c.field-meta.xml
<CustomField>
    <fullName>Payee_s_Routing_Number__c</fullName>
    <description>This field will contain the routing number for the payee.</description>
    <inlineHelpText>This field will contain the routing number for the payee.</inlineHelpText>
    <label>Payee's Routing Number</label>
    <length>9</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Bank_Account__c/Bank_Account__c.object-meta.xml
<CustomObject>
    <label>Bank Account</label>
    <nameField>
        <label>Bank Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bank Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/cmbls__Disbursement__c/cmbls__Disbursement__c.object-meta.xml
<CustomObject>
    <label>Disbursement</label>
    <nameField>
        <displayFormat>D-{0000}</displayFormat>
        <label>Disbursement Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Disbursements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/cmbls__Disbursement__c/fields/cmbls__Bank_Routing_Number__c.field-meta.xml
<CustomField>
    <fullName>cmbls__Bank_Routing_Number__c</fullName>
    <label>Bank Routing Number</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/cmbls__Disbursement__c/fields/cmbls__Effective_Date__c.field-meta.xml
<CustomField>
    <fullName>cmbls__Effective_Date__c</fullName>
    <label>Effective Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/cmbls__Disbursement__c/fields/cmbls__Repayment__c.field-meta.xml
<CustomField>
    <fullName>cmbls__Repayment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Repayment</label>
    <referenceTo>cmbls__Repayment__c</referenceTo>
    <relationshipLabel>Disbursements</relationshipLabel>
    <relationshipName>Disbursements</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/cmbls__Disbursement__c/fields/cmbls__Status__c.field-meta.xml
<CustomField>
    <fullName>cmbls__Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>Pre-Pending</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Settled</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Sent Error</fullName>
            </value>
            <value>
                <fullName>Staging</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/cmbls__Disbursement__c/fields/cmbls__Transaction_Amount__c.field-meta.xml
<CustomField>
    <fullName>cmbls__Transaction_Amount__c</fullName>
    <label>Transaction Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/cmbls__Disbursement__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Disbursements</relationshipLabel>
    <relationshipName>Disbursements</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/cmbls__Expense__c/cmbls__Expense__c.object-meta.xml
<CustomObject>
    <label>Expense</label>
    <nameField>
        <displayFormat>E-{0000}</displayFormat>
        <label>Expense Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Expenses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/cmbls__Expense__c/fields/cmbls__Repayment__c.field-meta.xml
<CustomField>
    <fullName>cmbls__Repayment__c</fullName>
    <label>Repayment</label>
    <referenceTo>cmbls__Repayment__c</referenceTo>
    <relationshipLabel>Expenses</relationshipLabel>
    <relationshipName>Expenses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/cmbls__Repayment__c/cmbls__Repayment__c.object-meta.xml
<CustomObject>
    <label>Repayment</label>
    <nameField>
        <displayFormat>RPMT-{0000000}</displayFormat>
        <label>Repayment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Repayments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/cmbls__Repayment__c/fields/cmbls__Bank_Account_Number__c.field-meta.xml
<CustomField>
    <fullName>cmbls__Bank_Account_Number__c</fullName>
    <label>Bank Account Number</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/cmbls__Repayment__c/fields/cmbls__Bank_Routing_Number__c.field-meta.xml
<CustomField>
    <fullName>cmbls__Bank_Routing_Number__c</fullName>
    <label>Bank Routing Number</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/cmbls__Repayment__c/fields/cmbls__Origination_Fee__c.field-meta.xml
<CustomField>
    <fullName>cmbls__Origination_Fee__c</fullName>
    <description>Amount that is being withheld for upfront fees</description>
    <inlineHelpText>Amount that is being withheld for upfront fees</inlineHelpText>
    <label>Origination Fee</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/cmbls__Repayment__c/fields/cmbls__Status__c.field-meta.xml
<CustomField>
    <fullName>cmbls__Status__c</fullName>
    <description>Active, pause, complete, and new</description>
    <inlineHelpText>Active, pause, complete, and new</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Temporary Pause</fullName>
            </value>
            <value>
                <fullName>Pause</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Write Off</fullName>
            </value>
            <value>
                <fullName>Recovery</fullName>
            </value>
            <value>
                <fullName>Unwind</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/cmbls__Repayment__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Repayments (Opportunity)</relationshipLabel>
    <relationshipName>Repayments</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Company_DBA__c.field-meta.xml
<CustomField>
    <fullName>Company_DBA__c</fullName>
    <description>This field is the location specific DBA for the opportunity. The logic behind the field is as follows- If the DBA (Multiple Locations) is populated, then populate the field with that DBA, if it isn't populate with the Account DBA.</description>
    <formula>IF(DBA_Multiple_Locations__c = "", Account.Company_DBA__c,  DBA_Multiple_Locations__c )</formula>
    <inlineHelpText>This field displays the DBA to the physical location associated with this opportunity.</inlineHelpText>
    <label>Company DBA</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Loan_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Loan_Start_Date__c</fullName>
    <label>Loan Start Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/classes/ACHPaymentTriggerHandlerTest.cls
@IsTest
public with sharing class ACHPaymentTriggerHandlerTest {
    
    @TestSetup static void setupMethod(){
        Account acc = TestDataFactory.createAccount();
        insert acc;
        
        Bank_Account__c bankAccount = TestDataFactory.createBankAccount();
        insert bankAccount;
    
        Opportunity opp = TestDataFactory.createOpportunity(acc.Id);
        opp.Loan_Start_Date__c = System.today();
        insert opp;
    }
    
    @IsTest
    static void testCreateDisbursements(){
        Account acc = [SELECT Id FROM Account];
        Opportunity opp = [SELECT Id FROM Opportunity];
        Bank_Account__c bankAccount = [SELECT Id FROM Bank_Account__c];
        
        Test.startTest();
        ACH_Payment__c pay = TestDataFactory.createDefaultACHPaymentRecord(acc.Id, opp.Id, bankAccount.Id);
        insert pay;
        Test.stopTest();

        cmbls__Disbursement__c dis = [
            SELECT  Id, cmbls__Effective_Date__c, cmbls__Addenda__c, Opportunity__c,cmbls__Transaction_Amount__c,
                    cmbls__Bank_Account_Number__c,cmbls__Bank_Routing_Number__c,cmbls__Bank_Account_Type__c
            FROM cmbls__Disbursement__c ORDER BY CreatedDate DESC LIMIT 1];
       
        System.assertEquals(dis.cmbls__Effective_Date__c , pay.Pay_On_This_Date__c);
        System.assertEquals(dis.cmbls__Effective_Date__c,pay.Pay_On_This_Date__c);
        System.assertEquals(dis.cmbls__Addenda__c,pay.Opportunity__r.Account.Company_DBA__c);
        System.assertEquals( dis.Opportunity__c,pay.Opportunity__c);
        System.assertEquals(dis.cmbls__Transaction_Amount__c,pay.Amount__c);
        System.assertEquals(dis.cmbls__Bank_Account_Number__c,pay.Payee_s_Bank_Account_Number__c);
        System.assertEquals(dis.cmbls__Bank_Routing_Number__c,pay.Payee_s_Routing_Number__c);
        System.assertEquals( dis.cmbls__Bank_Account_Type__c,pay.Payee_s_Account_Type__c);
    }

    @IsTest
    static void testRelateDisbursements(){
        Account acc = [SELECT Id FROM Account];
        Opportunity opp = [SELECT Id FROM Opportunity];
        Bank_Account__c bankAccount = [SELECT Id FROM Bank_Account__c];
    
        ACH_Payment__c pay = TestDataFactory.createDefaultACHPaymentRecord(acc.Id, opp.Id, bankAccount.Id);
        insert pay;

        Test.startTest();
        cmbls__Repayment__c repayment = TestDataFactory.createRepayment(acc.Id);
        repayment.Opportunity__c = opp.Id;
        insert repayment;
        Test.stopTest();

        cmbls__Disbursement__c dis = [SELECT Id,cmbls__Status__c,cmbls__Repayment__c FROM cmbls__Disbursement__c ORDER BY CreatedDate DESC LIMIT 1];
        System.assertEquals(dis.cmbls__Repayment__c , repayment.Id);
        System.assertEquals(dis.cmbls__Status__c , DisbursementUtils.DISBURSEMENT_STATUS_SCHEDULED);
    }

    @IsTest
    static void testNotCreateExpenses(){
        Account acc = [SELECT Id FROM Account];

        cmbls__Repayment__c repayment = TestDataFactory.createRepayment(acc.Id);
        insert repayment;

        List<cmbls__Expense__c> exps = [SELECT Id FROM cmbls__Expense__c WHERE cmbls__Repayment__c =: repayment.Id];
        System.assertEquals(exps.size() , 0);
        
    }

    @IsTest
    static void testCreateExpenses(){
        Account acc = [SELECT Id FROM Account];
        
        cmbls__Repayment__c repayment = TestDataFactory.createRepayment(acc.Id);
        repayment.cmbls__Origination_Fee__c = 100;
        insert repayment;
        
        List<cmbls__Expense__c> exps = [SELECT Id FROM cmbls__Expense__c WHERE cmbls__Repayment__c =: repayment.Id];
        System.assertEquals(exps.size() , 1);
    }
}