unpackaged/main/default/objects/Account/fields/Date_Established__c.field-meta.xml
<CustomField>
    <fullName>Date_Established__c</fullName>
    <description>Date Business Established</description>
    <inlineHelpText>Enter Date business was established</inlineHelpText>
    <label>Date Established</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Account/recordTypes/Lender.recordType-meta.xml
<RecordType>
    <fullName>Lender</fullName>
    <active>true</active>
    <label>Lender</label>
</RecordType>

unpackaged/main/default/objects/Contact/fields/Isprimary__c.field-meta.xml
<CustomField>
    <fullName>Isprimary__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Primary Contact</description>
    <inlineHelpText>Check box if contact is designated as primary .</inlineHelpText>
    <label>Isprimary</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/LinkShorteningAPI__c/LinkShorteningAPI__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>LSA is responsible for setting endpoint values for WS to shorten application links or other links.</description>
    <label>LinkShorteningAPI</label>
</CustomObject>

unpackaged/main/default/objects/LinkShorteningAPI__c/fields/Authorization__c.field-meta.xml
<CustomField>
    <fullName>Authorization__c</fullName>
    <label>Authorization</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/LinkShorteningAPI__c/fields/Service_Endpoint__c.field-meta.xml
<CustomField>
    <fullName>Service_Endpoint__c</fullName>
    <label>Service Endpoint</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Date_Established__c.field-meta.xml
<CustomField>
    <fullName>Date_Established__c</fullName>
    <description>This field captures the Date Established Associated with the Opportunity.  It is a formula field.</description>
    <formula>BLANKVALUE( Date_Established_Multiple_Locations__c , Account.Date_Established__c )</formula>
    <inlineHelpText>This field captures the Date Established Associated with the Opportunity.  It is a formula field.</inlineHelpText>
    <label>Date Established</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/FACILITY_OWNED_LEASED__c.field-meta.xml
<CustomField>
    <fullName>FACILITY_OWNED_LEASED__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Facility Rent/Own Status.</description>
    <inlineHelpText>Check box if merchant owns facility business is located in.</inlineHelpText>
    <label>Facility Owned or Leased</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/classes/AutomatedCreditStartTest.cls
/**
 * Created by oporter on 3/19/2018.
 */
@IsTest
public with sharing class AutomatedCreditStartTest {

    @isTest
    public static void testAutomatedCreditStart(){
        Id lenderRecordType = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Lender Acct').getRecordTypeId();
        LinkShorteningAPI__c mcs = new LinkShorteningAPI__c(Name = 'V2', Endpoint__c = 'test', Service_Endpoint__c = 'test', Authorization__c = 'test');
        insert mcs;
        
        Account lenderAccountPlatinum = new Account(name = 'National Funding - Platinum WC Funding' , RecordTypeId = lenderRecordType);
        insert lenderAccountPlatinum;
        Account a = new Account(Name = 'Acct Name', Date_Established__c = Date.today());
        insert a;
        Contact c = new Contact(LastName = 'Test', Account = a, Isprimary__c = true);
        insert c;
        Contact c2 = new Contact(LastName = 'Test', Account = a, Isprimary__c = true);
        insert c2;
        Contact c3 = new Contact(LastName = 'Test', Account = a, Isprimary__c = true);
        insert c3;
        
        Opportunity o = new Opportunity(StageName = 'Identified', Account = a, FACILITY_OWNED_LEASED__c = TRUE, Name = 'Test Opp 2', CloseDate = Date.today());
        insert o;
        OpportunityContactRole ocr1 = new OpportunityContactRole();
        ocr1.OpportunityId = o.Id;
        ocr1.Role = 'Signor';
        ocr1.IsPrimary = TRUE;
        ocr1.ContactId = c.Id;
        insert ocr1;
        
        OpportunityContactRole ocr2 = new OpportunityContactRole();
        ocr2.OpportunityId = o.Id;
        ocr2.Role = 'Guarantor 2';
        ocr2.IsPrimary = FALSE;
        ocr2.ContactId = c2.Id;
        insert ocr2;
        
        OpportunityContactRole ocr3 = new OpportunityContactRole();
        ocr3.OpportunityId = o.Id;
        ocr3.Role = 'Guarantor 3';
        ocr3.IsPrimary = FALSE;
        ocr3.ContactId = c3.Id;
        insert ocr3;
        
        List<Id> listOppty = new List<Id>();
        listOppty.add(o.Id);
        Test.startTest();
        HttpMockGenerator mock = new HttpMockGenerator('true', 200);
        Test.setMock(HttpCalloutMock.class, mock);
        AutomatedCreditStart acs = new AutomatedCreditStart();
        AutomatedCreditStart.automatedClass(listOppty);
        Test.stopTest();
    }
}