unpackaged/main/default/objects/Account/fields/Date_Established__c.field-meta.xml
<CustomField>
    <fullName>Date_Established__c</fullName>
    <description>Date Business Established</description>
    <inlineHelpText>Enter Date business was established</inlineHelpText>
    <label>Date Established</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Fed_Tax_ID__c.field-meta.xml
<CustomField>
    <fullName>Fed_Tax_ID__c</fullName>
    <description>The federal Tax ID of the account</description>
    <externalId>true</externalId>
    <inlineHelpText>The federal Tax ID of the account</inlineHelpText>
    <label>Fed Tax ID</label>
    <length>16</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Legal_Name__c.field-meta.xml
<CustomField>
    <fullName>Legal_Name__c</fullName>
    <description>the account's legal name as filed with the Secretary of State.</description>
    <externalId>true</externalId>
    <inlineHelpText>the account's legal name as filed with the Secretary of State.</inlineHelpText>
    <label>Legal Name</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Legal_Status__c.field-meta.xml
<CustomField>
    <fullName>Legal_Status__c</fullName>
    <description>Legal Status / Structure of the Customers Business.</description>
    <inlineHelpText>Legal Status / Structure of the Customers Business.</inlineHelpText>
    <label>Legal Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Corporation</fullName>
            </value>
            <value>
                <fullName>LLC</fullName>
            </value>
            <value>
                <fullName>Partnership</fullName>
            </value>
            <value>
                <fullName>Limited Partnership</fullName>
            </value>
            <value>
                <fullName>LLP</fullName>
            </value>
            <value>
                <fullName>Sole Proprietor</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/State_of_Incorporation__c.field-meta.xml
<CustomField>
    <fullName>State_of_Incorporation__c</fullName>
    <description>State that the business is incorporated in.</description>
    <inlineHelpText>Pick the state that the lessee is incorporated in.</inlineHelpText>
    <label>State of Incorporation</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AK</fullName>
            </value>
            <value>
                <fullName>AL</fullName>
            </value>
            <value>
                <fullName>AR</fullName>
            </value>
            <value>
                <fullName>AZ</fullName>
            </value>
            <value>
                <fullName>CA</fullName>
            </value>
            <value>
                <fullName>CO</fullName>
            </value>
            <value>
                <fullName>CT</fullName>
            </value>
            <value>
                <fullName>DC</fullName>
            </value>
            <value>
                <fullName>DE</fullName>
            </value>
            <value>
                <fullName>FL</fullName>
            </value>
            <value>
                <fullName>GA</fullName>
            </value>
            <value>
                <fullName>HI</fullName>
            </value>
            <value>
                <fullName>IA</fullName>
            </value>
            <value>
                <fullName>ID</fullName>
            </value>
            <value>
                <fullName>IL</fullName>
            </value>
            <value>
                <fullName>IN</fullName>
            </value>
            <value>
                <fullName>KS</fullName>
            </value>
            <value>
                <fullName>KY</fullName>
            </value>
            <value>
                <fullName>LA</fullName>
            </value>
            <value>
                <fullName>MA</fullName>
            </value>
            <value>
                <fullName>MD</fullName>
            </value>
            <value>
                <fullName>ME</fullName>
            </value>
            <value>
                <fullName>MI</fullName>
            </value>
            <value>
                <fullName>MN</fullName>
            </value>
            <value>
                <fullName>MO</fullName>
            </value>
            <value>
                <fullName>MS</fullName>
            </value>
            <value>
                <fullName>MT</fullName>
            </value>
            <value>
                <fullName>NC</fullName>
            </value>
            <value>
                <fullName>ND</fullName>
            </value>
            <value>
                <fullName>NE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Bank_Data__c/Bank_Data__c.object-meta.xml
<CustomObject>
    <label>Bank Data</label>
    <nameField>
        <displayFormat>BD-{0}</displayFormat>
        <label>Bank_Data</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bank Data</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Bank_Data__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Bank Data</relationshipLabel>
    <relationshipName>Bank_Data</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/FCRA_Accepted_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>FCRA_Accepted_Date_Time__c</fullName>
    <description>Timestamp of when the contact has agreed to the FCRA consent.</description>
    <label>FCRA Accepted Date/Time</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Ownership_Percentage__c.field-meta.xml
<CustomField>
    <fullName>Ownership_Percentage__c</fullName>
    <description>Percentage of Ownership that FPC_Contact has.</description>
    <inlineHelpText>Type in the percentage of ownership that contact has in company.</inlineHelpText>
    <label>Ownership %</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/SSN_Encrypted__c.field-meta.xml
<CustomField>
    <fullName>SSN_Encrypted__c</fullName>
    <description>This field will contain a customer's Social Security number in an encrypted format. Accessing the full visibility of this field will be determined by job role and permission set.</description>
    <inlineHelpText>Encrypted Social Security Number - See your administrator if you have questions.</inlineHelpText>
    <label>SSN Encrypted</label>
    <length>11</length>
    <maskChar>asterisk</maskChar>
    <maskType>ssn</maskType>
    <type>EncryptedText</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Date_Established__c.field-meta.xml
<CustomField>
    <fullName>Date_Established__c</fullName>
    <description>This field captures the Date Established Associated with the Opportunity.  It is a formula field.</description>
    <formula>BLANKVALUE( Date_Established_Multiple_Locations__c , Account.Date_Established__c )</formula>
    <inlineHelpText>This field captures the Date Established Associated with the Opportunity.  It is a formula field.</inlineHelpText>
    <label>Date Established</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Fed_Tax_Id__c.field-meta.xml
<CustomField>
    <fullName>Fed_Tax_Id__c</fullName>
    <description>This is a formula field for Federal Tax Id number for an Account.  This field will carry it through to the Opportunity to verify that the field is populated.  It mirrors the Doc Formula field for Fed Tax Id.  This will be in the documentation section for each product.</description>
    <formula>Account.Fed_Tax_ID__c</formula>
    <inlineHelpText>This is a read only field.  If this field is blank please check the Fed Tax Id field on the Account record.</inlineHelpText>
    <label>Fed Tax Id</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Legal_Name__c.field-meta.xml
<CustomField>
    <fullName>Legal_Name__c</fullName>
    <description>This is a formula field that displays the Legal Name of an account on the Opportunity Record.</description>
    <formula>Account.Legal_Name__c</formula>
    <inlineHelpText>This is a read only field that displays the Legal Name of an account on the Opportunity Record.</inlineHelpText>
    <label>Legal Name</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Legal_Status__c.field-meta.xml
<CustomField>
    <fullName>Legal_Status__c</fullName>
    <description>This field is a formula field that carries over into the opportunity.  It mirrors the doc formulas fields that indicate Legal Status of the business.  (Corp, LLC, Partnership, Sole)  This will be a reference for the ops team to use when creating legal docs.</description>
    <formula>TEXT(Account.Legal_Status__c)</formula>
    <inlineHelpText>This is a read only field.  If this field is blank, please populate the Legal Status field on the Account record.</inlineHelpText>
    <label>Legal Status</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/ApplicationCheck.cls
public class ApplicationCheck {

    @AuraEnabled
    public static list<OpportunityContactRole> getOCR(string opportunityId) {
        return [
            SELECT Id, Role
            FROM OpportunityContactRole
            Where OpportunityId =: opportunityId
        ];
    }
    
    @AuraEnabled
    public static list<Account> getAccountFields(string AccountId){
        return [
            SELECT Id,Fed_Tax_ID__c,Legal_Status__c, Date_Established__c, State_of_Incorporation__c, AnnualRevenue, ShippingAddress, BillingAddress, Legal_Name__c, Phone, BillingPostalCode, BillingState, BillingCity, BillingStreet
            FROM Account
            WHERE Id=:AccountId
        ];
    }

    @AuraEnabled
    public static Application_Setting__mdt getApplicationSettingsCMDT(){
        try {
            Application_Setting__mdt settings = [
                SELECT Id, DeveloperName, Label, MasterLabel, FCRA_Date_Limit__c
                FROM Application_Setting__mdt 
                WHERE DeveloperName = 'settings'
                LIMIT 1
            ];
            System.debug('settings - ' + settings);
            return settings;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    @AuraEnabled
    public static List<String> getFileAndAttachmentNames(string OpportunityId){

        List<string> fileNames = new List<string>();

        List<Attachment> attachments = [SELECT Id, Name FROM Attachment WHERE ParentId =:OpportunityId];
        List<ContentDocumentLink> files = [SELECT ContentDocumentId, ContentDocument.Title FROM ContentDocumentLink WHERE LinkedEntityId =:OpportunityId];

        for(Integer i=0; i<attachments.size(); i++){
            filenames.add(attachments[i].Name);
        }

        for(Integer i=0; i<files.size(); i++){
            filenames.add(files[i].ContentDocument.Title);
        }

        Boolean isPlaidPresent = hasPlaid(OpportunityId);
        if (isPlaidPresent) {
            filenames.add('Plaid_Bank_Data_Present');
        }

        return fileNames;
    }

    public static Boolean hasPlaid (string recordId) {
        try {
            // ensure pdf files relating to bank statements and plaid json files on related opportunity
            Opportunity opp = [SELECT Id, AccountId FROM Opportunity WHERE Id = :recordId ORDER BY CreatedDate DESC LIMIT 1];
            List<Bank_Data__c> bankData = [SELECT Id FROM Bank_Data__c WHERE Account__c = :opp.AccountId];
            boolean plaidPresent = bankData.size() > 0;
            return plaidPresent;
        } catch (Exception e) {
            return false;
        }
    }
    
    @AuraEnabled
    public static List<object> getContactInformation(string OpportunityId){
        return [
            SELECT Id,  Contact.Name, Contact.FCRA_Accepted_Date_Time__c, Contact.FirstName, Contact.LastName, Contact.Title, Contact.Email, Contact.MobilePhone, Contact.Birthdate, Contact.SSN_Encrypted__c, Contact.Ownership_Percentage__c, Contact.HomePhone, Contact.MailingState, Contact.OtherAddress, Contact.OtherStreet, Contact.OtherState, Contact.OtherPostalCode, Contact.OtherCity, Contact.OtherCountry, Role
            FROM OpportunityContactRole
            WHERE (OpportunityId =:OpportunityId) AND (Role = 'Signor' OR Role = 'Guarantor 2' OR Role = 'Guarantor 3')
            WITH USER_MODE
        ];
    }
}

// Enforce User Mode for Database Operations
// Added WITH USER_MODE to end of contact query to limit scope to user access
// https://developer.salesforce.com/docs/atlas.en-us.apexcode.meta/apexcode/apex_classes_enforce_usermode.htm