unpackaged/main/default/objects/Account/fields/Date_Established__c.field-meta.xml
<CustomField>
    <fullName>Date_Established__c</fullName>
    <description>Date Business Established</description>
    <inlineHelpText>Enter Date business was established</inlineHelpText>
    <label>Date Established</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Fed_Tax_ID__c.field-meta.xml
<CustomField>
    <fullName>Fed_Tax_ID__c</fullName>
    <description>The federal Tax ID of the account</description>
    <externalId>true</externalId>
    <inlineHelpText>The federal Tax ID of the account</inlineHelpText>
    <label>Fed Tax ID</label>
    <length>16</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Legal_Status__c.field-meta.xml
<CustomField>
    <fullName>Legal_Status__c</fullName>
    <description>Legal Status / Structure of the Customers Business.</description>
    <inlineHelpText>Legal Status / Structure of the Customers Business.</inlineHelpText>
    <label>Legal Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Corporation</fullName>
            </value>
            <value>
                <fullName>LLC</fullName>
            </value>
            <value>
                <fullName>Partnership</fullName>
            </value>
            <value>
                <fullName>Limited Partnership</fullName>
            </value>
            <value>
                <fullName>LLP</fullName>
            </value>
            <value>
                <fullName>Sole Proprietor</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/fields/State_of_Incorporation__c.field-meta.xml
<CustomField>
    <fullName>State_of_Incorporation__c</fullName>
    <description>State that the business is incorporated in.</description>
    <inlineHelpText>Pick the state that the lessee is incorporated in.</inlineHelpText>
    <label>State of Incorporation</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AK</fullName>
            </value>
            <value>
                <fullName>AL</fullName>
            </value>
            <value>
                <fullName>AR</fullName>
            </value>
            <value>
                <fullName>AZ</fullName>
            </value>
            <value>
                <fullName>CA</fullName>
            </value>
            <value>
                <fullName>CO</fullName>
            </value>
            <value>
                <fullName>CT</fullName>
            </value>
            <value>
                <fullName>DC</fullName>
            </value>
            <value>
                <fullName>DE</fullName>
            </value>
            <value>
                <fullName>FL</fullName>
            </value>
            <value>
                <fullName>GA</fullName>
            </value>
            <value>
                <fullName>HI</fullName>
            </value>
            <value>
                <fullName>IA</fullName>
            </value>
            <value>
                <fullName>ID</fullName>
            </value>
            <value>
                <fullName>IL</fullName>
            </value>
            <value>
                <fullName>IN</fullName>
            </value>
            <value>
                <fullName>KS</fullName>
            </value>
            <value>
                <fullName>KY</fullName>
            </value>
            <value>
                <fullName>LA</fullName>
            </value>
            <value>
                <fullName>MA</fullName>
            </value>
            <value>
                <fullName>MD</fullName>
            </value>
            <value>
                <fullName>ME</fullName>
            </value>
            <value>
                <fullName>MI</fullName>
            </value>
            <value>
                <fullName>MN</fullName>
            </value>
            <value>
                <fullName>MO</fullName>
            </value>
            <value>
                <fullName>MS</fullName>
            </value>
            <value>
                <fullName>MT</fullName>
            </value>
            <value>
                <fullName>NC</fullName>
            </value>
            <value>
                <fullName>ND</fullName>
            </value>
            <value>
                <fullName>NE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Bank_Data__c/Bank_Data__c.object-meta.xml
<CustomObject>
    <label>Bank Data</label>
    <nameField>
        <displayFormat>BD-{0}</displayFormat>
        <label>Bank_Data</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bank Data</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Bank_Data__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Bank Data</relationshipLabel>
    <relationshipName>Bank_Data</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Ownership_Percentage__c.field-meta.xml
<CustomField>
    <fullName>Ownership_Percentage__c</fullName>
    <description>Percentage of Ownership that FPC_Contact has.</description>
    <inlineHelpText>Type in the percentage of ownership that contact has in company.</inlineHelpText>
    <label>Ownership %</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/SSN_Encrypted__c.field-meta.xml
<CustomField>
    <fullName>SSN_Encrypted__c</fullName>
    <description>This field will contain a customer's Social Security number in an encrypted format. Accessing the full visibility of this field will be determined by job role and permission set.</description>
    <inlineHelpText>Encrypted Social Security Number - See your administrator if you have questions.</inlineHelpText>
    <label>SSN Encrypted</label>
    <length>11</length>
    <maskChar>asterisk</maskChar>
    <maskType>ssn</maskType>
    <type>EncryptedText</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Date_Established__c.field-meta.xml
<CustomField>
    <fullName>Date_Established__c</fullName>
    <description>This field captures the Date Established Associated with the Opportunity.  It is a formula field.</description>
    <formula>BLANKVALUE( Date_Established_Multiple_Locations__c , Account.Date_Established__c )</formula>
    <inlineHelpText>This field captures the Date Established Associated with the Opportunity.  It is a formula field.</inlineHelpText>
    <label>Date Established</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Fed_Tax_Id__c.field-meta.xml
<CustomField>
    <fullName>Fed_Tax_Id__c</fullName>
    <description>This is a formula field for Federal Tax Id number for an Account.  This field will carry it through to the Opportunity to verify that the field is populated.  It mirrors the Doc Formula field for Fed Tax Id.  This will be in the documentation section for each product.</description>
    <formula>Account.Fed_Tax_ID__c</formula>
    <inlineHelpText>This is a read only field.  If this field is blank please check the Fed Tax Id field on the Account record.</inlineHelpText>
    <label>Fed Tax Id</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Legal_Status__c.field-meta.xml
<CustomField>
    <fullName>Legal_Status__c</fullName>
    <description>This field is a formula field that carries over into the opportunity.  It mirrors the doc formulas fields that indicate Legal Status of the business.  (Corp, LLC, Partnership, Sole)  This will be a reference for the ops team to use when creating legal docs.</description>
    <formula>TEXT(Account.Legal_Status__c)</formula>
    <inlineHelpText>This is a read only field.  If this field is blank, please populate the Legal Status field on the Account record.</inlineHelpText>
    <label>Legal Status</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/ApplicationCheckTest.cls
@isTest
public class ApplicationCheckTest {

    @isTest
    static void getOCRTest(){
        
        // Create c1
        Contact c1 = new Contact(LastName = 'LN1');
        insert c1;
        // Create c2
        Contact c2 = new Contact(LastName = 'LN2');
        insert c2;
        // Create Opp
        Opportunity o = new Opportunity(Name = 'OppName', StageName = 'Identified', closeDate = date.today() );
        insert o;
        // create opp contact role for c1 & opp
        OpportunityContactRole ocr = new OpportunityContactRole(OpportunityId = o.id, ContactId =c1.id, Role = 'role');
        insert ocr;
        
        //Test
        list <object> opportunityContactRoles = ApplicationCheck.getOCR(o.id);
        
        system.assertNotEquals(null, opportunityContactRoles, 'OCR Validation for ApplicationCheck Failed');
    }

    @isTest
    static void getAccountFieldsTest(){
        
        // Create Acc
        Account a = new Account(Name = 'Account Name', Fed_Tax_ID__c = '123456789', Legal_Status__c = 'LLC', Date_Established__c = date.today(), State_of_Incorporation__c = 'CA', AnnualRevenue = 1234);
        insert a;
        
        //Test
        list <object> Account = ApplicationCheck.getAccountFields(a.Id);
        
        System.assertNotEquals(null, Account, 'AccountFieldsTest Validation Failed');
        
    }

    @isTest
    static void getFilesTest(){
        
        //Create Opportunity
        Opportunity o = new Opportunity(Name = 'OppName', StageName = 'Identified', closeDate = date.today() );
        insert o;
        
        //Create File 
        ContentVersion cv = new ContentVersion(Title = 'Test Document', PathOnClient = 'TestDocument.pdf', VersionData = Blob.valueOf('Test Content'), IsMajorVersion = true);
    	Insert cv;
        
        ContentVersion testContent = [Select id, contentDocumentId FROM ContentVersion where Id = :cv.Id];
        
        //Link File to Opp
        ContentDocumentLink cdl = new ContentDocumentLink(LinkedEntityId = o.id, ContentDocumentId = testcontent.ContentDocumentId);
        insert cdl;
        
        //Test
        list <object> ContentDocumentLink = ApplicationCheck.getFileAndAttachmentNames(o.Id);
        
        System.assertNotEquals(null, ContentDocumentLink, 'getFilesTest Validation Failed');
    }

    @isTest
    public static void testHasPlaid() {
        Account acc = new Account(Name = 'Test');
        insert acc;
        Bank_Data__c bd = new Bank_Data__c(Account__c = acc.Id);
        insert bd;
        Opportunity opp = new Opportunity(Name = 'Test Name', StageName = 'Qualification', CloseDate = Date.today(), AccountId = acc.Id);
        insert opp;
        boolean result = ApplicationCheck.hasPlaid(opp.Id);
        System.AssertEquals(true, result);
    }

    @isTest
    static void getContactInformationTest(){
        
        // Create Contact
        Contact c = new Contact(FirstName = 'fn', LastName = 'Ln', Title = 'Title', Email = 'mhandler@nationalfunding.com', MobilePhone = '1234567890', BirthDate = date.today(), SSN_Encrypted__c = '123456789', Ownership_Percentage__c = 100, HomePhone = '1234567890');
        insert c;
        
        // Create Opportunity
        Opportunity o = new Opportunity(Name = 'OppName', StageName = 'Identified', closeDate = date.today() );
        insert o;
        
        // Create Opp Contact Role
        OpportunityContactRole ocr = new OpportunityContactRole(OpportunityId = o.Id, ContactId = c.Id, Role = 'Signor');
        insert ocr;
        
        // Test
        list <object> Contact = ApplicationCheck.getContactInformation(o.Id);
        
        System.assertNotEquals(null, Contact, 'GetContactInformation Validation Failed');
            
    }

    @isTest
    static void getApplicationSettingsCMDT() {
        ApplicationCheck.getApplicationSettingsCMDT();
    }
}