unpackaged/main/default/objects/Account/fields/National_Funding_WebId__c.field-meta.xml
<CustomField>
    <fullName>National_Funding_WebId__c</fullName>
    <displayFormat>NFSA-{000000}</displayFormat>
    <label>National Funding WebId</label>
    <type>AutoNumber</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/NF_Renewal_Rep__c.field-meta.xml
<CustomField>
    <fullName>NF_Renewal_Rep__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Previously was “NF Renewal Rep” but the “NF” was removed to make this field generic enough to support Quick Bridge renewals with working out of National Funding Salesforce.</description>
    <inlineHelpText>The renewal rep's name is entered in this field.</inlineHelpText>
    <label>Renewal Rep</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Accounts4</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Web_Id_NatFund__c.field-meta.xml
<CustomField>
    <fullName>Web_Id_NatFund__c</fullName>
    <description>This field will be the unique record identifier for leads that are created from nationalfunding.com. This field will be populated on create and subsequently when the customer completes steps of the application. For de-duping, the field in the new lead should overwrite the existing value.</description>
    <externalId>true</externalId>
    <inlineHelpText>This field should not be edited</inlineHelpText>
    <label>Web Id NatFund</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/DLP_Email_Status__c.field-meta.xml
<CustomField>
    <fullName>DLP_Email_Status__c</fullName>
    <description>Status of DLP Emails - can be automatic or single end.</description>
    <label>DLP Email Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Prequal DocuSign Complete</fullName>
            </value>
            <value>
                <fullName>Prequal Bank Statements Uploaded</fullName>
            </value>
            <value>
                <fullName>Driver's License Uploaded</fullName>
            </value>
            <value>
                <fullName>Voided Check Uploaded</fullName>
            </value>
            <value>
                <fullName>Drip Campaign Started</fullName>
            </value>
            <value>
                <fullName>DLP Drip Activated</fullName>
            </value>
            <value>
                <fullName>DLP Email Sent</fullName>
            </value>
            <value>
                <fullName>DLP Drip Deactivated</fullName>
            </value>
            <value>
                <fullName>DLP Drip Campaign Ended</fullName>
            </value>
            <value>
                <fullName>Prequal Application Signing Complete</fullName>
            </value>
            <value>
                <fullName>DLP Page 1 Complete</fullName>
            </value>
            <value>
                <fullName>DLP Page 2 Complete</fullName>
            </value>
            <value>
                <fullName>Email Link Clicked</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Encrypted_Email_String_Refresh_Date__c.field-meta.xml
<CustomField>
    <fullName>Encrypted_Email_String_Refresh_Date__c</fullName>
    <label>Encrypted Email String Refresh Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/NF_Renewal_Rep__c.field-meta.xml
<CustomField>
    <fullName>NF_Renewal_Rep__c</fullName>
    <formula>Account.NF_Renewal_Rep__r.Full_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>NF Renewal Rep</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/User/fields/Available_Brands__c.field-meta.xml
<CustomField>
    <fullName>Available_Brands__c</fullName>
    <description>Introduced as part of the Quick Bridge to National Funding migration project to capture which brands this user works for. Originally all users will have one available brand but this is being created as a multi select picklist with the possibility that reps can work under multiple brands in the future.</description>
    <inlineHelpText>Which brand does this user work under?</inlineHelpText>
    <label>Available Brands</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>National Funding</fullName>
                <default>true</default>
                <label>National Funding</label>
            </value>
            <value>
                <fullName>Quick Bridge</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/SendFundingOptionsController.cls
/**
 * Created by oporter on 8/17/2018.
 */

public with sharing class SendFundingOptionsController {

    private Apexpages.StandardController con;
    public List<ContactWrapper> contactList { get; set; }
    public Id opportunityID;
    private Id contactID;
    private String nfID;

    public SendFundingOptionsController(Apexpages.StandardController con){
        this.con = con; //con is the Opportunity ID
        opportunityID = this.con.getId();

        Init();
    }

    private void Init(){
        String contactName;
        Boolean flag;
        contactList = new List<ContactWrapper>(); //contact wrapper is the contact and a boolean if they have an email or not
        List<Opportunity> associatedAccountId = [SELECT AccountId FROM Opportunity WHERE Id = :opportunityID LIMIT 1];

        for(Contact c : [Select Id, Name, Email, DLP_Email_Status__c, AccountId, Account.Web_Id_NatFund__c, Account.National_Funding_WebId__c, HasOptedOutOfEmail From Contact Where AccountId = :associatedAccountId[0].AccountId]){
            contactID = c.Id;
            contactName = c.Name;
            if(c.Account.Web_Id_NatFund__c != NULL && c.Account.Web_Id_NatFund__c != '' ){
                nfId = c.Account.Web_Id_NatFund__c;
            }
            else{
                System.debug('Account Web Id::::::::> ' + c.Account.National_Funding_WebId__c);
                nfId = c.Account.National_Funding_WebId__c;
            }
            contactList.Add(new ContactWrapper(c, (c.Email != null)));
            system.debug('contactList:: ' + contactList);
        }
    }

    public pageReference SendEmail(){
        String emailValue;
        Opportunity oppty = [SELECT StageName FROM Opportunity WHERE Id = :opportunityID];
        if(oppty.StageName == 'Approved - MCA' || oppty.StageName == 'Offer Out - MCA') {
            try {
                Integer selectedcontactList = 0;
                for (ContactWrapper c : contactList) {
                    if (c.IsSelected == true) {
                        if (c.theContact.HasOptedOutOfEmail) {
                            throw new GenericException(c.theContact.Name + ' has opted out of email at this time');
                        }
                        contactID = c.theContact.Id;
                        emailValue = c.theContact.Email;
                        if (c.theContact.Email == null) {
                            throw new GenericException('Please provide email address for: ' + c.theContact.Name);
                        }

                        if (nfId == null) {
                            throw new GenericException('Missing NF Web ID Please Update for: ' + c.theContact.Name);
                        } 
                        selectedcontactList++;
                    }
                }

                if (selectedcontactList == 0) {
                    throw new GenericException('Please select at least 1 contact');
                }

                String tokenCred;
                String qbTokenCred;
                String nfTokenCred;
                String brand;
                String sourceOrg = 'National Funding';
                Boolean userHasBothBrands = false;
                User userInfo = new User();
    
                Contact contactRec = [SELECT Id, Account.NF_Renewal_Rep__c, Account.OwnerId, Account.Web_Id_NatFund__c, Encrypted_Email_String_Refresh_Date__c 
                                    FROM CONTACT WHERE Id =: contactID];

                if(contactRec == null) {
                    throw new GenericException('Contact record cannot be found.');
                }
    
                if(contactRec.Account?.NF_Renewal_Rep__c != null) {
                    userInfo = [Select Id, Available_Brands__c From User Where Id =:contactRec.Account.NF_Renewal_Rep__c];
                } else if(contactRec.Account?.OwnerId != null) {
                    //owned by a user
                    if(contactRec.Account?.OwnerId.getsobjecttype() == User.sobjecttype){
                        userInfo = [Select Id, Available_Brands__c From User Where Id =:contactRec.Account.OwnerId];
                    } else {
                        //if not owned by a user, we are defaulting to generating both tokens
                        userHasBothBrands = true;
                    }
                }
            
                if(userInfo?.Available_Brands__c != null) {
                    if(userInfo?.Available_Brands__c.contains('Quick Bridge') && userInfo?.Available_Brands__c.contains('National Funding')) {
                        userHasBothBrands = true;
                    }
                    else if(userInfo.Available_Brands__c.contains('Quick Bridge')) {
                        brand = 'Quick Bridge';
                    }
                    else if(userInfo.Available_Brands__c.contains('National Funding')) {
                        brand = 'National Funding';
                    }
                } else {
                    brand = 'National Funding';
                }
        
                if(userHasBothBrands) {
                    qbTokenCred = ConsoleApplicationLinkController.getShortenedLink(contactRec.Id, nfID, sourceOrg, 'Quick Bridge');
                    nfTokenCred = ConsoleApplicationLinkController.getShortenedLink(contactRec.Id, nfId, sourceOrg, 'National Funding');
                    if(qbTokenCred.startsWith('This service is temporarily unavailable.') || nfTokenCred.startsWith('This service is temporarily unavailable.')){
                        throw new GenericException('This service is temporarily unavailable.');
                    }
                    HelperClass.upsertDFPToken(contactRec.Id, 'Quick Bridge', qbTokenCred);
                    HelperClass.upsertDFPToken(contactRec.Id, 'National Funding', nfTokenCred);
                    return new pageReference('/apex/DLPEmailLinkUpdateSvc?id=' + contactID + '&opportunityID=' + opportunityID + '&tokencred=' + nfTokenCred + '&data=Funding Email Sent&ptype=contact' + '&email=' + emailValue);
                }
                else {
                    tokencred = ConsoleApplicationLinkController.getShortenedLink(contactRec.Id, nfID, sourceOrg, brand); 
                    if(tokencred.startsWith('This service is temporarily unavailable.')){
                        throw new GenericException('This service is temporarily unavailable.');
                    }
                    HelperClass.upsertDFPToken(contactRec.Id, brand, tokencred);
                    return new pageReference('/apex/DLPEmailLinkUpdateSvc?id=' + contactID + '&opportunityID=' + opportunityID + '&tokencred=' + tokencred + '&data=Funding Email Sent&ptype=contact' + '&email=' + emailValue);
                }
            } catch (Exception ex) {
                Apexpages.addMessages(ex);
                return null;
            }
        }
        else {
            ApexPages.Message newMsg = new ApexPages.Message(ApexPages.Severity.ERROR, 'Opportunity Stage is not Approved - MCA or Offer Out - MCA. Please go back and update before proceeding.');
            ApexPages.addMessage(newMsg);
            return null;
        }
    }

    public class ContactWrapper {
        public boolean isSelected { get; set; }
        public Contact theContact { get; set; }
        public boolean hasEmail { get; set; }

        public ContactWrapper(Contact c, boolean hasEmail){
            theContact = c;
            isSelected = false ;
            this.hasEmail = hasEmail;
        }
    }
}