unpackaged/main/default/objects/Account/fields/NF_Renewal_Rep__c.field-meta.xml
<CustomField>
    <fullName>NF_Renewal_Rep__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Previously was “NF Renewal Rep” but the “NF” was removed to make this field generic enough to support Quick Bridge renewals with working out of National Funding Salesforce.</description>
    <inlineHelpText>The renewal rep's name is entered in this field.</inlineHelpText>
    <label>Renewal Rep</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Accounts4</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Web_Id_NatFund__c.field-meta.xml
<CustomField>
    <fullName>Web_Id_NatFund__c</fullName>
    <description>This field will be the unique record identifier for leads that are created from nationalfunding.com. This field will be populated on create and subsequently when the customer completes steps of the application. For de-duping, the field in the new lead should overwrite the existing value.</description>
    <externalId>true</externalId>
    <inlineHelpText>This field should not be edited</inlineHelpText>
    <label>Web Id NatFund</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Lead/fields/Web_Id_NatFund__c.field-meta.xml
<CustomField>
    <fullName>Web_Id_NatFund__c</fullName>
    <description>This field will be the unique record identifier for leads that are created from nationalfunding.com.  This field will be populated on create and subsequently when the customer completes steps of the application. For de-duping, the field in the new lead should overwrite the existing value.</description>
    <externalId>true</externalId>
    <inlineHelpText>This field should not be edited.</inlineHelpText>
    <label>Web Id NatFund</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/User/fields/Available_Brands__c.field-meta.xml
<CustomField>
    <fullName>Available_Brands__c</fullName>
    <description>Introduced as part of the Quick Bridge to National Funding migration project to capture which brands this user works for. Originally all users will have one available brand but this is being created as a multi select picklist with the possibility that reps can work under multiple brands in the future.</description>
    <inlineHelpText>Which brand does this user work under?</inlineHelpText>
    <label>Available Brands</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>National Funding</fullName>
                <default>true</default>
                <label>National Funding</label>
            </value>
            <value>
                <fullName>Quick Bridge</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/RefreshEncryptedEmailStringTest.cls
@isTest
public class RefreshEncryptedEmailStringTest {

    @isTest
    static void refreshContactTest(){

      
        Profile p = [SELECT Id FROM Profile WHERE Name='Standard User']; 
        User u = new User(Alias = 'standt', Email='standarduser@testorg.com.nf',EmailEncodingKey='UTF-8', 
                          LastName='Testing', LanguageLocaleKey='en_US',LocaleSidKey='en_US', ProfileId = p.Id, 
                          TimeZoneSidKey='America/Los_Angeles', UserName='standardus@testorg.com.nf', Available_Brands__c = 'Quick Bridge');
        insert u;

        Account a = new Account(Name = 'Name', Web_Id_NatFund__c = '1', NF_Renewal_Rep__c = u.Id);
        insert a;
        
        Contact c = new Contact(LastName = 'LastName', email = 'mhandler@nationalfunding.com', LeadSource = 'Email', AccountId = a.id);
        insert c;
        
        test.startTest();
          HttpMockGenerator mock = new HttpMockGenerator('[{"Id":"' + c.Id+ '","Token":"bxofefoHG9wLuWDiynV4"}]', 200);
          Test.setMock(HttpCalloutMock.class, mock);
          String sId = c.Id;
          
          RefreshEncryptedEmailString test1 = new RefreshEncryptedEmailString();
          
          try{
            test1.refresh(sId, 'National Funding', 'Quick Bridge');
          } catch(Exception e) {
            System.assertNotEquals('expectedTypeName', e.getTypeName());
          }
          
        test.stopTest();
    }
    
    @isTest
    static void refreshLeadTest(){
            
        Profile p = [SELECT Id FROM Profile WHERE Name='Standard User']; 
        User u = new User(Alias = 'standt', Email='standarduser@testorg.com.nf',EmailEncodingKey='UTF-8', 
                          LastName='Testing', LanguageLocaleKey='en_US',LocaleSidKey='en_US', ProfileId = p.Id, 
                          TimeZoneSidKey='America/Los_Angeles', UserName='standardus@testorg.com.nf', Available_Brands__c = 'Quick Bridge');
        insert u;

        Lead l = new Lead(LastName = 'LastName', email = 'mhandler@nationalfunding.com', LeadSource = 'Email', Company='1', OwnerId = u.Id);
        insert l;
        
        test.startTest();

          HttpMockGenerator mock = new HttpMockGenerator('[{"Id":"' + l.Id+ '","Token":"bxofefoHG9wLuWDiynV4"}]', 200);
          Test.setMock(HttpCalloutMock.class, mock);
          
          String sId = l.Id;
          
          RefreshEncryptedEmailString test1 = new RefreshEncryptedEmailString();
          
          try{
            test1.refresh(sId, 'National Funding', 'Quick Bridge');
          } catch(Exception e) {
            System.assertNotEquals('expectedTypeName', e.getTypeName());
          }

        test.stopTest();
    }
    
}