unpackaged/main/default/objects/Account/fields/Response__c.field-meta.xml
<CustomField>
    <fullName>Response__c</fullName>
    <description>Internal Marketing Field</description>
    <inlineHelpText>Internal Marketing Field</inlineHelpText>
    <label>Response</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>The status of this account.</description>
    <inlineHelpText>The status of this account.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Active - Renewals</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Fraud</fullName>
            </value>
            <value>
                <fullName>Duplicate</fullName>
            </value>
            <value>
                <fullName>Activator</fullName>
            </value>
            <value>
                <fullName>Prospect</fullName>
            </value>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
            <value>
                <fullName>Under Review</fullName>
            </value>
            <value>
                <fullName>Broker Declined</fullName>
            </value>
            <value>
                <fullName>Agreement Out</fullName>
            </value>
            <value>
                <fullName>Agreement In</fullName>
            </value>
            <value>
                <fullName>Additional Information Needed</fullName>
            </value>
            <value>
                <fullName>Remove From List</fullName>
            </value>
            <value>
                <fullName>Deprecated</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ACH_Transaction_Log__c/ACH_Transaction_Log__c.object-meta.xml
<CustomObject>
    <label>ACH Transaction Log</label>
    <nameField>
        <displayFormat>LOG-{0000000}</displayFormat>
        <label>ACH Transaction Log Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ACH Transactions Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ACH_Transaction_Log__c/fields/Payment__c.field-meta.xml
<CustomField>
    <fullName>Payment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment</label>
    <referenceTo>cmbls__Payment__c</referenceTo>
    <relationshipLabel>ACH Transactions Logs</relationshipLabel>
    <relationshipName>ACH_Transactions_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ACH_Transaction_Log__c/fields/Response__c.field-meta.xml
<CustomField>
    <fullName>Response__c</fullName>
    <label>Response</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/ACH_Transaction_Log__c/fields/Response_Code__c.field-meta.xml
<CustomField>
    <fullName>Response_Code__c</fullName>
    <label>Response Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ACH_Transaction_Log__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Notification of Change</fullName>
            </value>
            <value>
                <fullName>Sent to Wells Fargo</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/cmbls__Disbursement__c/cmbls__Disbursement__c.object-meta.xml
<CustomObject>
    <label>Disbursement</label>
    <nameField>
        <displayFormat>D-{0000}</displayFormat>
        <label>Disbursement Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Disbursements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/cmbls__Disbursement__c/fields/cmbls__ACH_Processor__c.field-meta.xml
<CustomField>
    <fullName>cmbls__ACH_Processor__c</fullName>
    <label>ACH Processor</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Wells Fargo - NF Funding</fullName>
            </value>
            <value>
                <fullName>Wells Fargo - QBF Funding</fullName>
            </value>
            <value>
                <fullName>NFAS2 Transfer</fullName>
            </value>
            <value>
                <fullName>NF Transfer (QB)</fullName>
            </value>
            <value>
                <fullName>NFSPV1 Transfer</fullName>
            </value>
            <value>
                <fullName>Wire</fullName>
            </value>
            <value>
                <fullName>ACH Processing Co</fullName>
                <isActive>false</isActive>
                <label>ACH Processing Co</label>
            </value>
            <value>
                <fullName>ACH.com</fullName>
                <isActive>false</isActive>
                <label>ACH.com</label>
            </value>
            <value>
                <fullName>ACHWorks</fullName>
                <isActive>false</isActive>
                <label>ACHWorks</label>
            </value>
            <value>
                <fullName>ACHeck21</fullName>
                <isActive>false</isActive>
                <label>ACHeck21</label>
            </value>
            <value>
                <fullName>Forte</fullName>
                <isActive>false</isActive>
                <label>Forte</label>
            </value>
            <value>
                <fullName>PaySafe</fullName>
                <isActive>false</isActive>
                <label>PaySafe</label>
            </value>
            <value>
                <fullName>NFSPV2 Transfer</fullName>
            </value>
            <value>
                <fullName>NFAS3 Transfer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/cmbls__Disbursement__c/fields/cmbls__Disbursement_Batch__c.field-meta.xml
<CustomField>
    <fullName>cmbls__Disbursement_Batch__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Disbursement Batch</label>
    <referenceTo>cmbls__Disbursement_Batch__c</referenceTo>
    <relationshipLabel>Disbursements</relationshipLabel>
    <relationshipName>Disbursements</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/cmbls__Disbursement__c/fields/cmbls__Repayment__c.field-meta.xml
<CustomField>
    <fullName>cmbls__Repayment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Repayment</label>
    <referenceTo>cmbls__Repayment__c</referenceTo>
    <relationshipLabel>Disbursements</relationshipLabel>
    <relationshipName>Disbursements</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/cmbls__Payment__c/cmbls__Payment__c.object-meta.xml
<CustomObject>
    <label>Payment</label>
    <nameField>
        <displayFormat>PMT-{0000}</displayFormat>
        <label>Payment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/cmbls__Payment__c/fields/cmbls__ACH_Batch__c.field-meta.xml
<CustomField>
    <fullName>cmbls__ACH_Batch__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ACH Batch</label>
    <referenceTo>cmbls__ACH_Batch__c</referenceTo>
    <relationshipName>Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/cmbls__Payment__c/fields/cmbls__ACH_Processor__c.field-meta.xml
<CustomField>
    <fullName>cmbls__ACH_Processor__c</fullName>
    <label>ACH Processor</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Wells Fargo - NF Collections</fullName>
            </value>
            <value>
                <fullName>Wells Fargo - NFAS2 Collections</fullName>
            </value>
            <value>
                <fullName>Wells Fargo - NF Funding</fullName>
            </value>
            <value>
                <fullName>Wells Fargo - QBF Funding</fullName>
            </value>
            <value>
                <fullName>Wells Fargo - NFSPV1 Collections</fullName>
            </value>
            <value>
                <fullName>Wells Fargo - NFSPV2 Collections</fullName>
            </value>
            <value>
                <fullName>Wells Fargo - NFAS3 Collections</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/cmbls__Payment__c/fields/cmbls__Repayment__c.field-meta.xml
<CustomField>
    <fullName>cmbls__Repayment__c</fullName>
    <label>Repayment</label>
    <referenceTo>cmbls__Repayment__c</referenceTo>
    <relationshipLabel>Payments</relationshipLabel>
    <relationshipName>Payments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/cmbls__Payment__c/fields/cmbls__Transaction_Type__c.field-meta.xml
<CustomField>
    <fullName>cmbls__Transaction_Type__c</fullName>
    <description>This field indicates wether if it is a Fee or a Payment, and should be displayed in the page detail layout.</description>
    <inlineHelpText>This field indicates wether if it is a Fee or a Payment, and should be displayed in the page detail layout.</inlineHelpText>
    <label>Transaction Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Fee</fullName>
            </value>
            <value>
                <fullName>Payment</fullName>
            </value>
            <value>
                <fullName>Adjustment</fullName>
            </value>
            <value>
                <fullName>Distribution</fullName>
            </value>
            <value>
                <fullName>Fee Collection</fullName>
            </value>
            <value>
                <fullName>Reserve</fullName>
            </value>
            <value>
                <fullName>Interest</fullName>
            </value>
            <value>
                <fullName>Draw</fullName>
            </value>
            <value>
                <fullName>Draw Reserve</fullName>
            </value>
            <value>
                <fullName>Deferred Fee</fullName>
            </value>
            <value>
                <fullName>Lender Reimbursement</fullName>
            </value>
            <value>
                <fullName>Discount</fullName>
            </value>
            <value>
                <fullName>Payoff</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/cmbls__Payment__c/fields/Payment__c.field-meta.xml
<CustomField>
    <fullName>Payment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Rescheduled From</label>
    <referenceTo>cmbls__Payment__c</referenceTo>
    <relationshipLabel>Payments (Payment)</relationshipLabel>
    <relationshipName>Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/cmbls__Repayment__c/cmbls__Repayment__c.object-meta.xml
<CustomObject>
    <label>Repayment</label>
    <nameField>
        <displayFormat>RPMT-{0000000}</displayFormat>
        <label>Repayment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Repayments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/cmbls__Repayment__c/fields/cmbls__ACH_Processor__c.field-meta.xml
<CustomField>
    <fullName>cmbls__ACH_Processor__c</fullName>
    <description>The name of the processor being used</description>
    <inlineHelpText>The name of the processor being used</inlineHelpText>
    <label>ACH Processor</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Wells Fargo - NF Collections</fullName>
            </value>
            <value>
                <fullName>Wells Fargo - NFAS2 Collections</fullName>
            </value>
            <value>
                <fullName>Wells Fargo - NFSPV1 Collections</fullName>
            </value>
            <value>
                <fullName>Wells Fargo - NFSPV2 Collections</fullName>
            </value>
            <value>
                <fullName>Wells Fargo - NFAS3 Collections</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/cmbls__Repayment__c/fields/Merchant_Number__c.field-meta.xml
<CustomField>
    <fullName>Merchant_Number__c</fullName>
    <externalId>true</externalId>
    <label>LoanNumber</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/classes/PaymentsBatchProcessorTest.cls
/**
 * PaymentsBatchProcessorTest class
 * @author CloudMyBiz (r)
 * @date 05/08/2022
 * @description
 * @group 
 */

@IsTest
private class PaymentsBatchProcessorTest {

    @TestSetup static void setupMethod(){
        Test.startTest();
        Account acc = new Account(Name = 'Test account');
        insert acc;

        List<cmbls__Repayment__c> repayments = new List<cmbls__Repayment__c>();
        cmbls__Repayment__c repayment1 = TestDataFactory.createRepayment(acc.Id);
        repayment1.cmbls__ACH_Processor__c = 'Wells Fargo Account';
        repayment1.Merchant_Number__c = '123456';
        repayments.add(repayment1);
        cmbls__Repayment__c repayment2 = TestDataFactory.createRepayment(acc.Id);
        repayment2.Merchant_Number__c = '123457';
        repayment2.cmbls__ACH_Processor__c = Constant.ACH_PROCESSOR_NF_FUNDING;
        repayments.add(repayment2);
        insert repayments;

        cmbls__ACH_Batch__c achBatch = TestDataFactory.createACHBatch('Wells Fargo Account', 'Pending', DateTimeUtils.getNextValidDate(Date.today().addDays(1)));
        insert achBatch;
    
        cmbls__Payment__c[] payments = new cmbls__Payment__c[]{
            TestDataFactory.createPayment(repayment1.Id,'Debit', 'Scheduled', 100.00, Date.today(), 'Wells Fargo Account'),
            TestDataFactory.createPayment(repayment1.Id,'Debit', 'Scheduled', 100.00, Date.today(), 'Wells Fargo Account')
        };
        
        payments[0].cmbls__ACH_Batch__c = achBatch.Id;
        payments[0].cmbls__Transaction_Type__c = PaymentUtils.PAYMENT_TRANSACTION_TYPE_PAYMENT;
        payments[1].cmbls__ACH_Batch__c = achBatch.Id;
        payments[1].cmbls__Transaction_Type__c = PaymentUtils.PAYMENT_TRANSACTION_TYPE_PAYMENT;
        insert payments;

        cmbls__Disbursement_Batch__c disBatch = TestDataFactory.createDisBatch(Constant.ACH_PROCESSOR_NF_FUNDING, 'Pending', DateTimeUtils.getNextValidDate(Date.today().addDays(1)));
        insert disBatch;

        cmbls__Disbursement__c dis = TestDataFactory.createDisbursement('Funding', Constant.STATUS_SCHEDULED, Constant.ACH_PROCESSOR_NF_FUNDING);
        dis.cmbls__Repayment__c = repayment2.Id;
        dis.cmbls__Disbursement_Batch__c = disBatch.Id;
        insert dis;

        WF_Api_Settings__c wellsFargoAPiSettings = TestDataFactory.wfSettings();
        insert wellsFargoAPiSettings;
        Test.stopTest();
    }

    @IsTest
    static void paymentsToWellsFargoSuccess(){
        Test.startTest();
        String httpResp = '{"access_token": "TKWJGRwlSR1R5PWZLpKLU2hIpUM4","scope": "ACH-Payments ACH-Payments-Status WBHK-Webhooks WBHK-TEST-Events am_application_scope","token_type": "Bearer","expires_in": 86400}';
        Test.setMock(HttpCalloutMock.class, new ServiceConnectorMock(201, 'Status', httpResp, new Map<String,String>()));
        PaymentsBatchProcessor.PROCESS_ACH_TRANSACTIONS_BATCH = false;
        PaymentsSchedulerProcessor ps = new PaymentsSchedulerProcessor(WellsFargoAPI.PAYMENTS_PROCESS);
        ps.execute(null);
        Test.stopTest();

        cmbls__Payment__c pay = [SELECT Id, cmbls__ACH_Batch__c FROM cmbls__Payment__c ORDER BY CreatedDate DESC LIMIT 1];
        ACH_Transaction_Log__c achTransactionLog = [SELECT Id, Status__c, Response__c, Response_Code__c FROM ACH_Transaction_Log__c WHERE Payment__c = :pay.Id];
        System.assertEquals(achTransactionLog.Status__c, Constant.ACH_TRANSACTION_LOG_WF_SENT);
        System.assertEquals(achTransactionLog.Response__c, httpResp);
        System.assertEquals(achTransactionLog.Response_Code__c, '201');

        cmbls__ACH_Batch__c achBatch = [SELECT cmbls__Status__c FROM cmbls__ACH_Batch__c WHERE Id =: pay.cmbls__ACH_Batch__c];
        System.assertEquals(Constant.ACH_BATCH_STATUS_SUCCESS, achBatch.cmbls__Status__c);
    }

    @IsTest
    static void paymentsResubmission(){
        Test.startTest();
        
        WellsFargoAPI.WF_Settings.Error_Codes_To_Resubmit_Request__c = '500*;401*;429*;504-001;520*';
        upsert WellsFargoAPI.WF_Settings;

        WellsFargo.WFErrors serviceErrors = new WellsFargo.WFErrors();
        serviceErrors.errors = new List<WellsFargo.Error>();
        WellsFargo.Error respError = new WellsFargo.Error();
        respError.error_code = '500-001';
        respError.description = 'Internal System error.';
        serviceErrors.errors.add(respError);

        String httpResp = JSON.serialize(serviceErrors);
        Test.setMock(HttpCalloutMock.class, new ServiceConnectorMock(500, 'Status', httpResp, new Map<String,String>()));
        PaymentsBatchProcessor.PROCESS_ACH_TRANSACTIONS_BATCH = false;
        PaymentsSchedulerProcessor ps = new PaymentsSchedulerProcessor(WellsFargoAPI.PAYMENTS_PROCESS);
        ps.execute(null);
        Test.stopTest();

        cmbls__Payment__c pay = [SELECT Id, cmbls__ACH_Batch__c FROM cmbls__Payment__c ORDER BY CreatedDate DESC LIMIT 1];
        List<ACH_Transaction_Log__c> achTransactionLogs = [SELECT Id, Status__c, Response__c, Error_Code__c, Response_Code__c FROM ACH_Transaction_Log__c WHERE Payment__c = :pay.Id];
        System.assertEquals(1, achTransactionLogs.size());
        System.assertEquals(Constant.ACH_TRANSACTION_LOG_STATUS_COMPLETED, achTransactionLogs[0].Status__c);
        System.assertEquals(achTransactionLogs[0].Response__c, httpResp);
        System.assertEquals(achTransactionLogs[0].Error_Code__c, '500-001');
        System.assertEquals(achTransactionLogs[0].Response_Code__c, '500');

        cmbls__ACH_Batch__c resubmissionBatch = [SELECT cmbls__Status__c, WellsFargo_Number_of_Attempts__c, cmbls__Number_of_Failed_Payments__c FROM cmbls__ACH_Batch__c WHERE Id =: pay.cmbls__ACH_Batch__c];
        System.assertEquals(Constant.ACH_BATCH_STATUS_RESUBMISSION, resubmissionBatch.cmbls__Status__c);
        System.assertEquals(1, resubmissionBatch.WellsFargo_Number_of_Attempts__c);
        System.assertEquals(0, resubmissionBatch.cmbls__Number_of_Failed_Payments__c);
    }
    
    @IsTest
    static void paymentsResubmission2(){
        Test.startTest();
        
        WellsFargoAPI.WF_Settings.Error_Codes_To_Resubmit_Request__c = '500*;401*;429*;504-001;520*';
        upsert WellsFargoAPI.WF_Settings;
        
        WellsFargo.WFErrors serviceErrors = new WellsFargo.WFErrors();
        serviceErrors.errors = new List<WellsFargo.Error>();
        WellsFargo.Error respError = new WellsFargo.Error();
        respError.error_code = '401-002';
        respError.description = 'API key missing';
        serviceErrors.errors.add(respError);
        
        String httpResp = JSON.serialize(serviceErrors);
        Test.setMock(HttpCalloutMock.class, new ServiceConnectorMock(401, 'Status', httpResp, new Map<String,String>()));
        PaymentsBatchProcessor.PROCESS_ACH_TRANSACTIONS_BATCH = false;
        PaymentsSchedulerProcessor ps = new PaymentsSchedulerProcessor(WellsFargoAPI.PAYMENTS_PROCESS);
        ps.execute(null);
        Test.stopTest();
        
        cmbls__Payment__c pay = [SELECT Id, cmbls__ACH_Batch__c FROM cmbls__Payment__c ORDER BY CreatedDate DESC LIMIT 1];
        List<ACH_Transaction_Log__c> achTransactionLogs = [SELECT Id, Status__c, Response__c, Error_Code__c, Response_Code__c FROM ACH_Transaction_Log__c WHERE Payment__c = :pay.Id];
        System.assertEquals(1, achTransactionLogs.size());
        System.assertEquals(Constant.ACH_TRANSACTION_LOG_STATUS_COMPLETED, achTransactionLogs[0].Status__c);
        System.assertEquals(achTransactionLogs[0].Response__c, httpResp);
        System.assertEquals(achTransactionLogs[0].Error_Code__c, '401-002');
        System.assertEquals(achTransactionLogs[0].Response_Code__c, '401');
        
        cmbls__ACH_Batch__c resubmissionBatch = [SELECT cmbls__Status__c, WellsFargo_Number_of_Attempts__c, cmbls__Number_of_Failed_Payments__c FROM cmbls__ACH_Batch__c WHERE Id =: pay.cmbls__ACH_Batch__c];
        System.assertEquals(Constant.ACH_BATCH_STATUS_RESUBMISSION, resubmissionBatch.cmbls__Status__c);
        System.assertEquals(1, resubmissionBatch.WellsFargo_Number_of_Attempts__c);
        System.assertEquals(0, resubmissionBatch.cmbls__Number_of_Failed_Payments__c);
    }
    
    @IsTest
    static void paymentsResubmissionTimedOut(){
        Test.startTest();
        
        WellsFargoAPI.WF_Settings.Error_Codes_To_Resubmit_Request__c = '';
        upsert WellsFargoAPI.WF_Settings;
        
        Test.setMock(HttpCalloutMock.class, new ServiceConnectorMock(null, '', 'Exceeded maximum time allotted for callout (120000 ms)', new Map<String,String>()));
        PaymentsBatchProcessor.PROCESS_ACH_TRANSACTIONS_BATCH = false;
        PaymentsSchedulerProcessor ps = new PaymentsSchedulerProcessor(WellsFargoAPI.PAYMENTS_PROCESS);
        ps.execute(null);
        Test.stopTest();
        
        cmbls__Payment__c pay = [SELECT Id, cmbls__ACH_Batch__c, cmbls__Status__c FROM cmbls__Payment__c ORDER BY CreatedDate DESC LIMIT 1];
        List<ACH_Transaction_Log__c> achTransactionLogs = [SELECT Id, Status__c, Response__c, Error_Code__c FROM ACH_Transaction_Log__c WHERE Payment__c = :pay.Id];
        System.assertEquals(1, achTransactionLogs.size());
        System.assertEquals(Constant.ACH_TRANSACTION_LOG_STATUS_COMPLETED, achTransactionLogs[0].Status__c);
        System.assertEquals('Exceeded maximum time allotted for callout (120000 ms)', achTransactionLogs[0].Response__c);
        System.assertEquals(null, achTransactionLogs[0].Error_Code__c);
        System.assertEquals(PaymentUtils.PAYMENT_STATUS_SCHEDULED, pay.cmbls__Status__c);
        
        cmbls__ACH_Batch__c resubmissionBatch = [SELECT cmbls__Status__c, WellsFargo_Number_of_Attempts__c, cmbls__Number_of_Failed_Payments__c FROM cmbls__ACH_Batch__c WHERE Id =: pay.cmbls__ACH_Batch__c];
        System.assertEquals(Constant.ACH_BATCH_STATUS_RESUBMISSION, resubmissionBatch.cmbls__Status__c);
        System.assertEquals(1, resubmissionBatch.WellsFargo_Number_of_Attempts__c);
        System.assertEquals(0, resubmissionBatch.cmbls__Number_of_Failed_Payments__c);
    }
    
    @IsTest
    static void paymentsDuplicate(){
        Test.startTest();
        
        WellsFargoAPI.WF_Settings.Error_Codes_To_Resubmit_Request__c = '';
        upsert WellsFargoAPI.WF_Settings;
        
        WellsFargo.WFErrors serviceErrors = new WellsFargo.WFErrors();
        serviceErrors.errors = new List<WellsFargo.Error>();
        WellsFargo.Error respError = new WellsFargo.Error();
        respError.error_code = '1003-001';
        respError.description = 'Duplicate payment ID, transaction not processed.';
        serviceErrors.errors.add(respError);
        
        String httpResp = JSON.serialize(serviceErrors);
        
        Test.setMock(HttpCalloutMock.class, new ServiceConnectorMock(400, '', httpResp, new Map<String,String>()));
        PaymentsBatchProcessor.PROCESS_ACH_TRANSACTIONS_BATCH = false;
        PaymentsSchedulerProcessor ps = new PaymentsSchedulerProcessor(WellsFargoAPI.PAYMENTS_PROCESS);
        ps.execute(null);
        Test.stopTest();
        
        cmbls__Payment__c pay = [SELECT Id, cmbls__ACH_Batch__c, cmbls__Status__c FROM cmbls__Payment__c ORDER BY CreatedDate DESC LIMIT 1];
        List<ACH_Transaction_Log__c> achTransactionLogs = [SELECT Id, Status__c, Response__c, Error_Code__c, Response_Code__c FROM ACH_Transaction_Log__c WHERE Payment__c = :pay.Id];
        System.assertEquals(1, achTransactionLogs.size());
        System.assertEquals(Constant.ACH_TRANSACTION_LOG_WF_SENT, achTransactionLogs[0].Status__c);
        System.assertEquals(httpResp, achTransactionLogs[0].Response__c);
        System.assertEquals(respError.error_code, achTransactionLogs[0].Error_Code__c);
        System.assertEquals('201', achTransactionLogs[0].Response_Code__c);
        System.assertEquals(PaymentUtils.PAYMENT_STATUS_PRE_PENDING, pay.cmbls__Status__c);
        
        cmbls__ACH_Batch__c resubmissionBatch = [SELECT cmbls__Status__c, WellsFargo_Number_of_Attempts__c, cmbls__Number_of_Failed_Payments__c FROM cmbls__ACH_Batch__c WHERE Id =: pay.cmbls__ACH_Batch__c];
        System.assertEquals(Constant.ACH_BATCH_STATUS_SUCCESS, resubmissionBatch.cmbls__Status__c);
        System.assertEquals(1, resubmissionBatch.WellsFargo_Number_of_Attempts__c);
        System.assertEquals(0, resubmissionBatch.cmbls__Number_of_Failed_Payments__c);
    }

    @IsTest
    static void batchNumberOfAttemptsReached(){
        cmbls__Payment__c pay = [SELECT Id, cmbls__ACH_Batch__c FROM cmbls__Payment__c ORDER BY CreatedDate DESC LIMIT 1];
        update new cmbls__ACH_Batch__c(Id = pay.cmbls__ACH_Batch__c, WellsFargo_Number_of_Attempts__c = 1);
        
        WellsFargoAPI.WF_Settings.Error_Codes_To_Resubmit_Request__c = '500*;401*;429*;504-001;520*';
        WellsFargoAPI.WF_Settings.Max_Number_of_attempts__c = 2;
        upsert WellsFargoAPI.WF_Settings;

        WellsFargo.WFErrors serviceErrors = new WellsFargo.WFErrors();
        serviceErrors.errors = new List<WellsFargo.Error>();
        WellsFargo.Error respError = new WellsFargo.Error();
        respError.error_code = '500-001';
        respError.description = 'Internal System error.';
        serviceErrors.errors.add(respError);

        String httpResp = JSON.serialize(serviceErrors);
        Test.setMock(HttpCalloutMock.class, new ServiceConnectorMock(500, 'Status', httpResp, new Map<String,String>()));

        Test.startTest();
        PaymentsBatchProcessor.PROCESS_ACH_TRANSACTIONS_BATCH = false;
        PaymentsSchedulerProcessor ps = new PaymentsSchedulerProcessor(WellsFargoAPI.PAYMENTS_PROCESS);
        ps.execute(null);
        Test.stopTest();

        List<ACH_Transaction_Log__c> achTransactionLogs = [SELECT Id, Status__c, Response__c, Error_Code__c, Response_Code__c FROM ACH_Transaction_Log__c WHERE Payment__c = :pay.Id];
        System.assertEquals(1, achTransactionLogs.size());
        System.assertEquals(Constant.ACH_TRANSACTION_LOG_STATUS_COMPLETED, achTransactionLogs[0].Status__c);
        System.assertEquals(achTransactionLogs[0].Response__c, httpResp);
        System.assertEquals(achTransactionLogs[0].Error_Code__c, '500-001');
        System.assertEquals(achTransactionLogs[0].Response_Code__c, '500');

        cmbls__ACH_Batch__c resubmissionBatch = [SELECT cmbls__Status__c, WellsFargo_Number_of_Attempts__c, cmbls__Number_of_Failed_Payments__c FROM cmbls__ACH_Batch__c WHERE Id =: pay.cmbls__ACH_Batch__c];
        System.assertEquals(Constant.ACH_BATCH_STATUS_SUCCESS, resubmissionBatch.cmbls__Status__c);
        System.assertEquals(2, resubmissionBatch.WellsFargo_Number_of_Attempts__c);
    }

    @IsTest
    static void batchNumberOfAttemptsReachedNotSkipTransactionsBatch(){
        cmbls__Payment__c pay = [SELECT Id, cmbls__ACH_Batch__c FROM cmbls__Payment__c ORDER BY CreatedDate DESC LIMIT 1];
        update new cmbls__ACH_Batch__c(Id = pay.cmbls__ACH_Batch__c, WellsFargo_Number_of_Attempts__c = 1);
    
        WellsFargoAPI.WF_Settings.Error_Codes_To_Resubmit_Request__c = '';
        upsert WellsFargoAPI.WF_Settings;

        WellsFargo.WFErrors serviceErrors = new WellsFargo.WFErrors();
        serviceErrors.errors = new List<WellsFargo.Error>();
        WellsFargo.Error respError = new WellsFargo.Error();
        respError.error_code = '500-001';
        respError.description = 'Internal System error.';
        serviceErrors.errors.add(respError);

        String httpResp = JSON.serialize(serviceErrors);
        Test.setMock(HttpCalloutMock.class, new ServiceConnectorMock(500, 'Status', httpResp, new Map<String,String>()));

        Test.startTest();
        PaymentsSchedulerProcessor ps = new PaymentsSchedulerProcessor(WellsFargoAPI.PAYMENTS_PROCESS);
        ps.execute(null);
        Test.stopTest();

        pay = [SELECT Id, cmbls__ACH_Batch__c, cmbls__Status__c FROM cmbls__Payment__c ORDER BY CreatedDate DESC LIMIT 1];
        List<ACH_Transaction_Log__c> achTransactionLogs = [SELECT Id, Status__c, Response__c, Error_Code__c, Response_Code__c FROM ACH_Transaction_Log__c WHERE Payment__c = :pay.Id ORDER BY CreatedDate DESC];
        System.assertEquals(Constant.ACH_TRANSACTION_LOG_STATUS_COMPLETED, achTransactionLogs[0].Status__c);
        System.assertEquals(Constant.STATUS_FAILED, pay.cmbls__Status__c);

        cmbls__ACH_Batch__c resubmissionBatch = [SELECT cmbls__Status__c, WellsFargo_Number_of_Attempts__c, cmbls__Number_of_Failed_Payments__c FROM cmbls__ACH_Batch__c WHERE Id =: pay.cmbls__ACH_Batch__c];
        System.assertEquals(Constant.ACH_BATCH_STATUS_SUCCESS, resubmissionBatch.cmbls__Status__c);
        System.assertEquals(2, resubmissionBatch.WellsFargo_Number_of_Attempts__c);
        System.assertEquals(2, resubmissionBatch.cmbls__Number_of_Failed_Payments__c);
    }

    @IsTest
    static void paymentsError(){
        String responseBody = '{"errors":[{"error_code":"1003-002","description":"Payer Bank ID failed checksum and is invalid","api_specification_url":"https://developer.wellsfargo.com"}]}';
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new ServiceConnectorMock(400, 'Status', responseBody, new Map<String,String>()));
        PaymentsSchedulerProcessor ps = new PaymentsSchedulerProcessor(WellsFargoAPI.PAYMENTS_PROCESS);
        ps.execute(null);
        Test.stopTest();

        cmbls__Payment__c pay = [SELECT Id, cmbls__ACH_Batch__c, cmbls__ACH_Batch__r.cmbls__Status__c, cmbls__Status__c FROM cmbls__Payment__c ORDER BY CreatedDate DESC LIMIT 1];
        ACH_Transaction_Log__c achTransactionLog = [SELECT Id, Status__c, Response__c, Response_Code__c, Error_Code__c FROM ACH_Transaction_Log__c WHERE Payment__c = :pay.Id];
        System.assertEquals(Constant.ACH_TRANSACTION_LOG_STATUS_COMPLETED, achTransactionLog.Status__c);
        System.assertEquals(responseBody, achTransactionLog.Response__c);
        System.assertEquals('400', achTransactionLog.Response_Code__c);
        System.assertEquals('1003-002', achTransactionLog.Error_Code__c);
        System.assertEquals(PaymentUtils.PAYMENT_STATUS_FAILED, pay.cmbls__Status__c);

        System.assertEquals(Constant.ACH_BATCH_STATUS_SUCCESS, pay.cmbls__ACH_Batch__r.cmbls__Status__c);
    }
    
    @IsTest
    static void disbursementsToWellsFargoSuccess(){
        Test.startTest();
        String httpResp = '{"access_token": "TKWJGRwlSR1R5PWZLpKLU2hIpUM4","scope": "ACH-Payments ACH-Payments-Status WBHK-Webhooks WBHK-TEST-Events am_application_scope","token_type": "Bearer","expires_in": 86400}';
        Test.setMock(HttpCalloutMock.class, new ServiceConnectorMock(201, 'Status', httpResp, new Map<String,String>()));
        PaymentsBatchProcessor.PROCESS_ACH_TRANSACTIONS_BATCH = false;
        PaymentsSchedulerProcessor ps = new PaymentsSchedulerProcessor(WellsFargoAPI.DISBURSEMENT_PROCESS);
        ps.execute(null);
        Test.stopTest();
    }
    
    @IsTest
    static void ACHTransactionErrors(){
        Test.startTest();
        String httpResp = '{"access_token": "TKWJGRwlSR1R5PWZLpKLU2hIpUM4","scope": "ACH-Payments ACH-Payments-Status WBHK-Webhooks WBHK-TEST-Events am_application_scope","token_type": "Bearer","expires_in": 86400}';
        Test.setMock(HttpCalloutMock.class, new ServiceConnectorMock(201, 'Status', httpResp, new Map<String,String>()));
        PaymentsBatchProcessor.PROCESS_ACH_TRANSACTIONS_BATCH = false;
        PaymentsBatchProcessor.throwACHTransactionLogInsertError = true;
        PaymentsSchedulerProcessor ps = new PaymentsSchedulerProcessor(WellsFargoAPI.PAYMENTS_PROCESS);
        ps.execute(null);
        Test.stopTest();
        
        cmbls__Payment__c pay = [SELECT Id, cmbls__ACH_Batch__c FROM cmbls__Payment__c ORDER BY CreatedDate DESC LIMIT 1];
        System.assertEquals(0, [SELECT COUNT() FROM ACH_Transaction_Log__c WHERE Payment__c = :pay.Id]);
        
        cmbls__ACH_Batch__c achBatch = [SELECT cmbls__Status__c FROM cmbls__ACH_Batch__c WHERE Id =: pay.cmbls__ACH_Batch__c];
        System.assertEquals(Constant.ACH_BATCH_STATUS_SUCCESS, achBatch.cmbls__Status__c);
        
        String expectedSubject = String.format(PaymentsBatchProcessor.DEBUG_LOG_ACH_LOG_INSERT_FAILURE_SUBJECT, new String[]{PaymentsBatchProcessor.getJobName(WellsFargoAPI.PAYMENTS_PROCESS)});
        cmbls__Debug_Log__c[] logs = [SELECT Id, cmbls__Description__c, cmbls__Log__c FROM cmbls__Debug_Log__c WHERE cmbls__Subject__c = :expectedSubject];
        Assert.areEqual(1, logs.size());
        Assert.areEqual(PaymentsBatchProcessor.DEBUG_LOG_ACH_LOG_INSERT_FAILURE_DESCRIPTION, logs[0].cmbls__Description__c);
        Assert.isTrue(logs[0].cmbls__Log__c.containsIgnoreCase('Code: FIELD_INTEGRITY_EXCEPTION'));
    }
}