unpackaged/main/default/objects/Account/fields/Response__c.field-meta.xml
<CustomField>
    <fullName>Response__c</fullName>
    <description>Internal Marketing Field</description>
    <inlineHelpText>Internal Marketing Field</inlineHelpText>
    <label>Response</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>The status of this account.</description>
    <inlineHelpText>The status of this account.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Active - Renewals</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Fraud</fullName>
            </value>
            <value>
                <fullName>Duplicate</fullName>
            </value>
            <value>
                <fullName>Activator</fullName>
            </value>
            <value>
                <fullName>Prospect</fullName>
            </value>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
            <value>
                <fullName>Under Review</fullName>
            </value>
            <value>
                <fullName>Broker Declined</fullName>
            </value>
            <value>
                <fullName>Agreement Out</fullName>
            </value>
            <value>
                <fullName>Agreement In</fullName>
            </value>
            <value>
                <fullName>Additional Information Needed</fullName>
            </value>
            <value>
                <fullName>Remove From List</fullName>
            </value>
            <value>
                <fullName>Deprecated</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ACH_Transaction_Log__c/ACH_Transaction_Log__c.object-meta.xml
<CustomObject>
    <label>ACH Transaction Log</label>
    <nameField>
        <displayFormat>LOG-{0000000}</displayFormat>
        <label>ACH Transaction Log Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ACH Transactions Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ACH_Transaction_Log__c/fields/Disbursement__c.field-meta.xml
<CustomField>
    <fullName>Disbursement__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Disbursement</label>
    <referenceTo>cmbls__Disbursement__c</referenceTo>
    <relationshipLabel>ACH Transactions Logs</relationshipLabel>
    <relationshipName>ACH_Transactions_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ACH_Transaction_Log__c/fields/Payment__c.field-meta.xml
<CustomField>
    <fullName>Payment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment</label>
    <referenceTo>cmbls__Payment__c</referenceTo>
    <relationshipLabel>ACH Transactions Logs</relationshipLabel>
    <relationshipName>ACH_Transactions_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ACH_Transaction_Log__c/fields/Response__c.field-meta.xml
<CustomField>
    <fullName>Response__c</fullName>
    <label>Response</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/ACH_Transaction_Log__c/fields/Response_Code__c.field-meta.xml
<CustomField>
    <fullName>Response_Code__c</fullName>
    <label>Response Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/ACH_Transaction_Log__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Notification of Change</fullName>
            </value>
            <value>
                <fullName>Sent to Wells Fargo</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/cmbls__Disbursement__c/cmbls__Disbursement__c.object-meta.xml
<CustomObject>
    <label>Disbursement</label>
    <nameField>
        <displayFormat>D-{0000}</displayFormat>
        <label>Disbursement Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Disbursements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/cmbls__Disbursement__c/fields/cmbls__ACH_Processor__c.field-meta.xml
<CustomField>
    <fullName>cmbls__ACH_Processor__c</fullName>
    <label>ACH Processor</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Wells Fargo - NF Funding</fullName>
            </value>
            <value>
                <fullName>Wells Fargo - QBF Funding</fullName>
            </value>
            <value>
                <fullName>NFAS2 Transfer</fullName>
            </value>
            <value>
                <fullName>NF Transfer (QB)</fullName>
            </value>
            <value>
                <fullName>NFSPV1 Transfer</fullName>
            </value>
            <value>
                <fullName>Wire</fullName>
            </value>
            <value>
                <fullName>ACH Processing Co</fullName>
                <isActive>false</isActive>
                <label>ACH Processing Co</label>
            </value>
            <value>
                <fullName>ACH.com</fullName>
                <isActive>false</isActive>
                <label>ACH.com</label>
            </value>
            <value>
                <fullName>ACHWorks</fullName>
                <isActive>false</isActive>
                <label>ACHWorks</label>
            </value>
            <value>
                <fullName>ACHeck21</fullName>
                <isActive>false</isActive>
                <label>ACHeck21</label>
            </value>
            <value>
                <fullName>Forte</fullName>
                <isActive>false</isActive>
                <label>Forte</label>
            </value>
            <value>
                <fullName>PaySafe</fullName>
                <isActive>false</isActive>
                <label>PaySafe</label>
            </value>
            <value>
                <fullName>NFSPV2 Transfer</fullName>
            </value>
            <value>
                <fullName>NFAS3 Transfer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/cmbls__Disbursement__c/fields/cmbls__Disbursement_Batch__c.field-meta.xml
<CustomField>
    <fullName>cmbls__Disbursement_Batch__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Disbursement Batch</label>
    <referenceTo>cmbls__Disbursement_Batch__c</referenceTo>
    <relationshipLabel>Disbursements</relationshipLabel>
    <relationshipName>Disbursements</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/cmbls__Disbursement__c/fields/cmbls__Repayment__c.field-meta.xml
<CustomField>
    <fullName>cmbls__Repayment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Repayment</label>
    <referenceTo>cmbls__Repayment__c</referenceTo>
    <relationshipLabel>Disbursements</relationshipLabel>
    <relationshipName>Disbursements</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/cmbls__Payment__c/cmbls__Payment__c.object-meta.xml
<CustomObject>
    <label>Payment</label>
    <nameField>
        <displayFormat>PMT-{0000}</displayFormat>
        <label>Payment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/cmbls__Payment__c/fields/cmbls__ACH_Batch__c.field-meta.xml
<CustomField>
    <fullName>cmbls__ACH_Batch__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ACH Batch</label>
    <referenceTo>cmbls__ACH_Batch__c</referenceTo>
    <relationshipName>Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/cmbls__Payment__c/fields/cmbls__ACH_Processor__c.field-meta.xml
<CustomField>
    <fullName>cmbls__ACH_Processor__c</fullName>
    <label>ACH Processor</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Wells Fargo - NF Collections</fullName>
            </value>
            <value>
                <fullName>Wells Fargo - NFAS2 Collections</fullName>
            </value>
            <value>
                <fullName>Wells Fargo - NF Funding</fullName>
            </value>
            <value>
                <fullName>Wells Fargo - QBF Funding</fullName>
            </value>
            <value>
                <fullName>Wells Fargo - NFSPV1 Collections</fullName>
            </value>
            <value>
                <fullName>Wells Fargo - NFSPV2 Collections</fullName>
            </value>
            <value>
                <fullName>Wells Fargo - NFAS3 Collections</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/cmbls__Payment__c/fields/cmbls__Repayment__c.field-meta.xml
<CustomField>
    <fullName>cmbls__Repayment__c</fullName>
    <label>Repayment</label>
    <referenceTo>cmbls__Repayment__c</referenceTo>
    <relationshipLabel>Payments</relationshipLabel>
    <relationshipName>Payments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/cmbls__Payment__c/fields/Payment__c.field-meta.xml
<CustomField>
    <fullName>Payment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Rescheduled From</label>
    <referenceTo>cmbls__Payment__c</referenceTo>
    <relationshipLabel>Payments (Payment)</relationshipLabel>
    <relationshipName>Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/cmbls__Repayment__c/cmbls__Repayment__c.object-meta.xml
<CustomObject>
    <label>Repayment</label>
    <nameField>
        <displayFormat>RPMT-{0000000}</displayFormat>
        <label>Repayment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Repayments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/cmbls__Repayment__c/fields/cmbls__ACH_Processor__c.field-meta.xml
<CustomField>
    <fullName>cmbls__ACH_Processor__c</fullName>
    <description>The name of the processor being used</description>
    <inlineHelpText>The name of the processor being used</inlineHelpText>
    <label>ACH Processor</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Wells Fargo - NF Collections</fullName>
            </value>
            <value>
                <fullName>Wells Fargo - NFAS2 Collections</fullName>
            </value>
            <value>
                <fullName>Wells Fargo - NFSPV1 Collections</fullName>
            </value>
            <value>
                <fullName>Wells Fargo - NFSPV2 Collections</fullName>
            </value>
            <value>
                <fullName>Wells Fargo - NFAS3 Collections</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/cmbls__Repayment__c/fields/Merchant_Number__c.field-meta.xml
<CustomField>
    <fullName>Merchant_Number__c</fullName>
    <externalId>true</externalId>
    <label>LoanNumber</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/WF_Api_Settings__c/WF_Api_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Wells Fargo API Settings</label>
</CustomObject>

unpackaged/main/default/objects/WF_Api_Settings__c/fields/Gateway_Entity_Id__c.field-meta.xml
<CustomField>
    <fullName>Gateway_Entity_Id__c</fullName>
    <label>Gateway Entity Id</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/WF_Api_Settings__c/fields/WF_CHECK_NOTIFICATIONS_URL__c.field-meta.xml
<CustomField>
    <fullName>WF_CHECK_NOTIFICATIONS_URL__c</fullName>
    <label>WF CHECK NOTIFICATIONS URL</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/WF_Api_Settings__c/fields/WF_COMPANY_ID__c.field-meta.xml
<CustomField>
    <fullName>WF_COMPANY_ID__c</fullName>
    <description>Wells Fargo API Company ID</description>
    <inlineHelpText>Wells Fargo API Company ID</inlineHelpText>
    <label>WF COMPANY ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/WF_Api_Settings__c/fields/WF_TOKEN_URL__c.field-meta.xml
<CustomField>
    <fullName>WF_TOKEN_URL__c</fullName>
    <description>URL of Wells Fargo API to get access token.</description>
    <inlineHelpText>URL of Wells Fargo API to get access token.</inlineHelpText>
    <label>WF TOKEN URL</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/BatchCheckWFNotificationsTest.cls
/**
 * BatchCheckWFNotificationsTest class
 * @author CloudMyBiz (r)
 * @date 3/28/2023
 */

@IsTest
private class BatchCheckWFNotificationsTest{
    
    @TestSetup static void setupMethod(){
        Test.startTest();
        Account acc = TestDataFactory.createAccount();
        insert acc;
    
        Bank_Account__c bankAccount = TestDataFactory.createBankAccount();
        insert bankAccount;
    
        List<cmbls__Repayment__c> repayments = new List<cmbls__Repayment__c>();
        cmbls__Repayment__c repayment1 = TestDataFactory.createRepayment(acc.Id);
        repayment1.cmbls__ACH_Processor__c = 'Wells Fargo Account';
        repayment1.Merchant_Number__c = '123456';
        repayments.add(repayment1);
    
        cmbls__Repayment__c repayment2 = TestDataFactory.createRepayment(acc.Id);
        repayment2.Merchant_Number__c = '123457';
        repayment2.cmbls__ACH_Processor__c = Constant.ACH_PROCESSOR_NF_FUNDING;
        repayments.add(repayment2);
        insert repayments;
    
        cmbls__ACH_Batch__c achBatch = TestDataFactory.createACHBatch('Wells Fargo Account', Constant.ACH_BATCH_STATUS_SUCCESS, DateTimeUtils.getNextValidDate(Date.today().addDays(1)));
        insert achBatch;
    
        cmbls__Payment__c payment = TestDataFactory.createPayment(repayment1.Id,'Debit', Constant.STATUS_SETTLED, 100.00, Date.today(), 'Wells Fargo Account');
        payment.cmbls__ACH_Batch__c = achBatch.Id;
        insert payment;
    
        cmbls__Disbursement_Batch__c disBatch = TestDataFactory.createDisBatch(Constant.ACH_PROCESSOR_NF_FUNDING, Constant.ACH_BATCH_STATUS_SUCCESS, DateTimeUtils.getNextValidDate(Date.today().addDays(1)));
        insert disBatch;
    
        cmbls__Disbursement__c dis = TestDataFactory.createDisbursement('Funding', Constant.STATUS_SETTLED, Constant.ACH_PROCESSOR_NF_FUNDING);
        dis.cmbls__Repayment__c = repayment2.Id;
        dis.cmbls__Disbursement_Batch__c = disBatch.Id;
        insert dis;
        
        WellsFargoAPI.WF_Settings.WF_CHECK_NOTIFICATIONS_URL__c = 'https://test.com/';
        WellsFargoAPI.WF_Settings.WF_TOKEN_URL__c = 'https://test.com/';
        WellsFargoAPI.WF_Settings.WF_COMPANY_ID__c = '123456789';
        WellsFargoAPI.WF_Settings.Gateway_Entity_Id__c = '123456789';
        upsert WellsFargoAPI.WF_Settings;
        Test.stopTest();
    }
    
    @IsTest
    static void exception(){
        WellsFargoAPI.THROW_TEST_EXCEPTION = true;
        Test.startTest();
        new BatchCheckWFNotifications(1).execute(null);
        Test.stopTest();
        
        ACH_Transaction_Log__c log = [SELECT Payment__c, Disbursement__c, Status__c, Response__c FROM ACH_Transaction_Log__c];
        Assert.areEqual(Constant.ACH_TRANSACTION_LOG_STATUS_FAILED, log.Status__c);
        Assert.areEqual(null, log.Payment__c);
        Assert.areEqual(null, log.Disbursement__c);
        Assert.isTrue(log.Response__c.contains('Exception message for testing purposes'));
    }
    
    @IsTest
    static void responseError(){
        String httpResp = '{"errors":[{"error_code":"400-009","description":"\\u0027start_datetime\\u0027 is missing from the query string.","field_name":"start_datetime","api_specification_url":"https://developer.wellsfargo.com"}]}';
        Test.setMock(HttpCalloutMock.class, new ServiceConnectorMock(400, 'Bad Request', httpResp, new Map<String,String>()));
        Test.startTest();
        new BatchCheckWFNotifications(1).execute(null);
        Test.stopTest();
    
        ACH_Transaction_Log__c log = [SELECT Payment__c, Disbursement__c, Status__c, Response__c, Response_Code__c FROM ACH_Transaction_Log__c];
        Assert.areEqual(Constant.ACH_TRANSACTION_LOG_STATUS_FAILED, log.Status__c);
        Assert.areEqual(null, log.Payment__c);
        Assert.areEqual(null, log.Disbursement__c);
        Assert.areEqual('400', log.Response_Code__c);
        Assert.areEqual(httpResp, log.Response__c);
    }
    
    @IsTest
    static void success(){
        cmbls__Disbursement__c disbursement = [SELECT Id FROM cmbls__Disbursement__c WHERE cmbls__Status__c = :PaymentUtils.PAYMENT_STATUS_SETTLED LIMIT 1];
        cmbls__Payment__c payment = [SELECT Id FROM cmbls__Payment__c WHERE cmbls__Status__c = :PaymentUtils.PAYMENT_STATUS_SETTLED LIMIT 1];
        String httpResp = '{"item_count": 2,"notifications": [' +
            '{"data": {"recipient_id": "' + String.valueOf(disbursement.Id).left(15) + '","return_reason_description": "INCORRECT R/T NUMBER                              "}},' +
            '{"data": {"recipient_id": "' + String.valueOf(payment.Id).left(15) + '","return_reason_description": "INCORRECT R/T NUMBER                              "}}' +
            ']}';
        Test.setMock(HttpCalloutMock.class, new ServiceConnectorMock(200, 'OK', httpResp, new Map<String,String>()));
        Test.startTest();
        new BatchCheckWFNotifications(1).execute(null);
        Test.stopTest();
    
        ACH_Transaction_Log__c[] logs = [SELECT Payment__c, Disbursement__c, Status__c, Response__c, Response_Code__c FROM ACH_Transaction_Log__c];
        Assert.areEqual(Constant.ACH_TRANSACTION_LOG_STATUS_COMPLETED, logs[0].Status__c);
        Assert.areEqual(Constant.ACH_TRANSACTION_LOG_STATUS_COMPLETED, logs[1].Status__c);
        Assert.areEqual(1, [SELECT COUNT() FROM cmbls__Disbursement__c WHERE Id = :disbursement.Id AND cmbls__Status__c = :PaymentUtils.PAYMENT_STATUS_FAILED]);
        Assert.areEqual(1, [SELECT COUNT() FROM cmbls__Payment__c WHERE Id = :payment.Id AND cmbls__Status__c = :PaymentUtils.PAYMENT_STATUS_FAILED]);
    }
    
    @IsTest
    static void successCreateReversal(){
        WF_Api_Settings__c setting = WF_Api_Settings__c.getInstance();
        setting.Create_Reversal_Payment_for_Late_Returns__c = true;
        upsert setting;
        
        cmbls__Disbursement__c disbursement = [SELECT Id FROM cmbls__Disbursement__c WHERE cmbls__Status__c = :PaymentUtils.PAYMENT_STATUS_SETTLED LIMIT 1];
        cmbls__Payment__c payment = [SELECT Id FROM cmbls__Payment__c WHERE cmbls__Status__c = :PaymentUtils.PAYMENT_STATUS_SETTLED LIMIT 1];
        String httpResp = '{"item_count": 2,"notifications": [' +
            '{"data": {"recipient_id": "' + String.valueOf(disbursement.Id).left(15) + '","return_reason_description": "INCORRECT R/T NUMBER                              "}},' +
            '{"data": {"recipient_id": "' + String.valueOf(payment.Id).left(15) + '","return_reason_description": "INCORRECT R/T NUMBER                              "}}' +
            ']}';
        Test.setMock(HttpCalloutMock.class, new ServiceConnectorMock(200, 'OK', httpResp, new Map<String,String>()));
        Test.startTest();
        new BatchCheckWFNotifications(1).execute(null);
        Test.stopTest();
        
        ACH_Transaction_Log__c[] logs = [SELECT Payment__c, Disbursement__c, Status__c, Response__c, Response_Code__c FROM ACH_Transaction_Log__c];
        Assert.areEqual(Constant.ACH_TRANSACTION_LOG_STATUS_COMPLETED, logs[0].Status__c);
        Assert.areEqual(Constant.ACH_TRANSACTION_LOG_STATUS_COMPLETED, logs[1].Status__c);
        Assert.areEqual(1, [SELECT COUNT() FROM cmbls__Disbursement__c WHERE Id = :disbursement.Id AND cmbls__Status__c = :PaymentUtils.PAYMENT_STATUS_FAILED]);
        Assert.areEqual(1, [SELECT COUNT() FROM cmbls__Payment__c WHERE Id = :payment.Id AND cmbls__Status__c = :PaymentUtils.PAYMENT_STATUS_SETTLED AND cmbls__Reversal_Created__c = TRUE]);
        Assert.areEqual(1, [SELECT COUNT() FROM cmbls__Payment__c WHERE cmbls__Reversal_Of__c = :payment.Id AND cmbls__Status__c = :PaymentUtils.PAYMENT_STATUS_SETTLED]);
    }
    
    @IsTest
    static void ignoredReversalAndCancel(){
        WF_Api_Settings__c setting = WF_Api_Settings__c.getInstance();
        setting.Create_Reversal_Payment_for_Late_Returns__c = true;
        upsert setting;
        
        cmbls__Disbursement__c disbursement = [SELECT Id FROM cmbls__Disbursement__c WHERE cmbls__Status__c = :PaymentUtils.PAYMENT_STATUS_SETTLED LIMIT 1];
        disbursement.cmbls__Status__c = PaymentUtils.PAYMENT_STATUS_FAILED;
        update disbursement;
        
        cmbls__Payment__c payment = [SELECT Id FROM cmbls__Payment__c WHERE cmbls__Status__c = :PaymentUtils.PAYMENT_STATUS_SETTLED LIMIT 1];
        payment.cmbls__Reversal_Created__c = true;
        update payment;
        
        
        String httpResp = '{"item_count": 2,"notifications": [' +
            '{"data": {"recipient_id": "' + disbursement.Id + '","return_reason_description": "INCORRECT R/T NUMBER                              "}},' +
            '{"data": {"recipient_id": "' + payment.Id + '","return_reason_description": "INCORRECT R/T NUMBER                              "}}' +
            ']}';
        Test.setMock(HttpCalloutMock.class, new ServiceConnectorMock(200, 'OK', httpResp, new Map<String,String>()));
        Test.startTest();
        BatchCheckWFNotifications.isTest = true;
        new BatchCheckWFNotifications(1).execute(null);
        Test.stopTest();
        
        Assert.areEqual(0, [SELECT COUNT() FROM ACH_Transaction_Log__c WHERE Disbursement__c =:disbursement.Id OR Payment__c = :payment.Id]);
        Assert.areEqual(1, [SELECT COUNT() FROM cmbls__Disbursement__c WHERE Id = :disbursement.Id AND cmbls__Status__c = :PaymentUtils.PAYMENT_STATUS_FAILED]);
        Assert.areEqual(1, [SELECT COUNT() FROM cmbls__Payment__c WHERE Id = :payment.Id AND cmbls__Status__c = :PaymentUtils.PAYMENT_STATUS_SETTLED AND cmbls__Reversal_Created__c = TRUE]);
        Assert.areEqual(0, [SELECT COUNT() FROM cmbls__Payment__c WHERE cmbls__Reversal_Of__c = :payment.Id AND cmbls__Status__c = :PaymentUtils.PAYMENT_STATUS_SETTLED]);
    }
    
    @IsTest
    static void successKeySensitive(){
        cmbls__Disbursement__c disbursement = [SELECT Id FROM cmbls__Disbursement__c WHERE cmbls__Status__c = :PaymentUtils.PAYMENT_STATUS_SETTLED LIMIT 1];
        cmbls__Payment__c payment = [SELECT Id FROM cmbls__Payment__c WHERE cmbls__Status__c = :PaymentUtils.PAYMENT_STATUS_SETTLED LIMIT 1];
        
        String httpResp = '{"item_count": 2,"notifications": [' +
            '{"data": {"recipient_id": "' + String.valueOf(disbursement.Id).left(15).toUpperCase() + '","return_reason_description": "INCORRECT R/T NUMBER"}},' +
            '{"data": {"recipient_id": "' + String.valueOf(payment.Id).left(15).toUpperCase() + '","return_reason_description": "INCORRECT R/T NUMBER"}},' +
            '{"data": {"recipient_id": "' + String.valueOf(disbursement.Id).left(15) + '","return_reason_description": "INCORRECT R/T NUMBER"}},' +
            '{"data": {"recipient_id": "' + String.valueOf(payment.Id).left(15) + '","return_reason_description": "INCORRECT R/T NUMBER"}}' +
        ']}';
        Test.setMock(HttpCalloutMock.class, new ServiceConnectorMock(200, 'OK', httpResp, new Map<String,String>()));
        Test.startTest();
        new BatchCheckWFNotifications(1).execute(null);
        Test.stopTest();
        
        ACH_Transaction_Log__c[] logs = [SELECT Payment__c, Disbursement__c, Status__c, Response__c, Response_Code__c FROM ACH_Transaction_Log__c];
        Assert.areEqual(Constant.ACH_TRANSACTION_LOG_STATUS_COMPLETED, logs[0].Status__c);
        Assert.areEqual(Constant.ACH_TRANSACTION_LOG_STATUS_COMPLETED, logs[1].Status__c);
        Assert.areEqual(1, [SELECT COUNT() FROM cmbls__Disbursement__c WHERE Id = :disbursement.Id AND cmbls__Status__c = :PaymentUtils.PAYMENT_STATUS_FAILED]);
        Assert.areEqual(1, [SELECT COUNT() FROM cmbls__Payment__c WHERE Id = :payment.Id AND cmbls__Status__c = :PaymentUtils.PAYMENT_STATUS_FAILED]);
    }
    
    @IsTest
    static void noRecordsKeySensitive(){
        cmbls__Disbursement__c disbursement = [SELECT Id FROM cmbls__Disbursement__c WHERE cmbls__Status__c = :PaymentUtils.PAYMENT_STATUS_SETTLED LIMIT 1];
        cmbls__Payment__c payment = [SELECT Id FROM cmbls__Payment__c WHERE cmbls__Status__c = :PaymentUtils.PAYMENT_STATUS_SETTLED LIMIT 1];
        
        String httpResp = '{"item_count": 2,"notifications": [' +
            '{"data": {"recipient_id": "' + String.valueOf(disbursement.Id).left(15).toUpperCase() + '","return_reason_description": "INCORRECT R/T NUMBER"}},' +
            '{"data": {"recipient_id": "' + String.valueOf(payment.Id).left(15).toUpperCase() + '","return_reason_description": "INCORRECT R/T NUMBER"}}' +
            ']}';
        Test.setMock(HttpCalloutMock.class, new ServiceConnectorMock(200, 'OK', httpResp, new Map<String,String>()));
        
        Test.startTest();
        new BatchCheckWFNotifications(1).execute(null);
        Test.stopTest();
        
        Assert.areEqual(0, [SELECT COUNT() FROM ACH_Transaction_Log__c]);
        Assert.areEqual(1, [SELECT COUNT() FROM cmbls__Disbursement__c WHERE Id = :disbursement.Id AND cmbls__Status__c = :PaymentUtils.PAYMENT_STATUS_SETTLED]);
        Assert.areEqual(1, [SELECT COUNT() FROM cmbls__Payment__c WHERE Id = :payment.Id AND cmbls__Status__c = :PaymentUtils.PAYMENT_STATUS_SETTLED]);
    }
    
    @IsTest
    static void coverage(){
        Test.startTest();
        BatchCheckWFNotifications.resubmitJob(1);
        BatchCheckWFNotifications.shouldReschedule();
        Test.stopTest();
    }
}