unpackaged/main/default/objects/Account/fields/Short_Account_Number__c.field-meta.xml
<CustomField>
    <fullName>Short_Account_Number__c</fullName>
    <description>The last 8 digits of the customer's 16 digit account number.</description>
    <inlineHelpText>Type in the last 8 digits of the customer's 16 digit account number.</inlineHelpText>
    <label>Short Account Number</label>
    <length>9</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account/recordTypes/Customer.recordType-meta.xml
<RecordType>
    <fullName>Customer</fullName>
    <active>true</active>
    <label>Customer</label>
</RecordType>

unpackaged/main/default/objects/CampaignMember/fields/Short_Account_Number__c.field-meta.xml
<CustomField>
    <fullName>Short_Account_Number__c</fullName>
    <description>The last 8 of the account number field.</description>
    <externalId>true</externalId>
    <inlineHelpText>The last 8 of the account number field.</inlineHelpText>
    <label>Short Account Number</label>
    <length>9</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/FICO_Score__c.field-meta.xml
<CustomField>
    <fullName>FICO_Score__c</fullName>
    <description>This field displays this contact's most recently updated credit score.</description>
    <inlineHelpText>This field displays this contact's most recently updated credit score.</inlineHelpText>
    <label>FICO Score</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/SSN_Encrypted__c.field-meta.xml
<CustomField>
    <fullName>SSN_Encrypted__c</fullName>
    <description>This field will contain a customer's Social Security number in an encrypted format. Accessing the full visibility of this field will be determined by job role and permission set.</description>
    <inlineHelpText>Encrypted Social Security Number - See your administrator if you have questions.</inlineHelpText>
    <label>SSN Encrypted</label>
    <length>11</length>
    <maskChar>asterisk</maskChar>
    <maskType>ssn</maskType>
    <type>EncryptedText</type>
</CustomField>

unpackaged/main/default/objects/Lead/fields/FICO_Score__c.field-meta.xml
<CustomField>
    <fullName>FICO_Score__c</fullName>
    <description>Customers FICO Score</description>
    <inlineHelpText>Customers FICO Score</inlineHelpText>
    <label>Min FICO Score</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Lead/fields/Short_Account_Number__c.field-meta.xml
<CustomField>
    <fullName>Short_Account_Number__c</fullName>
    <description>A calculated field that is that last 8 digits of the account number.  Used for many lookups.</description>
    <inlineHelpText>A calculated field that is that last 8 digits of the account number.  Used for many lookups.</inlineHelpText>
    <label>Short Account Number</label>
    <length>9</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Lead/fields/SSN_Encrypted__c.field-meta.xml
<CustomField>
    <fullName>SSN_Encrypted__c</fullName>
    <description>This field will contain a customer's Social Security number in an encrypted format.  Accessing the full visibility of this field will be determined by job role and permission set.</description>
    <inlineHelpText>Encrypted Social Security Number - See your administrator if you have questions.</inlineHelpText>
    <label>SSN Encrypted</label>
    <length>11</length>
    <maskChar>asterisk</maskChar>
    <maskType>ssn</maskType>
    <type>EncryptedText</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/EPP_Equip_LP__c.field-meta.xml
<CustomField>
    <fullName>EPP_Equip_LP__c</fullName>
    <defaultValue>false</defaultValue>
    <label>EPP Equip - LP #</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/EPP_Equip_PO_to_Accounting__c.field-meta.xml
<CustomField>
    <fullName>EPP_Equip_PO_to_Accounting__c</fullName>
    <defaultValue>false</defaultValue>
    <label>EPP Equip - PO to Accounting</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Funds_Released_By__c.field-meta.xml
<CustomField>
    <fullName>Funds_Released_By__c</fullName>
    <description>This field will indicate how funds need to be released to the customer and any other party that needs funding as result of this transaction.</description>
    <inlineHelpText>This field will indicate how funds need to be released to the customer and any other party that needs funding as result of this transaction.</inlineHelpText>
    <label>Funds Released By:</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ACH</fullName>
            </value>
            <value>
                <fullName>Wire</fullName>
            </value>
            <value>
                <fullName>Check</fullName>
            </value>
            <value>
                <fullName>ACH &amp; Wire</fullName>
            </value>
            <value>
                <fullName>ACH &amp; Check</fullName>
            </value>
            <value>
                <fullName>Wire &amp; Check</fullName>
            </value>
            <value>
                <fullName>ACH &amp; Wire &amp; Check</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Lease_Deposit_Check_Received__c.field-meta.xml
<CustomField>
    <fullName>Lease_Deposit_Check_Received__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field will notate that a Deposit Check has been received by the accounting team.  This field must be populated to create a Lease Plus Number.  It is a required value in the Lease Plus number trigger.</description>
    <inlineHelpText>Check this box when the accounting team has received the lease deposit check.</inlineHelpText>
    <label>Lease Deposit Check Received</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Lender_Account__c.field-meta.xml
<CustomField>
    <fullName>Lender_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lender Account selected for Oppty</description>
    <inlineHelpText>Select the Lender being used for this Opportunity</inlineHelpText>
    <label>Lender Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Lender Acct</value>
        </filterItems>
        <infoMessage>Select the Lender for this Opportunity</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities (Lender Account)</relationshipLabel>
    <relationshipName>Opportunities1</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Merchant_Number__c.field-meta.xml
<CustomField>
    <fullName>Merchant_Number__c</fullName>
    <description>MCA or ML merchant number provided by the lender.</description>
    <inlineHelpText>MCA or ML merchant number provided by the lender.</inlineHelpText>
    <label>Merchant Number</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/recordTypes/Broker_FRPSA.recordType-meta.xml
<RecordType>
    <fullName>Broker_FRPSA</fullName>
    <active>true</active>
    <businessProcess>Broker WC Sales</businessProcess>
    <description>Broker FRPSA</description>
    <label>Broker FRPSA</label>
</RecordType>

unpackaged/main/default/objects/Opportunity/recordTypes/Broker_WC_Oppty.recordType-meta.xml
<RecordType>
    <fullName>Broker_WC_Oppty</fullName>
    <active>true</active>
    <businessProcess>Broker WC Sales</businessProcess>
    <label>Broker WC Oppty</label>
</RecordType>

unpackaged/main/default/objects/Opportunity/recordTypes/Direct_MLP.recordType-meta.xml
<RecordType>
    <fullName>Direct_MLP</fullName>
    <active>true</active>
    <businessProcess>FPC Working Capital Sales</businessProcess>
    <label>Direct MLP</label>
</RecordType>

unpackaged/main/default/objects/Opportunity/recordTypes/EPP_Oppty.recordType-meta.xml
<RecordType>
    <fullName>EPP_Oppty</fullName>
    <active>true</active>
    <businessProcess>FPC EPP Sales</businessProcess>
    <description>Electronic Payment Processing</description>
    <label>EPP Oppty</label>
</RecordType>

unpackaged/main/default/objects/Opportunity/recordTypes/External_Collections.recordType-meta.xml
<RecordType>
    <fullName>External_Collections</fullName>
    <active>true</active>
    <businessProcess>FPC Working Capital Sales</businessProcess>
    <description>Used for loans originated outside of National Funding</description>
    <label>External Collections</label>
</RecordType>

unpackaged/main/default/objects/Opportunity/recordTypes/FRPSA.recordType-meta.xml
<RecordType>
    <fullName>FRPSA</fullName>
    <active>true</active>
    <businessProcess>FPC Working Capital Sales</businessProcess>
    <description>FRPSA</description>
    <label>FRPSA</label>
</RecordType>

unpackaged/main/default/objects/Opportunity/recordTypes/Lease_Oppty_Record_Type.recordType-meta.xml
<RecordType>
    <fullName>Lease_Oppty_Record_Type</fullName>
    <active>true</active>
    <businessProcess>FPC Lease Sales</businessProcess>
    <description>Lease</description>
    <label>Lease Oppty</label>
</RecordType>

unpackaged/main/default/classes/TestLibrary.cls
/**
 * ─────────────────────────────────────────────────────────────────────────────────────────────────
 * TITLE: TestDataFactory
 * DESCRIPTION: Utility class for creating test data for Contacts and Accounts and Opportunity
 * @author         Amrit
 * @version        1.0
 * @created        31/01/2025
 * ─────────────────────────────────────────────────────────────────────────────────────────────────
 */
@isTest
public class TestLibrary {
    public static Account createTestAccount() {
        Account newAccount = new Account(
            Name = 'Test Account',
            RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('New Customer Acct').getRecordTypeId()
        );
        insert newAccount;
        return newAccount;
    }
	public static Account createAccountOfRecordType(String accountName, String recordTypeName) {
        Account newAccount = new Account(
            Name = accountName,
            RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get(recordTypeName).getRecordTypeId()
        );
        insert newAccount;
        return newAccount;
    }
    public static Contact createTestContact(Account account) {
        Contact newContact = new Contact(
            FirstName = 'John',
            LastName = 'Doe',
            AccountId = account != null ? account.Id : null,
            SSN_Encrypted__c = '123-45-6789',
            Phone = '(123) 456-7890',
            MobilePhone  = '(123) 456-7890',
            OtherPhone   = '(123) 456-7890',
            HomePhone    = '(123) 456-7890',
            FICO_Score__c = 700
        );
        insert newContact;
        return newContact;
    }
    
    public static Lead createTestLead() {
        Lead l = new Lead();
        l.FirstName = 'Tom';
        l.LastName = 'Test';
        l.Company = 'Five9';
		l.Email = 'test1@example.com';
        l.PostalCode = '12345';
        l.Short_Account_Number__c = 'SACC123';
        l.Status='House';
 		l.SSN_Encrypted__c = '123-45-6789';
        insert l;
        return l;
    }
    // Create test Campaigns
    public static List<Campaign> createTestCampaigns(Integer numCampaigns) {
        List<Campaign> testCampaigns = new List<Campaign>();
        for (Integer i = 0; i < numCampaigns; i++) {
            testCampaigns.add(new Campaign(Name = 'Test Campaign ' + i));
        }
        insert testCampaigns;
        return testCampaigns;
    }

    // Create test CampaignMembers
    public static List<CampaignMember> createTestCampaignMembers(List<Contact> contacts, List<Campaign> campaigns) {
        List<CampaignMember> testCampaignMembers = new List<CampaignMember>();
        for (Contact con : contacts) {
            for (Campaign camp : campaigns) {
                testCampaignMembers.add(new CampaignMember(
                    ContactId = con.Id,
                    CampaignId = camp.Id
                ));
            }
        }
        insert testCampaignMembers;
        return testCampaignMembers;
    }

    // Create test Opportunities
    public static List<Opportunity> createTestOpportunities(List<Account> accounts, Id lenderAccountId, Map<String, Id> recordTypeMap) {
        List<Opportunity> testOpps = new List<Opportunity>();
        for (Account acc : accounts) {
            testOpps.add(new Opportunity(
                Name = 'Test Opp 1 - ' + acc.Name,
                AccountId = acc.Id,
                RecordTypeId = recordTypeMap.get('Lease_Oppty_Record_Type'),
                Lender_Account__c = lenderAccountId,
                Merchant_Number__c = '12345',
                Funds_Released_By__c = 'ACH',
                StageName = 'Funded',
                Type = 'NEW',
                Lease_Deposit_Check_Received__c = true,
                CloseDate = System.today().addDays(30)
            ));
            testOpps.add(new Opportunity(
                Name = 'Test Opp 3 - ' + acc.Name,
                AccountId = acc.Id,
                RecordTypeId = recordTypeMap.get('EPP_Oppty'),
                Lender_Account__c = lenderAccountId,
                Merchant_Number__c = '12345',
                Funds_Released_By__c = 'ACH',
                StageName = 'Funded',
                EPP_Equip_LP__c = true,
                EPP_Equip_PO_to_Accounting__c = true,
                CloseDate = System.today().addDays(30)
            ));
            testOpps.add(new Opportunity(
                Name = 'Test Opp 4 - ' + acc.Name,
                AccountId = acc.Id,
                RecordTypeId = recordTypeMap.get('Broker_WC_Oppty'),
                StageName = 'Funded',
                Type = 'NEW',
                Lender_Account__c = lenderAccountId,
                Funds_Released_By__c = 'ACH',
                Merchant_Number__c = '12345',
                CloseDate = System.today().addDays(30)
            ));
            testOpps.add(new Opportunity(
                Name = 'Test Opp 5 - ' + acc.Name,
                AccountId = acc.Id,
                RecordTypeId = recordTypeMap.get('External_Collections'),
                StageName = 'Funded',
                Lender_Account__c = lenderAccountId,
                Funds_Released_By__c = 'ACH',
                Merchant_Number__c = '12345',
                CloseDate = System.today().addDays(30)
            ));
            testOpps.add(new Opportunity(
                Name = 'Test Opp 6 - ' + acc.Name,
                AccountId = acc.Id,
                RecordTypeId = recordTypeMap.get('FRPSA'),
                StageName = 'Funded',
                Type = 'NEW',
                Lender_Account__c = lenderAccountId,
                Funds_Released_By__c = 'ACH',
                Merchant_Number__c = '12345',
                CloseDate = System.today().addDays(30)
            ));
            testOpps.add(new Opportunity(
                Name = 'Test Opp 7 - ' + acc.Name,
                AccountId = acc.Id,
                RecordTypeId = recordTypeMap.get('Direct_MLP'),
                StageName = 'Funded',
                Type = 'NEW',
                Lender_Account__c = lenderAccountId,
                Funds_Released_By__c = 'ACH',
                Merchant_Number__c = '12345',
                CloseDate = System.today().addDays(30)
            ));
        }
        insert testOpps;
        return testOpps;
    }

    // Fetch RecordTypeIds for Opportunities
    public static Map<String, Id> getOpportunityRecordTypeMap() {
        Map<String, Id> recordTypeMap = new Map<String, Id>();
        for (RecordType rt : [
            SELECT Id, DeveloperName 
            FROM RecordType 
            WHERE SObjectType = 'Opportunity' 
            AND DeveloperName IN ('Lease_Oppty_Record_Type', 'EPP_Oppty', 'Broker_WC_Oppty', 'External_Collections', 'FRPSA', 'Broker_FRPSA', 'Direct_MLP')
        ]) {
            recordTypeMap.put(rt.DeveloperName, rt.Id);
        }
        return recordTypeMap;
    }
    public static Opportunity createOpportunity(Id lenderAccountId, Id accountId, Id oppRecordType){
        Id oppRecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('FRPSA').getRecordTypeId();
        Opportunity opp = new Opportunity();
        opp.Name = 'Test Opp 1';
        opp.AccountId = accountId;
        opp.RecordTypeId = oppRecordType !=null ? oppRecordType : oppRecordTypeId;
        opp.StageName = 'Identified';
        if (lenderAccountId != null)opp.Lender_Account__c = lenderAccountId;
        opp.CloseDate = System.today().addDays(30);
        insert opp;
        return opp;
    }
}