unpackaged/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>The status of this account.</description>
    <inlineHelpText>The status of this account.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Active - Renewals</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Fraud</fullName>
            </value>
            <value>
                <fullName>Duplicate</fullName>
            </value>
            <value>
                <fullName>Activator</fullName>
            </value>
            <value>
                <fullName>Prospect</fullName>
            </value>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
            <value>
                <fullName>Under Review</fullName>
            </value>
            <value>
                <fullName>Broker Declined</fullName>
            </value>
            <value>
                <fullName>Agreement Out</fullName>
            </value>
            <value>
                <fullName>Agreement In</fullName>
            </value>
            <value>
                <fullName>Additional Information Needed</fullName>
            </value>
            <value>
                <fullName>Remove From List</fullName>
            </value>
            <value>
                <fullName>Deprecated</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ACH_Transaction_Log__c/ACH_Transaction_Log__c.object-meta.xml
<CustomObject>
    <label>ACH Transaction Log</label>
    <nameField>
        <displayFormat>LOG-{0000000}</displayFormat>
        <label>ACH Transaction Log Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ACH Transactions Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/ACH_Transaction_Log__c/fields/Disbursement__c.field-meta.xml
<CustomField>
    <fullName>Disbursement__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Disbursement</label>
    <referenceTo>cmbls__Disbursement__c</referenceTo>
    <relationshipLabel>ACH Transactions Logs</relationshipLabel>
    <relationshipName>ACH_Transactions_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ACH_Transaction_Log__c/fields/Payment__c.field-meta.xml
<CustomField>
    <fullName>Payment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment</label>
    <referenceTo>cmbls__Payment__c</referenceTo>
    <relationshipLabel>ACH Transactions Logs</relationshipLabel>
    <relationshipName>ACH_Transactions_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/ACH_Transaction_Log__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Notification of Change</fullName>
            </value>
            <value>
                <fullName>Sent to Wells Fargo</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/cmbls__Disbursement__c/cmbls__Disbursement__c.object-meta.xml
<CustomObject>
    <label>Disbursement</label>
    <nameField>
        <displayFormat>D-{0000}</displayFormat>
        <label>Disbursement Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Disbursements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/cmbls__Disbursement__c/fields/cmbls__ACH_Processor__c.field-meta.xml
<CustomField>
    <fullName>cmbls__ACH_Processor__c</fullName>
    <label>ACH Processor</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Wells Fargo - NF Funding</fullName>
            </value>
            <value>
                <fullName>Wells Fargo - QBF Funding</fullName>
            </value>
            <value>
                <fullName>NFAS2 Transfer</fullName>
            </value>
            <value>
                <fullName>NF Transfer (QB)</fullName>
            </value>
            <value>
                <fullName>NFSPV1 Transfer</fullName>
            </value>
            <value>
                <fullName>Wire</fullName>
            </value>
            <value>
                <fullName>ACH Processing Co</fullName>
                <isActive>false</isActive>
                <label>ACH Processing Co</label>
            </value>
            <value>
                <fullName>ACH.com</fullName>
                <isActive>false</isActive>
                <label>ACH.com</label>
            </value>
            <value>
                <fullName>ACHWorks</fullName>
                <isActive>false</isActive>
                <label>ACHWorks</label>
            </value>
            <value>
                <fullName>ACHeck21</fullName>
                <isActive>false</isActive>
                <label>ACHeck21</label>
            </value>
            <value>
                <fullName>Forte</fullName>
                <isActive>false</isActive>
                <label>Forte</label>
            </value>
            <value>
                <fullName>PaySafe</fullName>
                <isActive>false</isActive>
                <label>PaySafe</label>
            </value>
            <value>
                <fullName>NFSPV2 Transfer</fullName>
            </value>
            <value>
                <fullName>NFAS3 Transfer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/cmbls__Disbursement__c/fields/cmbls__Effective_Date__c.field-meta.xml
<CustomField>
    <fullName>cmbls__Effective_Date__c</fullName>
    <label>Effective Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/cmbls__Disbursement__c/fields/cmbls__Repayment__c.field-meta.xml
<CustomField>
    <fullName>cmbls__Repayment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Repayment</label>
    <referenceTo>cmbls__Repayment__c</referenceTo>
    <relationshipLabel>Disbursements</relationshipLabel>
    <relationshipName>Disbursements</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/cmbls__Disbursement__c/fields/cmbls__Transaction_Amount__c.field-meta.xml
<CustomField>
    <fullName>cmbls__Transaction_Amount__c</fullName>
    <label>Transaction Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/cmbls__Disbursement__c/fields/Wells_Fargo_Disbursement_ID_Formula__c.field-meta.xml
<CustomField>
    <fullName>Wells_Fargo_Disbursement_ID_Formula__c</fullName>
    <description>Uses 'Record ID' if 'Wells Fargo Disbursement ID Override' is null</description>
    <formula>IF( ISBLANK( Wells_Fargo_Disbursement_ID_Override__c), Id ,  Wells_Fargo_Disbursement_ID_Override__c )</formula>
    <inlineHelpText>Uses 'Record ID' if 'Wells Fargo Disbursement ID Override' is null</inlineHelpText>
    <label>Wells Fargo Disbursement ID Formula</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/cmbls__Payment__c/cmbls__Payment__c.object-meta.xml
<CustomObject>
    <label>Payment</label>
    <nameField>
        <displayFormat>PMT-{0000}</displayFormat>
        <label>Payment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/cmbls__Payment__c/fields/cmbls__ACH_Processor__c.field-meta.xml
<CustomField>
    <fullName>cmbls__ACH_Processor__c</fullName>
    <label>ACH Processor</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Wells Fargo - NF Collections</fullName>
            </value>
            <value>
                <fullName>Wells Fargo - NFAS2 Collections</fullName>
            </value>
            <value>
                <fullName>Wells Fargo - NF Funding</fullName>
            </value>
            <value>
                <fullName>Wells Fargo - QBF Funding</fullName>
            </value>
            <value>
                <fullName>Wells Fargo - NFSPV1 Collections</fullName>
            </value>
            <value>
                <fullName>Wells Fargo - NFSPV2 Collections</fullName>
            </value>
            <value>
                <fullName>Wells Fargo - NFAS3 Collections</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/cmbls__Payment__c/fields/cmbls__Effective_Date__c.field-meta.xml
<CustomField>
    <fullName>cmbls__Effective_Date__c</fullName>
    <inlineHelpText>Effective Date</inlineHelpText>
    <label>Effective Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/cmbls__Payment__c/fields/cmbls__Repayment__c.field-meta.xml
<CustomField>
    <fullName>cmbls__Repayment__c</fullName>
    <label>Repayment</label>
    <referenceTo>cmbls__Repayment__c</referenceTo>
    <relationshipLabel>Payments</relationshipLabel>
    <relationshipName>Payments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/cmbls__Payment__c/fields/cmbls__Transaction_Amount__c.field-meta.xml
<CustomField>
    <fullName>cmbls__Transaction_Amount__c</fullName>
    <label>Transaction Amount</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/cmbls__Payment__c/fields/Payment__c.field-meta.xml
<CustomField>
    <fullName>Payment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Rescheduled From</label>
    <referenceTo>cmbls__Payment__c</referenceTo>
    <relationshipLabel>Payments (Payment)</relationshipLabel>
    <relationshipName>Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/cmbls__Payment__c/fields/Wells_Fargo_Payment_ID_Formula__c.field-meta.xml
<CustomField>
    <fullName>Wells_Fargo_Payment_ID_Formula__c</fullName>
    <description>Uses 'Record ID' if 'Wells Fargo Payment ID Override' is null</description>
    <formula>IF( ISBLANK( Wells_Fargo_Payment_ID_Override__c), Id , Wells_Fargo_Payment_ID_Override__c )</formula>
    <inlineHelpText>Uses 'Record ID' if 'Wells Fargo Payment ID Override' is null</inlineHelpText>
    <label>Wells Fargo Payment ID Formula</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/cmbls__Payment__c/fields/Wells_Fargo_Payment_ID_Override__c.field-meta.xml
<CustomField>
    <fullName>Wells_Fargo_Payment_ID_Override__c</fullName>
    <description>This payment ID will be sent to Wells Fargo when populated as an override. Otherwise, the external transaction ID will be used.</description>
    <inlineHelpText>This payment ID will be sent to Wells Fargo when populated as an override. Otherwise, the external transaction ID will be used.</inlineHelpText>
    <label>Wells Fargo Payment ID Override</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/cmbls__Repayment__c/cmbls__Repayment__c.object-meta.xml
<CustomObject>
    <label>Repayment</label>
    <nameField>
        <displayFormat>RPMT-{0000000}</displayFormat>
        <label>Repayment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Repayments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/cmbls__Repayment__c/fields/cmbls__ACH_Processor__c.field-meta.xml
<CustomField>
    <fullName>cmbls__ACH_Processor__c</fullName>
    <description>The name of the processor being used</description>
    <inlineHelpText>The name of the processor being used</inlineHelpText>
    <label>ACH Processor</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Wells Fargo - NF Collections</fullName>
            </value>
            <value>
                <fullName>Wells Fargo - NFAS2 Collections</fullName>
            </value>
            <value>
                <fullName>Wells Fargo - NFSPV1 Collections</fullName>
            </value>
            <value>
                <fullName>Wells Fargo - NFSPV2 Collections</fullName>
            </value>
            <value>
                <fullName>Wells Fargo - NFAS3 Collections</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/cmbls__Repayment__c/fields/Merchant_Number__c.field-meta.xml
<CustomField>
    <fullName>Merchant_Number__c</fullName>
    <externalId>true</externalId>
    <label>LoanNumber</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/classes/WellsFargoConnectorTest.cls
/**
 * WellsFargoConnectorTest class
 * @author CloudMyBiz (r)
 * @date 18/07/2022
 * @description
 * @group 
 */

@IsTest
private class WellsFargoConnectorTest {

    @TestSetup static void setupMethod() {
        Test.startTest();
        Account acc = new Account(Name = 'Test account');
        insert acc;

        cmbls__Repayment__c repayment1 = TestDataFactory.createRepayment(acc.Id);
        repayment1.cmbls__ACH_Processor__c = 'Wells Fargo Account';
        repayment1.Merchant_Number__c = '123456';
        insert repayment1;

        cmbls__Disbursement__c dis = TestDataFactory.createDisbursement('Funding', Constant.STATUS_SCHEDULED, Constant.ACH_PROCESSOR_NF_FUNDING);
        dis.cmbls__Repayment__c = repayment1.Id;
        insert dis;

        Test.stopTest();
    }

    @IsTest
    static void webhookPaymentReversal(){
        RestRequest req = new RestRequest();
        req.addHeader('httpMethod', 'POST');
        req.requestURI = '/services/apexrest/wellsFargoPayments/';

        WellsFargo.WebhookReturn webhReturn = new WellsFargo.WebhookReturn();
        webhReturn.data = new WellsFargo.WebhookData();
        webhReturn.data.return_reason_description = 'INSUFFICIENT FUNDS';

        cmbls__Payment__c payment = [SELECT Id, Wells_Fargo_Payment_ID_Formula__c FROM cmbls__Payment__c];
        webhReturn.data.recipient_id = payment.Wells_Fargo_Payment_ID_Formula__c;
        req.requestBody = Blob.valueOf(JSON.serialize(webhReturn));
        RestContext.request = req;
        RestContext.response = new RestResponse();

        Test.startTest();
        WellsFargoConnector.POST();
        Test.stopTest();

        System.assert([SELECT COUNT() FROM ACH_Transaction_Log__c WHERE Status__c =: Constant.ACH_TRANSACTION_LOG_STATUS_FAILED AND Payment__c = :payment.Id] == 1);
    }

    @IsTest
    static void webhookDisbursementReversal(){
        RestRequest req = new RestRequest();
        req.addHeader('httpMethod', 'POST');
        req.requestURI = '/services/apexrest/wellsFargoPayments/';

        WellsFargo.WebhookReturn webhReturn = new WellsFargo.WebhookReturn();
        webhReturn.data = new WellsFargo.WebhookData();
        webhReturn.data.return_reason_description = 'INSUFFICIENT FUNDS';

        cmbls__Disbursement__c disb = [SELECT Id, Wells_Fargo_Disbursement_ID_Formula__c FROM cmbls__Disbursement__c];
        webhReturn.data.recipient_id = disb.Wells_Fargo_Disbursement_ID_Formula__c;
        req.requestBody = Blob.valueOf(JSON.serialize(webhReturn));
        RestContext.request = req;
        RestContext.response = new RestResponse();

        Test.startTest();
        WellsFargoConnector.POST();
        Test.stopTest();

        System.assert([SELECT COUNT() FROM ACH_Transaction_Log__c WHERE Status__c =: Constant.ACH_TRANSACTION_LOG_STATUS_FAILED AND Disbursement__c = :disb.Id] == 1);
    }

    @IsTest
    static void webhookNotificationOfChange(){
        RestRequest req = new RestRequest();
        req.addHeader('httpMethod', 'POST');
        req.requestURI = '/services/apexrest/wellsFargoPayments/';

        WellsFargo.WebhookReturn webhReturn = new WellsFargo.WebhookReturn();
        webhReturn.data = new WellsFargo.WebhookData();
        webhReturn.data.return_reason_code = 'C01';
        webhReturn.data.return_reason_description = 'Notification of Change.';

        cmbls__Payment__c payment = [SELECT Id, Wells_Fargo_Payment_ID_Formula__c FROM cmbls__Payment__c];
        webhReturn.data.recipient_id = payment.Wells_Fargo_Payment_ID_Formula__c;
        req.requestBody = Blob.valueOf(JSON.serialize(webhReturn));
        RestContext.request = req;
        RestContext.response = new RestResponse();

        Test.startTest();
        WellsFargoConnector.POST();
        Test.stopTest();

        System.assert([SELECT COUNT() FROM ACH_Transaction_Log__c WHERE Status__c =: Constant.ACH_TRANSACTION_LOG_STATUS_NOTIFICATION AND Payment__c = :payment.Id] == 1);
    }
    
    @IsTest
    static void webhookPaymentReversalKeySensitive(){
        RestRequest req = new RestRequest();
        req.addHeader('httpMethod', 'POST');
        req.requestURI = '/services/apexrest/wellsFargoPayments/';
        
        WellsFargo.WebhookReturn webhReturn = new WellsFargo.WebhookReturn();
        webhReturn.data = new WellsFargo.WebhookData();
        webhReturn.data.return_reason_description = 'INSUFFICIENT FUNDS';
        
        cmbls__Payment__c payment = [SELECT Id, Wells_Fargo_Payment_ID_Formula__c FROM cmbls__Payment__c];
        payment.Wells_Fargo_Payment_ID_Override__c = 'ABCDEFGH';
        update payment;
        
        insert new cmbls__Payment__c(
            cmbls__Transaction_Amount__c = 200,
            Wells_Fargo_Payment_ID_Override__c = 'ABCDEFGh',
            cmbls__Repayment__c = [SELECT Id FROM cmbls__Repayment__c].Id,
            cmbls__Effective_Date__c = System.today()
        );
        
        webhReturn.data.recipient_id = 'ABCDEFGH';//payment.Wells_Fargo_Payment_ID_Override__c;
        req.requestBody = Blob.valueOf(JSON.serialize(webhReturn));
        RestContext.request = req;
        RestContext.response = new RestResponse();
        
        Test.startTest();
        WellsFargoConnector.POST();
        Test.stopTest();
        
        System.assertEquals(1, [SELECT COUNT() FROM ACH_Transaction_Log__c WHERE Status__c =: Constant.ACH_TRANSACTION_LOG_STATUS_FAILED AND Payment__c = :payment.Id]);
    }

}