unpackaged/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>The status of this account.</description>
    <inlineHelpText>The status of this account.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Active - Renewals</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Fraud</fullName>
            </value>
            <value>
                <fullName>Duplicate</fullName>
            </value>
            <value>
                <fullName>Activator</fullName>
            </value>
            <value>
                <fullName>Prospect</fullName>
            </value>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
            <value>
                <fullName>Under Review</fullName>
            </value>
            <value>
                <fullName>Broker Declined</fullName>
            </value>
            <value>
                <fullName>Agreement Out</fullName>
            </value>
            <value>
                <fullName>Agreement In</fullName>
            </value>
            <value>
                <fullName>Additional Information Needed</fullName>
            </value>
            <value>
                <fullName>Remove From List</fullName>
            </value>
            <value>
                <fullName>Deprecated</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/recordTypes/Lender.recordType-meta.xml
<RecordType>
    <fullName>Lender</fullName>
    <active>true</active>
    <label>Lender</label>
</RecordType>

unpackaged/main/default/objects/Apex_Configuration__mdt/Apex_Configuration__mdt.object-meta.xml
<CustomObject>
    <label>Apex Configuration</label>
    <pluralLabel>Apex Configurations</pluralLabel>
</CustomObject>

unpackaged/main/default/objects/Credit_Review__c/Credit_Review__c.object-meta.xml
<CustomObject>
    <label>Credit Review</label>
    <nameField>
        <displayFormat>CR-{00000000}</displayFormat>
        <label>Credit Review ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Credit Reviews</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Credit_Review__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Credit Reviews</relationshipLabel>
    <relationshipName>Credit_Reviews</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Credit_Review__c/fields/AutomatedCreditProcess__c.field-meta.xml
<CustomField>
    <fullName>AutomatedCreditProcess__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Field will be checked when the Credit Review was created by the Automated Credit Process trigger</description>
    <label>AutomatedCreditProcess</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Credit_Review__c/fields/Create_WC_Decision_Record__c.field-meta.xml
<CustomField>
    <fullName>Create_WC_Decision_Record__c</fullName>
    <label>Create WC Decision Record</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Create</fullName>
            </value>
            <value>
                <fullName>Ready</fullName>
                <default>true</default>
                <label>Ready</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Credit_Review__c/fields/Credit_Review_Version__c.field-meta.xml
<CustomField>
    <fullName>Credit_Review_Version__c</fullName>
    <label>Credit Review Version</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Version 1</fullName>
            </value>
            <value>
                <fullName>Version 2</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Credit_Review__c/fields/eNoah_Review_Completed_Date__c.field-meta.xml
<CustomField>
    <fullName>eNoah_Review_Completed_Date__c</fullName>
    <description>This field will capture the date/time that the eNoah review process is completed the first time they indicate that it has been completed.</description>
    <inlineHelpText>This field will capture the date/time that the eNoah review process is completed the first time they indicate that it has been completed.</inlineHelpText>
    <label>eNoah Review Completed Date</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Credit_Review__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Credit Reviews</relationshipLabel>
    <relationshipName>Credit_Reviews</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Credit_Review__c/fields/Opportunity_Owner_Email__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Owner_Email__c</fullName>
    <label>Opportunity Owner Email</label>
    <type>Email</type>
</CustomField>

unpackaged/main/default/objects/Credit_Review__c/fields/PG1__c.field-meta.xml
<CustomField>
    <fullName>PG1__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>PG1</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Credit Reviews</relationshipLabel>
    <relationshipName>Credit_Reviews</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Credit_Review__c/fields/PG2__c.field-meta.xml
<CustomField>
    <fullName>PG2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>PG2</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Credit Reviews (PG2)</relationshipLabel>
    <relationshipName>Credit_Reviews1</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Credit_Review__c/fields/PG3__c.field-meta.xml
<CustomField>
    <fullName>PG3__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>PG3</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Credit Reviews (PG3)</relationshipLabel>
    <relationshipName>Credit_Reviews2</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Credit_Review__c/fields/Related_Funding_Record__c.field-meta.xml
<CustomField>
    <fullName>Related_Funding_Record__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Related Funding Record</label>
    <referenceTo>FPC_Funding_del__c</referenceTo>
    <relationshipLabel>Credit Reviews</relationshipLabel>
    <relationshipName>Credit_Reviews</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Credit_Review__c/fields/Review_Type__c.field-meta.xml
<CustomField>
    <fullName>Review_Type__c</fullName>
    <label>Review Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Initial Review</fullName>
                <default>true</default>
                <label>Initial Review</label>
            </value>
            <value>
                <fullName>Gold Review</fullName>
            </value>
            <value>
                <fullName>Platinum Review</fullName>
            </value>
            <value>
                <fullName>Diamond Review</fullName>
            </value>
            <value>
                <fullName>Commercial Review</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Credit_Review__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>In Progress</fullName>
                <default>true</default>
                <label>In Progress</label>
            </value>
            <value>
                <fullName>Second Review</fullName>
            </value>
            <value>
                <fullName>Need More Information</fullName>
            </value>
            <value>
                <fullName>Financial Analysis</fullName>
            </value>
            <value>
                <fullName>UW Call</fullName>
            </value>
            <value>
                <fullName>Commercial 2nd Review</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>EP Review Done</fullName>
            </value>
            <value>
                <fullName>Increase Review</fullName>
            </value>
            <value>
                <fullName>Withdrawn</fullName>
            </value>
            <value>
                <fullName>Reactivated</fullName>
            </value>
            <value>
                <fullName>NF Decline</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Credit_Review__c/fields/Withdrawn_By__c.field-meta.xml
<CustomField>
    <fullName>Withdrawn_By__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Withdrawn By</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Credit_Reviews</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/FPC_Funding_del__c/FPC_Funding_del__c.object-meta.xml
<CustomObject>
    <description>Table of lenders this deal is shopped to.</description>
    <label>Funding</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Funding ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Funding</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/FPC_Funding_del__c/fields/Lender_ID__c.field-meta.xml
<CustomField>
    <fullName>Lender_ID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>ID for the lender in a custom object lookup.</description>
    <inlineHelpText>ID for the lender in a custom object lookup.</inlineHelpText>
    <label>Lender ID</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Lender Acct</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Lender ID</relationshipLabel>
    <relationshipName>Funding</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/FPC_Funding_del__c/fields/Lender_Position__c.field-meta.xml
<CustomField>
    <fullName>Lender_Position__c</fullName>
    <description>This field will capture the position that a lender is in when shopping a deal for an approval.</description>
    <inlineHelpText>This field will capture the position that a lender is in when shopping a deal for an approval.</inlineHelpText>
    <label>Lender Position</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/FPC_Funding_del__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Funding</relationshipLabel>
    <relationshipName>Funding</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/FPC_Funding_del__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status of funding</description>
    <inlineHelpText>Pick the funding status of the opportunity.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Older Approval</fullName>
            </value>
            <value>
                <fullName>Lender Pend Info</fullName>
            </value>
            <value>
                <fullName>Lender Approved</fullName>
            </value>
            <value>
                <fullName>Send to Lender</fullName>
            </value>
            <value>
                <fullName>Hold</fullName>
            </value>
            <value>
                <fullName>Not Eligible</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Withdrawn</fullName>
            </value>
            <value>
                <fullName>Auto Submitting</fullName>
            </value>
            <value>
                <fullName>Submission in Progress</fullName>
            </value>
            <value>
                <fullName>Referred</fullName>
            </value>
            <value>
                <fullName>Processing</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Broker_Preferred_Email__c.field-meta.xml
<CustomField>
    <fullName>Broker_Preferred_Email__c</fullName>
    <label>Broker Preferred Email</label>
    <type>Email</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Closed - Won</fullName>
            </value>
            <value>
                <fullName>Closed - Lost</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/recordTypes/MCA_Oppty.recordType-meta.xml
<RecordType>
    <fullName>MCA_Oppty</fullName>
    <active>true</active>
    <businessProcess>FPC MCA Sales</businessProcess>
    <description>Working Capital Record Type</description>
    <label>Working Capital Oppty</label>
</RecordType>

unpackaged/main/default/objects/User/fields/CaseSafe_User_Id__c.field-meta.xml
<CustomField>
    <fullName>CaseSafe_User_Id__c</fullName>
    <formula>CASESAFEID(Id)</formula>
    <label>CaseSafe User Id</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/User/fields/User_Developer_Name__c.field-meta.xml
<CustomField>
    <fullName>User_Developer_Name__c</fullName>
    <description>Unique name for user that can be used across orgs for workflow rules other automated tasks. Should not contain spaces.</description>
    <inlineHelpText>Unique name for user that can be used across orgs for workflow rules other automated tasks. Should not contain spaces.</inlineHelpText>
    <label>User Developer Name</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/classes/AutomatedCreditStart.cls
/**
 * Created by oporter on 12/5/2017.
* ─────────────────────────────────────────────────────────────────────────────────────────────────
* TITLE: AutomatedCreditStart
* DESCRIPTION: Automated Credit Project Phase 1. Class is called by trigger, creates a new Credit Review and calls CreditReviewScreenController
*
* ──────────────────────────────────────────────────────────────────────────────────────────────────
* @author         Olivia Porter       <oporter@nationalfunding.com>
* @modifiedBy     Olivia Porter       <oporter@nationalfunding.com>
* @maintainedBy   Olivia Porter       <oporter@nationalfunding.com>
* @version        3.0
* @created        2018-04-06
* ──────────────────────────────────────────────────────────────────────────────────────────────────
* v1              oporter@nationalfunding.com
* 2017-02-13      Explanation of the change.  Multiple lines can be used to explain the change, but
*                 each line should be indented till left aligned with the previous description text.
*
* v2              oporter@nationalfunding.com
* 2018-04-06      Removed Static variables to fix bug. Bug was causing incorrect association of OCRs to Opportunties.
*                 Bulkified code.
*
* v3              oporter@nationalfunding.com
* 2018-04-20      Removed call to CreditReviewScreenController
*                 Took necessary code from CreditReviewScreen Controller and implemented within this class
*                 to minimize the amount of time we exceed gov limits. Currently we can bulk process 16 Opportunities 
*
* v4 			  aburdick@nationalfunding.com
* 2021-02-04 	  Added logic to update Opportunity Stage to PreQual under certain conditions.
*/

public class AutomatedCreditStart {

    //Creates Credit Review record associated to newly created Opportunity
    @InvocableMethod
    public static void automatedClass(List<Id> oppStatementsIn) {
        List<Credit_Review__c> crList = new List<Credit_Review__c>();
        System.debug('Total Number of SOQL Queries allowed in this apex code context: ' +  Limits.getLimitQueries());
        System.debug('Returns the number of SOQL queries that have been issued.: ' +  Limits.getQueries());
        system.debug('oppStatementsIn:: ' + oppStatementsIn + ', oppStatementsIn.count():: ' + oppStatementsIn.size());

        //for every opportunity that was passed we instantiate new pgs, Credit_Review__c object,
        for (Opportunity o : [SELECT AccountId, Broker_Preferred_Email__c, OwnerId, Owner.Email, (SELECT Id, ContactId, Role FROM OpportunityContactRoles), (SELECT Id FROM Credit_Reviews__r) FROM Opportunity WHERE Id IN :oppStatementsIn]) {
            Id pg1, pg2, pg3;
            Credit_Review__c obj;

            try {
                if (o.Credit_Reviews__r == NULL || o.Credit_Reviews__r.size() == 0) {
                    obj = new Credit_review__c();
                    obj.Credit_Review_Version__c = 'Version 2';
                    obj.Account__c = o.AccountId;
                    obj.Opportunity__c = o.Id;
                    obj.Status__c = 'In Progress';
                    obj.Create_WC_Decision_Record__c = 'Ready';
                    obj.AutomatedCreditProcess__c = TRUE;
                    obj.Broker_Preferred_Email__c = o.Broker_Preferred_Email__c;
                    obj.Opportunity_Owner_Email__c = o.Owner.Email;
                    for (OpportunityContactRole ocr : o.OpportunityContactRoles) {
                        if (ocr.Role == 'Signor') {
                            pg1 = ocr.ContactId;
                        } else if (ocr.Role == 'Guarantor 2') {
                            pg2 = ocr.ContactId;
                        } else if (ocr.Role == 'Guarantor 3') {
                            pg3 = ocr.ContactId;
                        }
                    }
                    obj.PG1__c = pg1;
                    obj.PG2__c = pg2;
                    obj.PG3__c = pg3;
                    crList.add(obj);
                } else {
                    system.debug('cr is NOT NULL');
                }
            } catch (Exception e) {
                system.debug('Credit Review in Automated Process Catch:: ' + e);
                //todo:: why are we eating this exception?
            }
        }

        if (!crList.isEmpty()) {
            insert crList;

            for (Credit_Review__c cr : crList) {
                funderInsert(cr);
                callAutomationFlow(cr);
            }
        }
    }

    public static void funderInsert(Credit_Review__c cr) {
        Id profileId = UserInfo.getProfileId();
        String profileName = [SELECT Id,Name FROM Profile WHERE Id = :profileId].Name;

        // Count number of lenders already for this account so we can set lender position correctly
        AggregateResult AR = [SELECT Count(id) tot FROM FPC_Funding_del__c WHERE Opportunity__c = :cr.Opportunity__c];

        // retrieve lender account
        Account lender = [SELECT Id FROM Account WHERE Name = 'National Funding - Platinum WC Funding' LIMIT 1];
        FPC_Funding_del__c fd = new FPC_Funding_del__c(Opportunity__c = cr.Opportunity__c);
        fd.Lender_ID__c = lender.id;
        fd.Lender_Position__c = (Decimal) AR.get('tot') + 1;
        fd.Status__c = 'Submitted';
        insert fd;

        //update CR with newly created funding record
        cr.Related_Funding_Record__c = fd.id;
        cr.Review_Type__c = 'Platinum Review';

        if (profileName != 'NF Partner - Brokers') {
            Id crOwnerId = [SELECT CaseSafe_User_Id__c FROM User WHERE User_Developer_Name__c = 'NF_Automation_User'].Id;
            cr.OwnerId = crOwnerId;
        }
        update cr;
        
        // Update Opportunity Stage to PreQual if record type is Direct and New or Type <> Not New and Config set to true
        Apex_Configuration__mdt config = [SELECT Active__c, DeveloperName, Label FROM Apex_Configuration__mdt WHERE DeveloperName = 'AutomatedCreditStart_Update_Opp_Stage'];
        Opportunity opp = [SELECT RecordTypeId, Type FROM Opportunity WHERE Id = :cr.Opportunity__c];
        RecordType opprt = [SELECT Id, DeveloperName From RecordType WHERE Id = :opp.RecordTypeId];
        
        if (((opprt.DeveloperName == 'MCA_Oppty' && opp.Type == 'NEW') || opp.Type == 'RENEWAL' || opp.Type == 'CONCURRENT' || opp.Type == 'RENEWAL CONCURRENT') && config.Active__c == TRUE){
            opp.StageName = 'Pre-Qual MCA';
        } else {
            system.debug('Opportunity not eligible to update stage to PreQual. Type ='+ opp.Type);
        }
        update opp; 
    }
    
        
    public static void callAutomationFlow(Credit_Review__c cr){
        Opportunity oppData = [SELECT RecordTypeId, Type, StageName FROM Opportunity WHERE Id = :cr.Opportunity__c];
        RecordType rt = [SELECT Id, DeveloperName From RecordType WHERE Id = :oppData.RecordTypeId];

        System.debug('callAutomationFlow:: Total Number of SOQL Queries allowed in this apex code context: ' + Limits.getLimitQueries());
        System.debug('callAutomationFlow:: Returns the number of SOQL queries that have been issued.: ' + Limits.getQueries());

        //publishing Platform Event
        //CRC3AutomationPlatformEvents.createPlatformEvent(cr, oppData, rt);

        //passing params to flow
        Map<String, Object> params = new Map<String, Object>();
        params.put('varCRId', cr.Id);
        params.put('inputOpptyId', cr.Opportunity__c);
        params.put('inputOpptyStageName', oppData.StageName);
        params.put('varOpptyRecordType', rt.DeveloperName);
        params.put('varFundingRecordId', cr.Related_Funding_Record__c);
        params.put('varDealType', oppData.Type);
        params.put('varCRStatus', cr.Status__c);
        params.put('vareNoahCompleteDate', cr.eNoah_Review_Completed_Date__c);
        system.debug('CRC_3_Automation_AutoStart params:: ' + params);
        if(oppData.Type == 'NEW' || oppData.Type == 'New') {
            Flow.Interview.CRC_3_Automation_AutoStart automation = new Flow.Interview.CRC_3_Automation_AutoStart(params);
            automation.start();
        }
    }
}