unpackaged/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>The status of this account.</description>
    <inlineHelpText>The status of this account.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Active - Renewals</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Fraud</fullName>
            </value>
            <value>
                <fullName>Duplicate</fullName>
            </value>
            <value>
                <fullName>Activator</fullName>
            </value>
            <value>
                <fullName>Prospect</fullName>
            </value>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
            <value>
                <fullName>Under Review</fullName>
            </value>
            <value>
                <fullName>Broker Declined</fullName>
            </value>
            <value>
                <fullName>Agreement Out</fullName>
            </value>
            <value>
                <fullName>Agreement In</fullName>
            </value>
            <value>
                <fullName>Additional Information Needed</fullName>
            </value>
            <value>
                <fullName>Remove From List</fullName>
            </value>
            <value>
                <fullName>Deprecated</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account/recordTypes/Lender.recordType-meta.xml
<RecordType>
    <fullName>Lender</fullName>
    <active>true</active>
    <label>Lender</label>
</RecordType>

unpackaged/main/default/objects/FPC_Funding_del__c/FPC_Funding_del__c.object-meta.xml
<CustomObject>
    <description>Table of lenders this deal is shopped to.</description>
    <label>Funding</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Funding ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Funding</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/FPC_Funding_del__c/fields/Lender_ID__c.field-meta.xml
<CustomField>
    <fullName>Lender_ID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>ID for the lender in a custom object lookup.</description>
    <inlineHelpText>ID for the lender in a custom object lookup.</inlineHelpText>
    <label>Lender ID</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Lender Acct</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Lender ID</relationshipLabel>
    <relationshipName>Funding</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/FPC_Funding_del__c/fields/Lender_Position__c.field-meta.xml
<CustomField>
    <fullName>Lender_Position__c</fullName>
    <description>This field will capture the position that a lender is in when shopping a deal for an approval.</description>
    <inlineHelpText>This field will capture the position that a lender is in when shopping a deal for an approval.</inlineHelpText>
    <label>Lender Position</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/FPC_Funding_del__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Funding</relationshipLabel>
    <relationshipName>Funding</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/FPC_Funding_del__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status of funding</description>
    <inlineHelpText>Pick the funding status of the opportunity.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Older Approval</fullName>
            </value>
            <value>
                <fullName>Lender Pend Info</fullName>
            </value>
            <value>
                <fullName>Lender Approved</fullName>
            </value>
            <value>
                <fullName>Send to Lender</fullName>
            </value>
            <value>
                <fullName>Hold</fullName>
            </value>
            <value>
                <fullName>Not Eligible</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Withdrawn</fullName>
            </value>
            <value>
                <fullName>Auto Submitting</fullName>
            </value>
            <value>
                <fullName>Submission in Progress</fullName>
            </value>
            <value>
                <fullName>Referred</fullName>
            </value>
            <value>
                <fullName>Processing</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/LinkShorteningAPI__c/LinkShorteningAPI__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>LSA is responsible for setting endpoint values for WS to shorten application links or other links.</description>
    <label>LinkShorteningAPI</label>
</CustomObject>

unpackaged/main/default/objects/LinkShorteningAPI__c/fields/Authorization__c.field-meta.xml
<CustomField>
    <fullName>Authorization__c</fullName>
    <label>Authorization</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/LinkShorteningAPI__c/fields/Service_Endpoint__c.field-meta.xml
<CustomField>
    <fullName>Service_Endpoint__c</fullName>
    <label>Service Endpoint</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Lender_Account__c.field-meta.xml
<CustomField>
    <fullName>Lender_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lender Account selected for Oppty</description>
    <inlineHelpText>Select the Lender being used for this Opportunity</inlineHelpText>
    <label>Lender Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Lender Acct</value>
        </filterItems>
        <infoMessage>Select the Lender for this Opportunity</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities (Lender Account)</relationshipLabel>
    <relationshipName>Opportunities1</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Residual_Assigned_To__c.field-meta.xml
<CustomField>
    <fullName>Residual_Assigned_To__c</fullName>
    <description>This field will indicate if FPC or the Lender owns the rights to any residual payments at the end of the lease.</description>
    <inlineHelpText>This field will indicate if FPC or the Lender owns the rights to any residual payments at the end of the lease.</inlineHelpText>
    <label>Residual Assigned To</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>FPC</fullName>
            </value>
            <value>
                <fullName>Lender</fullName>
            </value>
            <value>
                <fullName>No Residual</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Closed - Won</fullName>
            </value>
            <value>
                <fullName>Closed - Lost</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/OnlineSalesCalculatorTest.cls
/**
 * Created by oporter on 6/21/2018.
 */

@IsTest
public with sharing class OnlineSalesCalculatorTest {

    public static testMethod void test1(){
        LinkShorteningAPI__c lsapi = new LinkShorteningAPI__c(Name = 'V2', Endpoint__c = 'test', Authorization__c= '123', Service_Endpoint__c = 'test');
        insert lsapi;
        //if (lenderName.contains('National Funding') && (recordTypeName == 'Broker WC Oppty' || recordTypeName == 'Working Capital Oppty')) {

        Id workingCapitalOpptId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Working Capital Oppty').getRecordTypeId();

        Id lenderRecordType = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Lender Acct').getRecordTypeId();
        Account lenderAccountPlatinum = new Account(name = 'National Funding - Platinum WC Funding' , RecordTypeId = lenderRecordType);
        insert lenderAccountPlatinum;

        Account a = new Account(name = 'test');
        insert a;

        Opportunity o = new Opportunity(RecordTypeId = workingCapitalOpptId, Lender_Account__c = lenderAccountPlatinum.Id, Residual_Assigned_To__c = 'FPC', AccountId = a.Id, StageName = 'Identified', CloseDate = Date.today());
        insert o;

        FPC_Funding_del__c fpc = new FPC_Funding_del__c(Lender_ID__c = lenderAccountPlatinum.Id, Lender_Position__c = 1, Status__c = 'Submitted', Opportunity__c = o.Id);
        insert fpc;

        FPC_Funding_del__c fpcUpdate = new FPC_Funding_del__c(Id = fpc.Id, Status__c = 'Approved');
        update fpcUpdate;

        SingleRequestMockClass fakeResponse = new SingleRequestMockClass(201,'Complete','[{"Id":"a0D2C000000Zcz7UAC","Token":"1XQhA-ofQwWJD3RtaV5-"}]',null);
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, fakeResponse);
        Test.stopTest();
    }
}