unpackaged/main/default/objects/Account/fields/Web_Id_NatFund__c.field-meta.xml
<CustomField>
    <fullName>Web_Id_NatFund__c</fullName>
    <description>This field will be the unique record identifier for leads that are created from nationalfunding.com. This field will be populated on create and subsequently when the customer completes steps of the application. For de-duping, the field in the new lead should overwrite the existing value.</description>
    <externalId>true</externalId>
    <inlineHelpText>This field should not be edited</inlineHelpText>
    <label>Web Id NatFund</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Encrypted_Email_String__c.field-meta.xml
<CustomField>
    <fullName>Encrypted_Email_String__c</fullName>
    <label>Encrypted Email String</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Encrypted_Email_String_Refresh_Date__c.field-meta.xml
<CustomField>
    <fullName>Encrypted_Email_String_Refresh_Date__c</fullName>
    <label>Encrypted Email String Refresh Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/DFP_Token__c/DFP_Token__c.object-meta.xml
<CustomObject>
    <description>Introduced as part of the Quick Bridge to National Funding migration project to support one customer/lead seeing multiple DFP experiences (QB and/or NF). Originally DFP tokens were shown under the Encrypted Email String field on Contact/Lead.</description>
    <label>DFP Token</label>
    <nameField>
        <label>DFP Token Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DFP Tokens</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/DFP_Token__c/fields/Brand_Experience__c.field-meta.xml
<CustomField>
    <fullName>Brand_Experience__c</fullName>
    <description>This field should control which DFP experience the guarantors see when loading the corresponding token (payload). This field is used in conjunction with Opportunity - Brand Experience field to present the correct opportunity for the payload being used.</description>
    <label>Brand Experience</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Originating_Brand</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/DFP_Token__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>DFP Tokens</relationshipLabel>
    <relationshipName>DFP_Tokens</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/DFP_Token__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>DFP Tokens</relationshipLabel>
    <relationshipName>DFP_Tokens</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/DFP_Token__c/fields/Token__c.field-meta.xml
<CustomField>
    <fullName>Token__c</fullName>
    <description>This field holds the token/payload for the corresponding brand experience. When loading this payload, DFP frontend will find the correct opportunity by matching the brand experience. This was previously the Encrypted Email String field on the Lead and Contact</description>
    <label>Token</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Lead/fields/Web_Id_NatFund__c.field-meta.xml
<CustomField>
    <fullName>Web_Id_NatFund__c</fullName>
    <description>This field will be the unique record identifier for leads that are created from nationalfunding.com.  This field will be populated on create and subsequently when the customer completes steps of the application. For de-duping, the field in the new lead should overwrite the existing value.</description>
    <externalId>true</externalId>
    <inlineHelpText>This field should not be edited.</inlineHelpText>
    <label>Web Id NatFund</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/globalValueSets/Originating_Brand.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>National Funding</fullName>
    </customValue>
    <customValue>
        <fullName>Quick Bridge</fullName>
    </customValue>
    <customValue>
        <fullName>National Funding XPRS</fullName>
    </customValue>
    <description>Introduced as part of the Quick Bridge to National Funding migration project to capture which brand the response originally came from. Inserted by LeadGen.</description>
    <masterLabel>Originating Brand</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/HelperClass.cls
public class HelperClass {
  public static boolean firstRun = true;

  public static void upsertDFPToken(String recordId, String brand, String token) {
    
    String contactId = recordId != null && recordId.startsWithIgnoreCase('003') ? recordId : null;
    String leadId = recordId != null && recordId.startsWithIgnoreCase('00Q') ? recordId : null;

    if(contactId != null) {
      //update the contact record's encrypted_email_string__c field first.
      //per client, it is ok for this field to be overwritten if the owner has two brands
      contact c = [SELECT Id, Account.Web_Id_NatFund__c, Encrypted_Email_String_Refresh_Date__c 
                    FROM Contact 
                    WHERE Id =: recordId];
      c.Encrypted_Email_String__c = token;
      c.Encrypted_Email_String_Refresh_Date__c = date.parse(system.today().format());
      update c;
      
      //update or create a DFP_Toekn__c record for the contact record
      List<DFP_Token__c> dfpContactTokens = [SELECT Token__c, Contact__c, Brand_Experience__c 
                                              FROM DFP_Token__c 
                                              WHERE Contact__c = :contactId AND Brand_Experience__c = :brand AND Token__c <> NULL];
      if(dfpContactTokens.size() > 0) {
        for(DFP_Token__c dfpToken : dfpContactTokens) {
          dfpToken.Token__c = token;
        }
        update dfpContactTokens;
      } else {
        DFP_Token__c dfpContactToken = new DFP_Token__c(
          Token__c = token,
          Brand_Experience__c = brand,
          Contact__c = contactId
        );
        insert dfpContactToken;
      }      
    }

    if(leadId != null) {
      //update the lead record's encrypted_email_string__c field first.
      //per client, it is ok for this field to be overwritten if the owner has two brands
      lead l = [SELECT Id, Web_Id_NatFund__c, Encrypted_Email_String_Refresh_Date__c 
                FROM Lead 
                WHERE Id =: leadId];
      l.Encrypted_Email_String__c = token;
      l.Encrypted_Email_String_Refresh_Date__c = date.parse(system.today().format());
      update l; 
      
      //update or create a DFP_Toekn__c record for the lead record
      List<DFP_Token__c> dfpLeadTokens = [SELECT Token__c, Lead__c, Brand_Experience__c 
                                              FROM DFP_Token__c 
                                              WHERE Lead__c = :leadId and Brand_Experience__c = :brand AND Token__c <> NULL];
      if(dfpLeadTokens.size() > 0) {
        for(DFP_Token__c dfpToken : dfpLeadTokens) {
          dfpToken.Token__c = token;
        }
        update dfpLeadTokens;
      } else {
        DFP_Token__c dfpLeadToken = new DFP_Token__c(
          Token__c = token,
          Brand_Experience__c = brand,
          Lead__c = leadId
        );
        insert dfpLeadToken;
      }      
    }
  }
}