unpackaged/main/default/objects/Accounting_Period__c/Accounting_Period__c.object-meta.xml
<CustomObject>
    <label>Accounting Period</label>
    <nameField>
        <displayFormat>AcctPeriod-{0000}</displayFormat>
        <label>Accounting Period Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Accounting Periods</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Accounting_Period__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <formula>DATE(VALUE(Year__c), VALUE(TEXT(Month__c)) ,1)</formula>
    <label>Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Accounting_Period__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Reopened</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/cmbls__GL_Transaction__c/cmbls__GL_Transaction__c.object-meta.xml
<CustomObject>
    <label>GL Transaction</label>
    <nameField>
        <label>GL Transaction Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GL Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/cmbls__GL_Transaction__c/fields/cmbls__Date__c.field-meta.xml
<CustomField>
    <fullName>cmbls__Date__c</fullName>
    <label>Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/cmbls__GL_Transaction__c/fields/Earliest_Post_Date__c.field-meta.xml
<CustomField>
    <fullName>Earliest_Post_Date__c</fullName>
    <inlineHelpText>Earliest available post date for the accounting period that has not been closed. Populated via automation at the time of GL Transaction creation by referencing the ‘Accounting Period’ records.</inlineHelpText>
    <label>Earliest Post Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/classes/GL_TransactionTriggerHandler.cls
/**
 * GL_TransactionTriggerHandler class
 * @author CloudMyBiz (r)
 * @date 11/8/2022
 * @description Follows the One Trigger Per Object design pattern, which allows for the control of execution order and recursion.
 * Ideally, business logic should not be included in this class. Trigger handlers are used to control recursion and order of execution and should delegate other work to service classes.
 * @group Trigger Handlers
 */
public inherited sharing class GL_TransactionTriggerHandler{
    
    public static void onBeforeInsertUpdate(cmbls__GL_Transaction__c[] records, Map<Id, cmbls__GL_Transaction__c> oldMap){
        if(Trigger.isInsert){
            List<Accounting_Period__c> closedPeriods = [SELECT Id, Date__c FROM Accounting_Period__c WHERE Status__c = 'Closed' ORDER BY Date__c DESC LIMIT 1];
            if(!closedPeriods.isEmpty()){
                Date earliestPostDate;
                Accounting_Period__c earliest = closedPeriods[0];
                earliestPostDate = earliest.Date__c.addMonths(1).toStartOfMonth();
                for(cmbls__GL_Transaction__c tr : records){
                    tr.Earliest_Post_Date__c = earliestPostDate;
                }
            }
        }
    }
    
    public static void onAfterInsertUpdate(cmbls__GL_Transaction__c[] records, Map<Id, cmbls__GL_Transaction__c> oldMap){
        if(Trigger.isInsert){
            List<Approval.ProcessSubmitRequest> requests = new List<Approval.ProcessSubmitRequest>();
            for(cmbls__GL_Transaction__c tr : records){
                if(tr.cmbls__Date__c < tr.Earliest_Post_Date__c){
                    Approval.ProcessSubmitRequest req1 = new Approval.ProcessSubmitRequest();
                    req1.setObjectId(tr.Id);
                    requests.add(req1);
                }
            }
            if(!requests.isEmpty()) Approval.process(requests,false);
        }
    }
}