unpackaged/main/default/objects/Accounting_Period__c/Accounting_Period__c.object-meta.xml
<CustomObject>
    <label>Accounting Period</label>
    <nameField>
        <displayFormat>AcctPeriod-{0000}</displayFormat>
        <label>Accounting Period Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Accounting Periods</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Accounting_Period__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <formula>DATE(VALUE(Year__c), VALUE(TEXT(Month__c)) ,1)</formula>
    <label>Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Accounting_Period__c/fields/Month__c.field-meta.xml
<CustomField>
    <fullName>Month__c</fullName>
    <label>Month</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>9</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
            <value>
                <fullName>11</fullName>
            </value>
            <value>
                <fullName>12</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Accounting_Period__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Reopened</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Accounting_Period__c/fields/Year__c.field-meta.xml
<CustomField>
    <fullName>Year__c</fullName>
    <label>Year</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/cmbls__GL_Transaction__c/cmbls__GL_Transaction__c.object-meta.xml
<CustomObject>
    <label>GL Transaction</label>
    <nameField>
        <label>GL Transaction Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GL Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/cmbls__GL_Transaction__c/fields/cmbls__Date__c.field-meta.xml
<CustomField>
    <fullName>cmbls__Date__c</fullName>
    <label>Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/cmbls__GL_Transaction__c/fields/Earliest_Post_Date__c.field-meta.xml
<CustomField>
    <fullName>Earliest_Post_Date__c</fullName>
    <inlineHelpText>Earliest available post date for the accounting period that has not been closed. Populated via automation at the time of GL Transaction creation by referencing the ‘Accounting Period’ records.</inlineHelpText>
    <label>Earliest Post Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/classes/GL_TransactionTriggerTest.cls
@IsTest
public with sharing class GL_TransactionTriggerTest {

    @TestSetup
    static void setupMethod(){
        insert new Accounting_Period__c(
            Month__c = '9',
            Year__c = '2022',
            Status__c = 'Closed'
        );
    }
    
    @IsTest
    public static void testTrigger() {
        cmbls__GL_Transaction__c trans = new cmbls__GL_Transaction__c(
            cmbls__Date__c = Date.today().addYears(-10)
        );
        Test.startTest();
        insert trans;
        Test.stopTest();
    
        trans = [SELECT Id, Earliest_Post_Date__c FROM cmbls__GL_Transaction__c WHERE Id = :trans.Id];
        Accounting_Period__c closedPeriods = [SELECT Id, Date__c FROM Accounting_Period__c WHERE Status__c = 'Closed' ORDER BY Date__c DESC LIMIT 1];
        System.assertEquals(closedPeriods.Date__c.addMonths(1).toStartOfMonth(), trans.Earliest_Post_Date__c);
    }
}