unpackaged/main/default/objects/Account/recordTypes/Lender.recordType-meta.xml
<RecordType>
    <fullName>Lender</fullName>
    <active>true</active>
    <label>Lender</label>
</RecordType>

unpackaged/main/default/objects/Case/fields/Lender_Account__c.field-meta.xml
<CustomField>
    <fullName>Lender_Account__c</fullName>
    <formula>Opportunity__r.Lender_Account__c</formula>
    <label>Lender Account</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Actual_Monthly_Payment__c.field-meta.xml
<CustomField>
    <fullName>Actual_Monthly_Payment__c</fullName>
    <description>Actual lease monthly payment.</description>
    <inlineHelpText>Type in the lessee's actual monthly payment.</inlineHelpText>
    <label>Actual Monthly Payment</label>
    <precision>17</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Actual_Term__c.field-meta.xml
<CustomField>
    <fullName>Actual_Term__c</fullName>
    <description>Actual term</description>
    <inlineHelpText>Type in the actual term of a Closed-Won opportunity.</inlineHelpText>
    <label>Actual Term</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Advanced_Payments_For_Actual__c.field-meta.xml
<CustomField>
    <fullName>Advanced_Payments_For_Actual__c</fullName>
    <description>Advanced_Payments_For_Actual</description>
    <inlineHelpText>IF LENDER.[Discount # Of Pmts] &gt; 0 THEN
 [Discount # Pmts] * [Monthly Pmt];
ELSE
 0;</inlineHelpText>
    <label>Advanced Payments</label>
    <precision>17</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Calc_Net_Proceeds_For_Actual__c.field-meta.xml
<CustomField>
    <fullName>Calc_Net_Proceeds_For_Actual__c</fullName>
    <description>Calc Net Proceeds</description>
    <inlineHelpText>[Calc Net Proceeds] = [Discount PV] – [Int Settlement] – [Lender Doc Fee] –[Fee 1 Amount] – [Fee 2 Amount]  – [Lost Margin] – [Equip Cost]</inlineHelpText>
    <label>Calc Net Proceeds</label>
    <precision>17</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Discount_PV_Overwrite__c.field-meta.xml
<CustomField>
    <fullName>Discount_PV_Overwrite__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If this field is checked, the operations user will overwrite the Discount PV and Discount PV calculation will be based on the manually entered data.</description>
    <inlineHelpText>If this field is checked, the operations user will overwrite the Discount PV and Discount PV calculation will be based on the manually entered data.</inlineHelpText>
    <label>Discount PV Overwrite</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Doc_Fee_Collected__c.field-meta.xml
<CustomField>
    <fullName>Doc_Fee_Collected__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Doc Fee Collected for actuals</description>
    <inlineHelpText>Doc Fee Collected for actuals</inlineHelpText>
    <label>Doc Fee Collected</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/FlagToClickCalculateActuals__c.field-meta.xml
<CustomField>
    <fullName>FlagToClickCalculateActuals__c</fullName>
    <defaultValue>false</defaultValue>
    <description>just a flag, please don't update manually.
trigger CalculateActualFromOpportunity will fire when this field value is true;
and the value of this field is set by code.</description>
    <inlineHelpText>just a flag, please don't update manually.
trigger CalculateActualFromOpportunity will fire when this field value is true;
and the value of this field is set by code.</inlineHelpText>
    <label>FlagToClickCalculateActuals</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Lender_Account__c.field-meta.xml
<CustomField>
    <fullName>Lender_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lender Account selected for Oppty</description>
    <inlineHelpText>Select the Lender being used for this Opportunity</inlineHelpText>
    <label>Lender Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Lender Acct</value>
        </filterItems>
        <infoMessage>Select the Lender for this Opportunity</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities (Lender Account)</relationshipLabel>
    <relationshipName>Opportunities1</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Num_Discounted_Pmts_For_Actual__c.field-meta.xml
<CustomField>
    <fullName>Num_Discounted_Pmts_For_Actual__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Num_Discounted_Pmts_For_Actual</description>
    <inlineHelpText>Num_Discounted_Pmts_For_Actual</inlineHelpText>
    <label>Num Discounted Pmts</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/classes/TestoppGMCalcUtil.cls
@isTest
public class TestoppGMCalcUtil {

    // Store record type ID for lender account
    private static Id lenderRecordTypeId;

    // Store Opportunity Account and Lender Account Ids for reuse
    private static Id oppAccountId;
    private static Id lenderAccountId;

    // Store all test opportunities
    private static List<Opportunity> allTestOpps;

    // Common test data setup for all test methods
    @TestSetup
    static void setupTestData() {
        // Get RecordTypeId for 'Lender Acct'
        lenderRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Lender Acct').getRecordTypeId();

        // Create and insert a Lender Account
        Account lenderAccount = new Account(
            Name = 'Test Lender Account',
            Type = 'Lender - MCA',
            RecordTypeId = lenderRecordTypeId
        );
        insert lenderAccount;
        lenderAccountId = lenderAccount.Id;

        // Create and insert a generic Account for Opportunity
        Account oppAccount = TestLibrary.createTestAccount();
        oppAccountId = oppAccount.Id;

        // Prepare list of Opportunities with varying conditions
        allTestOpps = new List<Opportunity>();

        // Opp 1: Without Lender_Account__c and Flag = false (initial setup for error test)
        allTestOpps.add(new Opportunity(
            Name = 'Test Opp 2 - No Lender Account',
            StageName = 'Prospecting',
            CloseDate = Date.today().addDays(30),
            FlagToClickCalculateActuals__c = false,
            AccountId = oppAccount.Id
        ));

        // Opp 2: With Lender_Account__c and Flag = true (valid scenario for calculation)
        allTestOpps.add(new Opportunity(
            Name = 'Test Opp 3 - Valid for Calculation',
            StageName = 'Prospecting',
            CloseDate = Date.today().addDays(30),
            FlagToClickCalculateActuals__c = true,
            Lender_Account__c = lenderAccount.Id,
            AccountId = oppAccount.Id
        ));

        // Opp 3: Another valid opportunity for calculation
        allTestOpps.add(new Opportunity(
            Name = 'Test Opp 4 - Valid for Calculation',
            StageName = 'Prospecting',
            CloseDate = Date.today().addDays(30),
            FlagToClickCalculateActuals__c = true,
            Lender_Account__c = lenderAccount.Id,
            AccountId = oppAccount.Id
        ));

        // Insert all test opportunities
        insert allTestOpps;
    }

    // Test case: Ensure DML fails when Flag is set but Lender_Account__c is missing
    @isTest
    static void testNoLenderError() {
        // Get Opportunity without lender
        Opportunity oppWithoutLender = [
            SELECT Id, StageName, FlagToClickCalculateActuals__c
            FROM Opportunity
            WHERE Lender_Account__c = NULL
            LIMIT 1
        ];

        // Simulate update triggering flag and stage change
        oppWithoutLender.StageName = 'Qualification';
        oppWithoutLender.FlagToClickCalculateActuals__c = true;

        Test.startTest();
        try {
            update oppWithoutLender;
            System.assert(false, 'Expected error not thrown');
        } catch (DmlException e) {
            // Validate error message contains required field reference
            System.assert(e.getMessage().contains('Lender_Account__c'));
        }
        Test.stopTest();
    }

    // Test case: Ensure valid Opportunity updates without error
    @isTest
    static void testValidUpdate() {
        // Get one valid Opportunity for update
        Opportunity validOpp = [
            SELECT Id, StageName
            FROM Opportunity
            WHERE FlagToClickCalculateActuals__c = true
            AND Lender_Account__c != NULL
            LIMIT 1
        ];

        // Change StageName to simulate progression
        validOpp.StageName = 'Proposal';

        Test.startTest();
        update validOpp;
        Test.stopTest();

        // Verify update succeeded
        Opportunity updatedOpp = [SELECT StageName FROM Opportunity WHERE Id = :validOpp.Id];
        System.assertEquals('Proposal', updatedOpp.StageName);
    }

    // Test case: Directly call utility class methods with updated Opportunity
    @isTest
    static void Test() {
        // Static method invocation: test getJavaPVa formula logic
        oppGMCalcUtil.getJavaPVa(1.5, 2.5, 3);

        // Prepare opportunity with all calculation fields populated
        Opportunity opp = [
            SELECT Id, Num_Discounted_Pmts_For_Actual__c, Actual_Monthly_Payment__c, Actual_Term__c,
                   Calc_Net_Proceeds_For_Actual__c, Doc_Fee_Collected__c, Advanced_Payments_For_Actual__c,
                   Lender_Account__c
            FROM Opportunity
            WHERE Lender_Account__c != NULL
            AND FlagToClickCalculateActuals__c = true
            LIMIT 1
        ];

        // Set fields required by constructor logic
        opp.Num_Discounted_Pmts_For_Actual__c = 1.5;
        opp.Actual_Monthly_Payment__c = 2.5;
        opp.Actual_Term__c = 3.5;
        opp.Calc_Net_Proceeds_For_Actual__c = 1.5;
        opp.Doc_Fee_Collected__c = 2.5;
        opp.Advanced_Payments_For_Actual__c = 3.5;
        opp.Discount_PV_Overwrite__c = false;

        update opp;

        // Instantiate oppGMCalcUtil with prepared opportunity
        Test.startTest();
        oppGMCalcUtil oppGM = new oppGMCalcUtil(new List<Opportunity>{opp});
        Test.stopTest();
    }
}