unpackaged/main/default/objects/Account/recordTypes/Lender_Acct.recordType-meta.xml
<RecordType>
    <fullName>Lender_Acct</fullName>
    <active>true</active>
    <description>FPC Lender Account Record</description>
    <label>Lender Acct</label>
</RecordType>

unpackaged/main/default/objects/cmbls__Fund__c/cmbls__Fund__c.object-meta.xml
<CustomObject>
    <label>Fund</label>
    <nameField>
        <label>Fund Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Funds</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/cmbls__Loan_Servicing_Settings__c/cmbls__Loan_Servicing_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Loan Servicing Settings</label>
</CustomObject>

unpackaged/main/default/objects/cmbls__Loan_Servicing_Settings__c/fields/Enable_Automatic_Transfers__c.field-meta.xml
<CustomField>
    <fullName>Enable_Automatic_Transfers__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Quick Bridge loans will be automatically transferred to National Funding.</description>
    <inlineHelpText>Quick Bridge loans will be automatically transferred to National Funding.</inlineHelpText>
    <label>Enable Automatic Transfers</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/cmbls__Loan_Servicing_Settings__c/fields/National_Funding_Fund_Id__c.field-meta.xml
<CustomField>
    <fullName>National_Funding_Fund_Id__c</fullName>
    <inlineHelpText>National Funding’s ‘Fund’ record to transfer loans</inlineHelpText>
    <label>National Funding Fund Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/cmbls__Repayment__c/cmbls__Repayment__c.object-meta.xml
<CustomObject>
    <label>Repayment</label>
    <nameField>
        <displayFormat>RPMT-{0000000}</displayFormat>
        <label>Repayment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Repayments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/cmbls__Repayment__c/fields/Lender_Account__c.field-meta.xml
<CustomField>
    <fullName>Lender_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lender Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Repayments (Lender Account)</relationshipLabel>
    <relationshipName>Repayments</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/cmbls__Repayment__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Repayments (Opportunity)</relationshipLabel>
    <relationshipName>Repayments</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Lender_Account__c.field-meta.xml
<CustomField>
    <fullName>Lender_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lender Account selected for Oppty</description>
    <inlineHelpText>Select the Lender being used for this Opportunity</inlineHelpText>
    <label>Lender Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Lender Acct</value>
        </filterItems>
        <infoMessage>Select the Lender for this Opportunity</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities (Lender Account)</relationshipLabel>
    <relationshipName>Opportunities1</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/TransferQueuedEventBatchTest.cls
/**
 * TransferQueuedEventBatchTest class
 * @author CloudMyBiz (r)
 * @date 9/7/2022
 * @description
 * @group 
 */

@IsTest
private class TransferQueuedEventBatchTest{
    
    @TestSetup static void setupMethod(){
        Test.startTest();
        Account acc = TestDataFactory.createAccount();
        Account lenderAccount = TestDataFactory.createAccount();
        lenderAccount.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Lender_Acct').getRecordTypeId();
        lenderAccount.Name = RepaymentUtils.QUICK_BRIDGE_FUND_RECORD_NAME;
        insert new Account[]{acc, lenderAccount};
    
        Opportunity opp = TestDataFactory.createOpportunity(acc.Id);
        opp.Lender_Account__c = lenderAccount.Id;
        insert opp;

        cmbls__Repayment__c repayment = TestDataFactory.createRepayment(acc.Id);
        repayment.Opportunity__c = opp.Id;
        insert repayment;
    
        cmbls__Banking_Information__c bankingInformation = TestDataFactory.createBankingInformation(acc.Id);
        insert bankingInformation;
    
        cmbls__Fund__c[] fundRecords = new cmbls__Fund__c[]{
            TestDataFactory.createFund(RepaymentUtils.QUICK_BRIDGE_FUND_RECORD_NAME, bankingInformation),
            TestDataFactory.createFund('National Funding - Fund', bankingInformation)
        };
        insert fundRecords;
    
        cmbls__Loan_Servicing_Settings__c settings = cmbls__Loan_Servicing_Settings__c.getInstance();
        settings.National_Funding_Fund_Id__c = fundRecords[1].Id;
        settings.Enable_Automatic_Transfers__c = true;
        upsert settings;
    
        Test.stopTest();
    }
    
    @IsTest
    static void executeBatch(){
    
    }
    
    @IsTest
    static void executeSchedule(){
        Test.startTest();
        System.schedule('TransferQueuedEventBatch Test', '0 0 23 * * ?', new TransferQueuedEventBatch());
        Test.stopTest();
    }
}