unpackaged/main/default/objects/Account/recordTypes/Lender_Acct.recordType-meta.xml
<RecordType>
    <fullName>Lender_Acct</fullName>
    <active>true</active>
    <description>FPC Lender Account Record</description>
    <label>Lender Acct</label>
</RecordType>

unpackaged/main/default/objects/Additional_GL_Transaction__c/Additional_GL_Transaction__c.object-meta.xml
<CustomObject>
    <label>Additional GL Transaction</label>
    <nameField>
        <displayFormat>AGLT-{0000}</displayFormat>
        <label>Additional GL Transactions Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Additional GL Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Additional_GL_Transaction__c/fields/Intercompany_Transaction__c.field-meta.xml
<CustomField>
    <fullName>Intercompany_Transaction__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Intercompany Transaction</label>
    <referenceTo>cmbls__Intercompany_Transaction__c</referenceTo>
    <relationshipLabel>Additional GL Transactions</relationshipLabel>
    <relationshipName>Additional_GL_Transactions</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Additional_GL_Transaction__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Paid Intercompany Transaction</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/cmbls__Fund__c/cmbls__Fund__c.object-meta.xml
<CustomObject>
    <label>Fund</label>
    <nameField>
        <label>Fund Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Funds</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/cmbls__Fund__c/fields/cmbls__Default_Debit_ACH_Processor__c.field-meta.xml
<CustomField>
    <fullName>cmbls__Default_Debit_ACH_Processor__c</fullName>
    <inlineHelpText>When transferring Loans to this Fund, this ACH processor will be the default in the loan Transfer UI for each Repayment being transferred.</inlineHelpText>
    <label>Default Debit ACH Processor</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Wells Fargo - NF Collections</fullName>
            </value>
            <value>
                <fullName>Wells Fargo - NFAS2 Collections</fullName>
            </value>
            <value>
                <fullName>Wells Fargo - NF Funding</fullName>
            </value>
            <value>
                <fullName>Wells Fargo - QBF Funding</fullName>
            </value>
            <value>
                <fullName>Wells Fargo - NFSPV1 Collections</fullName>
            </value>
            <value>
                <fullName>Wells Fargo - NFSPV2 Collections</fullName>
            </value>
            <value>
                <fullName>Wells Fargo - NFAS3 Collections</fullName>
            </value>
            <value>
                <fullName>ACH Processing Co</fullName>
                <isActive>false</isActive>
                <label>ACH Processing Co</label>
            </value>
            <value>
                <fullName>ACH.com</fullName>
                <isActive>false</isActive>
                <label>ACH.com</label>
            </value>
            <value>
                <fullName>ACHWorks</fullName>
                <isActive>false</isActive>
                <label>ACHWorks</label>
            </value>
            <value>
                <fullName>ACHeck21</fullName>
                <isActive>false</isActive>
                <label>ACHeck21</label>
            </value>
            <value>
                <fullName>Forte</fullName>
                <isActive>false</isActive>
                <label>Forte</label>
            </value>
            <value>
                <fullName>PaySafe</fullName>
                <isActive>false</isActive>
                <label>PaySafe</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/cmbls__Intercompany_Transaction__c/cmbls__Intercompany_Transaction__c.object-meta.xml
<CustomObject>
    <label>Intercompany Transaction</label>
    <nameField>
        <displayFormat>ICT-{0000000}</displayFormat>
        <label>Intercompany Transaction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Intercompany Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/cmbls__Loan_Servicing_Settings__c/cmbls__Loan_Servicing_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Loan Servicing Settings</label>
</CustomObject>

unpackaged/main/default/objects/cmbls__Loan_Servicing_Settings__c/fields/Enable_Automatic_Transfers__c.field-meta.xml
<CustomField>
    <fullName>Enable_Automatic_Transfers__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Quick Bridge loans will be automatically transferred to National Funding.</description>
    <inlineHelpText>Quick Bridge loans will be automatically transferred to National Funding.</inlineHelpText>
    <label>Enable Automatic Transfers</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/cmbls__Loan_Servicing_Settings__c/fields/National_Funding_Fund_Id__c.field-meta.xml
<CustomField>
    <fullName>National_Funding_Fund_Id__c</fullName>
    <inlineHelpText>National Funding’s ‘Fund’ record to transfer loans</inlineHelpText>
    <label>National Funding Fund Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/cmbls__Loan_Servicing_Triggers__c/cmbls__Loan_Servicing_Triggers__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Loan Servicing Triggers</label>
</CustomObject>

unpackaged/main/default/objects/cmbls__Loan_Servicing_Triggers__c/fields/Disable_Additional_GL_Trans_Trigger__c.field-meta.xml
<CustomField>
    <fullName>Disable_Additional_GL_Trans_Trigger__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Disable Additional GL Transactions creation trigger, the new Additional GL Transaction records will not be created when an Intercompany Transaction status is updated to "Paid"</inlineHelpText>
    <label>Disable Additional GL Trans. Trigger</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/cmbls__Loan_Transfer__c/cmbls__Loan_Transfer__c.object-meta.xml
<CustomObject>
    <label>Loan Transfer</label>
    <nameField>
        <label>Loan Transfer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Loans Transfer</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/cmbls__Loan_Transfer__c/fields/cmbls__Loan_Transfer_Summary__c.field-meta.xml
<CustomField>
    <fullName>cmbls__Loan_Transfer_Summary__c</fullName>
    <label>Loan Transfer Summary</label>
    <referenceTo>cmbls__Loan_Transfer_Summary__c</referenceTo>
    <relationshipLabel>Loan Transfers</relationshipLabel>
    <relationshipName>Loan_Transfers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/cmbls__Loan_Transfer__c/fields/cmbls__Repayment__c.field-meta.xml
<CustomField>
    <fullName>cmbls__Repayment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Repayment</label>
    <referenceTo>cmbls__Repayment__c</referenceTo>
    <relationshipLabel>Loan Transfers</relationshipLabel>
    <relationshipName>Loan_Transfers</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/cmbls__Loan_Transfer_Summary__c/cmbls__Loan_Transfer_Summary__c.object-meta.xml
<CustomObject>
    <label>Loan Transfer Summary</label>
    <nameField>
        <displayFormat>LT Summary-{0000}</displayFormat>
        <label>Loan Transfer Summary Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Loan Transfer Summaries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/cmbls__Queued_Event__c/cmbls__Queued_Event__c.object-meta.xml
<CustomObject>
    <label>Queued Event</label>
    <nameField>
        <displayFormat>QE-{0000}</displayFormat>
        <label>Queued Event Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Queued Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/cmbls__Repayment__c/cmbls__Repayment__c.object-meta.xml
<CustomObject>
    <label>Repayment</label>
    <nameField>
        <displayFormat>RPMT-{0000000}</displayFormat>
        <label>Repayment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Repayments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/cmbls__Repayment__c/fields/cmbls__ACH_Processor__c.field-meta.xml
<CustomField>
    <fullName>cmbls__ACH_Processor__c</fullName>
    <description>The name of the processor being used</description>
    <inlineHelpText>The name of the processor being used</inlineHelpText>
    <label>ACH Processor</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Wells Fargo - NF Collections</fullName>
            </value>
            <value>
                <fullName>Wells Fargo - NFAS2 Collections</fullName>
            </value>
            <value>
                <fullName>Wells Fargo - NFSPV1 Collections</fullName>
            </value>
            <value>
                <fullName>Wells Fargo - NFSPV2 Collections</fullName>
            </value>
            <value>
                <fullName>Wells Fargo - NFAS3 Collections</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/cmbls__Repayment__c/fields/cmbls__Loan_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>cmbls__Loan_Start_Date__c</fullName>
    <label>Loan Start Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/cmbls__Repayment__c/fields/cmbls__Primary_Fund__c.field-meta.xml
<CustomField>
    <fullName>cmbls__Primary_Fund__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Primary Fund</label>
    <referenceTo>cmbls__Fund__c</referenceTo>
    <relationshipLabel>Repayments</relationshipLabel>
    <relationshipName>Repayments</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/cmbls__Repayment__c/fields/cmbls__Status__c.field-meta.xml
<CustomField>
    <fullName>cmbls__Status__c</fullName>
    <description>Active, pause, complete, and new</description>
    <inlineHelpText>Active, pause, complete, and new</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Temporary Pause</fullName>
            </value>
            <value>
                <fullName>Pause</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Write Off</fullName>
            </value>
            <value>
                <fullName>Recovery</fullName>
            </value>
            <value>
                <fullName>Unwind</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/cmbls__Repayment__c/fields/Lender_Account__c.field-meta.xml
<CustomField>
    <fullName>Lender_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lender Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Repayments (Lender Account)</relationshipLabel>
    <relationshipName>Repayments</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/cmbls__Repayment__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Repayments (Opportunity)</relationshipLabel>
    <relationshipName>Repayments</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Lender_Account__c.field-meta.xml
<CustomField>
    <fullName>Lender_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lender Account selected for Oppty</description>
    <inlineHelpText>Select the Lender being used for this Opportunity</inlineHelpText>
    <label>Lender Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Lender Acct</value>
        </filterItems>
        <infoMessage>Select the Lender for this Opportunity</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities (Lender Account)</relationshipLabel>
    <relationshipName>Opportunities1</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/IntercompanyTransactionTriggerTest.cls
/**
 * IntercompanyTransactionTriggerTest class
 * @author CloudMyBiz (r)
 * @date 2/13/2023
 */

@IsTest
private class IntercompanyTransactionTriggerTest{
    
    @TestSetup static void setupMethod(){
        Test.startTest();
        Account acc = TestDataFactory.createAccount();
        Account lenderAccount = TestDataFactory.createAccount();
        lenderAccount.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Lender_Acct').getRecordTypeId();
        lenderAccount.Name = RepaymentUtils.QUICK_BRIDGE_FUND_RECORD_NAME;
        insert new Account[]{acc, lenderAccount};
    
        Opportunity opp = TestDataFactory.createOpportunity(acc.Id);
        opp.Lender_Account__c = lenderAccount.Id;
        insert opp;
    
        cmbls__Banking_Information__c bankingInformation = TestDataFactory.createBankingInformation(acc.Id);
        insert bankingInformation;
    
        cmbls__Fund__c[] fundRecords = new cmbls__Fund__c[]{
            TestDataFactory.createFund('Quick Bridge', bankingInformation),
            TestDataFactory.createFund('National Funding - Fund', bankingInformation)
        };
        fundRecords[0].cmbls__Default_Debit_ACH_Processor__c = 'Wells Fargo - NF Collections';
        fundRecords[1].cmbls__Default_Debit_ACH_Processor__c = 'Wells Fargo - NF Collections';
        insert fundRecords;
    
        cmbls__Repayment__c repayment = TestDataFactory.createRepayment(acc.Id);
        repayment.Opportunity__c = opp.Id;
        repayment.cmbls__Primary_Fund__c = fundRecords[0].Id;
        repayment.cmbls__ACH_Processor__c = 'Wells Fargo - NF Collections';
        repayment.cmbls__Loan_Start_Date__c = System.today().addDays(-1);
        repayment.Migrated__c = false;
        insert repayment;

        System.debug(RepaymentSelector.getQuickBridgeFundedRecords(new Set<Id>{repayment.Id}));


        cmbls__Loan_Servicing_Settings__c settings = cmbls__Loan_Servicing_Settings__c.getInstance();
        settings.National_Funding_Fund_Id__c = fundRecords[1].Id;
        settings.Enable_Automatic_Transfers__c = true;
        upsert settings;
    
        cmbls__Queued_Event__c queuedEvent = new cmbls__Queued_Event__c(
            cmbls__Record_Id__c = repayment.Id,
            cmbls__Type__c = TransferQueuedEventBatch.TRANSFER_RECORDS_CREATION
        );
        insert queuedEvent;
    
        RepaymentService.createTransferRecords(new cmbls__Queued_Event__c[]{queuedEvent});
        
        Test.stopTest();
    }
    
    @IsTest
    static void updateDisableSetting(){
        cmbls__Loan_Servicing_Triggers__c settings = cmbls__Loan_Servicing_Triggers__c.getInstance();
        settings.Disable_Additional_GL_Trans_Trigger__c = true;
        upsert settings;
        
        cmbls__Repayment__c repayment = [SELECT Id FROM cmbls__Repayment__c];
        cmbls__Intercompany_Transaction__c intercompanyTransaction = getIntercompanyTransaction(repayment.Id);
        
        Test.startTest();
        intercompanyTransaction.cmbls__Status__c = IntercompanyTransactionHandler.PAID_STATUS;
        update intercompanyTransaction;
        Test.stopTest();
        
        System.assertEquals(0, [SELECT COUNT() FROM Additional_GL_Transaction__c]);
    }
    @IsTest
    static void updateExistingRecords(){
        cmbls__Repayment__c repayment = [SELECT Id FROM cmbls__Repayment__c];
        cmbls__Intercompany_Transaction__c intercompanyTransaction = getIntercompanyTransaction(repayment.Id);
        Additional_GL_Transaction__c additionalGLTransaction = new Additional_GL_Transaction__c(
            Intercompany_Transaction__c = intercompanyTransaction.Id,
            Type__c = IntercompanyTransactionHandler.PAID_TYPE
        );
        insert additionalGLTransaction;
    
        Test.startTest();
        intercompanyTransaction.cmbls__Status__c = IntercompanyTransactionHandler.PAID_STATUS;
        update intercompanyTransaction;
        Test.stopTest();
    
        System.assertEquals(1, [SELECT COUNT() FROM Additional_GL_Transaction__c WHERE Intercompany_Transaction__c = :intercompanyTransaction.Id AND Type__c = :IntercompanyTransactionHandler.PAID_TYPE]);
    }
    
    @IsTest
    static void updateSuccessful(){
        cmbls__Repayment__c repayment = [SELECT Id FROM cmbls__Repayment__c];
        cmbls__Intercompany_Transaction__c intercompanyTransaction = getIntercompanyTransaction(repayment.Id);
    
        Test.startTest();
        intercompanyTransaction.cmbls__Status__c = IntercompanyTransactionHandler.PAID_STATUS;
        update intercompanyTransaction;
        Test.stopTest();
    
        System.assertEquals(1, [SELECT COUNT() FROM Additional_GL_Transaction__c WHERE Intercompany_Transaction__c = :intercompanyTransaction.Id AND Type__c = :IntercompanyTransactionHandler.PAID_TYPE]);
    }
    
    @IsTest
    static void updateStatusNotIncluded(){
        cmbls__Repayment__c repayment = [SELECT Id FROM cmbls__Repayment__c];
        cmbls__Intercompany_Transaction__c intercompanyTransaction = getIntercompanyTransaction(repayment.Id);
    
        Test.startTest();
        intercompanyTransaction.cmbls__Status__c = 'Due';
        update intercompanyTransaction;
        Test.stopTest();
    
        System.assertEquals(0, [SELECT COUNT() FROM Additional_GL_Transaction__c]);
    }
    
    @IsTest
    static void insertTrigger(){
        cmbls__Repayment__c repayment = [SELECT Id FROM cmbls__Repayment__c];
        cmbls__Loan_Transfer__c loanTransfer = [SELECT Id, cmbls__Loan_Transfer_Summary__c FROM cmbls__Loan_Transfer__c WHERE cmbls__Repayment__c = :repayment.Id];
        cmbls__Intercompany_Transaction__c intercompanyTransaction = new cmbls__Intercompany_Transaction__c(
            cmbls__Loan_Transfer_Summary__c = loanTransfer.cmbls__Loan_Transfer_Summary__c,
            cmbls__Status__c = IntercompanyTransactionHandler.PAID_STATUS
        );
    
        Test.startTest();
        insert intercompanyTransaction;
        Test.stopTest();
    
        System.assertEquals(0, [SELECT COUNT() FROM Additional_GL_Transaction__c]);
    }
    
    private static cmbls__Intercompany_Transaction__c getIntercompanyTransaction(Id repaymentId){
        cmbls__Loan_Transfer__c loanTransfer = [SELECT Id, cmbls__Loan_Transfer_Summary__c FROM cmbls__Loan_Transfer__c WHERE cmbls__Repayment__c = :repaymentId];
        return  [SELECT Id, cmbls__Status__c FROM cmbls__Intercompany_Transaction__c WHERE cmbls__Loan_Transfer_Summary__c = :loanTransfer.cmbls__Loan_Transfer_Summary__c];
    }
}