unpackaged/main/default/objects/Account/recordTypes/Lender.recordType-meta.xml
<RecordType>
    <fullName>Lender</fullName>
    <active>true</active>
    <label>Lender</label>
</RecordType>

unpackaged/main/default/objects/Contact/fields/Isprimary__c.field-meta.xml
<CustomField>
    <fullName>Isprimary__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Primary Contact</description>
    <inlineHelpText>Check box if contact is designated as primary .</inlineHelpText>
    <label>Isprimary</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Credit_Review__c/Credit_Review__c.object-meta.xml
<CustomObject>
    <label>Credit Review</label>
    <nameField>
        <displayFormat>CR-{00000000}</displayFormat>
        <label>Credit Review ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Credit Reviews</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

unpackaged/main/default/objects/LinkShorteningAPI__c/LinkShorteningAPI__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>LSA is responsible for setting endpoint values for WS to shorten application links or other links.</description>
    <label>LinkShorteningAPI</label>
</CustomObject>

unpackaged/main/default/objects/LinkShorteningAPI__c/fields/Authorization__c.field-meta.xml
<CustomField>
    <fullName>Authorization__c</fullName>
    <label>Authorization</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/LinkShorteningAPI__c/fields/Service_Endpoint__c.field-meta.xml
<CustomField>
    <fullName>Service_Endpoint__c</fullName>
    <label>Service Endpoint</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/FACILITY_OWNED_LEASED__c.field-meta.xml
<CustomField>
    <fullName>FACILITY_OWNED_LEASED__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Facility Rent/Own Status.</description>
    <inlineHelpText>Check box if merchant owns facility business is located in.</inlineHelpText>
    <label>Facility Owned or Leased</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/classes/AutomatedCreditStartOppTest.cls
/**
 * Created by oporter on 12/22/2017.
 */
@isTest
public with sharing class AutomatedCreditStartOppTest {

    @TestSetup
    static void makeData(){
        LinkShorteningAPI__c mcs = new LinkShorteningAPI__c(Name = 'V2', Endpoint__c = 'test', Service_Endpoint__c = 'test', Authorization__c = 'test');
        insert mcs;
    }

    @isTest
    public static void insertOpp() {
        Test.startTest();
        Id lenderRecordType = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Lender Acct').getRecordTypeId();
        List<Credit_Review__c> oldList  = new List<Credit_Review__c>([SELECT Id FROM Credit_Review__c]);
        Account lenderAccountPlatinum = new Account(name = 'National Funding - Platinum WC Funding' , RecordTypeId = lenderRecordType);
        insert lenderAccountPlatinum;
        Opportunity o = new Opportunity(Account = lenderAccountPlatinum, StageName = 'Statements In - MCA', Name = 'Test Opp 1', CloseDate = Date.today()); 
        insert o;
        List<Credit_Review__c> newList = new List<Credit_Review__c>([SELECT Id FROM Credit_Review__c]);
        Test.stopTest();
        //assert that the class was called
        System.assertNotEquals(oldList.size(), newList.size());

    }

    @isTest
    public static void updateOpp() {
        Test.startTest();
        Id lenderRecordType = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Lender Acct').getRecordTypeId();
        List<Credit_Review__c> oldList = new List<Credit_Review__c>([SELECT Id FROM Credit_Review__c]);
        Account lenderAccountPlatinum = new Account(name = 'National Funding - Platinum WC Funding' , RecordTypeId = lenderRecordType);
        insert lenderAccountPlatinum;
        Contact c = new Contact(LastName = 'Test', Account = lenderAccountPlatinum, Isprimary__c = true);
        insert c;
        Opportunity o = new Opportunity(StageName = 'Identified', Account = lenderAccountPlatinum, FACILITY_OWNED_LEASED__c = TRUE, Name = 'Test Opp 2', CloseDate = Date.today());
        insert o;
        Opportunity o2 = new Opportunity(Id = o.Id, StageName = 'Statements In - MCA');
        update o;
        List<Credit_Review__c> newList  = new List<Credit_Review__c>([SELECT Id FROM Credit_Review__c]);
        Test.stopTest();
        //assert that the class was called
        System.assertEquals(oldList.size(), newList.size());
    }
}