unpackaged/main/default/objects/Account/recordTypes/Lender_Acct.recordType-meta.xml
<RecordType>
    <fullName>Lender_Acct</fullName>
    <active>true</active>
    <description>FPC Lender Account Record</description>
    <label>Lender Acct</label>
</RecordType>

unpackaged/main/default/objects/cmbls__Fund__c/cmbls__Fund__c.object-meta.xml
<CustomObject>
    <label>Fund</label>
    <nameField>
        <label>Fund Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Funds</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/cmbls__Fund__c/fields/cmbls__Default_Debit_ACH_Processor__c.field-meta.xml
<CustomField>
    <fullName>cmbls__Default_Debit_ACH_Processor__c</fullName>
    <inlineHelpText>When transferring Loans to this Fund, this ACH processor will be the default in the loan Transfer UI for each Repayment being transferred.</inlineHelpText>
    <label>Default Debit ACH Processor</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Wells Fargo - NF Collections</fullName>
            </value>
            <value>
                <fullName>Wells Fargo - NFAS2 Collections</fullName>
            </value>
            <value>
                <fullName>Wells Fargo - NF Funding</fullName>
            </value>
            <value>
                <fullName>Wells Fargo - QBF Funding</fullName>
            </value>
            <value>
                <fullName>Wells Fargo - NFSPV1 Collections</fullName>
            </value>
            <value>
                <fullName>Wells Fargo - NFSPV2 Collections</fullName>
            </value>
            <value>
                <fullName>Wells Fargo - NFAS3 Collections</fullName>
            </value>
            <value>
                <fullName>ACH Processing Co</fullName>
                <isActive>false</isActive>
                <label>ACH Processing Co</label>
            </value>
            <value>
                <fullName>ACH.com</fullName>
                <isActive>false</isActive>
                <label>ACH.com</label>
            </value>
            <value>
                <fullName>ACHWorks</fullName>
                <isActive>false</isActive>
                <label>ACHWorks</label>
            </value>
            <value>
                <fullName>ACHeck21</fullName>
                <isActive>false</isActive>
                <label>ACHeck21</label>
            </value>
            <value>
                <fullName>Forte</fullName>
                <isActive>false</isActive>
                <label>Forte</label>
            </value>
            <value>
                <fullName>PaySafe</fullName>
                <isActive>false</isActive>
                <label>PaySafe</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/cmbls__Repayment__c/cmbls__Repayment__c.object-meta.xml
<CustomObject>
    <label>Repayment</label>
    <nameField>
        <displayFormat>RPMT-{0000000}</displayFormat>
        <label>Repayment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Repayments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/cmbls__Repayment__c/fields/cmbls__ACH_Processor__c.field-meta.xml
<CustomField>
    <fullName>cmbls__ACH_Processor__c</fullName>
    <description>The name of the processor being used</description>
    <inlineHelpText>The name of the processor being used</inlineHelpText>
    <label>ACH Processor</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Wells Fargo - NF Collections</fullName>
            </value>
            <value>
                <fullName>Wells Fargo - NFAS2 Collections</fullName>
            </value>
            <value>
                <fullName>Wells Fargo - NFSPV1 Collections</fullName>
            </value>
            <value>
                <fullName>Wells Fargo - NFSPV2 Collections</fullName>
            </value>
            <value>
                <fullName>Wells Fargo - NFAS3 Collections</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/cmbls__Repayment__c/fields/cmbls__Bank_Account_Number__c.field-meta.xml
<CustomField>
    <fullName>cmbls__Bank_Account_Number__c</fullName>
    <label>Bank Account Number</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/cmbls__Repayment__c/fields/cmbls__Bank_Routing_Number__c.field-meta.xml
<CustomField>
    <fullName>cmbls__Bank_Routing_Number__c</fullName>
    <label>Bank Routing Number</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/cmbls__Repayment__c/fields/cmbls__Funded_Date__c.field-meta.xml
<CustomField>
    <fullName>cmbls__Funded_Date__c</fullName>
    <inlineHelpText>This will be used to indicate the funded date for the original deal</inlineHelpText>
    <label>Funded Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/cmbls__Repayment__c/fields/cmbls__Loan_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>cmbls__Loan_Start_Date__c</fullName>
    <label>Loan Start Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/cmbls__Repayment__c/fields/cmbls__Primary_Fund__c.field-meta.xml
<CustomField>
    <fullName>cmbls__Primary_Fund__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Primary Fund</label>
    <referenceTo>cmbls__Fund__c</referenceTo>
    <relationshipLabel>Repayments</relationshipLabel>
    <relationshipName>Repayments</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/cmbls__Repayment__c/fields/Lender_Account__c.field-meta.xml
<CustomField>
    <fullName>Lender_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lender Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Repayments (Lender Account)</relationshipLabel>
    <relationshipName>Repayments</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/cmbls__Repayment__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Repayments (Opportunity)</relationshipLabel>
    <relationshipName>Repayments</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/cmbls__Repayment_Schedule__c/cmbls__Repayment_Schedule__c.object-meta.xml
<CustomObject>
    <label>Repayment Schedule</label>
    <nameField>
        <displayFormat>RS-{000000}</displayFormat>
        <label>Repayment Schedule</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Repayment Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/cmbls__Repayment_Schedule__c/fields/cmbls__Active__c.field-meta.xml
<CustomField>
    <fullName>cmbls__Active__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/cmbls__Repayment_Schedule__c/fields/cmbls__Bank_Account_Number__c.field-meta.xml
<CustomField>
    <fullName>cmbls__Bank_Account_Number__c</fullName>
    <label>Bank Account Number</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/cmbls__Repayment_Schedule__c/fields/cmbls__Bank_Routing_Number__c.field-meta.xml
<CustomField>
    <fullName>cmbls__Bank_Routing_Number__c</fullName>
    <label>Bank Routing Number</label>
    <length>9</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/cmbls__Repayment_Schedule__c/fields/cmbls__Days__c.field-meta.xml
<CustomField>
    <fullName>cmbls__Days__c</fullName>
    <inlineHelpText>Specifies the day/date of the payment frequency</inlineHelpText>
    <label>Days</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <controllingField>cmbls__Preset__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Monday</fullName>
            </value>
            <value>
                <fullName>Tuesday</fullName>
            </value>
            <value>
                <fullName>Wednesday</fullName>
            </value>
            <value>
                <fullName>Thursday</fullName>
            </value>
            <value>
                <fullName>Friday</fullName>
            </value>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>9</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
            <value>
                <fullName>11</fullName>
            </value>
            <value>
                <fullName>12</fullName>
            </value>
            <value>
                <fullName>13</fullName>
            </value>
            <value>
                <fullName>14</fullName>
            </value>
            <value>
                <fullName>15</fullName>
            </value>
            <value>
                <fullName>16</fullName>
            </value>
            <value>
                <fullName>17</fullName>
            </value>
            <value>
                <fullName>18</fullName>
            </value>
            <value>
                <fullName>19</fullName>
            </value>
            <value>
                <fullName>20</fullName>
            </value>
            <value>
                <fullName>21</fullName>
            </value>
            <value>
                <fullName>22</fullName>
            </value>
            <value>
                <fullName>23</fullName>
            </value>
            <value>
                <fullName>24</fullName>
            </value>
            <value>
                <fullName>25</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/cmbls__Repayment_Schedule__c/fields/cmbls__Preset__c.field-meta.xml
<CustomField>
    <fullName>cmbls__Preset__c</fullName>
    <inlineHelpText>Payment frequency</inlineHelpText>
    <label>Preset</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Weekly</fullName>
            </value>
            <value>
                <fullName>Bi-Weekly</fullName>
            </value>
            <value>
                <fullName>Monthly</fullName>
            </value>
            <value>
                <fullName>Pause</fullName>
            </value>
            <value>
                <fullName>Daily</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/cmbls__Repayment_Schedule__c/fields/cmbls__Repayment__c.field-meta.xml
<CustomField>
    <fullName>cmbls__Repayment__c</fullName>
    <label>Repayment</label>
    <referenceTo>cmbls__Repayment__c</referenceTo>
    <relationshipLabel>Repayment Schedules</relationshipLabel>
    <relationshipName>Repayment_Schedules</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/cmbls__Repayment_Schedule__c/fields/cmbls__Start_Date__c.field-meta.xml
<CustomField>
    <fullName>cmbls__Start_Date__c</fullName>
    <inlineHelpText>This is the first date the system will start evaluating this Repayment Schedule to begin creating ACH payments. NOTE: This must be at least one day before the Next Payment Date and should also be a business day</inlineHelpText>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Lender_Account__c.field-meta.xml
<CustomField>
    <fullName>Lender_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lender Account selected for Oppty</description>
    <inlineHelpText>Select the Lender being used for this Opportunity</inlineHelpText>
    <label>Lender Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Lender Acct</value>
        </filterItems>
        <infoMessage>Select the Lender for this Opportunity</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities (Lender Account)</relationshipLabel>
    <relationshipName>Opportunities1</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Loan_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Loan_Start_Date__c</fullName>
    <label>Loan Start Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/classes/SetStartDateRepaymentScheduleTest.cls
/**
 * SetStartDateRepaymentScheduleTest class
 * @author CloudMyBiz (r)
 * @date 5/10/2023
 */

@IsTest
private class SetStartDateRepaymentScheduleTest{
    
    @TestSetup static void setupMethod(){
        Test.startTest();
        Account acc = TestDataFactory.createAccount();
        Account lenderAccount = TestDataFactory.createAccount();
        lenderAccount.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Lender_Acct').getRecordTypeId();
        lenderAccount.Name = RepaymentUtils.QUICK_BRIDGE_FUND_RECORD_NAME;
        insert new Account[]{acc, lenderAccount};
        
        Opportunity opp = TestDataFactory.createOpportunity(acc.Id);
        opp.Lender_Account__c = lenderAccount.Id;
        opp.Loan_Start_Date__c = Date.newInstance(2023,1,6);
        insert opp;
        
        cmbls__Banking_Information__c bankingInformation = TestDataFactory.createBankingInformation(acc.Id);
        insert bankingInformation;
        
        cmbls__Fund__c fundRecord = TestDataFactory.createFund('National Funding - Fund', bankingInformation);
        fundRecord.cmbls__Default_Debit_ACH_Processor__c = 'Wells Fargo - NF Collections';
        insert fundRecord;
        
        cmbls__Repayment__c repayment = TestDataFactory.createRepayment(acc.Id);
        repayment.Opportunity__c = opp.Id;
        repayment.cmbls__Primary_Fund__c = fundRecord.Id;
        repayment.cmbls__ACH_Processor__c = 'Wells Fargo - NF Collections';
        repayment.cmbls__Funded_Date__c = Date.newInstance(2023,5,8);//Monday
        repayment.cmbls__Enable_AS_Fixed_Payback_Loan__c = true;
        repayment.cmbls__Loan_Start_Date__c = opp.Loan_Start_Date__c;
        insert repayment;
        
        repayment = [SELECT Id, cmbls__Loan_Start_Date__c FROM cmbls__Repayment__c WHERE Id = :repayment.Id];
        Assert.areEqual(Date.newInstance(2023,1,6), repayment.cmbls__Loan_Start_Date__c);
        
        Test.stopTest();
    }
    
    @IsTest
    static void flowNonFixedPaybackLoan(){
        cmbls__Repayment__c repayment = [SELECT Id, cmbls__Funded_Date__c FROM cmbls__Repayment__c LIMIT 1];
        repayment.cmbls__Enable_AS_Fixed_Payback_Loan__c = false;
        update repayment;
        
        
        cmbls__Repayment_Schedule__c[] schedules = new cmbls__Repayment_Schedule__c[]{
            TestDataFactory.createRepaymentSchedule(repayment.Id),
            TestDataFactory.createRepaymentSchedule(repayment.Id)
        };
        schedules[0].cmbls__Active__c = true;
        schedules[0].cmbls__Bank_Account_Number__c = '1212';
        schedules[0].cmbls__Bank_Routing_Number__c = '999999963';
        schedules[0].cmbls__Preset__c = 'Weekly';
        schedules[0].cmbls__Start_Date__c = repayment.cmbls__Funded_Date__c;
        schedules[0].cmbls__Days__c = 'Monday';
        
        schedules[1].cmbls__Active__c = false;
        schedules[1].cmbls__Bank_Account_Number__c = '1212';
        schedules[1].cmbls__Bank_Routing_Number__c = '999999963';
        schedules[1].cmbls__Preset__c = 'Weekly';
        schedules[1].cmbls__Start_Date__c = repayment.cmbls__Funded_Date__c;
        schedules[1].cmbls__Days__c = 'Monday';
        insert schedules;
        
        SetStartDateRepaymentSchedule.SetStartDateRequest[] requests = new SetStartDateRepaymentSchedule.SetStartDateRequest[]{};
        for(cmbls__Repayment_Schedule__c item :schedules){
            SetStartDateRepaymentSchedule.SetStartDateRequest req = new SetStartDateRepaymentSchedule.SetStartDateRequest();
            req.recordId = item.Id;
            req.frequency = item.cmbls__Preset__c;
            req.startDate = item.cmbls__Start_Date__c;
            requests.add(req);
        }
        Test.startTest();
        SetStartDateRepaymentSchedule.mainInvocableMethod(requests);
        Test.stopTest();
        
        schedules = [SELECT Id, cmbls__Days__c, cmbls__Start_Date__c FROM cmbls__Repayment_Schedule__c WHERE cmbls__Repayment__c =:repayment.Id];
        Assert.areEqual('Monday', schedules[0].cmbls__Days__c);
        Assert.areEqual(repayment.cmbls__Funded_Date__c, schedules[0].cmbls__Start_Date__c);
        Assert.areEqual('Monday', schedules[1].cmbls__Days__c);
        Assert.areEqual(repayment.cmbls__Funded_Date__c, schedules[1].cmbls__Start_Date__c);
    }
    
    @IsTest
    static void flowFixedPaybackLoan(){
        cmbls__Repayment__c repayment = [SELECT Id, cmbls__Funded_Date__c, cmbls__Loan_Start_Date__c FROM cmbls__Repayment__c LIMIT 1];
        
        cmbls__Repayment_Schedule__c[] schedules = new cmbls__Repayment_Schedule__c[]{
            TestDataFactory.createRepaymentSchedule(repayment.Id),
            TestDataFactory.createRepaymentSchedule(repayment.Id)
        };
        schedules[0].cmbls__Active__c = true;
        schedules[0].cmbls__Bank_Account_Number__c = '1212';
        schedules[0].cmbls__Bank_Routing_Number__c = '999999963';
        schedules[0].cmbls__Preset__c = 'Weekly';
        schedules[0].cmbls__Start_Date__c = repayment.cmbls__Funded_Date__c;
        schedules[0].cmbls__Days__c = 'Monday';
        
        schedules[1].cmbls__Active__c = false;
        schedules[1].cmbls__Bank_Account_Number__c = '1212';
        schedules[1].cmbls__Bank_Routing_Number__c = '999999963';
        schedules[1].cmbls__Preset__c = 'Weekly';
        schedules[1].cmbls__Start_Date__c = repayment.cmbls__Funded_Date__c;
        schedules[1].cmbls__Days__c = 'Monday';
        insert schedules;
        
        SetStartDateRepaymentSchedule.SetStartDateRequest[] requests = new SetStartDateRepaymentSchedule.SetStartDateRequest[]{};
        for(cmbls__Repayment_Schedule__c item :schedules){
            SetStartDateRepaymentSchedule.SetStartDateRequest req = new SetStartDateRepaymentSchedule.SetStartDateRequest();
            req.recordId = item.Id;
            req.frequency = item.cmbls__Preset__c;
            req.startDate = repayment.cmbls__Loan_Start_Date__c;
            requests.add(req);
        }
        Test.startTest();
        SetStartDateRepaymentSchedule.mainInvocableMethod(requests);
        Test.stopTest();
        
        schedules = [SELECT Id, cmbls__Days__c, cmbls__Start_Date__c FROM cmbls__Repayment_Schedule__c WHERE cmbls__Repayment__c =:repayment.Id];
        
        Assert.areEqual('Friday', schedules[0].cmbls__Days__c);
        Assert.areEqual(repayment.cmbls__Loan_Start_Date__c, schedules[0].cmbls__Start_Date__c);
        Assert.areEqual('Friday', schedules[1].cmbls__Days__c);
        Assert.areEqual(repayment.cmbls__Loan_Start_Date__c, schedules[1].cmbls__Start_Date__c);
    }
}