unpackaged/main/default/objects/Automation_Custom_Settings__c/Automation_Custom_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Holds configurable values to be used in automation logic.</description>
    <label>Automation Custom Settings</label>
</CustomObject>

unpackaged/main/default/objects/Automation_Custom_Settings__c/fields/Repayment_Calculation_Batch_Size__c.field-meta.xml
<CustomField>
    <fullName>Repayment_Calculation_Batch_Size__c</fullName>
    <label>Repayment Calculation Batch Size</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/cmbls__Repayment__c/cmbls__Repayment__c.object-meta.xml
<CustomObject>
    <label>Repayment</label>
    <nameField>
        <displayFormat>RPMT-{0000000}</displayFormat>
        <label>Repayment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Repayments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/cmbls__Repayment__c/fields/cmbls__Payment_Amount__c.field-meta.xml
<CustomField>
    <fullName>cmbls__Payment_Amount__c</fullName>
    <description>Amount of incremental payments</description>
    <inlineHelpText>Amount of incremental payments</inlineHelpText>
    <label>Installment Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/cmbls__Repayment__c/fields/cmbls__Status__c.field-meta.xml
<CustomField>
    <fullName>cmbls__Status__c</fullName>
    <description>Active, pause, complete, and new</description>
    <inlineHelpText>Active, pause, complete, and new</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Temporary Pause</fullName>
            </value>
            <value>
                <fullName>Pause</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Write Off</fullName>
            </value>
            <value>
                <fullName>Recovery</fullName>
            </value>
            <value>
                <fullName>Unwind</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/cmbls__Repayment__c/fields/Expected_Payment_Amount__c.field-meta.xml
<CustomField>
    <fullName>Expected_Payment_Amount__c</fullName>
    <defaultValue>0</defaultValue>
    <description>SUM of Amortization Schdules Payment Amount up to today's date. Used in the balance refresh process. Populated nightly by an apex job.</description>
    <inlineHelpText>SUM of Amortization Schdules Payment Amount up to today's date. Used in the balance refresh process. Populated nightly by an apex job.</inlineHelpText>
    <label>Expected Payment Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/cmbls__Repayment__c/fields/Expected_Payment_Last_Updated__c.field-meta.xml
<CustomField>
    <fullName>Expected_Payment_Last_Updated__c</fullName>
    <label>Expected Payment Last Updated</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/classes/BatchCalcRepaymentExpectedPaymentAmt.cls
/*
    @Author - FTC
    @Created Date - 12/4/2024

    Batch class that is used for calculating the Expected Payment Amount field on the Repayment object.  This class is tested by the test
    class BatchCalcRepaymentExpectedPaymentAmtTest.cls.

    The class has an invocable method that is called from the Screen Flow:  Calculate Expected Payment Amount. The flow allows the Expected
    Payment Amount to be calculated for a specific Repayment record.  The screen flow is associated with an action button on the Repayment
    Object and the action button is added to a record page.

*/
public class BatchCalcRepaymentExpectedPaymentAmt implements Database.Batchable<sObject>, Schedulable, Database.Stateful {
    
    public List<cmbls__Repayment__c> repaymentsToProcess = new List<cmbls__Repayment__c>();
    public Integer totalRecordsProcessed = 0;
    public String batchStartTime;
    public String batchEndTime;
    public Integer errorCount = 0;
    public String errorMessage;

    public BatchCalcRepaymentExpectedPaymentAmt() {}

    public BatchCalcRepaymentExpectedPaymentAmt(List<cmbls__Repayment__c> incomingRepayments) {
        repaymentsToProcess = incomingRepayments;
    }

    public List<cmbls__Repayment__c> start(Database.BatchableContext bc) {
        if(repaymentsToProcess.isEmpty()) {
            return [SELECT Id, Expected_Payment_Amount__c, Expected_Payment_Last_Updated__c
                FROM cmbls__Repayment__c
                WHERE cmbls__Status__c in ('Active','Pause')];    
        }
        else {
            return repaymentsToProcess;
        }
    }

    public void execute(Database.BatchableContext bc, List<cmbls__Repayment__c > repayments) {
        batchStartTime = String.valueOf(System.now());
        totalRecordsProcessed += repayments.size();
        if(!repayments.isEmpty()) {
            summarizeAmortizations(repayments);
        }
    }

    public void execute(SchedulableContext scon) {
        Integer batchSize = getBatchSize() != null ? getBatchSize() : 1;
        Database.executeBatch(new BatchCalcRepaymentExpectedPaymentAmt(), batchSize);
    }

    public void finish(Database.BatchableContext bc) {
        batchEndTime = String.valueOf(System.now());
        String logMessage = 'Apex Job Id: '+ bc.getJobId() + ', Start Time: '+ batchStartTime +', End Time: '+ batchEndTime +', Total Records Processed: '+ totalRecordsProcessed +', Error Count: ' + errorCount +', Error Message: ' + errorMessage;
        NFLogger.logInfo('Batch Calculate Expected Payment Amount', logMessage);
    }

    @InvocableMethod(description='Calculate Expected Payment Amount')
    public static void calculateExpectedPaymentAmount(List<Id> repaymentIds) {
        List<cmbls__Repayment__c> repayments = [SELECT Id, Expected_Payment_Amount__c
                                                FROM cmbls__Repayment__c
                                                WHERE Id in:repaymentIds];
        Integer batchSize = getBatchSize() != null ? getBatchSize() : 1;
        Database.executeBatch(new BatchCalcRepaymentExpectedPaymentAmt(repayments), batchSize);
    }

    public void summarizeAmortizations(List<cmbls__Repayment__c> repayments) {

        Set<Id> repaymentIds = new Set<Id>();
        for (cmbls__Repayment__c repayment : repayments) {
            repaymentIds.add(repayment.Id);
        }
       
        Map<Id, double> resultsByRepaymentId = new Map<Id, double>();
        AggregateResult[] results = aggregateAmortizationPaymentAmounts(repaymentIds);
        for (AggregateResult result : results) {
            Id repaymentId = (Id) result.get('Repayment');
            double totalPaymentAmount = (double) result.get('PaymentAmount');

            resultsByRepaymentId.put(repaymentId, totalPaymentAmount);
        }

        List<cmbls__Repayment__c> repaymentsToUpdate = new List<cmbls__Repayment__c>();
        for (cmbls__Repayment__c repayment : repayments) {
            double totalExpectedPaymentAmount = 0;
            if (resultsByRepaymentId.containsKey(repayment.Id)) {
                totalExpectedPaymentAmount = resultsByRepaymentId.get(repayment.Id);
            }

            //Check if the Total Expected Amount has changed
            if (repayment.Expected_Payment_Amount__c != totalExpectedPaymentAmount) {
                repayment.Expected_Payment_Amount__c = totalExpectedPaymentAmount;
                repayment.Expected_Payment_Last_Updated__c = datetime.now();
                repaymentsToUpdate.add(repayment); 
            }
        }

        if(repaymentsToUpdate.isEmpty() == false) {
            Database.SaveResult[] saveResults = Database.update(repaymentsToUpdate, false);
            
            for(Database.SaveResult saveResult : saveResults) {
                if(saveResult.isSuccess() == false) {
                    errorCount++;
                    for(Database.Error error : saveResult.getErrors()) {
                        errorMessage += saveResult.getId() + ', ' + error.getStatusCode() + ', ' + error.getMessage() + '\n';
                    }
                }
            }
        }
    }

    private AggregateResult[] aggregateAmortizationPaymentAmounts(Set<Id> repaymentIds) {

        return [SELECT cmbls__Repayment__c Repayment, SUM(cmbls__Payment_Amount__c) PaymentAmount
                FROM cmbls__Amortization_Schedule__c
                WHERE cmbls__Date__c <= TODAY AND 
                      cmbls__Repayment__c IN :repaymentIds
                GROUP BY cmbls__Repayment__c];
    }

    private static Integer getBatchSize() {
        Automation_Custom_Settings__c automationSetting = Automation_Custom_Settings__c.getInstance();
        return Integer.valueOf(automationSetting.Repayment_Calculation_Batch_Size__c);
    }
}