unpackaged/main/default/objects/Lead/fields/Account_Number__c.field-meta.xml
<CustomField>
    <fullName>Account_Number__c</fullName>
    <description>The 16 digit account number assigned to this account.</description>
    <inlineHelpText>The 16 digit account number assigned to this account.</inlineHelpText>
    <label>Account Number</label>
    <length>16</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Lead/fields/Activation_Date__c.field-meta.xml
<CustomField>
    <fullName>Activation_Date__c</fullName>
    <description>The date the card was activated.</description>
    <inlineHelpText>The date the card was activated.</inlineHelpText>
    <label>Activation Date</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Lead/fields/Buyer_Zone_Id__c.field-meta.xml
<CustomField>
    <fullName>Buyer_Zone_Id__c</fullName>
    <label>Buyerzone Id</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Lead/fields/Lending_Tree_Id__c.field-meta.xml
<CustomField>
    <fullName>Lending_Tree_Id__c</fullName>
    <description>Lending Tree Id for reporting.</description>
    <label>Lending Tree Id</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Lead/fields/Originating_Brand__c.field-meta.xml
<CustomField>
    <fullName>Originating_Brand__c</fullName>
    <description>Introduced as part of the Quick Bridge to National Funding migration project to capture which brand the response originally came from. Inserted by LeadGen.</description>
    <inlineHelpText>Displays which brand this lead was originally sourced from</inlineHelpText>
    <label>Originating Brand</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Originating_Brand</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Lead/fields/Response_Channel__c.field-meta.xml
<CustomField>
    <fullName>Response_Channel__c</fullName>
    <description>Indicate the response channel used to reach this Lead</description>
    <inlineHelpText>Select the response channel used to reach this Lead</inlineHelpText>
    <label>Response Channel</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Email</fullName>
            </value>
            <value>
                <fullName>Fax</fullName>
            </value>
            <value>
                <fullName>Inbound Call</fullName>
            </value>
            <value>
                <fullName>Internet</fullName>
            </value>
            <value>
                <fullName>Internet Activation</fullName>
            </value>
            <value>
                <fullName>Internet Application</fullName>
            </value>
            <value>
                <fullName>Internet- Lead Aggregator</fullName>
            </value>
            <value>
                <fullName>Outbound Call</fullName>
            </value>
            <value>
                <fullName>Overflow</fullName>
            </value>
            <value>
                <fullName>After Hours Voice Mail</fullName>
            </value>
            <value>
                <fullName>Dev Site</fullName>
            </value>
            <value>
                <fullName>Facebook</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Lead/fields/Short_Account_Number__c.field-meta.xml
<CustomField>
    <fullName>Short_Account_Number__c</fullName>
    <description>A calculated field that is that last 8 digits of the account number.  Used for many lookups.</description>
    <inlineHelpText>A calculated field that is that last 8 digits of the account number.  Used for many lookups.</inlineHelpText>
    <label>Short Account Number</label>
    <length>9</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/LinkShorteningAPI__c/LinkShorteningAPI__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>LSA is responsible for setting endpoint values for WS to shorten application links or other links.</description>
    <label>LinkShorteningAPI</label>
</CustomObject>

unpackaged/main/default/objects/LinkShorteningAPI__c/fields/Authorization__c.field-meta.xml
<CustomField>
    <fullName>Authorization__c</fullName>
    <label>Authorization</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/LinkShorteningAPI__c/fields/Retrieval_Endpoint__c.field-meta.xml
<CustomField>
    <fullName>Retrieval_Endpoint__c</fullName>
    <label>Retrieval Endpoint</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/LinkShorteningAPI__c/fields/Service_Endpoint__c.field-meta.xml
<CustomField>
    <fullName>Service_Endpoint__c</fullName>
    <label>Service Endpoint</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/User/fields/Available_Brands__c.field-meta.xml
<CustomField>
    <fullName>Available_Brands__c</fullName>
    <description>Introduced as part of the Quick Bridge to National Funding migration project to capture which brands this user works for. Originally all users will have one available brand but this is being created as a multi select picklist with the possibility that reps can work under multiple brands in the future.</description>
    <inlineHelpText>Which brand does this user work under?</inlineHelpText>
    <label>Available Brands</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>National Funding</fullName>
                <default>true</default>
                <label>National Funding</label>
            </value>
            <value>
                <fullName>Quick Bridge</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/ValidationRules__c/ValidationRules__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Validation Rules</label>
</CustomObject>

unpackaged/main/default/globalValueSets/Originating_Brand.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>National Funding</fullName>
    </customValue>
    <customValue>
        <fullName>Quick Bridge</fullName>
    </customValue>
    <customValue>
        <fullName>National Funding XPRS</fullName>
    </customValue>
    <description>Introduced as part of the Quick Bridge to National Funding migration project to capture which brand the response originally came from. Inserted by LeadGen.</description>
    <masterLabel>Originating Brand</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/TestLeadNewEncryptedLink.cls
@isTest
public class TestLeadNewEncryptedLink {
    public static testmethod void test() {
    Profile p = [SELECT Id FROM Profile WHERE Name='Standard User']; 
    String UniqueUserName = 'uniqueuser_' + System.currentTimeMillis() + '@example.com';
        User u = new User(Alias = 'standt', Email='standarduser@testorg.com',EmailEncodingKey='UTF-8', 
                          LastName='Testing', LanguageLocaleKey='en_US',LocaleSidKey='en_US', ProfileId = p.Id, 
                          TimeZoneSidKey='America/Los_Angeles', UserName=UniqueUserName,Available_Brands__c='Quick Bridge,National Funding');
        Insert u;
        User testUser1 = [select id from user where email ='standarduser@testorg.com' limit 1]; 
        
        ValidationRules__c customSettingForUser = ValidationRules__c.getInstance(testUser1.id);
        Lead ld = new Lead();
        ld.LastName = 'test lead 1';
        ld.Company = 'Test Company';
        ld.Account_Number__c = '1234567890';
        ld.Short_Account_Number__c = '098765432';
        ld.PostalCode = '12345';
        ld.Lending_Tree_Id__c = '1111';
        ld.Buyer_Zone_Id__c= '2222';
        ld.Activation_Date__c = Date.today();
        ld.Encrypted_Email_String__c = null;
        ld.IsConverted = FALSE;
        ld.Status = 'Prospect'; // can't do this in the initial run.
        ld.Response_Channel__c = 'Internet';
        ld.ownerId = testUser1.id;
        insert ld;
        /*LinkShorteningAPI__c lsAPI= new LinkShorteningAPI__c(Name = 'ProdEndpoint');
        insert lsAPI;
        lsAPI.Authorization__c = 'apikey 0BFC69A7-2A45-4BFA-A02D-B10C999E6491';
        lsAPI.Endpoint__c = 'https://dev.app.nationalfunding.com:8443/tokenizer/api/v1/SecurityToken'; 
        lsAPI.Retrieval_Endpoint__c = 'https://dev.app.nationalfunding.com:8443/tokenizer/api/v1/Token/';
        lsAPI.Service_Endpoint__c = 'https://dev.app.nationalfunding.com:8443/tokenizer/api/v1/Token';
        update lsAPI;*/
        
        LinkShorteningAPI__c lsAPI2= new LinkShorteningAPI__c(Name = 'V2');
        insert lsAPI2;
        lsAPI2.Authorization__c = '0BFC69A7-2A45-4BFA-A02D-B10C999E6491';
        lsAPI2.Endpoint__c = 'https://dev.app.nationalfunding.com:8443/sts/api/v1/Token'; 
        lsAPI2.Retrieval_Endpoint__c = 'https://dev.app.nationalfunding.com:8443/tokenizer/api/v1/Token/';
        lsAPI2.Service_Endpoint__c = 'https://dev.app.nationalfunding.com:8443/tokenizer/api/v2/Tokens'; 
        update lsAPI2;
        
        Test.startTest();
        HttpMockGenerator mock = new HttpMockGenerator('[{"Id":"' + ld.Id+ '","Token":"bxofefoHG9wLuWDiynV4"}]', 200);
        Test.setMock(HttpCalloutMock.class, mock);
        Test.stopTest();
        
    }

    public static testmethod void test2() {
    Profile p = [SELECT Id FROM Profile WHERE Name='Standard User']; 
    String UniqueUserName = 'uniqueuser_' + System.currentTimeMillis() + '@example.com';
        User u = new User(Alias = 'standt', Email='standarduser@testorg.com',EmailEncodingKey='UTF-8', 
                          LastName='Testing', LanguageLocaleKey='en_US',LocaleSidKey='en_US', ProfileId = p.Id, 
                          TimeZoneSidKey='America/Los_Angeles', UserName=UniqueUserName,Available_Brands__c='National Funding');
        Insert u;
        User testUser1 = [select id from user where email ='standarduser@testorg.com' limit 1]; 
        
        ValidationRules__c customSettingForUser = ValidationRules__c.getInstance(testUser1.id);
        Lead ld = new Lead();
        ld.LastName = 'test lead 1';
        ld.Company = 'Test Company';
        ld.Account_Number__c = '1234567890';
        ld.Short_Account_Number__c = '098765432';
        ld.PostalCode = '12345';
        ld.Lending_Tree_Id__c = '1111';
        ld.Buyer_Zone_Id__c= '2222';
        ld.Activation_Date__c = Date.today();
        ld.Response_Channel__c = 'Internet';
        ld.Status = 'Activator'; // can't do this in the initial run.
        ld.ownerId =testUser1.id;
        insert ld;
        /*LinkShorteningAPI__c lsAPI= new LinkShorteningAPI__c(Name = 'ProdEndpoint');
        insert lsAPI;
        lsAPI.Authorization__c = '0BFC69A7-2A45-4BFA-A02D-B10C999E6491';
        lsAPI.Endpoint__c = 'https://stage.app.nationalfunding.com:8443/sts/api/v1/Token'; 
        lsAPI.Retrieval_Endpoint__c = 'https://stage.app.nationalfunding.com:8443/tokenizer/api/v2/SecurityToken';
        lsAPI.Service_Endpoint__c = 'https://stage.app.nationalfunding.com:8443/tokenizer/api/v2/Tokens';
        update lsAPI;*/

        LinkShorteningAPI__c lsAPI2= new LinkShorteningAPI__c(Name = 'V2');
        insert lsAPI2;
        lsAPI2.Authorization__c = '0BFC69A7-2A45-4BFA-A02D-B10C999E6491';
        lsAPI2.Endpoint__c = 'https://stage.app.nationalfunding.com:8443/sts/api/v1/Token'; 
        lsAPI2.Retrieval_Endpoint__c = 'https://stage.app.nationalfunding.com:8443/tokenizer/api/v2/SecurityToken';
        lsAPI2.Service_Endpoint__c = 'https://stage.app.nationalfunding.com:8443/tokenizer/api/v2/Tokens';
        update lsAPI2;

        Test.startTest();
        HttpMockGenerator mock = new HttpMockGenerator('[{"Id":"' + ld.Id+ '","Token":"bxofefoHG9wLuWDiynV4"}]', 200);
        Test.setMock(HttpCalloutMock.class, mock);
        Test.stopTest();

    }
    public static testmethod void test3() {
        
        Group publicGroup = [select id from Group where name = 'National Funding Leads'];
    
        Lead ld = new Lead();
        ld.LastName = 'test lead 1';
        ld.Company = 'Test Company';
        ld.Account_Number__c = '1234567890';
        ld.Short_Account_Number__c = '098765432';
        ld.PostalCode = '12345';
        ld.Lending_Tree_Id__c = '1111';
        ld.Buyer_Zone_Id__c= '2222';
        ld.Activation_Date__c = Date.today();
        ld.Response_Channel__c = 'Internet';
        ld.Status = 'Activator'; // can't do this in the initial run.
        if(publicGroup!=null)
        ld.ownerId = publicGroup.id;
        ld.Originating_Brand__c = 'Quick Bridge';
        insert ld;
        /*LinkShorteningAPI__c lsAPI= new LinkShorteningAPI__c(Name = 'ProdEndpoint');
        insert lsAPI;
        lsAPI.Authorization__c = '0BFC69A7-2A45-4BFA-A02D-B10C999E6491';
        lsAPI.Endpoint__c = 'https://stage.app.nationalfunding.com:8443/sts/api/v1/Token'; 
        lsAPI.Retrieval_Endpoint__c = 'https://stage.app.nationalfunding.com:8443/tokenizer/api/v2/SecurityToken';
        lsAPI.Service_Endpoint__c = 'https://stage.app.nationalfunding.com:8443/tokenizer/api/v2/Tokens';
        update lsAPI;*/

        LinkShorteningAPI__c lsAPI2= new LinkShorteningAPI__c(Name = 'V2');
        insert lsAPI2;
        lsAPI2.Authorization__c = '0BFC69A7-2A45-4BFA-A02D-B10C999E6491';
        lsAPI2.Endpoint__c = 'https://stage.app.nationalfunding.com:8443/sts/api/v1/Token'; 
        lsAPI2.Retrieval_Endpoint__c = 'https://stage.app.nationalfunding.com:8443/tokenizer/api/v2/SecurityToken';
        lsAPI2.Service_Endpoint__c = 'https://stage.app.nationalfunding.com:8443/tokenizer/api/v2/Tokens';
        update lsAPI2;

        Test.startTest();
        HttpMockGenerator mock = new HttpMockGenerator('[{"Id":"' + ld.Id+ '","Token":"bxofefoHG9wLuWDiynV4"}]', 200);
        Test.setMock(HttpCalloutMock.class, mock);
        Test.stopTest();

    }
}