unpackaged/main/default/objects/Lead/fields/SSN_Encrypted__c.field-meta.xml
<CustomField>
    <fullName>SSN_Encrypted__c</fullName>
    <description>This field will contain a customer's Social Security number in an encrypted format.  Accessing the full visibility of this field will be determined by job role and permission set.</description>
    <inlineHelpText>Encrypted Social Security Number - See your administrator if you have questions.</inlineHelpText>
    <label>SSN Encrypted</label>
    <length>11</length>
    <maskChar>asterisk</maskChar>
    <maskType>ssn</maskType>
    <type>EncryptedText</type>
</CustomField>

unpackaged/main/default/objects/Lead/fields/SSN_is_Blank__c.field-meta.xml
<CustomField>
    <fullName>SSN_is_Blank__c</fullName>
    <defaultValue>true</defaultValue>
    <label>SSN is Blank</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/classes/lead_isSSNBlankHelper.cls
/**
* ─────────────────────────────────────────────────────────────────────────────────────────────────
* TITLE: lead_isSSNBlankHelper
* DESCRIPTION: checking if the lead's ssn is blank. this is a helper and is called in the AllLeadTriggers.trigger
*                this class is a part of a larger effort to merge all Lead triggers into one
* @author         
* @version        1.0
* @created        
* @mofidied       olivia.k.porter@gmail.com - pulled over from old lead trigger. this class is a direct copy and paste
* ────────────────────────────────────────────────────────────────────────────────────────────────
* Technical Debt Notes:
*   - naming convention should be updated
*/     
public with sharing class lead_isSSNBlankHelper {

    public void isLeadSSNBlank(List<Lead> newLeadList){
        for (Lead lead : newLeadList){
            lead.SSN_Is_Blank__c = ((lead.SSN_Encrypted__c == '') || (lead.SSN_Encrypted__c == null));        
        }
    }
}