unpackaged/main/default/objects/Lead/fields/SSN_Encrypted__c.field-meta.xml
<CustomField>
    <fullName>SSN_Encrypted__c</fullName>
    <description>This field will contain a customer's Social Security number in an encrypted format.  Accessing the full visibility of this field will be determined by job role and permission set.</description>
    <inlineHelpText>Encrypted Social Security Number - See your administrator if you have questions.</inlineHelpText>
    <label>SSN Encrypted</label>
    <length>11</length>
    <maskChar>asterisk</maskChar>
    <maskType>ssn</maskType>
    <type>EncryptedText</type>
</CustomField>

unpackaged/main/default/objects/Lead/fields/SSN_is_Blank__c.field-meta.xml
<CustomField>
    <fullName>SSN_is_Blank__c</fullName>
    <defaultValue>true</defaultValue>
    <label>SSN is Blank</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/classes/lead_isSSNBlankHelperTest.cls
@IsTest
public with sharing class lead_isSSNBlankHelperTest {

    @isTest
    public static void isSSNBlank(){
        Lead lead = new Lead();
        lead.Company = 'Test Company';
        lead.FirstName = 'First';
        lead.LastName = 'Test';
        lead.Phone = '123456789';
        lead.SSN_Encrypted__c = null;
        // lead.SSN_Is_Blank__c = true; //this is default value
        insert lead;
        
        lead = [ SELECT SSN_Encrypted__c, SSN_Is_Blank__c FROM Lead WHERE Id =: lead.Id ];
        System.assertEquals(true, lead.SSN_Is_Blank__c);
        
        lead.SSN_Encrypted__c = '123456789';
        update lead;
        
        lead = [ SELECT SSN_Encrypted__c, SSN_Is_Blank__c FROM Lead WHERE Id =: lead.Id ];
        System.assertEquals(false, lead.SSN_Is_Blank__c);

        Lead leadEncrypted = new Lead();
        leadEncrypted.Company = 'Test Company';
        leadEncrypted.FirstName = 'First';
        leadEncrypted.LastName = 'Test';
        leadEncrypted.Phone = '123456789';
        leadEncrypted.SSN_Encrypted__c = '123456789';
        // lead.SSN_Is_Blank__c = true; //this is default value
        insert leadEncrypted;
        System.assertEquals(false, leadEncrypted.SSN_Is_Blank__c);

    }
}