unpackaged/main/default/objects/Bank_Account__c/Bank_Account__c.object-meta.xml
<CustomObject>
    <label>Bank Account</label>
    <nameField>
        <label>Bank Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bank Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/cmbls__InterestAccrual__c/cmbls__InterestAccrual__c.object-meta.xml
<CustomObject>
    <label>Interest Accrual</label>
    <nameField>
        <displayFormat>Int-Accrual-{0000}</displayFormat>
        <label>Interest Accrual Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Interest Accruals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/cmbls__InterestAccrual__c/fields/cmbls__Repayment__c.field-meta.xml
<CustomField>
    <fullName>cmbls__Repayment__c</fullName>
    <inlineHelpText>Related Repayment ID</inlineHelpText>
    <label>Repayment</label>
    <referenceTo>cmbls__Repayment__c</referenceTo>
    <relationshipLabel>Interest Accruals</relationshipLabel>
    <relationshipName>Interest_Accruals</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/cmbls__Repayment__c/cmbls__Repayment__c.object-meta.xml
<CustomObject>
    <label>Repayment</label>
    <nameField>
        <displayFormat>RPMT-{0000000}</displayFormat>
        <label>Repayment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Repayments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/classes/InterestAccrualsSelectorTest.cls
/**
 * InterestAccrualsSelectorTest class
 * @author CloudMyBiz (r)
 * @date 9/7/2022
 * @description
 * @group 
 */

@IsTest
private class InterestAccrualsSelectorTest{
    
    @TestSetup static void setupMethod(){
        Test.startTest();
        Account acc = TestDataFactory.createAccount();
        insert acc;
    
        Bank_Account__c bankAccount = TestDataFactory.createBankAccount();
        insert bankAccount;
    
        Opportunity opp = TestDataFactory.createOpportunity(acc.Id);
        insert opp;
    
        cmbls__Repayment__c repayment = TestDataFactory.createRepayment(acc.Id);
        insert repayment;
        
        cmbls__InterestAccrual__c[] accruals = new cmbls__InterestAccrual__c[]{
            TestDataFactory.createInterestAccrual(repayment.Id, 1500, Date.newInstance(2022,1,1), Date.newInstance(2022,1,31)),
            TestDataFactory.createInterestAccrual(repayment.Id, 1000, Date.newInstance(2022,2,1), Date.newInstance(2022,2,28))
        };
        insert accruals;
        Test.stopTest();
    }
    
    @IsTest
    static void getSumInterestAccrualsByRepayment(){
        cmbls__Repayment__c repayment = [SELECT Id FROM cmbls__Repayment__c];
        Test.startTest();
        Map<Id, Decimal> records = InterestAccrualsSelector.getSumInterestAccrualsByRepayment(new Set<Id>{repayment.Id});
        System.assertEquals(2500, records.get(repayment.Id));
        Test.stopTest();
    }
}