unpackaged/main/default/objects/Bank_Account__c/Bank_Account__c.object-meta.xml
<CustomObject>
    <label>Bank Account</label>
    <nameField>
        <label>Bank Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bank Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/cmbls__ACH_Batch__c/cmbls__ACH_Batch__c.object-meta.xml
<CustomObject>
    <label>ACH Batch</label>
    <nameField>
        <displayFormat>BATCH-{0000000}</displayFormat>
        <label>ACH Batch Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ACH Batches</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/cmbls__ACH_Batch__c/fields/cmbls__ACH_Provider_Name__c.field-meta.xml
<CustomField>
    <fullName>cmbls__ACH_Provider_Name__c</fullName>
    <label>ACH Provider Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/cmbls__Payment__c/cmbls__Payment__c.object-meta.xml
<CustomObject>
    <label>Payment</label>
    <nameField>
        <displayFormat>PMT-{0000}</displayFormat>
        <label>Payment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/cmbls__Payment__c/fields/cmbls__ACH_Batch__c.field-meta.xml
<CustomField>
    <fullName>cmbls__ACH_Batch__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ACH Batch</label>
    <referenceTo>cmbls__ACH_Batch__c</referenceTo>
    <relationshipName>Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/cmbls__Payment__c/fields/cmbls__Interest_Payment_Amt__c.field-meta.xml
<CustomField>
    <fullName>cmbls__Interest_Payment_Amt__c</fullName>
    <label>Interest Payment Amt</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/cmbls__Payment__c/fields/cmbls__Repayment__c.field-meta.xml
<CustomField>
    <fullName>cmbls__Repayment__c</fullName>
    <label>Repayment</label>
    <referenceTo>cmbls__Repayment__c</referenceTo>
    <relationshipLabel>Payments</relationshipLabel>
    <relationshipName>Payments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/cmbls__Payment__c/fields/cmbls__Transaction_Amount__c.field-meta.xml
<CustomField>
    <fullName>cmbls__Transaction_Amount__c</fullName>
    <label>Transaction Amount</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/cmbls__Payment__c/fields/cmbls__Transaction_Type__c.field-meta.xml
<CustomField>
    <fullName>cmbls__Transaction_Type__c</fullName>
    <description>This field indicates wether if it is a Fee or a Payment, and should be displayed in the page detail layout.</description>
    <inlineHelpText>This field indicates wether if it is a Fee or a Payment, and should be displayed in the page detail layout.</inlineHelpText>
    <label>Transaction Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Fee</fullName>
            </value>
            <value>
                <fullName>Payment</fullName>
            </value>
            <value>
                <fullName>Adjustment</fullName>
            </value>
            <value>
                <fullName>Distribution</fullName>
            </value>
            <value>
                <fullName>Fee Collection</fullName>
            </value>
            <value>
                <fullName>Reserve</fullName>
            </value>
            <value>
                <fullName>Interest</fullName>
            </value>
            <value>
                <fullName>Draw</fullName>
            </value>
            <value>
                <fullName>Draw Reserve</fullName>
            </value>
            <value>
                <fullName>Deferred Fee</fullName>
            </value>
            <value>
                <fullName>Lender Reimbursement</fullName>
            </value>
            <value>
                <fullName>Discount</fullName>
            </value>
            <value>
                <fullName>Payoff</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/cmbls__Repayment__c/cmbls__Repayment__c.object-meta.xml
<CustomObject>
    <label>Repayment</label>
    <nameField>
        <displayFormat>RPMT-{0000000}</displayFormat>
        <label>Repayment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Repayments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/classes/PaymentSelectorTest.cls
/**
 * PaymentSelectorTest class
 * @author CloudMyBiz (r)
 * @date 9/7/2022
 * @description
 * @group 
 */

@IsTest
private class PaymentSelectorTest{
    
    @TestSetup static void setupMethod(){
        Test.startTest();
        Account acc = TestDataFactory.createAccount();
        insert acc;
    
        Bank_Account__c bankAccount = TestDataFactory.createBankAccount();
        insert bankAccount;
    
        Opportunity opp = TestDataFactory.createOpportunity(acc.Id);
        insert opp;
    
        cmbls__Repayment__c repayment = TestDataFactory.createRepayment(acc.Id);
        insert repayment;
    
        cmbls__ACH_Batch__c achBatch = TestDataFactory.createACHBatch('Wells Fargo Account', Constant.ACH_BATCH_STATUS_SUCCESS, DateTimeUtils.getNextValidDate(Date.today().addDays(1)));
        insert achBatch;
    
        cmbls__Payment__c[] payments = new cmbls__Payment__c[]{
            TestDataFactory.createPayment(repayment.Id, PaymentUtils.PAYMENT_RECORD_TYPE_CREDIT, PaymentUtils.PAYMENT_STATUS_SCHEDULED, 100, Date.today(), achBatch.cmbls__ACH_Provider_Name__c),
            TestDataFactory.createPayment(repayment.Id, PaymentUtils.PAYMENT_RECORD_TYPE_CREDIT, PaymentUtils.PAYMENT_STATUS_SCHEDULED, 500, Date.today(), achBatch.cmbls__ACH_Provider_Name__c),
            TestDataFactory.createPayment(repayment.Id, PaymentUtils.PAYMENT_RECORD_TYPE_DEBIT, PaymentUtils.PAYMENT_STATUS_PENDING, 1600, Date.today(), achBatch.cmbls__ACH_Provider_Name__c),
            TestDataFactory.createPayment(repayment.Id, PaymentUtils.PAYMENT_RECORD_TYPE_DEBIT, PaymentUtils.PAYMENT_STATUS_PENDING, 1200, Date.today(), achBatch.cmbls__ACH_Provider_Name__c),
            TestDataFactory.createPayment(repayment.Id, PaymentUtils.PAYMENT_RECORD_TYPE_DEBIT, PaymentUtils.PAYMENT_STATUS_SETTLED, 1200, Date.today(), achBatch.cmbls__ACH_Provider_Name__c)
        };
        payments[0]. cmbls__Transaction_Type__c = PaymentUtils.PAYMENT_TRANSACTION_TYPE_PAYMENT;
        payments[1]. cmbls__Transaction_Type__c = PaymentUtils.PAYMENT_TRANSACTION_TYPE_PAYMENT;
        payments[2].cmbls__Interest_Payment_Amt__c = payments[2].cmbls__Transaction_Amount__c;
        payments[3].cmbls__Interest_Payment_Amt__c = payments[3].cmbls__Transaction_Amount__c;
        payments[4].cmbls__Interest_Payment_Amt__c = payments[4].cmbls__Transaction_Amount__c;
        insert payments;
        Test.stopTest();
    }
    
    @IsTest
    static void queries(){
        cmbls__Repayment__c repayment = [SELECT Id FROM cmbls__Repayment__c];
        
        Test.startTest();
        Map<Id, cmbls__Payment__c[]> scheduled = PaymentSelector.getScheduledCreditPaymentsByRepaymentIds(new Set<Id>{repayment.Id});
        System.assertEquals(2, scheduled.get(repayment.Id).size());
        
        cmbls__Payment__c single = PaymentSelector.getPaymentById(scheduled.get(repayment.Id)[0].Id);
        System.assertNotEquals(null, single);
    
        Map<Id, Decimal> sumPending = PaymentSelector.getSumPendingDebitPaymentsByRepayment(new Set<Id>{repayment.Id});
        System.assertEquals(2800, sumPending.get(repayment.Id));
    
        Map<Id, Decimal> sumPendingSettled = PaymentSelector.getSumPendingSettledDebitPaymentsByRepayment(new Set<Id>{repayment.Id});
        System.assertEquals(4000, sumPendingSettled.get(repayment.Id));
    
        Test.stopTest();
    }
}