unpackaged/main/default/objects/cmbls__ACH_Batch__c/cmbls__ACH_Batch__c.object-meta.xml
<CustomObject>
    <label>ACH Batch</label>
    <nameField>
        <displayFormat>BATCH-{0000000}</displayFormat>
        <label>ACH Batch Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ACH Batches</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/cmbls__ACH_Batch__c/fields/cmbls__Status__c.field-meta.xml
<CustomField>
    <fullName>cmbls__Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Partial Success</fullName>
            </value>
            <value>
                <fullName>Resubmission</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/cmbls__Disbursement__c/cmbls__Disbursement__c.object-meta.xml
<CustomObject>
    <label>Disbursement</label>
    <nameField>
        <displayFormat>D-{0000}</displayFormat>
        <label>Disbursement Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Disbursements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/cmbls__Disbursement__c/fields/cmbls__Effective_Date__c.field-meta.xml
<CustomField>
    <fullName>cmbls__Effective_Date__c</fullName>
    <label>Effective Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/cmbls__Disbursement__c/fields/cmbls__Repayment__c.field-meta.xml
<CustomField>
    <fullName>cmbls__Repayment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Repayment</label>
    <referenceTo>cmbls__Repayment__c</referenceTo>
    <relationshipLabel>Disbursements</relationshipLabel>
    <relationshipName>Disbursements</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/cmbls__Disbursement__c/fields/cmbls__Status__c.field-meta.xml
<CustomField>
    <fullName>cmbls__Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>Pre-Pending</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Settled</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Sent Error</fullName>
            </value>
            <value>
                <fullName>Staging</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/cmbls__Disbursement__c/fields/cmbls__Transaction_Amount__c.field-meta.xml
<CustomField>
    <fullName>cmbls__Transaction_Amount__c</fullName>
    <label>Transaction Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/cmbls__Payment__c/cmbls__Payment__c.object-meta.xml
<CustomObject>
    <label>Payment</label>
    <nameField>
        <displayFormat>PMT-{0000}</displayFormat>
        <label>Payment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/cmbls__Payment__c/fields/cmbls__Effective_Date__c.field-meta.xml
<CustomField>
    <fullName>cmbls__Effective_Date__c</fullName>
    <inlineHelpText>Effective Date</inlineHelpText>
    <label>Effective Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/cmbls__Payment__c/fields/cmbls__Payment_Method__c.field-meta.xml
<CustomField>
    <fullName>cmbls__Payment_Method__c</fullName>
    <label>Payment Method</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ACH</fullName>
            </value>
            <value>
                <fullName>Wire</fullName>
            </value>
            <value>
                <fullName>Check</fullName>
            </value>
            <value>
                <fullName>Split Funding</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Credit Card</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/cmbls__Payment__c/fields/cmbls__Repayment__c.field-meta.xml
<CustomField>
    <fullName>cmbls__Repayment__c</fullName>
    <label>Repayment</label>
    <referenceTo>cmbls__Repayment__c</referenceTo>
    <relationshipLabel>Payments</relationshipLabel>
    <relationshipName>Payments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/cmbls__Payment__c/fields/cmbls__Status__c.field-meta.xml
<CustomField>
    <fullName>cmbls__Status__c</fullName>
    <inlineHelpText>Scheduled: Created and not submitted
Pending: Submitted to the ACH provider, but not yet settled.
Settled: The ACH payment was pulled successfully from the customer's account
Failed: Returned a failed response from the ACH provider</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>cmbls__Transaction_Type__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>Pre-Pending</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Settled</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Fees Applied</fullName>
            </value>
            <value>
                <fullName>Fees Collected</fullName>
            </value>
            <value>
                <fullName>Fees Reversed</fullName>
            </value>
            <value>
                <fullName>Applied</fullName>
            </value>
            <value>
                <fullName>Sent Error</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/cmbls__Payment__c/fields/cmbls__Sub_Type__c.field-meta.xml
<CustomField>
    <fullName>cmbls__Sub_Type__c</fullName>
    <label>Sub Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>cmbls__Transaction_Type__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Default</fullName>
            </value>
            <value>
                <fullName>General</fullName>
            </value>
            <value>
                <fullName>Renewal Payoff</fullName>
            </value>
            <value>
                <fullName>Add-on</fullName>
            </value>
            <value>
                <fullName>RTR</fullName>
            </value>
            <value>
                <fullName>Net Funding</fullName>
            </value>
            <value>
                <fullName>Fee Balance</fullName>
            </value>
            <value>
                <fullName>Write Off</fullName>
            </value>
            <value>
                <fullName>Write Off Fee Balance</fullName>
            </value>
            <value>
                <fullName>Overpayment Refund</fullName>
            </value>
            <value>
                <fullName>Initial Balance</fullName>
            </value>
            <value>
                <fullName>Refund</fullName>
            </value>
            <value>
                <fullName>Reversal</fullName>
            </value>
            <value>
                <fullName>Deferred Interest Write Off</fullName>
            </value>
            <value>
                <fullName>Collection on Write-Off</fullName>
            </value>
            <value>
                <fullName>Renewal Fee Payoff</fullName>
            </value>
            <value>
                <fullName>Interest Charge</fullName>
            </value>
            <value>
                <fullName>Reserve Request</fullName>
            </value>
            <value>
                <fullName>Payment From Reserve</fullName>
            </value>
            <value>
                <fullName>Refund from Reserve</fullName>
            </value>
            <value>
                <fullName>Adjustment</fullName>
            </value>
            <value>
                <fullName>Consulting Fee</fullName>
            </value>
            <value>
                <fullName>Additional Principal Payment</fullName>
            </value>
            <value>
                <fullName>Starting Draw Reserve Balance</fullName>
            </value>
            <value>
                <fullName>Extension Fee</fullName>
            </value>
            <value>
                <fullName>Maturity Default</fullName>
            </value>
            <value>
                <fullName>Payoff</fullName>
            </value>
            <value>
                <fullName>Origination Fee</fullName>
            </value>
            <value>
                <fullName>Recovery</fullName>
            </value>
            <value>
                <fullName>Unwind</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/cmbls__Payment__c/fields/cmbls__Transaction_Amount__c.field-meta.xml
<CustomField>
    <fullName>cmbls__Transaction_Amount__c</fullName>
    <label>Transaction Amount</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/cmbls__Payment__c/fields/cmbls__Transaction_Type__c.field-meta.xml
<CustomField>
    <fullName>cmbls__Transaction_Type__c</fullName>
    <description>This field indicates wether if it is a Fee or a Payment, and should be displayed in the page detail layout.</description>
    <inlineHelpText>This field indicates wether if it is a Fee or a Payment, and should be displayed in the page detail layout.</inlineHelpText>
    <label>Transaction Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Fee</fullName>
            </value>
            <value>
                <fullName>Payment</fullName>
            </value>
            <value>
                <fullName>Adjustment</fullName>
            </value>
            <value>
                <fullName>Distribution</fullName>
            </value>
            <value>
                <fullName>Fee Collection</fullName>
            </value>
            <value>
                <fullName>Reserve</fullName>
            </value>
            <value>
                <fullName>Interest</fullName>
            </value>
            <value>
                <fullName>Draw</fullName>
            </value>
            <value>
                <fullName>Draw Reserve</fullName>
            </value>
            <value>
                <fullName>Deferred Fee</fullName>
            </value>
            <value>
                <fullName>Lender Reimbursement</fullName>
            </value>
            <value>
                <fullName>Discount</fullName>
            </value>
            <value>
                <fullName>Payoff</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/cmbls__Payment__c/fields/Payment__c.field-meta.xml
<CustomField>
    <fullName>Payment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Rescheduled From</label>
    <referenceTo>cmbls__Payment__c</referenceTo>
    <relationshipLabel>Payments (Payment)</relationshipLabel>
    <relationshipName>Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/cmbls__Repayment__c/cmbls__Repayment__c.object-meta.xml
<CustomObject>
    <label>Repayment</label>
    <nameField>
        <displayFormat>RPMT-{0000000}</displayFormat>
        <label>Repayment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Repayments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/cmbls__Repayment__c/fields/cmbls__Status__c.field-meta.xml
<CustomField>
    <fullName>cmbls__Status__c</fullName>
    <description>Active, pause, complete, and new</description>
    <inlineHelpText>Active, pause, complete, and new</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Temporary Pause</fullName>
            </value>
            <value>
                <fullName>Pause</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Write Off</fullName>
            </value>
            <value>
                <fullName>Recovery</fullName>
            </value>
            <value>
                <fullName>Unwind</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/cmbls__Repayment_Schedule__c/cmbls__Repayment_Schedule__c.object-meta.xml
<CustomObject>
    <label>Repayment Schedule</label>
    <nameField>
        <displayFormat>RS-{000000}</displayFormat>
        <label>Repayment Schedule</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Repayment Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/cmbls__Repayment_Schedule__c/fields/cmbls__Repayment__c.field-meta.xml
<CustomField>
    <fullName>cmbls__Repayment__c</fullName>
    <label>Repayment</label>
    <referenceTo>cmbls__Repayment__c</referenceTo>
    <relationshipLabel>Repayment Schedules</relationshipLabel>
    <relationshipName>Repayment_Schedules</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/classes/PaymentServiceTest.cls
/**
 * PaymentServiceTest class
 * @author CloudMyBiz (r)
 * @date 9/7/2022
 * @description
 * @group 
 */

@IsTest
private class PaymentServiceTest{
    @TestSetup static void setupMethod(){
        Test.startTest();
        Account acc = TestDataFactory.createAccount();
        insert acc;
    
        cmbls__Repayment__c repayment = TestDataFactory.createRepayment(acc.Id);
        insert repayment;
    
        delete [SELECT Id FROM cmbls__Payment__c];
    
        insert new cmbls__Payment__c(
            cmbls__Repayment__c = repayment.Id,
            RecordTypeId = PaymentUtils.PAYMENT_RECORD_TYPE_CREDIT_ID,
            cmbls__Effective_Date__c = System.today().addDays(1),
            cmbls__Transaction_Type__c = PaymentUtils.PAYMENT_TRANSACTION_TYPE_PAYMENT,
            cmbls__Sub_Type__c = 'Adjustment',
            cmbls__Transaction_Amount__c = 4000,
            cmbls__Status__c = PaymentUtils.PAYMENT_STATUS_SCHEDULED,
            cmbls__Payment_Method__c = PaymentUtils.PAYMENT_METHOD_ACH,
            cmbls__ACH_Processor__c = 'ACH.com'
        );
        
        insert new cmbls__Active_Repayment_Statuses__c(
            cmbls__Status__c = 'Active',
            Name = 'Active'
        );
        Test.stopTest();
    }
    
    @IsTest
    static void createOneTimePaymentFromInvocable(){
        cmbls__Repayment__c repayment = [SELECT Id FROM cmbls__Repayment__c];
        CreateOneTimePayment.CreateRequest mainRequest = new CreateOneTimePayment.CreateRequest();
        mainRequest.repaymentId = repayment.Id;
        mainRequest.effectiveDate = System.today().addDays(15);
        mainRequest.transactionAmount = 2000;
        mainRequest.subType = 'Adjustment';
        mainRequest.achProcessor = 'ACH.com';
        mainRequest.notes = 'Test Notes';
        
        Test.startTest();
        cmbls__Payment__c payment = PaymentService.createOneTimePaymentFromInvocable(mainRequest);
        Test.stopTest();
        System.assertNotEquals(null, payment.Id);
    }
    
    @IsTest
    static void rescheduleAPaymentFromInvocable(){
        cmbls__Repayment__c repayment = [SELECT Id, (SELECT Id, Name, cmbls__Status__c FROM cmbls__Payments__r LIMIT 1) FROM cmbls__Repayment__c];
        
        ReschedulePayment.RescheduleRequest mainRequest = new ReschedulePayment.RescheduleRequest();
        mainRequest.paymentId = repayment.cmbls__Payments__r[0].Id;
        mainRequest.effectiveDate = System.today().addDays(10);
        mainRequest.notes = 'Test Notes';
        
        Test.startTest();
        cmbls__Payment__c payment = PaymentService.rescheduleAPaymentFromInvocable(mainRequest);
        System.assertNotEquals(null, payment.Id);
    
        String errorMessage = String.format(ReschedulePayment.NOT_SCHEDULED_ERROR_MESSAGE, new String[]{
            repayment.cmbls__Payments__r[0].Name, PaymentUtils.PAYMENT_STATUS_PENDING
        });
        try{
            update new cmbls__Payment__c(Id = repayment.cmbls__Payments__r[0].Id, cmbls__Status__c = PaymentUtils.PAYMENT_STATUS_PENDING);
            PaymentService.rescheduleAPaymentFromInvocable(mainRequest);
            System.assert(false, 'Should thrown an exception');
        }catch(Exception e){
            System.assertEquals(errorMessage, e.getMessage());
        }
        Test.stopTest();
        
    }
    
    @IsTest
    static void getPendingPayments(){
        Test.startTest();
        String query = PaymentService.getPendingPayments(WellsFargoAPI.PAYMENTS_PROCESS, new Set<Id>());
        query = PaymentService.getPendingPayments(WellsFargoAPI.DISBURSEMENT_PROCESS, new Set<Id>());
        Test.stopTest();
    }
    
    @IsTest
    static void getPendingRefundDisbursements(){
        cmbls__Repayment__c repayment = [SELECT Id FROM cmbls__Repayment__c];
        repayment.cmbls__Status__c = RepaymentUtils.STATUS_COMPLETE;
        update repayment;
        
        cmbls__Disbursement__c record = TestDataFactory.createDisbursement(DisbursementUtils.DISBURSEMENT_PAYMENT_TYPE_REFUND, DisbursementUtils.DISBURSEMENT_STATUS_SCHEDULED, 'Wells Fargo - QBF Funding');
        record.cmbls__Effective_Date__c = DateTimeUtils.getNextValidDate(Date.today().addDays(1));
        record.cmbls__Repayment__c = repayment.Id;
        insert record;
        
        Test.startTest();
        String query = PaymentService.getPendingPayments(WellsFargoAPI.DISBURSEMENT_PROCESS, new Set<Id>());
        cmbls__Disbursement__c result = (cmbls__Disbursement__c)Database.query(query);
        Test.stopTest();
        
        Assert.areEqual(record.Id, result.Id);
    }
    
    @IsTest
    static void getReversalPayment(){
        cmbls__Payment__c originalPayment = Database.query('SELECT ' + String.join(new List<String>(cmbls__Payment__c.getSObjectType().getDescribe().fields.getMap().keySet()), ',') + ' FROM cmbls__Payment__c LIMIT 1');
        Test.startTest();
        PaymentService.getRepaymentActiveStatuses();
        cmbls__Payment__c reversal = PaymentService.getReversalPayment(originalPayment);
        Test.stopTest();
        
        Assert.areEqual(PaymentUtils.PAYMENT_RECORD_TYPE_CREDIT_ID, reversal.RecordTypeId);
        Assert.areEqual(originalPayment.cmbls__Status__c, reversal.cmbls__Status__c);
        Assert.areEqual(PaymentUtils.PAYMENT_TRANSACTION_TYPE_ADJUSTMENT, reversal.cmbls__Transaction_Type__c);
        Assert.areEqual(PaymentUtils.PAYMENT_SUBTYPE_REVERSAL, reversal.cmbls__Sub_Type__c);
        Assert.areEqual(null, reversal.cmbls__External_Transaction_ID__c);
        Assert.areEqual(null, reversal.Wells_Fargo_Payment_ID_Override__c);
        Assert.areEqual(originalPayment.Id, reversal.cmbls__Reversal_Of__c);
        Assert.areEqual(null, reversal.cmbls__ACH_Batch__c);
        Assert.areEqual(null, reversal.cmbls__Running_Balance__c);
        Assert.areEqual(null, reversal.cmbls__Sequence__c);
        Assert.areEqual(null, reversal.cmbls__Posted_to_accounting__c);
    }
    
    @IsTest
    static void syncACHBatchOnUpdate(){
        cmbls__Repayment__c repayment = [SELECT Id FROM cmbls__Repayment__c LIMIT 1];
        cmbls__Payment__c[] payments = new cmbls__Payment__c[]{
            TestDataFactory.createPayment(repayment.Id, PaymentUtils.PAYMENT_RECORD_TYPE_CREDIT, PaymentUtils.PAYMENT_STATUS_SCHEDULED, 500, System.today(), 'Wells Fargo - NF Collections'),
            TestDataFactory.createPayment(repayment.Id, PaymentUtils.PAYMENT_RECORD_TYPE_CREDIT, PaymentUtils.PAYMENT_STATUS_SCHEDULED, 300, System.today(), 'Wells Fargo - NFAS2 Collections'),
            TestDataFactory.createPayment(repayment.Id, PaymentUtils.PAYMENT_RECORD_TYPE_CREDIT, PaymentUtils.PAYMENT_STATUS_SCHEDULED, 500, System.today().addDays(1), 'Wells Fargo - NF Collections'),
            TestDataFactory.createPayment(repayment.Id, PaymentUtils.PAYMENT_RECORD_TYPE_CREDIT, PaymentUtils.PAYMENT_STATUS_SCHEDULED, 300, System.today().addDays(1), 'Wells Fargo - NFAS2 Collections')
        };
        insert payments;
        Test.startTest();
        payments[0].cmbls__ACH_Processor__c = 'ACH.com';
        payments[0].cmbls__Effective_Date__c = System.today().addDays(1);
        payments[1].cmbls__Effective_Date__c = System.today().addDays(1);
        payments[2].cmbls__ACH_Processor__c = 'Wells Fargo - QBF Funding';
        payments[3].cmbls__Effective_Date__c = System.today().addDays(1);
        update payments;
        Test.stopTest();
    }
    
    @IsTest
    static void paymentReversalOnInsert(){
        cmbls__Repayment__c repayment = [SELECT Id FROM cmbls__Repayment__c];
        cmbls__Payment__c distPayment = TestDataFactory.createPayment(repayment.Id, PaymentUtils.PAYMENT_RECORD_TYPE_CREDIT, PaymentUtils.PAYMENT_STATUS_SETTLED, 4000, System.today().addDays(-1), null);
        distPayment.cmbls__Transaction_Type__c = 'Distribution';
        insert distPayment;
        
        Date nextPaymentDate = cmbls.DatetimeUtils.getNextValidDate(System.today().addDays(10));
        cmbls__Repayment_Schedule__c[] schedules = new cmbls__Repayment_Schedule__c[]{
            TestDataFactory.createRepaymentSchedule(repayment.Id),
            TestDataFactory.createRepaymentSchedule(repayment.Id)
        };
        schedules[0].cmbls__Active__c = true;
        schedules[0].cmbls__Next_Payment_Date__c = nextPaymentDate;
        schedules[1].cmbls__Next_Payment_Date__c = nextPaymentDate;
        insert schedules;
        
        schedules = [SELECT Id, cmbls__Next_Payment_Date__c FROM cmbls__Repayment_Schedule__c WHERE cmbls__Repayment__c = :repayment.Id ORDER BY cmbls__Active__c DESC];
        Assert.areEqual(nextPaymentDate, schedules[0].cmbls__Next_Payment_Date__c);
        Assert.areEqual(nextPaymentDate, schedules[1].cmbls__Next_Payment_Date__c);
        
        repayment = [SELECT Id, cmbls__Status__c, cmbls__Open_Balance__c FROM cmbls__Repayment__c];
        Assert.areEqual(distPayment.cmbls__Transaction_Amount__c, repayment.cmbls__Open_Balance__c);
        Assert.areEqual(RepaymentUtils.STATUS_ACTIVE, repayment.cmbls__Status__c);
        
        cmbls__Payment__c[] payments = new cmbls__Payment__c[]{
            TestDataFactory.createPayment(repayment.Id, PaymentUtils.PAYMENT_RECORD_TYPE_DEBIT, PaymentUtils.PAYMENT_STATUS_SETTLED, 3000, System.today(), null),
            TestDataFactory.createPayment(repayment.Id, PaymentUtils.PAYMENT_RECORD_TYPE_DEBIT, PaymentUtils.PAYMENT_STATUS_SETTLED, 1000, System.today(), null)
        };
        insert payments;
        
        repayment = [SELECT Id, cmbls__Status__c, cmbls__Open_Balance__c FROM cmbls__Repayment__c];
        
        Assert.areEqual(0, repayment.cmbls__Open_Balance__c);
        Assert.areEqual(RepaymentUtils.STATUS_COMPLETE, repayment.cmbls__Status__c);
        
        Test.startTest();
        cmbls__Payment__c reversal = TestDataFactory.createPayment(repayment.Id, PaymentUtils.PAYMENT_RECORD_TYPE_CREDIT, PaymentUtils.PAYMENT_STATUS_SETTLED, 1000, System.today(), null);
        reversal.cmbls__Transaction_Type__c = PaymentUtils.PAYMENT_TRANSACTION_TYPE_ADJUSTMENT;
        reversal.cmbls__Sub_Type__c = PaymentUtils.PAYMENT_SUBTYPE_REVERSAL;
        insert reversal;
        Test.stopTest();
        
        repayment = [SELECT Id, cmbls__Status__c  FROM cmbls__Repayment__c];
        Assert.areEqual(RepaymentUtils.STATUS_ACTIVE, repayment.cmbls__Status__c);
        
        schedules = [SELECT Id, cmbls__Next_Payment_Date__c FROM cmbls__Repayment_Schedule__c WHERE cmbls__Repayment__c = :repayment.Id ORDER BY cmbls__Active__c DESC];
        Assert.areNotEqual(nextPaymentDate, schedules[0].cmbls__Next_Payment_Date__c);
        Assert.areEqual(nextPaymentDate, schedules[1].cmbls__Next_Payment_Date__c);
    }
}