unpackaged/main/default/objects/cmbls__ACH_Batch__c/cmbls__ACH_Batch__c.object-meta.xml
<CustomObject>
    <label>ACH Batch</label>
    <nameField>
        <displayFormat>BATCH-{0000000}</displayFormat>
        <label>ACH Batch Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ACH Batches</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/cmbls__ACH_Batch__c/fields/cmbls__Status__c.field-meta.xml
<CustomField>
    <fullName>cmbls__Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Partial Success</fullName>
            </value>
            <value>
                <fullName>Resubmission</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/cmbls__Payment__c/cmbls__Payment__c.object-meta.xml
<CustomObject>
    <label>Payment</label>
    <nameField>
        <displayFormat>PMT-{0000}</displayFormat>
        <label>Payment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/cmbls__Payment__c/fields/cmbls__ACH_Batch__c.field-meta.xml
<CustomField>
    <fullName>cmbls__ACH_Batch__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ACH Batch</label>
    <referenceTo>cmbls__ACH_Batch__c</referenceTo>
    <relationshipName>Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/cmbls__Payment__c/fields/cmbls__ACH_Processor__c.field-meta.xml
<CustomField>
    <fullName>cmbls__ACH_Processor__c</fullName>
    <label>ACH Processor</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Wells Fargo - NF Collections</fullName>
            </value>
            <value>
                <fullName>Wells Fargo - NFAS2 Collections</fullName>
            </value>
            <value>
                <fullName>Wells Fargo - NF Funding</fullName>
            </value>
            <value>
                <fullName>Wells Fargo - QBF Funding</fullName>
            </value>
            <value>
                <fullName>Wells Fargo - NFSPV1 Collections</fullName>
            </value>
            <value>
                <fullName>Wells Fargo - NFSPV2 Collections</fullName>
            </value>
            <value>
                <fullName>Wells Fargo - NFAS3 Collections</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/cmbls__Payment__c/fields/cmbls__Interest_Payment_Amt__c.field-meta.xml
<CustomField>
    <fullName>cmbls__Interest_Payment_Amt__c</fullName>
    <label>Interest Payment Amt</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/cmbls__Payment__c/fields/cmbls__Repayment__c.field-meta.xml
<CustomField>
    <fullName>cmbls__Repayment__c</fullName>
    <label>Repayment</label>
    <referenceTo>cmbls__Repayment__c</referenceTo>
    <relationshipLabel>Payments</relationshipLabel>
    <relationshipName>Payments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/cmbls__Payment__c/fields/cmbls__Status__c.field-meta.xml
<CustomField>
    <fullName>cmbls__Status__c</fullName>
    <inlineHelpText>Scheduled: Created and not submitted
Pending: Submitted to the ACH provider, but not yet settled.
Settled: The ACH payment was pulled successfully from the customer's account
Failed: Returned a failed response from the ACH provider</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>cmbls__Transaction_Type__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>Pre-Pending</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Settled</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Fees Applied</fullName>
            </value>
            <value>
                <fullName>Fees Collected</fullName>
            </value>
            <value>
                <fullName>Fees Reversed</fullName>
            </value>
            <value>
                <fullName>Applied</fullName>
            </value>
            <value>
                <fullName>Sent Error</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/cmbls__Payment__c/fields/cmbls__Sub_Type__c.field-meta.xml
<CustomField>
    <fullName>cmbls__Sub_Type__c</fullName>
    <label>Sub Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>cmbls__Transaction_Type__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Default</fullName>
            </value>
            <value>
                <fullName>General</fullName>
            </value>
            <value>
                <fullName>Renewal Payoff</fullName>
            </value>
            <value>
                <fullName>Add-on</fullName>
            </value>
            <value>
                <fullName>RTR</fullName>
            </value>
            <value>
                <fullName>Net Funding</fullName>
            </value>
            <value>
                <fullName>Fee Balance</fullName>
            </value>
            <value>
                <fullName>Write Off</fullName>
            </value>
            <value>
                <fullName>Write Off Fee Balance</fullName>
            </value>
            <value>
                <fullName>Overpayment Refund</fullName>
            </value>
            <value>
                <fullName>Initial Balance</fullName>
            </value>
            <value>
                <fullName>Refund</fullName>
            </value>
            <value>
                <fullName>Reversal</fullName>
            </value>
            <value>
                <fullName>Deferred Interest Write Off</fullName>
            </value>
            <value>
                <fullName>Collection on Write-Off</fullName>
            </value>
            <value>
                <fullName>Renewal Fee Payoff</fullName>
            </value>
            <value>
                <fullName>Interest Charge</fullName>
            </value>
            <value>
                <fullName>Reserve Request</fullName>
            </value>
            <value>
                <fullName>Payment From Reserve</fullName>
            </value>
            <value>
                <fullName>Refund from Reserve</fullName>
            </value>
            <value>
                <fullName>Adjustment</fullName>
            </value>
            <value>
                <fullName>Consulting Fee</fullName>
            </value>
            <value>
                <fullName>Additional Principal Payment</fullName>
            </value>
            <value>
                <fullName>Starting Draw Reserve Balance</fullName>
            </value>
            <value>
                <fullName>Extension Fee</fullName>
            </value>
            <value>
                <fullName>Maturity Default</fullName>
            </value>
            <value>
                <fullName>Payoff</fullName>
            </value>
            <value>
                <fullName>Origination Fee</fullName>
            </value>
            <value>
                <fullName>Recovery</fullName>
            </value>
            <value>
                <fullName>Unwind</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/cmbls__Payment__c/fields/cmbls__Transaction_Amount__c.field-meta.xml
<CustomField>
    <fullName>cmbls__Transaction_Amount__c</fullName>
    <label>Transaction Amount</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/cmbls__Payment__c/fields/cmbls__Transaction_Type__c.field-meta.xml
<CustomField>
    <fullName>cmbls__Transaction_Type__c</fullName>
    <description>This field indicates wether if it is a Fee or a Payment, and should be displayed in the page detail layout.</description>
    <inlineHelpText>This field indicates wether if it is a Fee or a Payment, and should be displayed in the page detail layout.</inlineHelpText>
    <label>Transaction Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Fee</fullName>
            </value>
            <value>
                <fullName>Payment</fullName>
            </value>
            <value>
                <fullName>Adjustment</fullName>
            </value>
            <value>
                <fullName>Distribution</fullName>
            </value>
            <value>
                <fullName>Fee Collection</fullName>
            </value>
            <value>
                <fullName>Reserve</fullName>
            </value>
            <value>
                <fullName>Interest</fullName>
            </value>
            <value>
                <fullName>Draw</fullName>
            </value>
            <value>
                <fullName>Draw Reserve</fullName>
            </value>
            <value>
                <fullName>Deferred Fee</fullName>
            </value>
            <value>
                <fullName>Lender Reimbursement</fullName>
            </value>
            <value>
                <fullName>Discount</fullName>
            </value>
            <value>
                <fullName>Payoff</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/cmbls__Repayment__c/cmbls__Repayment__c.object-meta.xml
<CustomObject>
    <label>Repayment</label>
    <nameField>
        <displayFormat>RPMT-{0000000}</displayFormat>
        <label>Repayment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Repayments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/cmbls__Repayment__c/fields/cmbls__ACH_Processor__c.field-meta.xml
<CustomField>
    <fullName>cmbls__ACH_Processor__c</fullName>
    <description>The name of the processor being used</description>
    <inlineHelpText>The name of the processor being used</inlineHelpText>
    <label>ACH Processor</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Wells Fargo - NF Collections</fullName>
            </value>
            <value>
                <fullName>Wells Fargo - NFAS2 Collections</fullName>
            </value>
            <value>
                <fullName>Wells Fargo - NFSPV1 Collections</fullName>
            </value>
            <value>
                <fullName>Wells Fargo - NFSPV2 Collections</fullName>
            </value>
            <value>
                <fullName>Wells Fargo - NFAS3 Collections</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/cmbls__Repayment__c/fields/cmbls__Status__c.field-meta.xml
<CustomField>
    <fullName>cmbls__Status__c</fullName>
    <description>Active, pause, complete, and new</description>
    <inlineHelpText>Active, pause, complete, and new</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Temporary Pause</fullName>
            </value>
            <value>
                <fullName>Pause</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Write Off</fullName>
            </value>
            <value>
                <fullName>Recovery</fullName>
            </value>
            <value>
                <fullName>Unwind</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/PaymentSelector.cls
/**
 * PaymentSelector class
 * @author CloudMyBiz (r)
 * @date 9/6/2022
 * @description
 * @group 
 */

public inherited sharing class PaymentSelector{
    
    public static cmbls__Payment__c getPaymentById(Id paymentId){
        cmbls__Payment__c[] records = getPaymentByIds(new Set<Id>{paymentId});
        return records.isEmpty() ? null : records[0];
    }
    
    public static cmbls__Payment__c[] getPaymentByIds(Set<Id> paymentIds){
        return [
            SELECT Id, Name, cmbls__Repayment__c, cmbls__Sub_Type__c, cmbls__Transaction_Amount__c, cmbls__ACH_Processor__c, cmbls__Status__c, cmbls__Notes__c
            FROM cmbls__Payment__c
            WHERE Id IN :paymentIds
        ];
    }
    
    public static Map<Id, cmbls__Payment__c[]> getScheduledCreditPaymentsByRepaymentIds(Set<Id> repaymentIds){
        Map<Id, cmbls__Payment__c[]> output = new Map<Id, cmbls__Payment__c[]>();
        cmbls__Payment__c[] records = [
            SELECT Id, cmbls__Notes__c, cmbls__Repayment__c
            FROM cmbls__Payment__c
            WHERE
                RecordTypeId = :PaymentUtils.PAYMENT_RECORD_TYPE_CREDIT_ID AND
                cmbls__Transaction_Type__c = :PaymentUtils.PAYMENT_TRANSACTION_TYPE_PAYMENT AND
                cmbls__Status__c = :PaymentUtils.PAYMENT_STATUS_SCHEDULED AND
                cmbls__Repayment__c IN :repaymentIds
        ];
        for(cmbls__Payment__c item :records){
            if(output.containsKey(item.cmbls__Repayment__c)){
                output.get(item.cmbls__Repayment__c).add(item);
            }else{
                output.put(item.cmbls__Repayment__c, new cmbls__Payment__c[]{item});
            }
        }
        return output;
    }
    
    public static Map<Id, Decimal> getSumPendingDebitPaymentsByRepayment(Set<Id> repaymentIds){
        Map<Id, Decimal> output = new Map<Id, Decimal>();
        AggregateResult[] records = [
            SELECT SUM(cmbls__Transaction_Amount__c) total, cmbls__Repayment__c repayment
            FROM cmbls__Payment__c
            WHERE cmbls__Repayment__c IN :repaymentIds AND
                  cmbls__Status__c = :PaymentUtils.PAYMENT_STATUS_PENDING AND
                  RecordTypeId = :PaymentUtils.PAYMENT_RECORD_TYPE_DEBIT_ID
            GROUP BY cmbls__Repayment__c
        ];
        for(AggregateResult item :records) output.put((Id)item.get('repayment'), (Decimal)item.get('total'));
        return output;
    }
    
    public static Map<Id, Decimal> getSumPendingSettledDebitPaymentsByRepayment(Set<Id> repaymentIds){
        Map<Id, Decimal> output = new Map<Id, Decimal>();
        AggregateResult[] records =  [
            SELECT SUM(cmbls__Interest_Payment_Amt__c) total, cmbls__Repayment__c repayment
            FROM cmbls__Payment__c
            WHERE cmbls__Repayment__c IN :repaymentIds AND
                  cmbls__Status__c IN :new Set<String>{PaymentUtils.PAYMENT_STATUS_PENDING, PaymentUtils.PAYMENT_STATUS_SETTLED} AND
                  RecordTypeId = :PaymentUtils.PAYMENT_RECORD_TYPE_DEBIT_ID
            GROUP BY cmbls__Repayment__c
        ];
        for(AggregateResult item :records) output.put((Id)item.get('repayment'), (Decimal)item.get('total'));
        return output;
    }
	
	public static Map<Id, Set<Id>> getScheduledPaymentsByBatchIds(Set<Id> achBatches){
        Map<Id, Set<Id>> output = new Map<Id, Set<Id>>();
        for(cmbls__Payment__c item :[SELECT Id, cmbls__ACH_Batch__c FROM cmbls__Payment__c WHERE cmbls__Status__c =:PaymentUtils.PAYMENT_STATUS_SCHEDULED AND cmbls__ACH_Batch__c IN :achBatches]){
            if(!output.containsKey(item.cmbls__ACH_Batch__c)) output.put(item.cmbls__ACH_Batch__c, new Set<Id>());
            output.get(item.cmbls__ACH_Batch__c).add(item.Id);
        }
        return output;
    }
}