unpackaged/main/default/objects/cmbls__InterestAccrual__c/cmbls__InterestAccrual__c.object-meta.xml
<CustomObject>
    <label>Interest Accrual</label>
    <nameField>
        <displayFormat>Int-Accrual-{0000}</displayFormat>
        <label>Interest Accrual Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Interest Accruals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/cmbls__InterestAccrual__c/fields/cmbls__Repayment__c.field-meta.xml
<CustomField>
    <fullName>cmbls__Repayment__c</fullName>
    <inlineHelpText>Related Repayment ID</inlineHelpText>
    <label>Repayment</label>
    <referenceTo>cmbls__Repayment__c</referenceTo>
    <relationshipLabel>Interest Accruals</relationshipLabel>
    <relationshipName>Interest_Accruals</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/cmbls__Repayment__c/cmbls__Repayment__c.object-meta.xml
<CustomObject>
    <label>Repayment</label>
    <nameField>
        <displayFormat>RPMT-{0000000}</displayFormat>
        <label>Repayment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Repayments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/classes/InterestAccrualsSelector.cls
/**
 * InterestAccrualsSelector class
 * @author CloudMyBiz (r)
 * @date 9/6/2022
 * @description
 * @group 
 */

public inherited sharing class InterestAccrualsSelector{

    public static Map<Id, Decimal> getSumInterestAccrualsByRepayment(Set<Id> repaymentIds){
        Map<Id, Decimal> output = new Map<Id, Decimal>();
        AggregateResult[] records = [
            SELECT SUM(cmbls__Interest_Amount_for_Principal_for_Period__c) total, cmbls__Repayment__c repayment
            FROM cmbls__InterestAccrual__c
            WHERE cmbls__Repayment__c IN :repaymentIds
            GROUP BY cmbls__Repayment__c
        ];
        for(AggregateResult item :records) output.put((Id)item.get('repayment'), (Decimal)item.get('total'));
        return output;
    }
}