unpackaged/main/default/objects/cmbls__Repayment__c/cmbls__Repayment__c.object-meta.xml
<CustomObject>
    <label>Repayment</label>
    <nameField>
        <displayFormat>RPMT-{0000000}</displayFormat>
        <label>Repayment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Repayments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/cmbls__Repayment__c/fields/cmbls__ACH_Processor__c.field-meta.xml
<CustomField>
    <fullName>cmbls__ACH_Processor__c</fullName>
    <description>The name of the processor being used</description>
    <inlineHelpText>The name of the processor being used</inlineHelpText>
    <label>ACH Processor</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Wells Fargo - NF Collections</fullName>
            </value>
            <value>
                <fullName>Wells Fargo - NFAS2 Collections</fullName>
            </value>
            <value>
                <fullName>Wells Fargo - NFSPV1 Collections</fullName>
            </value>
            <value>
                <fullName>Wells Fargo - NFSPV2 Collections</fullName>
            </value>
            <value>
                <fullName>Wells Fargo - NFAS3 Collections</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/cmbls__Repayment__c/fields/cmbls__Status__c.field-meta.xml
<CustomField>
    <fullName>cmbls__Status__c</fullName>
    <description>Active, pause, complete, and new</description>
    <inlineHelpText>Active, pause, complete, and new</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Temporary Pause</fullName>
            </value>
            <value>
                <fullName>Pause</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Write Off</fullName>
            </value>
            <value>
                <fullName>Recovery</fullName>
            </value>
            <value>
                <fullName>Unwind</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/cmbls__Repayment_Schedule__c/cmbls__Repayment_Schedule__c.object-meta.xml
<CustomObject>
    <label>Repayment Schedule</label>
    <nameField>
        <displayFormat>RS-{000000}</displayFormat>
        <label>Repayment Schedule</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Repayment Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/cmbls__Repayment_Schedule__c/fields/cmbls__End_Date__c.field-meta.xml
<CustomField>
    <fullName>cmbls__End_Date__c</fullName>
    <inlineHelpText>This will be the final payment pulled. If populated, the system will no longer schedule payments for an Effective Date that is after this date. Note: An End Date is not required. If null, the system will continue to create payments until there is no longer a balance.</inlineHelpText>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/cmbls__Repayment_Schedule__c/fields/cmbls__Next_Payment_Date__c.field-meta.xml
<CustomField>
    <fullName>cmbls__Next_Payment_Date__c</fullName>
    <inlineHelpText>This is the Effective Date of the next ACH payment that will be created by the Repayment Schedule. This field is populated and updated by the system based on the current values in the Repayment Schedule. Note: This will always roll forward to the next valid business day if it falls on a holiday or weekend.</inlineHelpText>
    <label>Next Payment Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/cmbls__Repayment_Schedule__c/fields/cmbls__Notes__c.field-meta.xml
<CustomField>
    <fullName>cmbls__Notes__c</fullName>
    <label>Notes</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/cmbls__Repayment_Schedule__c/fields/cmbls__Payment_Amount_Method__c.field-meta.xml
<CustomField>
    <fullName>cmbls__Payment_Amount_Method__c</fullName>
    <inlineHelpText>Loans in Recovery - Use "Remaining Settlement Balance", otherwise use "Fixed Amount"</inlineHelpText>
    <label>Payment Amount Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Fixed Amount</fullName>
                <default>true</default>
                <label>Fixed Amount</label>
            </value>
            <value>
                <fullName>Active Invoice Balance</fullName>
            </value>
            <value>
                <fullName>Remaining Settlement Balance</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/cmbls__Repayment_Schedule__c/fields/cmbls__Repayment__c.field-meta.xml
<CustomField>
    <fullName>cmbls__Repayment__c</fullName>
    <label>Repayment</label>
    <referenceTo>cmbls__Repayment__c</referenceTo>
    <relationshipLabel>Repayment Schedules</relationshipLabel>
    <relationshipName>Repayment_Schedules</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/classes/RepaymentScheduleTriggerHandler.cls
/**
 * RepaymentScheduleTriggerHandler class
 * @author CloudMyBiz (r)
 * @date 8/15/2023
 * @description Follows the One Trigger Per Object design pattern, which allows for the control of execution order and recursion.
 * Ideally, business logic should not be included in this class. Trigger handlers are used to control recursion and order of execution and should delegate other work to service classes.
 * @group Trigger Handlers
 */
public inherited sharing class RepaymentScheduleTriggerHandler{
    
    public static Boolean RUN_NEXT_PAYMENT_DATE_VALIDATION = true;
    public static cmbls__Repayment_Schedule__c[] validateNextPaymentDateRecords = new cmbls__Repayment_Schedule__c[]{};
    
    public static void onBeforeInsertUpdate(List<cmbls__Repayment_Schedule__c> records, Map<Id, cmbls__Repayment_Schedule__c> oldMap){
        validateNextPaymentDateRecords = new cmbls__Repayment_Schedule__c[]{};
        Set<Id> repaysId = new Set<Id>();
        Set<String> processor = new Set<String>();
        cmbls__Repayment_Schedule__c[] recordsForValidateNextPaymentDate = new cmbls__Repayment_Schedule__c[]{};
        for(cmbls__Repayment_Schedule__c record :records){
            cmbls__Repayment_Schedule__c oldRecord = oldMap != null ? oldMap.get(record.Id) : null;
            processor.add(record.cmbls__ACH_Processor__c);

            if(record.cmbls__Next_Payment_Date__c != null && (oldRecord == null || oldRecord.cmbls__Next_Payment_Date__c != record.cmbls__Next_Payment_Date__c)){
                recordsForValidateNextPaymentDate.add(record);
            }
            if(Trigger.isBefore){
                repaysId.add(record.cmbls__Repayment__c);
            }
        }

        for(cmbls__Repayment_Schedule__c record :records){
            if(record.cmbls__End_Date__c != null && cmbls.DatetimeUtils.getNextValidDate(record.cmbls__End_Date__c) != record.cmbls__End_Date__c)
            {
                String prevValue = record.cmbls__End_Date__c.month()+ '/' + record.cmbls__End_Date__c.day() + '/' + record.cmbls__End_Date__c.year();
                String newValue = cmbls.DatetimeUtils.getNextValidDate(record.cmbls__End_Date__c).month()+ '/' + cmbls.DatetimeUtils.getNextValidDate(record.cmbls__End_Date__c).day() + '/' + cmbls.DatetimeUtils.getNextValidDate(record.cmbls__End_Date__c).year();

                record.cmbls__Notes__c =  ' End Date has been updated from ' + prevValue + ' to ' + newValue + ' so that the End Date will fall on a business day.';
                record.cmbls__End_Date__c = cmbls.DatetimeUtils.getNextValidDate(record.cmbls__End_Date__c);
            }
        }
        
        if(RUN_NEXT_PAYMENT_DATE_VALIDATION && !System.isBatch() && !System.isFuture()){
            RUN_NEXT_PAYMENT_DATE_VALIDATION = false;
            if(recordsForValidateNextPaymentDate.size() == 1){ //If only one record, we can run the validation immediately
                RepaymentScheduleService.validateNextPaymentDate(recordsForValidateNextPaymentDate[0]);
            }else{//Otherwise, lets prepare a batch to be executed onAfter
                validateNextPaymentDateRecords = recordsForValidateNextPaymentDate;
            }
        }
        if(!repaysId.isEmpty() && Trigger.isInsert) checkingPaymentAmountMethod(records, repaysId);
    }
    
    public static void onAfterInsertUpdate(List<cmbls__Repayment_Schedule__c> records, Map<Id, cmbls__Repayment_Schedule__c> oldMap){
        if(!validateNextPaymentDateRecords.isEmpty() && !System.isBatch() && !System.isFuture()){
            Database.executeBatch(new RSNextPaymentDateBatch(new Map<Id, cmbls__Repayment_Schedule__c>(validateNextPaymentDateRecords).keySet()), RSNextPaymentDateBatch.getBatchSize());
            validateNextPaymentDateRecords = new cmbls__Repayment_Schedule__c[]{};
        }
        if(Trigger.isInsert){
            updateRepaymentStatusToRecovery(records, oldMap);
        }
    }

    public static void checkingPaymentAmountMethod(List<cmbls__Repayment_Schedule__c> records, Set<Id> repaysId){
        Map<Id,cmbls__Repayment__c> mapRepayments = new Map<Id,cmbls__Repayment__c>([SELECT Id, cmbls__Status__c FROM cmbls__Repayment__c WHERE Id IN: repaysId]);
        for(cmbls__Repayment_Schedule__c repaySchedule : records){
            if(mapRepayments.containsKey(repaySchedule.cmbls__Repayment__c) == true &&
                    (mapRepayments.get(repaySchedule.cmbls__Repayment__c).cmbls__Status__c == RepaymentUtils.STATUS_WRITE_OFF ||
                    mapRepayments.get(repaySchedule.cmbls__Repayment__c).cmbls__Status__c == RepaymentUtils.STATUS_RECOVERY) &&
                    repaySchedule.cmbls__Payment_Amount_Method__c != RepaymentUtils.PAYMENT_AMOUNT_METHOD_REMAINING
            ){
                repaySchedule.cmbls__Payment_Amount_Method__c = RepaymentUtils.PAYMENT_AMOUNT_METHOD_REMAINING;
            }
    }
}

    public static void updateRepaymentStatusToRecovery(List<cmbls__Repayment_Schedule__c> records, Map<Id, cmbls__Repayment_Schedule__c> oldMap){
        Map<Id, cmbls__Repayment_Schedule__c> recordsMap = new Map<Id, cmbls__Repayment_Schedule__c>(records);
        List<cmbls__Repayment__c> repayments = new List<cmbls__Repayment__c>();
        for(cmbls__Repayment_Schedule__c repaySchedule :[
                SELECT
                        cmbls__Payment_Amount_Method__c, cmbls__Repayment__r.cmbls__Status__c, cmbls__Repayment__c
                FROM cmbls__Repayment_Schedule__c
                WHERE Id IN: recordsMap.keySet()]
        ){
            if(repaySchedule.cmbls__Repayment__r.cmbls__Status__c == RepaymentUtils.STATUS_WRITE_OFF){
                repayments.add(new cmbls__Repayment__c(
                        Id = repaySchedule.cmbls__Repayment__c,
                        cmbls__Status__c = RepaymentUtils.STATUS_RECOVERY
                ));
            }
        }
        if(!repayments.isEmpty()) update repayments;
    }

}