unpackaged/main/default/objects/cmbls__Repayment__c/cmbls__Repayment__c.object-meta.xml
<CustomObject>
    <label>Repayment</label>
    <nameField>
        <displayFormat>RPMT-{0000000}</displayFormat>
        <label>Repayment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Repayments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/cmbls__Repayment__c/fields/cmbls__Status__c.field-meta.xml
<CustomField>
    <fullName>cmbls__Status__c</fullName>
    <description>Active, pause, complete, and new</description>
    <inlineHelpText>Active, pause, complete, and new</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Temporary Pause</fullName>
            </value>
            <value>
                <fullName>Pause</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Write Off</fullName>
            </value>
            <value>
                <fullName>Recovery</fullName>
            </value>
            <value>
                <fullName>Unwind</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/cmbls__Repayment__c/fields/Expected_Payment_Amount__c.field-meta.xml
<CustomField>
    <fullName>Expected_Payment_Amount__c</fullName>
    <defaultValue>0</defaultValue>
    <description>SUM of Amortization Schdules Payment Amount up to today's date. Used in the balance refresh process. Populated nightly by an apex job.</description>
    <inlineHelpText>SUM of Amortization Schdules Payment Amount up to today's date. Used in the balance refresh process. Populated nightly by an apex job.</inlineHelpText>
    <label>Expected Payment Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/classes/BatchCalcRepaymentExpectedPaymentAmtTest.cls
@IsTest
public with sharing class BatchCalcRepaymentExpectedPaymentAmtTest {

    @IsTest
    public static void testBatchClass() {
     
        Account acc = TestDataFactory.createAccount();
        insert acc;

        cmbls__Repayment__c repayment = TestDataFactory.createRepayment(acc.Id);
        repayment.Expected_Payment_Amount__c = 0.0;
        insert repayment;

        List<cmbls__Amortization_Schedule__c> amortSchs = new List<cmbls__Amortization_Schedule__c>();
        for (Integer i = 0; i < 10; i++) {
            cmbls__Amortization_Schedule__c amortSch = TestDataFactory.createAmortizationSchedule(repayment.Id, i);
            amortSchs.add(amortSch);
        }
        insert amortSchs;

        Test.startTest();
            BatchCalcRepaymentExpectedPaymentAmt batch = new BatchCalcRepaymentExpectedPaymentAmt();
            Database.executeBatch(batch);
        Test.stopTest();

        List<cmbls__Repayment__c> updatedRepayment = [SELECT Id, Expected_Payment_Amount__c
                                                      FROM cmbls__Repayment__c
                                                      WHERE cmbls__Status__c in ('Active','Pause')];  

        system.assertNotEquals(null, updatedRepayment, 'Repayment record is not found');
        system.Assert.areEqual(updatedRepayment[0].Expected_Payment_Amount__c, 45, 'Expected_Payment_Amount__c calculation is not correct');

    }

    @IsTest
    public static void testBatchClassInvocable() {
     
        Account acc = TestDataFactory.createAccount();
        insert acc;

        cmbls__Repayment__c repayment = TestDataFactory.createRepayment(acc.Id);
        repayment.Expected_Payment_Amount__c = 0.0;
        insert repayment;

        List<cmbls__Amortization_Schedule__c> amortSchs = new List<cmbls__Amortization_Schedule__c>();
        for (Integer i = 0; i < 10; i++) {
            cmbls__Amortization_Schedule__c amortSch = TestDataFactory.createAmortizationSchedule(repayment.Id, i);
            amortSchs.add(amortSch);
        }
        insert amortSchs;
        
        List<Id> repayments = new List<Id>();
        repayments.add(repayment.Id);
        
        Test.startTest();
            BatchCalcRepaymentExpectedPaymentAmt.calculateExpectedPaymentAmount(repayments);
        Test.stopTest();

        List<cmbls__Repayment__c> updatedRepayment = [SELECT Id, Expected_Payment_Amount__c
                                                      FROM cmbls__Repayment__c
                                                      WHERE cmbls__Status__c in ('Active','Pause')];  

        system.assertNotEquals(null, updatedRepayment, 'Repayment record is not found');
        system.Assert.areEqual(updatedRepayment[0].Expected_Payment_Amount__c, 45, 'Expected_Payment_Amount__c calculation is not correct');

    }
}