unpackaged/main/default/objects/cmbls__Repayment__c/cmbls__Repayment__c.object-meta.xml
<CustomObject>
    <label>Repayment</label>
    <nameField>
        <displayFormat>RPMT-{0000000}</displayFormat>
        <label>Repayment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Repayments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/cmbls__Repayment__c/fields/cmbls__Status__c.field-meta.xml
<CustomField>
    <fullName>cmbls__Status__c</fullName>
    <description>Active, pause, complete, and new</description>
    <inlineHelpText>Active, pause, complete, and new</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Temporary Pause</fullName>
            </value>
            <value>
                <fullName>Pause</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Write Off</fullName>
            </value>
            <value>
                <fullName>Recovery</fullName>
            </value>
            <value>
                <fullName>Unwind</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/cmbls__Repayment__c/fields/Pause_Date__c.field-meta.xml
<CustomField>
    <fullName>Pause_Date__c</fullName>
    <label>Pause Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/cmbls__Repayment__c/fields/Resume_Date__c.field-meta.xml
<CustomField>
    <fullName>Resume_Date__c</fullName>
    <label>Resume Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/cmbls__Repayment_Schedule__c/cmbls__Repayment_Schedule__c.object-meta.xml
<CustomObject>
    <label>Repayment Schedule</label>
    <nameField>
        <displayFormat>RS-{000000}</displayFormat>
        <label>Repayment Schedule</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Repayment Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/cmbls__Repayment_Schedule__c/fields/cmbls__Next_Payment_Date__c.field-meta.xml
<CustomField>
    <fullName>cmbls__Next_Payment_Date__c</fullName>
    <inlineHelpText>This is the Effective Date of the next ACH payment that will be created by the Repayment Schedule. This field is populated and updated by the system based on the current values in the Repayment Schedule. Note: This will always roll forward to the next valid business day if it falls on a holiday or weekend.</inlineHelpText>
    <label>Next Payment Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/cmbls__Repayment_Schedule__c/fields/cmbls__Repayment__c.field-meta.xml
<CustomField>
    <fullName>cmbls__Repayment__c</fullName>
    <label>Repayment</label>
    <referenceTo>cmbls__Repayment__c</referenceTo>
    <relationshipLabel>Repayment Schedules</relationshipLabel>
    <relationshipName>Repayment_Schedules</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/classes/RepaymentStatusBatch.cls
/**
 * RepaymentStatusBatch class
 * @author CloudMyBiz (r)
 * @date 3/22/2022
 * @info If you use a QueryLocator object, the governor limit for the total number of records retrieved by SOQL queries is bypassed
 * Use the iterable to create a complex scope for the batch job. You can also use the iterable to create your own custom process for iterating through the list.
  (If you use an iterable, the governor limit for the total number of records retrieved by SOQL queries is still enforced.)
 * @group Batch
 */
global class RepaymentStatusBatch implements Database.Batchable<SObject>, Schedulable{
    
    global Database.QueryLocator start(Database.BatchableContext bc){
        return Database.getQueryLocator('SELECT Id, Pause_Date__c, Resume_Date__c FROM cmbls__Repayment__c WHERE Pause_Date__c = TODAY OR Resume_Date__c = TODAY');
    }
    
    global void execute(Database.BatchableContext bc, List<SObject> scope){
        Set<Id> repaymentsToResume = new Set<Id>();
        cmbls__Repayment__c[] repaymentsToUpdate = new cmbls__Repayment__c[]{};
        
        for(SObject item :scope){
            cmbls__Repayment__c repayment = (cmbls__Repayment__c)item;
            if(repayment.Pause_Date__c == System.today()){
                repayment.cmbls__Status__c = RepaymentUtils.STATUS_TEMPORARY_PAUSE;
            }else if(repayment.Resume_Date__c == System.today()){
                repayment.cmbls__Status__c = RepaymentUtils.STATUS_ACTIVE;
                repaymentsToResume.add(repayment.Id);
            }
            repaymentsToUpdate.add(repayment);
        }
        
        cmbls__Repayment_Schedule__c[] schedules = RepaymentScheduleSelector.getRepaymentSchedulesByRepaymentIds(repaymentsToResume);
        for(cmbls__Repayment_Schedule__c schedule :schedules){
            schedule.cmbls__Next_Payment_Date__c = null;
        }
        
        Database.update(repaymentsToUpdate);
        Database.update(schedules);
    }
    
    global void finish(Database.BatchableContext bc){}
    
    global void execute(SchedulableContext param1){
        Database.executeBatch(new RepaymentStatusBatch());
    }
}