unpackaged/main/default/objects/cmbls__Repayment__c/cmbls__Repayment__c.object-meta.xml
<CustomObject>
    <label>Repayment</label>
    <nameField>
        <displayFormat>RPMT-{0000000}</displayFormat>
        <label>Repayment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Repayments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/cmbls__Repayment__c/fields/Pause_Date__c.field-meta.xml
<CustomField>
    <fullName>Pause_Date__c</fullName>
    <label>Pause Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/cmbls__Repayment__c/fields/Resume_Date__c.field-meta.xml
<CustomField>
    <fullName>Resume_Date__c</fullName>
    <label>Resume Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/cmbls__Repayment_Schedule__c/cmbls__Repayment_Schedule__c.object-meta.xml
<CustomObject>
    <label>Repayment Schedule</label>
    <nameField>
        <displayFormat>RS-{000000}</displayFormat>
        <label>Repayment Schedule</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Repayment Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/cmbls__Repayment_Schedule__c/fields/cmbls__Next_Payment_Date__c.field-meta.xml
<CustomField>
    <fullName>cmbls__Next_Payment_Date__c</fullName>
    <inlineHelpText>This is the Effective Date of the next ACH payment that will be created by the Repayment Schedule. This field is populated and updated by the system based on the current values in the Repayment Schedule. Note: This will always roll forward to the next valid business day if it falls on a holiday or weekend.</inlineHelpText>
    <label>Next Payment Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/cmbls__Repayment_Schedule__c/fields/cmbls__Repayment__c.field-meta.xml
<CustomField>
    <fullName>cmbls__Repayment__c</fullName>
    <label>Repayment</label>
    <referenceTo>cmbls__Repayment__c</referenceTo>
    <relationshipLabel>Repayment Schedules</relationshipLabel>
    <relationshipName>Repayment_Schedules</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/classes/PauseResumeRepaymentScheduleTest.cls
/**
 * PauseResumeRepaymentScheduleTest class
 * @author CloudMyBiz (r)
 * @date 3/22/2022
 * @description
 * @group 
 */

@IsTest
private class PauseResumeRepaymentScheduleTest{
    
    @TestSetup static void setupMethod(){
        Account acc = TestDataFactory.createAccount();
        insert acc;
        
        cmbls__Repayment__c repayment = TestDataFactory.createRepayment(acc.Id);
        insert repayment;
        
        cmbls__Repayment_Schedule__c[] schedules = new cmbls__Repayment_Schedule__c[]{
            TestDataFactory.createRepaymentSchedule(repayment.Id),
            TestDataFactory.createRepaymentSchedule(repayment.Id)
        };
        schedules[0].cmbls__Next_Payment_Date__c = cmbls.DatetimeUtils.getNextValidDate(System.today().addDays(7));
        schedules[1].cmbls__Next_Payment_Date__c = cmbls.DatetimeUtils.getNextValidDate(System.today().addDays(7));
        insert schedules;
    }
    
    @IsTest
    static void mainInvocableMethod(){
        cmbls__Repayment__c repayment = [SELECT Id, Pause_Date__c, Resume_Date__c FROM cmbls__Repayment__c];
        System.assertEquals(null, repayment.Pause_Date__c);
        System.assertEquals(null, repayment.Resume_Date__c);
        PauseResumeRepaymentSchedule.PauseResumeRequest mainRequest = new PauseResumeRepaymentSchedule.PauseResumeRequest();
        mainRequest.repaymentId = repayment.Id;
        mainRequest.resumeDate = System.today().addDays(10);
        
        Test.startTest();
        PauseResumeRepaymentSchedule.PauseResumeResult[] mainResponse = PauseResumeRepaymentSchedule.mainInvocableMethod(new PauseResumeRepaymentSchedule.PauseResumeRequest[]{});
        System.assertEquals(1, mainResponse.size());
        System.assert(mainResponse[0].output.startsWith('Unable to Pause the Repayment Schedule'));
        
        repayment = [SELECT Id, Pause_Date__c, Resume_Date__c FROM cmbls__Repayment__c];
        System.assertEquals(null, repayment.Pause_Date__c);
        System.assertEquals(null, repayment.Resume_Date__c);
        
        mainResponse = PauseResumeRepaymentSchedule.mainInvocableMethod(new PauseResumeRepaymentSchedule.PauseResumeRequest[]{mainRequest});
        System.assertEquals(1, mainResponse.size());
        System.assertEquals(String.format(PauseResumeRepaymentSchedule.SUCCESS_MESSAGE, new String[]{System.today().addDays(10).format()}), mainResponse[0].output);
    
        repayment = [SELECT Id, Pause_Date__c, Resume_Date__c FROM cmbls__Repayment__c];
        System.assertEquals(System.today(), repayment.Pause_Date__c);
        System.assertEquals(System.today().addDays(10), repayment.Resume_Date__c);
        Test.stopTest();
    }
}