unpackaged/main/default/objects/cmbls__Repayment__c/cmbls__Repayment__c.object-meta.xml
<CustomObject>
    <label>Repayment</label>
    <nameField>
        <displayFormat>RPMT-{0000000}</displayFormat>
        <label>Repayment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Repayments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/cmbls__Repayment__c/fields/cmbls__ACH_Processor__c.field-meta.xml
<CustomField>
    <fullName>cmbls__ACH_Processor__c</fullName>
    <description>The name of the processor being used</description>
    <inlineHelpText>The name of the processor being used</inlineHelpText>
    <label>ACH Processor</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Wells Fargo - NF Collections</fullName>
            </value>
            <value>
                <fullName>Wells Fargo - NFAS2 Collections</fullName>
            </value>
            <value>
                <fullName>Wells Fargo - NFSPV1 Collections</fullName>
            </value>
            <value>
                <fullName>Wells Fargo - NFSPV2 Collections</fullName>
            </value>
            <value>
                <fullName>Wells Fargo - NFAS3 Collections</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/cmbls__Repayment_Schedule__c/cmbls__Repayment_Schedule__c.object-meta.xml
<CustomObject>
    <label>Repayment Schedule</label>
    <nameField>
        <displayFormat>RS-{000000}</displayFormat>
        <label>Repayment Schedule</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Repayment Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/cmbls__Repayment_Schedule__c/fields/cmbls__Active__c.field-meta.xml
<CustomField>
    <fullName>cmbls__Active__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/cmbls__Repayment_Schedule__c/fields/cmbls__Days__c.field-meta.xml
<CustomField>
    <fullName>cmbls__Days__c</fullName>
    <inlineHelpText>Specifies the day/date of the payment frequency</inlineHelpText>
    <label>Days</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <controllingField>cmbls__Preset__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Monday</fullName>
            </value>
            <value>
                <fullName>Tuesday</fullName>
            </value>
            <value>
                <fullName>Wednesday</fullName>
            </value>
            <value>
                <fullName>Thursday</fullName>
            </value>
            <value>
                <fullName>Friday</fullName>
            </value>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>9</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
            <value>
                <fullName>11</fullName>
            </value>
            <value>
                <fullName>12</fullName>
            </value>
            <value>
                <fullName>13</fullName>
            </value>
            <value>
                <fullName>14</fullName>
            </value>
            <value>
                <fullName>15</fullName>
            </value>
            <value>
                <fullName>16</fullName>
            </value>
            <value>
                <fullName>17</fullName>
            </value>
            <value>
                <fullName>18</fullName>
            </value>
            <value>
                <fullName>19</fullName>
            </value>
            <value>
                <fullName>20</fullName>
            </value>
            <value>
                <fullName>21</fullName>
            </value>
            <value>
                <fullName>22</fullName>
            </value>
            <value>
                <fullName>23</fullName>
            </value>
            <value>
                <fullName>24</fullName>
            </value>
            <value>
                <fullName>25</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/cmbls__Repayment_Schedule__c/fields/cmbls__Default__c.field-meta.xml
<CustomField>
    <fullName>cmbls__Default__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Default</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/cmbls__Repayment_Schedule__c/fields/cmbls__End_Date__c.field-meta.xml
<CustomField>
    <fullName>cmbls__End_Date__c</fullName>
    <inlineHelpText>This will be the final payment pulled. If populated, the system will no longer schedule payments for an Effective Date that is after this date. Note: An End Date is not required. If null, the system will continue to create payments until there is no longer a balance.</inlineHelpText>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/cmbls__Repayment_Schedule__c/fields/cmbls__Installment_Amount__c.field-meta.xml
<CustomField>
    <fullName>cmbls__Installment_Amount__c</fullName>
    <inlineHelpText>Note: If the remaining balance is less than the scheduled payment, the system will create a payment for the lesser amount</inlineHelpText>
    <label>Transaction Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/cmbls__Repayment_Schedule__c/fields/cmbls__Next_Payment_Date__c.field-meta.xml
<CustomField>
    <fullName>cmbls__Next_Payment_Date__c</fullName>
    <inlineHelpText>This is the Effective Date of the next ACH payment that will be created by the Repayment Schedule. This field is populated and updated by the system based on the current values in the Repayment Schedule. Note: This will always roll forward to the next valid business day if it falls on a holiday or weekend.</inlineHelpText>
    <label>Next Payment Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/cmbls__Repayment_Schedule__c/fields/cmbls__Notes__c.field-meta.xml
<CustomField>
    <fullName>cmbls__Notes__c</fullName>
    <label>Notes</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/cmbls__Repayment_Schedule__c/fields/cmbls__Preset__c.field-meta.xml
<CustomField>
    <fullName>cmbls__Preset__c</fullName>
    <inlineHelpText>Payment frequency</inlineHelpText>
    <label>Preset</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Weekly</fullName>
            </value>
            <value>
                <fullName>Bi-Weekly</fullName>
            </value>
            <value>
                <fullName>Monthly</fullName>
            </value>
            <value>
                <fullName>Pause</fullName>
            </value>
            <value>
                <fullName>Daily</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/cmbls__Repayment_Schedule__c/fields/cmbls__Repayment__c.field-meta.xml
<CustomField>
    <fullName>cmbls__Repayment__c</fullName>
    <label>Repayment</label>
    <referenceTo>cmbls__Repayment__c</referenceTo>
    <relationshipLabel>Repayment Schedules</relationshipLabel>
    <relationshipName>Repayment_Schedules</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/cmbls__Repayment_Schedule__c/fields/cmbls__Start_Date__c.field-meta.xml
<CustomField>
    <fullName>cmbls__Start_Date__c</fullName>
    <inlineHelpText>This is the first date the system will start evaluating this Repayment Schedule to begin creating ACH payments. NOTE: This must be at least one day before the Next Payment Date and should also be a business day</inlineHelpText>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/classes/RepaymentScheduleService.cls
/**
 * RepaymentScheduleService class
 * @author CloudMyBiz (r)
 * @date 3/22/2022
 * @description
 * @group 
 */

global inherited sharing class RepaymentScheduleService{
    
    public static cmbls__Repayment_Schedule__c validateNextPaymentDate(cmbls__Repayment_Schedule__c record){
        if(!cmbls.DatetimeUtils.isValidDate(record.cmbls__Next_Payment_Date__c, record.cmbls__ACH_Processor__c)){
            record.cmbls__Next_Payment_Date__c = cmbls.DatetimeUtils.getNextValidDate(record.cmbls__Next_Payment_Date__c, record.cmbls__ACH_Processor__c);
        }
        return record;
    }
    
    public static cmbls__Repayment_Schedule__c createRepaymentScheduleFromInvocable(CreateRepaymentSchedule.CreateRequest mainRequest){
        Set<Date> holidays = cmbls.DatetimeUtils.getAllHolidays();
        cmbls__Repayment_Schedule__c record = new cmbls__Repayment_Schedule__c(
            cmbls__Repayment__c = mainRequest.repaymentId,
            cmbls__Start_Date__c = getPreviousValidDate(mainRequest.expectedFirstPaymentDate, holidays),
            cmbls__Next_Payment_Date__c = cmbls.DatetimeUtils.getNextValidDate(mainRequest.expectedFirstPaymentDate),
            cmbls__End_Date__c = mainRequest.endDate,
            cmbls__Preset__c = mainRequest.paymentFrequency,
            cmbls__Days__c = mainRequest.day,
            cmbls__Active__c = true,
            cmbls__Default__c = mainRequest.isDefault,
            cmbls__Installment_Amount__c = mainRequest.paymentAmount,
            cmbls__Notes__c = mainRequest.notes
        );
        Database.insert(record);
        return record;
    }
    
    @TestVisible private static Date getPreviousValidDate(Date compareDate, Set<Date> holidays){
        compareDate = compareDate.addDays(-1);
        return cmbls.DatetimeUtils.isValidDate(compareDate, holidays) ? compareDate : getPreviousValidDate(compareDate, holidays);
    }
}