unpackaged/main/default/objects/cmbls__Expense__c/cmbls__Expense__c.object-meta.xml
<CustomObject>
    <label>Expense</label>
    <nameField>
        <displayFormat>E-{0000}</displayFormat>
        <label>Expense Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Expenses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/cmbls__Expense__c/fields/cmbls__Fee_Type__c.field-meta.xml
<CustomField>
    <fullName>cmbls__Fee_Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Origination Fee</fullName>
            </value>
            <value>
                <fullName>Broker Fee</fullName>
            </value>
            <value>
                <fullName>RevShare</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/cmbls__Expense__c/fields/cmbls__Repayment__c.field-meta.xml
<CustomField>
    <fullName>cmbls__Repayment__c</fullName>
    <label>Repayment</label>
    <referenceTo>cmbls__Repayment__c</referenceTo>
    <relationshipLabel>Expenses</relationshipLabel>
    <relationshipName>Expenses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/cmbls__Expense__c/fields/Lead_Provider__c.field-meta.xml
<CustomField>
    <fullName>Lead_Provider__c</fullName>
    <label>Lead Provider</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>LendingTree</fullName>
            </value>
            <value>
                <fullName>Strategic Partner</fullName>
            </value>
            <value>
                <fullName>Fundera</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/cmbls__Expense_Accrual__c/cmbls__Expense_Accrual__c.object-meta.xml
<CustomObject>
    <label>Expense Accrual</label>
    <nameField>
        <displayFormat>EA-{00000}</displayFormat>
        <label>Expense Accrual Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Expense Accruals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/cmbls__Expense_Accrual__c/fields/cmbls__Repayment__c.field-meta.xml
<CustomField>
    <fullName>cmbls__Repayment__c</fullName>
    <label>Repayment</label>
    <referenceTo>cmbls__Repayment__c</referenceTo>
    <relationshipLabel>Expense Accruals</relationshipLabel>
    <relationshipName>Expense_Accruals</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/cmbls__InterestAccrual__c/cmbls__InterestAccrual__c.object-meta.xml
<CustomObject>
    <label>Interest Accrual</label>
    <nameField>
        <displayFormat>Int-Accrual-{0000}</displayFormat>
        <label>Interest Accrual Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Interest Accruals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/cmbls__InterestAccrual__c/fields/cmbls__Repayment__c.field-meta.xml
<CustomField>
    <fullName>cmbls__Repayment__c</fullName>
    <inlineHelpText>Related Repayment ID</inlineHelpText>
    <label>Repayment</label>
    <referenceTo>cmbls__Repayment__c</referenceTo>
    <relationshipLabel>Interest Accruals</relationshipLabel>
    <relationshipName>Interest_Accruals</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/cmbls__Repayment__c/cmbls__Repayment__c.object-meta.xml
<CustomObject>
    <label>Repayment</label>
    <nameField>
        <displayFormat>RPMT-{0000000}</displayFormat>
        <label>Repayment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Repayments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/cmbls__Repayment__c/fields/cmbls__Funding_Amount__c.field-meta.xml
<CustomField>
    <fullName>cmbls__Funding_Amount__c</fullName>
    <description>Amount that was put on the Contract</description>
    <inlineHelpText>Amount that was put on the Contract</inlineHelpText>
    <label>Funding Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/cmbls__Repayment__c/fields/cmbls__Intial_Repayment_Amount__c.field-meta.xml
<CustomField>
    <fullName>cmbls__Intial_Repayment_Amount__c</fullName>
    <description>Amount due from merchant</description>
    <inlineHelpText>Amount due from merchant</inlineHelpText>
    <label>Initial Repayment Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/cmbls__Repayment__c/fields/cmbls__Origination_Fee__c.field-meta.xml
<CustomField>
    <fullName>cmbls__Origination_Fee__c</fullName>
    <description>Amount that is being withheld for upfront fees</description>
    <inlineHelpText>Amount that is being withheld for upfront fees</inlineHelpText>
    <label>Origination Fee</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/cmbls__Repayment__c/fields/cmbls__Payment_Amount__c.field-meta.xml
<CustomField>
    <fullName>cmbls__Payment_Amount__c</fullName>
    <description>Amount of incremental payments</description>
    <inlineHelpText>Amount of incremental payments</inlineHelpText>
    <label>Installment Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/cmbls__Repayment__c/fields/Total_Broker_Fee__c.field-meta.xml
<CustomField>
    <fullName>Total_Broker_Fee__c</fullName>
    <label>Total Broker Fee</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/cmbls__Repayment__c/fields/Total_Broker_Fee_Expense__c.field-meta.xml
<CustomField>
    <fullName>Total_Broker_Fee_Expense__c</fullName>
    <label>Total Broker Fee Expense</label>
    <summarizedField>cmbls__Expense__c.cmbls__Amount__c</summarizedField>
    <summaryFilterItems>
        <field>cmbls__Expense__c.cmbls__Fee_Type__c</field>
        <operation>equals</operation>
        <value>Broker Fee</value>
    </summaryFilterItems>
    <summaryForeignKey>cmbls__Expense__c.cmbls__Repayment__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

unpackaged/main/default/objects/cmbls__Repayment__c/fields/Total_Fundera_RevShare__c.field-meta.xml
<CustomField>
    <fullName>Total_Fundera_RevShare__c</fullName>
    <label>Total Fundera RevShare</label>
    <summarizedField>cmbls__Expense__c.cmbls__Amount__c</summarizedField>
    <summaryFilterItems>
        <field>cmbls__Expense__c.cmbls__Fee_Type__c</field>
        <operation>equals</operation>
        <value>RevShare</value>
    </summaryFilterItems>
    <summaryFilterItems>
        <field>cmbls__Expense__c.Lead_Provider__c</field>
        <operation>equals</operation>
        <value>Fundera</value>
    </summaryFilterItems>
    <summaryForeignKey>cmbls__Expense__c.cmbls__Repayment__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

unpackaged/main/default/objects/cmbls__Repayment__c/fields/Total_LendingTree_RevShare__c.field-meta.xml
<CustomField>
    <fullName>Total_LendingTree_RevShare__c</fullName>
    <label>Total LendingTree RevShare</label>
    <summarizedField>cmbls__Expense__c.cmbls__Amount__c</summarizedField>
    <summaryFilterItems>
        <field>cmbls__Expense__c.cmbls__Fee_Type__c</field>
        <operation>equals</operation>
        <value>RevShare</value>
    </summaryFilterItems>
    <summaryFilterItems>
        <field>cmbls__Expense__c.Lead_Provider__c</field>
        <operation>equals</operation>
        <value>LendingTree</value>
    </summaryFilterItems>
    <summaryForeignKey>cmbls__Expense__c.cmbls__Repayment__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

unpackaged/main/default/objects/cmbls__Repayment__c/fields/Total_Origination_Fee_Expense__c.field-meta.xml
<CustomField>
    <fullName>Total_Origination_Fee_Expense__c</fullName>
    <label>Total Origination Fee Expense</label>
    <summarizedField>cmbls__Expense__c.cmbls__Amount__c</summarizedField>
    <summaryFilterItems>
        <field>cmbls__Expense__c.cmbls__Fee_Type__c</field>
        <operation>equals</operation>
        <value>Origination Fee</value>
    </summaryFilterItems>
    <summaryForeignKey>cmbls__Expense__c.cmbls__Repayment__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

unpackaged/main/default/objects/cmbls__Repayment__c/fields/Total_Rev_Share__c.field-meta.xml
<CustomField>
    <fullName>Total_Rev_Share__c</fullName>
    <label>Total Rev Share</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/cmbls__Repayment__c/fields/Total_Strategic_Partner_RevShare__c.field-meta.xml
<CustomField>
    <fullName>Total_Strategic_Partner_RevShare__c</fullName>
    <label>Total Strategic Partner RevShare</label>
    <summarizedField>cmbls__Expense__c.cmbls__Amount__c</summarizedField>
    <summaryFilterItems>
        <field>cmbls__Expense__c.cmbls__Fee_Type__c</field>
        <operation>equals</operation>
        <value>RevShare</value>
    </summaryFilterItems>
    <summaryFilterItems>
        <field>cmbls__Expense__c.Lead_Provider__c</field>
        <operation>equals</operation>
        <value>Strategic Partner</value>
    </summaryFilterItems>
    <summaryForeignKey>cmbls__Expense__c.cmbls__Repayment__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

unpackaged/main/default/classes/PointInTimeCalculatedFormulaTest.cls
/**
 * PointInTimeCalculatedFormulaTest class
 * @author CloudMyBiz (r)
 * @date 12/19/2022
 */

@IsTest
private class PointInTimeCalculatedFormulaTest{

    @TestSetup static void setupMethod(){
        Test.startTest();
        Account acc = TestDataFactory.createAccount();
        insert acc;

        Opportunity opp = TestDataFactory.createOpportunity(acc.Id);
        insert opp;

        cmbls__Repayment__c repayment = TestDataFactory.createRepayment(acc.Id);
        repayment.Total_Broker_Fee__c = 300;
        repayment.cmbls__Payment_Amount__c = 100;
        repayment.cmbls__Intial_Repayment_Amount__c = 120;
        repayment.cmbls__Funding_Amount__c = 3400;
        repayment.cmbls__Origination_Fee__c = 340;
        repayment.Total_Rev_Share__c = 187;
        insert repayment;

        cmbls__InterestAccrual__c[] accruals = new cmbls__InterestAccrual__c[]{
                TestDataFactory.createInterestAccrual(repayment.Id, 1500, Date.newInstance(2022,1,1), Date.newInstance(2022,1,31))
        };
        insert accruals;

        cmbls__Expense__c[] expenses = new cmbls__Expense__c[]{
                TestDataFactory.createExpense(repayment.Id, RepaymentUtils.ORIGINATION_FEE, 123),
                TestDataFactory.createExpense(repayment.Id, RepaymentUtils.BROKER_FEE, 184),
                TestDataFactory.createExpense(repayment.Id, RepaymentUtils.REV_SHARE_FEE, 354)
        };
        expenses[2].Lead_Provider__c = 'LendingTree';
        insert expenses;

        cmbls__Expense_Accrual__c[] expenseAccruals = new cmbls__Expense_Accrual__c[]{
                TestDataFactory.createExpenseAccrual(repayment.Id, expenses[0].Id, 123),
                TestDataFactory.createExpenseAccrual(repayment.Id, expenses[1].Id, 184),
                TestDataFactory.createExpenseAccrual(repayment.Id, expenses[2].Id, 354)
        };
        insert expenseAccruals;
        Test.stopTest();
    }

    @IsTest
    static void execute(){
        cmbls__Repayment__c repayment = [SELECT Id, Total_Origination_Fee_Expense__c, Total_Broker_Fee_Expense__c, Total_Fundera_RevShare__c,Total_LendingTree_RevShare__c,Total_Strategic_Partner_RevShare__c, cmbls__Interest__c FROM cmbls__Repayment__c];
        Map<String, Object> context = new Map<String, Object>{
                PointInTimeCalculatedFormula.INTEREST_ACCRUAL_TOTAL_ACCRUED_FIELD => 50,
                PointInTimeCalculatedFormula.ORIGINATION_EXPENSE_TOTAL_ACCRUED_FIELD => 50,
                PointInTimeCalculatedFormula.BROKER_EXPENSE_TOTAL_ACCRUED_FIELD => 50,
                PointInTimeCalculatedFormula.REV_SHARE_EXPENSE_TOTAL_ACCRUED_FIELD => 50
        };

        Decimal revShare =  NumberUtils.getDecimal(repayment.Total_Fundera_RevShare__c) +
                NumberUtils.getDecimal(repayment.Total_LendingTree_RevShare__c) +
                NumberUtils.getDecimal(repayment.Total_Strategic_Partner_RevShare__c);

        Test.startTest();
        System.assertEquals(repayment.cmbls__Interest__c - 50, new PointInTimeCalculatedFormula().execute(context, repayment, PointInTimeCalculatedFormula.INTEREST_ACCRUAL_REMAINING_FIELD));
        System.assertEquals(repayment.Total_Origination_Fee_Expense__c - 50, new PointInTimeCalculatedFormula().execute(context, repayment, PointInTimeCalculatedFormula.ORIGINATION_EXPENSE_REMAINING_FIELD));
        System.assertEquals(repayment.Total_Broker_Fee_Expense__c - 50, new PointInTimeCalculatedFormula().execute(context, repayment, PointInTimeCalculatedFormula.BROKER_EXPENSE_REMAINING_FIELD));
        System.assertEquals(revShare - 50, new PointInTimeCalculatedFormula().execute(context, repayment, PointInTimeCalculatedFormula.REV_SHARE_EXPENSE_REMAINING_FIELD));
        Test.stopTest();
    }

    @IsTest
    static void filter(){
        cmbls__InterestAccrual__c interestAccrual = [SELECT Id FROM cmbls__InterestAccrual__c];
        Test.startTest();
        System.assertEquals(true, new PointInTimeCalculatedFormula().filter(interestAccrual, PointInTimeCalculatedFormula.INTEREST_ACCRUAL_TOTAL_ACCRUED_FIELD));
        for(cmbls__Expense_Accrual__c item :[SELECT Id, cmbls__Expense__r.cmbls__Fee_Type__c FROM cmbls__Expense_Accrual__c]){
            String field;
            if(item.cmbls__Expense__r.cmbls__Fee_Type__c == RepaymentUtils.ORIGINATION_FEE) field = PointInTimeCalculatedFormula.ORIGINATION_EXPENSE_TOTAL_ACCRUED_FIELD;
            if(item.cmbls__Expense__r.cmbls__Fee_Type__c == RepaymentUtils.BROKER_FEE) field = PointInTimeCalculatedFormula.BROKER_EXPENSE_TOTAL_ACCRUED_FIELD;
            if(item.cmbls__Expense__r.cmbls__Fee_Type__c == RepaymentUtils.REV_SHARE_FEE) field = PointInTimeCalculatedFormula.REV_SHARE_EXPENSE_TOTAL_ACCRUED_FIELD;
            System.assertEquals(true, new PointInTimeCalculatedFormula().filter(item, field));
        }
        Test.stopTest();
    }
}