unpackaged/main/default/objects/cmbls__Expense__c/cmbls__Expense__c.object-meta.xml
<CustomObject>
    <label>Expense</label>
    <nameField>
        <displayFormat>E-{0000}</displayFormat>
        <label>Expense Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Expenses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/cmbls__Expense__c/fields/cmbls__Fee_Type__c.field-meta.xml
<CustomField>
    <fullName>cmbls__Fee_Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Origination Fee</fullName>
            </value>
            <value>
                <fullName>Broker Fee</fullName>
            </value>
            <value>
                <fullName>RevShare</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/cmbls__Expense__c/fields/cmbls__Repayment__c.field-meta.xml
<CustomField>
    <fullName>cmbls__Repayment__c</fullName>
    <label>Repayment</label>
    <referenceTo>cmbls__Repayment__c</referenceTo>
    <relationshipLabel>Expenses</relationshipLabel>
    <relationshipName>Expenses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/cmbls__Repayment__c/cmbls__Repayment__c.object-meta.xml
<CustomObject>
    <label>Repayment</label>
    <nameField>
        <displayFormat>RPMT-{0000000}</displayFormat>
        <label>Repayment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Repayments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/classes/ExpenseSelector.cls
/**
 * ExpenseSelector class
 * @author CloudMyBiz (r)
 * @date 9/13/2022
 * @description Service Class. Interface between business logic and specific apex contexts such as Trigger Handlers, Controllers, Batch Classes, API etc.
 * Services generally include static methods that implement business logic. Exceptions are generally thrown for the caller to handle.
 * @group Services
 */
public inherited sharing class ExpenseSelector{

    public static Map<Id, Decimal> getSumOriginationFeeExpensesByRepayment(Set<Id> repaymentIds){
        Map<Id, Decimal> output = new Map<Id, Decimal>();
    
        AggregateResult[] records = [
            SELECT SUM(cmbls__Amount__c) total, cmbls__Repayment__c repayment
            FROM cmbls__Expense__c
            WHERE cmbls__Repayment__c IN :repaymentIds AND
            cmbls__Fee_Type__c = :RepaymentUtils.ORIGINATION_FEE
            GROUP BY cmbls__Repayment__c
        ];
        for(AggregateResult item :records) output.put((Id)item.get('repayment'), (Decimal)item.get('total'));
        
        return output;
    }
    
    public static Map<Id, Decimal> getSumExpenseBrokerFeesByRepayment(Set<Id> repaymentIds){
        Map<Id, Decimal> output = new Map<Id, Decimal>();
    
        AggregateResult[] records = [
            SELECT SUM(cmbls__Amount__c) total, cmbls__Repayment__c repayment
            FROM cmbls__Expense__c
            WHERE cmbls__Repayment__c IN :repaymentIds AND
            cmbls__Fee_Type__c = :RepaymentUtils.BROKER_FEE
            GROUP BY cmbls__Repayment__c
        ];
        for(AggregateResult item :records) output.put((Id)item.get('repayment'), (Decimal)item.get('total'));
    
        return output;
    }
}