unpackaged/main/default/objects/cmbls__Expense__c/cmbls__Expense__c.object-meta.xml
<CustomObject>
    <label>Expense</label>
    <nameField>
        <displayFormat>E-{0000}</displayFormat>
        <label>Expense Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Expenses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/cmbls__Expense__c/fields/cmbls__Fee_Type__c.field-meta.xml
<CustomField>
    <fullName>cmbls__Fee_Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Origination Fee</fullName>
            </value>
            <value>
                <fullName>Broker Fee</fullName>
            </value>
            <value>
                <fullName>RevShare</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/cmbls__Expense__c/fields/cmbls__Repayment__c.field-meta.xml
<CustomField>
    <fullName>cmbls__Repayment__c</fullName>
    <label>Repayment</label>
    <referenceTo>cmbls__Repayment__c</referenceTo>
    <relationshipLabel>Expenses</relationshipLabel>
    <relationshipName>Expenses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/cmbls__Repayment__c/cmbls__Repayment__c.object-meta.xml
<CustomObject>
    <label>Repayment</label>
    <nameField>
        <displayFormat>RPMT-{0000000}</displayFormat>
        <label>Repayment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Repayments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/cmbls__Repayment__c/fields/cmbls__Origination_Fee__c.field-meta.xml
<CustomField>
    <fullName>cmbls__Origination_Fee__c</fullName>
    <description>Amount that is being withheld for upfront fees</description>
    <inlineHelpText>Amount that is being withheld for upfront fees</inlineHelpText>
    <label>Origination Fee</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/cmbls__Repayment__c/fields/Total_Broker_Fee__c.field-meta.xml
<CustomField>
    <fullName>Total_Broker_Fee__c</fullName>
    <label>Total Broker Fee</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/classes/RepaymentTriggerTest.cls
@IsTest
private class RepaymentTriggerTest{
    
    @TestSetup static void setupMethod(){
        Account acc = TestDataFactory.createAccount();
        insert acc;
    }
    
    @IsTest
    static void createExpenses(){
        Account acc = [SELECT Id FROM Account];
        
        Test.startTest();
        cmbls__Repayment__c repayment = TestDataFactory.createRepayment(acc.Id);
        repayment.Total_Broker_Fee__c = 100;
        repayment.cmbls__Origination_Fee__c = 120;
        insert repayment;
        Test.stopTest();
    
        System.assertEquals(1, [
            SELECT COUNT() FROM cmbls__Expense__c WHERE
                cmbls__Repayment__c = :repayment.Id AND
                cmbls__Amount__c =:repayment.Total_Broker_Fee__c AND
                RecordTypeId = :RepaymentUtils.EXPENSE_RECORD_TYPE_EXPENSE AND
                cmbls__Fee_Type__c = :RepaymentUtils.BROKER_FEE
        ]);
    
        System.assertEquals(1, [
            SELECT COUNT() FROM cmbls__Expense__c WHERE
                cmbls__Repayment__c = :repayment.Id AND
                cmbls__Amount__c =:repayment.cmbls__Origination_Fee__c AND
                RecordTypeId = :RepaymentUtils.EXPENSE_RECORD_TYPE_INCOME AND
                cmbls__Fee_Type__c = :RepaymentUtils.ORIGINATION_FEE
        ]);
        
        System.assertEquals(2, [SELECT COUNT() FROM cmbls__Expense__c WHERE cmbls__Repayment__c = :repayment.Id]);
    }
}