unpackaged/main/default/objects/CampaignMember/fields/Account_Number__c.field-meta.xml
<CustomField>
    <fullName>Account_Number__c</fullName>
    <externalId>true</externalId>
    <label>Account Number</label>
    <length>16</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/CampaignMember/fields/Short_Account_Number__c.field-meta.xml
<CustomField>
    <fullName>Short_Account_Number__c</fullName>
    <description>The last 8 of the account number field.</description>
    <externalId>true</externalId>
    <inlineHelpText>The last 8 of the account number field.</inlineHelpText>
    <label>Short Account Number</label>
    <length>9</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Lead/fields/Account_Number__c.field-meta.xml
<CustomField>
    <fullName>Account_Number__c</fullName>
    <description>The 16 digit account number assigned to this account.</description>
    <inlineHelpText>The 16 digit account number assigned to this account.</inlineHelpText>
    <label>Account Number</label>
    <length>16</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Lead/fields/Delete_Me__c.field-meta.xml
<CustomField>
    <fullName>Delete_Me__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Delete Me</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Lead/fields/Internet_Workflows__c.field-meta.xml
<CustomField>
    <fullName>Internet_Workflows__c</fullName>
    <label>Internet Workflows</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>To Be Processed - New</fullName>
            </value>
            <value>
                <fullName>Processed</fullName>
            </value>
            <value>
                <fullName>To Be Processed - Merged</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Lead/fields/Short_Account_Number__c.field-meta.xml
<CustomField>
    <fullName>Short_Account_Number__c</fullName>
    <description>A calculated field that is that last 8 digits of the account number.  Used for many lookups.</description>
    <inlineHelpText>A calculated field that is that last 8 digits of the account number.  Used for many lookups.</inlineHelpText>
    <label>Short Account Number</label>
    <length>9</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Lead/fields/Web_Lead__c.field-meta.xml
<CustomField>
    <fullName>Web_Lead__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Web Lead</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/classes/LeadDeDuplicationHelperTest.cls
/*
* TITLE:            LeadDeDuplicationHelperTest
* DESCRIPTION:      Test class for LeadDeDuplicationHelper
* @modifiedBy       Olivia Porter       olivia.k.porter@gmail.com
* @version          1.0
* @created          2022-08-25
*/
@isTest
public with sharing class LeadDeDuplicationHelperTest {

    @testSetup static void createTestData(){
        Lead oldLead = new Lead(FirstName = 'oldLeadFN', LastName = 'oldLeadLN', Company = 'oldLeadCompany', Status = 'House', PostalCode = '92110');
        insert oldLead;

        Campaign camp = new Campaign(Name = 'TestCampaignName');
        insert camp;

        CampaignMember cm = new CampaignMember(CampaignId = camp.Id, LeadId = oldLead.Id, Account_Number__c = '1234567891011121');
        insert cm;
    }

    @isTest
    public static void duplicateLeadMerge(){
        Lead newLead = new Lead(FirstName = 'TestFN', LastName= 'TestLN', Company = 'TestCompanyName', Web_Lead__c = true, 
                                Internet_Workflows__c = 'To Be Processed - Merged', PostalCode = '92110', 
                                Account_Number__c = '1234567891011121', Short_Account_Number__c = '123456789');
        insert newLead;


        CampaignMember cmStatus = [SELECT Status FROM CampaignMember LIMIT 1];
        Lead oldLead = [SELECT FirstName, Status FROM Lead WHERE Id != :newLead.Id LIMIT 1];
        Lead newLeadThatShouldBeDeleted = [SELECT Delete_Me__c FROM Lead WHERE Id = :newLead.Id LIMIT 1];

        System.assertEquals('Responded', cmStatus.Status); //making sure the CM was updated
        System.assertEquals('TestFN', oldLead.FirstName); //making sure the old lead is updated with new lead data
        System.assertEquals(true, newLeadThatShouldBeDeleted.Delete_Me__c); //making sure we are marking new lead to be deleted
    }

}