unpackaged/main/default/objects/CampaignMember/fields/Account_Number__c.field-meta.xml
<CustomField>
    <fullName>Account_Number__c</fullName>
    <externalId>true</externalId>
    <label>Account Number</label>
    <length>16</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/DLP_Email_Status__c.field-meta.xml
<CustomField>
    <fullName>DLP_Email_Status__c</fullName>
    <description>Status of DLP Emails - can be automatic or single end.</description>
    <label>DLP Email Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Prequal DocuSign Complete</fullName>
            </value>
            <value>
                <fullName>Prequal Bank Statements Uploaded</fullName>
            </value>
            <value>
                <fullName>Driver's License Uploaded</fullName>
            </value>
            <value>
                <fullName>Voided Check Uploaded</fullName>
            </value>
            <value>
                <fullName>Drip Campaign Started</fullName>
            </value>
            <value>
                <fullName>DLP Drip Activated</fullName>
            </value>
            <value>
                <fullName>DLP Email Sent</fullName>
            </value>
            <value>
                <fullName>DLP Drip Deactivated</fullName>
            </value>
            <value>
                <fullName>DLP Drip Campaign Ended</fullName>
            </value>
            <value>
                <fullName>Prequal Application Signing Complete</fullName>
            </value>
            <value>
                <fullName>DLP Page 1 Complete</fullName>
            </value>
            <value>
                <fullName>DLP Page 2 Complete</fullName>
            </value>
            <value>
                <fullName>Email Link Clicked</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Last_Opt_In_Message_Sent__c.field-meta.xml
<CustomField>
    <fullName>Last_Opt_In_Message_Sent__c</fullName>
    <description>Date/Time of the last time an Opt-In Message was sent</description>
    <inlineHelpText>Date/Time of the last time an Opt-In Message was sent</inlineHelpText>
    <label>Last Opt In Message Sent</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Nickname__c.field-meta.xml
<CustomField>
    <fullName>Nickname__c</fullName>
    <description>Nickname of FPC_Contact</description>
    <inlineHelpText>Type in the nickname of the contact.</inlineHelpText>
    <label>Nickname</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Ownership_Percentage__c.field-meta.xml
<CustomField>
    <fullName>Ownership_Percentage__c</fullName>
    <description>Percentage of Ownership that FPC_Contact has.</description>
    <inlineHelpText>Type in the percentage of ownership that contact has in company.</inlineHelpText>
    <label>Ownership %</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/SMS_Opt_In_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>SMS_Opt_In_Date_Time__c</fullName>
    <label>SMS Opt In Date/Time</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/SMS_Requested__c.field-meta.xml
<CustomField>
    <fullName>SMS_Requested__c</fullName>
    <defaultValue>false</defaultValue>
    <label>SMS Requested</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/SSN_Encrypted__c.field-meta.xml
<CustomField>
    <fullName>SSN_Encrypted__c</fullName>
    <description>This field will contain a customer's Social Security number in an encrypted format. Accessing the full visibility of this field will be determined by job role and permission set.</description>
    <inlineHelpText>Encrypted Social Security Number - See your administrator if you have questions.</inlineHelpText>
    <label>SSN Encrypted</label>
    <length>11</length>
    <maskChar>asterisk</maskChar>
    <maskType>ssn</maskType>
    <type>EncryptedText</type>
</CustomField>

unpackaged/main/default/classes/GetAccountContacts.cls
public class GetAccountContacts {

    @AuraEnabled(cacheable=true)
    public static List<Contact> getContactList(string accountId) {
        Map<Id, String> contactPhoneMap = new Map<Id, String>();
        Map<String, Boolean> twilioMap = new Map<String, Boolean>();
        List<Contact> accountContacts = [SELECT Id, Name, Phone, Email, MobilePhone, Title, Ownership_Percentage__c, HasOptedOutOfEmail, SMS_Opt_Out__c, SMS_Opt_In__c, MailingAddress, MailingCity, MailingCountry, MailingState, MailingStreet, MailingPostalCode, DLP_Email_Status__c, OtherAddress, OtherCity, OtherCountry, OtherState, OtherStreet, OtherPostalCode, SSN_Encrypted__c, Nickname__c
                                        FROM Contact 
                                        WHERE AccountId = :accountId 
                                        ORDER BY Ownership_Percentage__c DESC Nulls Last, LastName ASC];   


        
        for(Contact c : accountContacts){
            if(c.MobilePhone != null){
                String unformattedPhone = c.MobilePhone.replaceAll('\\D','');
                contactPhoneMap.put(c.Id, unformattedPhone);

            }
        }


        for(TwilioSF__Opt_In__c twil : [SELECT Id, TwilioSF__Opt_In_Phone_Number_Unformatted__c, TwilioSF__Lead__c, TwilioSF__Opt_In_Date_Time__c, TwilioSF__Opt_Out_Date_Time__c
                                        FROM TwilioSF__Opt_In__c 
                                        WHERE TwilioSF__Opt_In_Date_Time__c != NULL
                                        AND TwilioSF__Opt_In_Phone_Number_Unformatted__c IN :contactPhoneMap.values() ]) {
            if((twil.TwilioSF__Opt_In_Date_Time__c != null && twil.TwilioSF__Opt_Out_Date_Time__c == null) 
            || (twil.TwilioSF__Opt_Out_Date_Time__c != null && twil.TwilioSF__Opt_In_Date_Time__c != null 
            && twil.TwilioSF__Opt_In_Date_Time__c > twil.TwilioSF__Opt_Out_Date_Time__c)){
                twilioMap.put(twil.TwilioSF__Opt_In_Phone_Number_Unformatted__c, true);
            }
        }

        if(!twilioMap.isEmpty()){
            for(Contact c : accountContacts){
                if(c.MobilePhone != null){
                    String unformattedPhone = c.MobilePhone.replaceAll('\\D','');
                    Boolean isOptedIn = twilioMap.get(unformattedPhone);
                    if(isOptedIn != null && isOptedIn){
                        c.SMS_Opt_In__c = true; 
                    } else {
                        c.SMS_Opt_In__c = false;
                    }
                }
            }
        }

        return accountContacts;
    }
    
    @AuraEnabled
    public static List<contact> getContactInfo(string contactId){
        return [
        	Select Id, Name, SMS_Opt_In__c, SMS_Opt_Out__c, SMS_Requested__c, Last_Opt_In_Message_Sent__c, SMS_Opt_In_Date_Time__c, SMS_Requested_Date_Time__c
        	FROM Contact
            WHERE Id =:contactId
        ];
    }
    
    @AuraEnabled(cacheable=true)
    public static List<object> getContactMarketingStatus(string accountId){
        return [
            SELECT Id, CampaignId, FirstRespondedDate, HasResponded, Status, ContactId, Campaign.Name, Contact.Name, Account_Number__c 
            FROM CampaignMember 
            Where Contact.AccountId =: accountId
        ];
    }
}