unpackaged/main/default/objects/cmbls__Repayment_Schedule__c/cmbls__Repayment_Schedule__c.object-meta.xml
<CustomObject>
    <label>Repayment Schedule</label>
    <nameField>
        <displayFormat>RS-{000000}</displayFormat>
        <label>Repayment Schedule</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Repayment Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/cmbls__Repayment_Schedule__c/fields/cmbls__Days__c.field-meta.xml
<CustomField>
    <fullName>cmbls__Days__c</fullName>
    <inlineHelpText>Specifies the day/date of the payment frequency</inlineHelpText>
    <label>Days</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <controllingField>cmbls__Preset__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Monday</fullName>
            </value>
            <value>
                <fullName>Tuesday</fullName>
            </value>
            <value>
                <fullName>Wednesday</fullName>
            </value>
            <value>
                <fullName>Thursday</fullName>
            </value>
            <value>
                <fullName>Friday</fullName>
            </value>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>9</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
            <value>
                <fullName>11</fullName>
            </value>
            <value>
                <fullName>12</fullName>
            </value>
            <value>
                <fullName>13</fullName>
            </value>
            <value>
                <fullName>14</fullName>
            </value>
            <value>
                <fullName>15</fullName>
            </value>
            <value>
                <fullName>16</fullName>
            </value>
            <value>
                <fullName>17</fullName>
            </value>
            <value>
                <fullName>18</fullName>
            </value>
            <value>
                <fullName>19</fullName>
            </value>
            <value>
                <fullName>20</fullName>
            </value>
            <value>
                <fullName>21</fullName>
            </value>
            <value>
                <fullName>22</fullName>
            </value>
            <value>
                <fullName>23</fullName>
            </value>
            <value>
                <fullName>24</fullName>
            </value>
            <value>
                <fullName>25</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/cmbls__Repayment_Schedule__c/fields/cmbls__Next_Payment_Date__c.field-meta.xml
<CustomField>
    <fullName>cmbls__Next_Payment_Date__c</fullName>
    <inlineHelpText>This is the Effective Date of the next ACH payment that will be created by the Repayment Schedule. This field is populated and updated by the system based on the current values in the Repayment Schedule. Note: This will always roll forward to the next valid business day if it falls on a holiday or weekend.</inlineHelpText>
    <label>Next Payment Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/cmbls__Repayment_Schedule__c/fields/cmbls__Start_Date__c.field-meta.xml
<CustomField>
    <fullName>cmbls__Start_Date__c</fullName>
    <inlineHelpText>This is the first date the system will start evaluating this Repayment Schedule to begin creating ACH payments. NOTE: This must be at least one day before the Next Payment Date and should also be a business day</inlineHelpText>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/classes/SetStartDateRepaymentSchedule.cls
/**
 * SetStartDateRepaymentSchedule class
 * @author CloudMyBiz (r)
 * @date 5/9/2023
 * @description Service Class. Interface between business logic and specific apex contexts such as Trigger Handlers, Controllers, Batch Classes, API etc.
 * Services generally include static methods that implement business logic. Exceptions are generally thrown for the caller to handle.
 * @group Services
 */
global inherited sharing class SetStartDateRepaymentSchedule{
    
    public static final String SUCCESS_MESSAGE = 'Repayment Schedule was updated successfully';
    public static final String ERROR_MESSAGE = 'Unable to set Start Date on the Repayment Schedule due to the following errors: {0}';
    @InvocableMethod(Label='Set Start Date on Repayment Schedules' Category='Repayment Schedule')
    global static SetStartDateResult[] mainInvocableMethod(SetStartDateRequest[] request){
        SetStartDateResult[] output = new SetStartDateResult[]{};
        try{
            cmbls__Repayment_Schedule__c[] recordsToUpdate = new cmbls__Repayment_Schedule__c[]{};
            for(SetStartDateRequest item :request){
                if(item.startDate != null){
                    cmbls__Repayment_Schedule__c record = new cmbls__Repayment_Schedule__c(
                        Id = item.recordId,
                        cmbls__Start_Date__c = item.startDate,
                        cmbls__Next_Payment_Date__c = null
                    );
                    if(item.frequency == 'Weekly') record.cmbls__Days__c = DateTimeUtils.getNameOfDay(item.startDate);
                    recordsToUpdate.add(record);
                }
                output.add(new SetStartDateResult(SUCCESS_MESSAGE));
            }
            update recordsToUpdate;
        }catch(Exception e){
            output = new SetStartDateResult[]{};
            for(SetStartDateRequest item :request){
                output.add(new SetStartDateResult(String.format(ERROR_MESSAGE, new String[]{e.getMessage()})));
            }
        }
        
        return output;
    }
    
    global class SetStartDateRequest{
        @InvocableVariable(Label='Repayment Schedule > Id' Required=true)
        global Id recordId;
        
        @InvocableVariable(Label='Repayment > Loan Start Date' Required=true)
        global Date startDate;
        
        @InvocableVariable(Label='Repayment Schedule > Preset' Required=true)
        global String frequency;
    }
    
    global class SetStartDateResult {
        @InvocableVariable(Label='Output description' Required=true)
        global String output;
        
        public SetStartDateResult(String message){
            this.output = message;
        }
    }
}