unpackaged/main/default/objects/cmbls__Payment__c/cmbls__Payment__c.object-meta.xml
<CustomObject>
    <label>Payment</label>
    <nameField>
        <displayFormat>PMT-{0000}</displayFormat>
        <label>Payment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/cmbls__Payment__c/fields/cmbls__Repayment__c.field-meta.xml
<CustomField>
    <fullName>cmbls__Repayment__c</fullName>
    <label>Repayment</label>
    <referenceTo>cmbls__Repayment__c</referenceTo>
    <relationshipLabel>Payments</relationshipLabel>
    <relationshipName>Payments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/cmbls__Repayment__c/cmbls__Repayment__c.object-meta.xml
<CustomObject>
    <label>Repayment</label>
    <nameField>
        <displayFormat>RPMT-{0000000}</displayFormat>
        <label>Repayment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Repayments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/classes/PaymentTriggerHandler.cls
/**
 * PaymentTriggerHandler class
 * @author CloudMyBiz (r)
 * @date 6/19/2023
 */

public inherited sharing class PaymentTriggerHandler{
    
    public static void onBeforeInsertUpdate(cmbls__Payment__c[] records, Map<Id, cmbls__Payment__c> oldMap){
        PaymentService.processACHBatchOnUpdate(records, oldMap);
    }
    
    public static void onAfterInsertUpdate(cmbls__Payment__c[] records, Map<Id, cmbls__Payment__c> oldMap){
        Set<Id> repaymentIdsFromCompletedToActive = new Set<Id>();
        for(cmbls__Payment__c record :records){
            cmbls__Payment__c oldRecord = oldMap != null ? oldMap.get(record.Id) : null;
            if(PaymentService.shouldMoveRepaymentToActive(record, oldRecord)){
                repaymentIdsFromCompletedToActive.add(record.cmbls__Repayment__c);
            }
        }
        
        if(!repaymentIdsFromCompletedToActive.isEmpty()) RepaymentService.moveRepaymentsFromCompletedToActive(repaymentIdsFromCompletedToActive);
    }
}