unpackaged/main/default/objects/cmbls__Payment__c/cmbls__Payment__c.object-meta.xml
<CustomObject>
    <label>Payment</label>
    <nameField>
        <displayFormat>PMT-{0000}</displayFormat>
        <label>Payment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/cmbls__Payment__c/fields/cmbls__Effective_Date__c.field-meta.xml
<CustomField>
    <fullName>cmbls__Effective_Date__c</fullName>
    <inlineHelpText>Effective Date</inlineHelpText>
    <label>Effective Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/cmbls__Payment__c/fields/cmbls__Repayment__c.field-meta.xml
<CustomField>
    <fullName>cmbls__Repayment__c</fullName>
    <label>Repayment</label>
    <referenceTo>cmbls__Repayment__c</referenceTo>
    <relationshipLabel>Payments</relationshipLabel>
    <relationshipName>Payments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/cmbls__Payment__c/fields/cmbls__Status__c.field-meta.xml
<CustomField>
    <fullName>cmbls__Status__c</fullName>
    <inlineHelpText>Scheduled: Created and not submitted
Pending: Submitted to the ACH provider, but not yet settled.
Settled: The ACH payment was pulled successfully from the customer's account
Failed: Returned a failed response from the ACH provider</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>cmbls__Transaction_Type__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>Pre-Pending</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Settled</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Fees Applied</fullName>
            </value>
            <value>
                <fullName>Fees Collected</fullName>
            </value>
            <value>
                <fullName>Fees Reversed</fullName>
            </value>
            <value>
                <fullName>Applied</fullName>
            </value>
            <value>
                <fullName>Sent Error</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/cmbls__Payment__c/fields/cmbls__Sub_Type__c.field-meta.xml
<CustomField>
    <fullName>cmbls__Sub_Type__c</fullName>
    <label>Sub Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>cmbls__Transaction_Type__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Default</fullName>
            </value>
            <value>
                <fullName>General</fullName>
            </value>
            <value>
                <fullName>Renewal Payoff</fullName>
            </value>
            <value>
                <fullName>Add-on</fullName>
            </value>
            <value>
                <fullName>RTR</fullName>
            </value>
            <value>
                <fullName>Net Funding</fullName>
            </value>
            <value>
                <fullName>Fee Balance</fullName>
            </value>
            <value>
                <fullName>Write Off</fullName>
            </value>
            <value>
                <fullName>Write Off Fee Balance</fullName>
            </value>
            <value>
                <fullName>Overpayment Refund</fullName>
            </value>
            <value>
                <fullName>Initial Balance</fullName>
            </value>
            <value>
                <fullName>Refund</fullName>
            </value>
            <value>
                <fullName>Reversal</fullName>
            </value>
            <value>
                <fullName>Deferred Interest Write Off</fullName>
            </value>
            <value>
                <fullName>Collection on Write-Off</fullName>
            </value>
            <value>
                <fullName>Renewal Fee Payoff</fullName>
            </value>
            <value>
                <fullName>Interest Charge</fullName>
            </value>
            <value>
                <fullName>Reserve Request</fullName>
            </value>
            <value>
                <fullName>Payment From Reserve</fullName>
            </value>
            <value>
                <fullName>Refund from Reserve</fullName>
            </value>
            <value>
                <fullName>Adjustment</fullName>
            </value>
            <value>
                <fullName>Consulting Fee</fullName>
            </value>
            <value>
                <fullName>Additional Principal Payment</fullName>
            </value>
            <value>
                <fullName>Starting Draw Reserve Balance</fullName>
            </value>
            <value>
                <fullName>Extension Fee</fullName>
            </value>
            <value>
                <fullName>Maturity Default</fullName>
            </value>
            <value>
                <fullName>Payoff</fullName>
            </value>
            <value>
                <fullName>Origination Fee</fullName>
            </value>
            <value>
                <fullName>Recovery</fullName>
            </value>
            <value>
                <fullName>Unwind</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/cmbls__Payment__c/fields/cmbls__Transaction_Amount__c.field-meta.xml
<CustomField>
    <fullName>cmbls__Transaction_Amount__c</fullName>
    <label>Transaction Amount</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/cmbls__Payment__c/fields/cmbls__Transaction_Type__c.field-meta.xml
<CustomField>
    <fullName>cmbls__Transaction_Type__c</fullName>
    <description>This field indicates wether if it is a Fee or a Payment, and should be displayed in the page detail layout.</description>
    <inlineHelpText>This field indicates wether if it is a Fee or a Payment, and should be displayed in the page detail layout.</inlineHelpText>
    <label>Transaction Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Fee</fullName>
            </value>
            <value>
                <fullName>Payment</fullName>
            </value>
            <value>
                <fullName>Adjustment</fullName>
            </value>
            <value>
                <fullName>Distribution</fullName>
            </value>
            <value>
                <fullName>Fee Collection</fullName>
            </value>
            <value>
                <fullName>Reserve</fullName>
            </value>
            <value>
                <fullName>Interest</fullName>
            </value>
            <value>
                <fullName>Draw</fullName>
            </value>
            <value>
                <fullName>Draw Reserve</fullName>
            </value>
            <value>
                <fullName>Deferred Fee</fullName>
            </value>
            <value>
                <fullName>Lender Reimbursement</fullName>
            </value>
            <value>
                <fullName>Discount</fullName>
            </value>
            <value>
                <fullName>Payoff</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/cmbls__Payment__c/fields/Payment__c.field-meta.xml
<CustomField>
    <fullName>Payment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Rescheduled From</label>
    <referenceTo>cmbls__Payment__c</referenceTo>
    <relationshipLabel>Payments (Payment)</relationshipLabel>
    <relationshipName>Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/cmbls__Repayment__c/cmbls__Repayment__c.object-meta.xml
<CustomObject>
    <label>Repayment</label>
    <nameField>
        <displayFormat>RPMT-{0000000}</displayFormat>
        <label>Repayment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Repayments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/cmbls__Repayment__c/fields/cmbls__Maturity_Date__c.field-meta.xml
<CustomField>
    <fullName>cmbls__Maturity_Date__c</fullName>
    <inlineHelpText>Maturity Date for Loan</inlineHelpText>
    <label>Current Maturity Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/cmbls__Repayment__c/fields/cmbls__Status__c.field-meta.xml
<CustomField>
    <fullName>cmbls__Status__c</fullName>
    <description>Active, pause, complete, and new</description>
    <inlineHelpText>Active, pause, complete, and new</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Temporary Pause</fullName>
            </value>
            <value>
                <fullName>Pause</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Write Off</fullName>
            </value>
            <value>
                <fullName>Recovery</fullName>
            </value>
            <value>
                <fullName>Unwind</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/cmbls__Repayment__c/fields/Enable_Maturity_Default_Fees__c.field-meta.xml
<CustomField>
    <fullName>Enable_Maturity_Default_Fees__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Enable Maturity Default Fees</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/cmbls__Repayment__c/fields/Maturity_Default_Fee_Amount__c.field-meta.xml
<CustomField>
    <fullName>Maturity_Default_Fee_Amount__c</fullName>
    <inlineHelpText>If null, the global ‘Maturity Default Fee Amount’ in National Funding Settings (Custom Settings) will be used</inlineHelpText>
    <label>Maturity Default Fee Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/cmbls__Repayment__c/fields/Merchant_Number__c.field-meta.xml
<CustomField>
    <fullName>Merchant_Number__c</fullName>
    <externalId>true</externalId>
    <label>LoanNumber</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/cmbls__Repayment__c/fields/Permanent_Mod__c.field-meta.xml
<CustomField>
    <fullName>Permanent_Mod__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Permanent Mod</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/National_Funding_Settings__c/National_Funding_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>National Funding Settings</label>
</CustomObject>

unpackaged/main/default/objects/National_Funding_Settings__c/fields/Maturity_Default_Fee_Amount__c.field-meta.xml
<CustomField>
    <fullName>Maturity_Default_Fee_Amount__c</fullName>
    <inlineHelpText>Global Maturity Default fee that is used unless Repayment has another one set.</inlineHelpText>
    <label>Maturity Default Fee Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/classes/AutomatedMaturityFeesScheduleTest.cls
@IsTest
public with sharing class  AutomatedMaturityFeesScheduleTest {
    
    @TestSetup static void setupMethod(){
        Account acc = new Account(Name = 'Test account');
        insert acc;
        
        cmbls__Repayment__c[] repayments = new cmbls__Repayment__c[]{
            TestDataFactory.createRepayment(acc.Id),
            TestDataFactory.createRepayment(acc.Id),
            TestDataFactory.createRepayment(acc.Id),
            TestDataFactory.createRepayment(acc.Id),
            TestDataFactory.createRepayment(acc.Id)
        };
        
        //Should create Maturity fees due to Enable_Maturity_Default_Fees__c = true
        repayments[0].Enable_Maturity_Default_Fees__c = true;
        repayments[0].cmbls__Maturity_Date__c = System.today().addDays(-3);
        repayments[0].Merchant_Number__c = 'NF-TEST01';
        
        //Should NOT create Maturity fees due to Status is NOT 'Active'
        repayments[1].cmbls__Status__c = RepaymentUtils.STATUS_COMPLETE;
        repayments[1].Enable_Maturity_Default_Fees__c = true;
        repayments[1].cmbls__Maturity_Date__c = System.today().addDays(-3);
        repayments[1].Merchant_Number__c = 'NF-TEST02';
        
        //Should NOT create Maturity fees due to Enable_Maturity_Default_Fees__c = false
        repayments[2].Enable_Maturity_Default_Fees__c = false;
        repayments[2].cmbls__Maturity_Date__c = System.today().addDays(-3);
        repayments[2].Merchant_Number__c = 'NF-TEST03';
        
        //Should NOT create Maturity fees due to cmbls__Maturity_Date__c > TODAY
        repayments[4].Enable_Maturity_Default_Fees__c = true;
        repayments[4].cmbls__Maturity_Date__c = System.today().addDays(1);
        repayments[4].Merchant_Number__c = 'NF-TEST04';
        
        insert repayments;
        
        Test.startTest();
        
        National_Funding_Settings__c settings = National_Funding_Settings__c.getOrgDefaults();
        settings.Maturity_Default_Fee_Amount__c = 10;
        upsert settings;
        Test.stopTest();
    }

    @IsTest
    static void automatedMaturityFeesScheduleTest(){
        for(cmbls__Repayment__c item :[SELECT Id, Merchant_Number__c, cmbls__Status__c, Enable_Maturity_Default_Fees__c, Permanent_Mod__c FROM cmbls__Repayment__c]){
            switch on item.Merchant_Number__c {
                when 'NF-TEST01' {
                    Assert.areEqual(RepaymentUtils.STATUS_ACTIVE, item.cmbls__Status__c);
                    Assert.isTrue(item.Enable_Maturity_Default_Fees__c);
                    Assert.isFalse(item.Permanent_Mod__c);
                }
                when 'NF-TEST02' {
                    Assert.areEqual(RepaymentUtils.STATUS_COMPLETE, item.cmbls__Status__c);
                    Assert.isTrue(item.Enable_Maturity_Default_Fees__c);
                    Assert.isFalse(item.Permanent_Mod__c);
                }
                when 'NF-TEST03' {
                    Assert.areEqual(RepaymentUtils.STATUS_ACTIVE, item.cmbls__Status__c);
                    Assert.isFalse(item.Enable_Maturity_Default_Fees__c);
                    Assert.isFalse(item.Permanent_Mod__c);
                }
                when 'NF-TEST04' {
                    Assert.areEqual(RepaymentUtils.STATUS_ACTIVE, item.cmbls__Status__c);
                    Assert.isTrue(item.Enable_Maturity_Default_Fees__c);
                }
            }
        }
        
        Test.startTest();
        new AutomatedMaturityFeesSchedule().execute(null);
        Test.stopTest();
        
        cmbls__Repayment__c[] repayments = [
            SELECT Id, Merchant_Number__c, (SELECT Id FROM cmbls__Payments__r WHERE RecordTypeId = :PaymentUtils.PAYMENT_RECORD_TYPE_CREDIT_ID AND
                                                                                    cmbls__Effective_Date__c = TODAY AND
                                                                                    cmbls__Transaction_Type__c = :PaymentUtils.PAYMENT_TRANSACTION_TYPE_FEE AND
                                                                                    cmbls__Sub_Type__c = :PaymentUtils.PAYMENT_SUBTYPE_MATURITY AND
                                                                                    cmbls__Status__c = :PaymentUtils.PAYMENT_STATUS_FEE_APPLIED AND
                                                                                    cmbls__Transaction_Amount__c = 10)
            FROM cmbls__Repayment__c
        ];
        for(cmbls__Repayment__c item :repayments){
            switch on item.Merchant_Number__c {
                when 'NF-TEST01' {
                    Assert.areEqual(1, item.cmbls__Payments__r.size());
                }
                when 'NF-TEST02' {
                    Assert.areEqual(0, item.cmbls__Payments__r.size());
                }
                when 'NF-TEST03' {
                    Assert.areEqual(0, item.cmbls__Payments__r.size());
                }
                when 'NF-TEST04' {
                    Assert.areEqual(0, item.cmbls__Payments__r.size());
                }
            }
        }
        
    }
}