unpackaged/main/default/objects/cmbls__Payment__c/cmbls__Payment__c.object-meta.xml
<CustomObject>
    <label>Payment</label>
    <nameField>
        <displayFormat>PMT-{0000}</displayFormat>
        <label>Payment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/cmbls__Payment__c/fields/cmbls__ACH_Processor__c.field-meta.xml
<CustomField>
    <fullName>cmbls__ACH_Processor__c</fullName>
    <label>ACH Processor</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Wells Fargo - NF Collections</fullName>
            </value>
            <value>
                <fullName>Wells Fargo - NFAS2 Collections</fullName>
            </value>
            <value>
                <fullName>Wells Fargo - NF Funding</fullName>
            </value>
            <value>
                <fullName>Wells Fargo - QBF Funding</fullName>
            </value>
            <value>
                <fullName>Wells Fargo - NFSPV1 Collections</fullName>
            </value>
            <value>
                <fullName>Wells Fargo - NFSPV2 Collections</fullName>
            </value>
            <value>
                <fullName>Wells Fargo - NFAS3 Collections</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/cmbls__Payment__c/fields/cmbls__Effective_Date__c.field-meta.xml
<CustomField>
    <fullName>cmbls__Effective_Date__c</fullName>
    <inlineHelpText>Effective Date</inlineHelpText>
    <label>Effective Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/cmbls__Payment__c/fields/cmbls__Payment_Method__c.field-meta.xml
<CustomField>
    <fullName>cmbls__Payment_Method__c</fullName>
    <label>Payment Method</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ACH</fullName>
            </value>
            <value>
                <fullName>Wire</fullName>
            </value>
            <value>
                <fullName>Check</fullName>
            </value>
            <value>
                <fullName>Split Funding</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Credit Card</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/cmbls__Payment__c/fields/cmbls__Repayment__c.field-meta.xml
<CustomField>
    <fullName>cmbls__Repayment__c</fullName>
    <label>Repayment</label>
    <referenceTo>cmbls__Repayment__c</referenceTo>
    <relationshipLabel>Payments</relationshipLabel>
    <relationshipName>Payments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/cmbls__Payment__c/fields/cmbls__Sub_Type__c.field-meta.xml
<CustomField>
    <fullName>cmbls__Sub_Type__c</fullName>
    <label>Sub Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>cmbls__Transaction_Type__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Default</fullName>
            </value>
            <value>
                <fullName>General</fullName>
            </value>
            <value>
                <fullName>Renewal Payoff</fullName>
            </value>
            <value>
                <fullName>Add-on</fullName>
            </value>
            <value>
                <fullName>RTR</fullName>
            </value>
            <value>
                <fullName>Net Funding</fullName>
            </value>
            <value>
                <fullName>Fee Balance</fullName>
            </value>
            <value>
                <fullName>Write Off</fullName>
            </value>
            <value>
                <fullName>Write Off Fee Balance</fullName>
            </value>
            <value>
                <fullName>Overpayment Refund</fullName>
            </value>
            <value>
                <fullName>Initial Balance</fullName>
            </value>
            <value>
                <fullName>Refund</fullName>
            </value>
            <value>
                <fullName>Reversal</fullName>
            </value>
            <value>
                <fullName>Deferred Interest Write Off</fullName>
            </value>
            <value>
                <fullName>Collection on Write-Off</fullName>
            </value>
            <value>
                <fullName>Renewal Fee Payoff</fullName>
            </value>
            <value>
                <fullName>Interest Charge</fullName>
            </value>
            <value>
                <fullName>Reserve Request</fullName>
            </value>
            <value>
                <fullName>Payment From Reserve</fullName>
            </value>
            <value>
                <fullName>Refund from Reserve</fullName>
            </value>
            <value>
                <fullName>Adjustment</fullName>
            </value>
            <value>
                <fullName>Consulting Fee</fullName>
            </value>
            <value>
                <fullName>Additional Principal Payment</fullName>
            </value>
            <value>
                <fullName>Starting Draw Reserve Balance</fullName>
            </value>
            <value>
                <fullName>Extension Fee</fullName>
            </value>
            <value>
                <fullName>Maturity Default</fullName>
            </value>
            <value>
                <fullName>Payoff</fullName>
            </value>
            <value>
                <fullName>Origination Fee</fullName>
            </value>
            <value>
                <fullName>Recovery</fullName>
            </value>
            <value>
                <fullName>Unwind</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/cmbls__Payment__c/fields/cmbls__Transaction_Amount__c.field-meta.xml
<CustomField>
    <fullName>cmbls__Transaction_Amount__c</fullName>
    <label>Transaction Amount</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/cmbls__Payment__c/fields/cmbls__Transaction_Type__c.field-meta.xml
<CustomField>
    <fullName>cmbls__Transaction_Type__c</fullName>
    <description>This field indicates wether if it is a Fee or a Payment, and should be displayed in the page detail layout.</description>
    <inlineHelpText>This field indicates wether if it is a Fee or a Payment, and should be displayed in the page detail layout.</inlineHelpText>
    <label>Transaction Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Fee</fullName>
            </value>
            <value>
                <fullName>Payment</fullName>
            </value>
            <value>
                <fullName>Adjustment</fullName>
            </value>
            <value>
                <fullName>Distribution</fullName>
            </value>
            <value>
                <fullName>Fee Collection</fullName>
            </value>
            <value>
                <fullName>Reserve</fullName>
            </value>
            <value>
                <fullName>Interest</fullName>
            </value>
            <value>
                <fullName>Draw</fullName>
            </value>
            <value>
                <fullName>Draw Reserve</fullName>
            </value>
            <value>
                <fullName>Deferred Fee</fullName>
            </value>
            <value>
                <fullName>Lender Reimbursement</fullName>
            </value>
            <value>
                <fullName>Discount</fullName>
            </value>
            <value>
                <fullName>Payoff</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/cmbls__Repayment__c/cmbls__Repayment__c.object-meta.xml
<CustomObject>
    <label>Repayment</label>
    <nameField>
        <displayFormat>RPMT-{0000000}</displayFormat>
        <label>Repayment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Repayments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/cmbls__Repayment__c/fields/cmbls__ACH_Processor__c.field-meta.xml
<CustomField>
    <fullName>cmbls__ACH_Processor__c</fullName>
    <description>The name of the processor being used</description>
    <inlineHelpText>The name of the processor being used</inlineHelpText>
    <label>ACH Processor</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Wells Fargo - NF Collections</fullName>
            </value>
            <value>
                <fullName>Wells Fargo - NFAS2 Collections</fullName>
            </value>
            <value>
                <fullName>Wells Fargo - NFSPV1 Collections</fullName>
            </value>
            <value>
                <fullName>Wells Fargo - NFSPV2 Collections</fullName>
            </value>
            <value>
                <fullName>Wells Fargo - NFAS3 Collections</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/CreateOneTimePaymentTest.cls
/**
 * CreateOneTimePaymentTest class
 * @author CloudMyBiz (r)
 * @date 3/24/2022
 * @description
 * @group 
 */

@IsTest
private class CreateOneTimePaymentTest{
    
    @TestSetup static void setupMethod(){
        Account acc = TestDataFactory.createAccount();
        insert acc;
    
        cmbls__Repayment__c repayment = TestDataFactory.createRepayment(acc.Id);
        insert repayment;
    }
    
    @IsTest
    static void mainInvocableMethod(){
        cmbls__Repayment__c repayment = [SELECT Id FROM cmbls__Repayment__c];
        delete [SELECT Id FROM cmbls__Payment__c];
        CreateOneTimePayment.CreateRequest mainRequest = new CreateOneTimePayment.CreateRequest();
        mainRequest.repaymentId = repayment.Id;
        mainRequest.effectiveDate = System.today().addDays(15);
        mainRequest.transactionAmount = 2000;
        mainRequest.subType = 'Adjustment';
        mainRequest.achProcessor = 'ACH.com';
        mainRequest.notes = 'Test Notes';
        
        Test.startTest();
        CreateOneTimePayment.CreateResult[] results = CreateOneTimePayment.mainInvocableMethod(new CreateOneTimePayment.CreateRequest[]{mainRequest});
        System.assertEquals(1, results.size());
        System.assertEquals(true, results[0].success);
        Test.stopTest();
        
        cmbls__Payment__c record = [SELECT Id, cmbls__Repayment__c, RecordTypeId, cmbls__Effective_Date__c, cmbls__Transaction_Type__c, cmbls__Transaction_Amount__c, cmbls__Sub_Type__c, cmbls__Payment_Method__c, cmbls__ACH_Processor__c, cmbls__Notes__c FROM cmbls__Payment__c WHERE cmbls__Repayment__c = :repayment.Id];
        System.assertEquals(record.Id, results[0].output);
        System.assertEquals(mainRequest.repaymentId, record.cmbls__Repayment__c);
        System.assertEquals(mainRequest.effectiveDate, record.cmbls__Effective_Date__c);
        System.assertEquals(mainRequest.transactionAmount, record.cmbls__Transaction_Amount__c);
        System.assertEquals(mainRequest.subType, record.cmbls__Sub_Type__c);
        System.assertEquals(mainRequest.achProcessor, record.cmbls__ACH_Processor__c);
        System.assertEquals(mainRequest.notes, record.cmbls__Notes__c);
    
        System.assertEquals(PaymentUtils.PAYMENT_RECORD_TYPE_DEBIT_ID, record.RecordTypeId);
        System.assertEquals(PaymentUtils.PAYMENT_TRANSACTION_TYPE_PAYMENT, record.cmbls__Transaction_Type__c);
        System.assertEquals(PaymentUtils.PAYMENT_METHOD_ACH, record.cmbls__Payment_Method__c);
    }
    
    @IsTest
    static void mainInvocableMethodError(){
        cmbls__Repayment__c repayment = [SELECT Id FROM cmbls__Repayment__c];
        delete [SELECT Id FROM cmbls__Payment__c];
        CreateOneTimePayment.CreateRequest mainRequest = new CreateOneTimePayment.CreateRequest();
        mainRequest.repaymentId = repayment.Id;
        
        Test.startTest();
        CreateOneTimePayment.CreateResult[] results = CreateOneTimePayment.mainInvocableMethod(new CreateOneTimePayment.CreateRequest[]{mainRequest});
        System.assertEquals(1, results.size());
        System.assertEquals(false, results[0].success);
        System.assert(results[0].output.contains('REQUIRED_FIELD_MISSING'));
        Test.stopTest();
        
        System.assertEquals(0, [SELECT COUNT() FROM cmbls__Payment__c WHERE cmbls__Repayment__c = :repayment.Id]);
    }
    
    @IsTest
    static void mainInvocableMethodNoProcessor(){
        cmbls__Repayment__c repayment = [SELECT Id, cmbls__ACH_Processor__c FROM cmbls__Repayment__c];
        delete [SELECT Id FROM cmbls__Payment__c];
        CreateOneTimePayment.CreateRequest mainRequest = new CreateOneTimePayment.CreateRequest();
        mainRequest.repaymentId = repayment.Id;
        mainRequest.effectiveDate = System.today().addDays(15);
        mainRequest.transactionAmount = 2000;
        mainRequest.subType = 'Adjustment';
        mainRequest.notes = 'Test Notes';
        
        Test.startTest();
        CreateOneTimePayment.CreateResult[] results = CreateOneTimePayment.mainInvocableMethod(new CreateOneTimePayment.CreateRequest[]{mainRequest});
        System.assertEquals(1, results.size());
        System.assertEquals(true, results[0].success);
        Test.stopTest();
        
        cmbls__Payment__c record = [SELECT Id, cmbls__Repayment__c, RecordTypeId, cmbls__Effective_Date__c, cmbls__Transaction_Type__c, cmbls__Transaction_Amount__c, cmbls__Sub_Type__c, cmbls__Payment_Method__c, cmbls__ACH_Processor__c, cmbls__Notes__c FROM cmbls__Payment__c WHERE cmbls__Repayment__c = :repayment.Id];
        System.assertEquals(record.Id, results[0].output);
        System.assertEquals(mainRequest.repaymentId, record.cmbls__Repayment__c);
        System.assertEquals(mainRequest.effectiveDate, record.cmbls__Effective_Date__c);
        System.assertEquals(mainRequest.transactionAmount, record.cmbls__Transaction_Amount__c);
        System.assertEquals(mainRequest.subType, record.cmbls__Sub_Type__c);
        System.assertEquals(repayment.cmbls__ACH_Processor__c, record.cmbls__ACH_Processor__c);
        System.assertEquals(mainRequest.notes, record.cmbls__Notes__c);
        
        System.assertEquals(PaymentUtils.PAYMENT_RECORD_TYPE_DEBIT_ID, record.RecordTypeId);
        System.assertEquals(PaymentUtils.PAYMENT_TRANSACTION_TYPE_PAYMENT, record.cmbls__Transaction_Type__c);
        System.assertEquals(PaymentUtils.PAYMENT_METHOD_ACH, record.cmbls__Payment_Method__c);
    }
}