unpackaged/main/default/objects/cmbls__Payment__c/cmbls__Payment__c.object-meta.xml
<CustomObject>
    <label>Payment</label>
    <nameField>
        <displayFormat>PMT-{0000}</displayFormat>
        <label>Payment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/cmbls__Payment__c/fields/cmbls__ACH_Processor__c.field-meta.xml
<CustomField>
    <fullName>cmbls__ACH_Processor__c</fullName>
    <label>ACH Processor</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Wells Fargo - NF Collections</fullName>
            </value>
            <value>
                <fullName>Wells Fargo - NFAS2 Collections</fullName>
            </value>
            <value>
                <fullName>Wells Fargo - NF Funding</fullName>
            </value>
            <value>
                <fullName>Wells Fargo - QBF Funding</fullName>
            </value>
            <value>
                <fullName>Wells Fargo - NFSPV1 Collections</fullName>
            </value>
            <value>
                <fullName>Wells Fargo - NFSPV2 Collections</fullName>
            </value>
            <value>
                <fullName>Wells Fargo - NFAS3 Collections</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/cmbls__Payment__c/fields/cmbls__Effective_Date__c.field-meta.xml
<CustomField>
    <fullName>cmbls__Effective_Date__c</fullName>
    <inlineHelpText>Effective Date</inlineHelpText>
    <label>Effective Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/cmbls__Payment__c/fields/cmbls__Payment_Method__c.field-meta.xml
<CustomField>
    <fullName>cmbls__Payment_Method__c</fullName>
    <label>Payment Method</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ACH</fullName>
            </value>
            <value>
                <fullName>Wire</fullName>
            </value>
            <value>
                <fullName>Check</fullName>
            </value>
            <value>
                <fullName>Split Funding</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Credit Card</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/cmbls__Payment__c/fields/cmbls__Repayment__c.field-meta.xml
<CustomField>
    <fullName>cmbls__Repayment__c</fullName>
    <label>Repayment</label>
    <referenceTo>cmbls__Repayment__c</referenceTo>
    <relationshipLabel>Payments</relationshipLabel>
    <relationshipName>Payments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/cmbls__Payment__c/fields/cmbls__Status__c.field-meta.xml
<CustomField>
    <fullName>cmbls__Status__c</fullName>
    <inlineHelpText>Scheduled: Created and not submitted
Pending: Submitted to the ACH provider, but not yet settled.
Settled: The ACH payment was pulled successfully from the customer's account
Failed: Returned a failed response from the ACH provider</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>cmbls__Transaction_Type__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>Pre-Pending</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Settled</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Fees Applied</fullName>
            </value>
            <value>
                <fullName>Fees Collected</fullName>
            </value>
            <value>
                <fullName>Fees Reversed</fullName>
            </value>
            <value>
                <fullName>Applied</fullName>
            </value>
            <value>
                <fullName>Sent Error</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/cmbls__Payment__c/fields/cmbls__Sub_Type__c.field-meta.xml
<CustomField>
    <fullName>cmbls__Sub_Type__c</fullName>
    <label>Sub Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>cmbls__Transaction_Type__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Default</fullName>
            </value>
            <value>
                <fullName>General</fullName>
            </value>
            <value>
                <fullName>Renewal Payoff</fullName>
            </value>
            <value>
                <fullName>Add-on</fullName>
            </value>
            <value>
                <fullName>RTR</fullName>
            </value>
            <value>
                <fullName>Net Funding</fullName>
            </value>
            <value>
                <fullName>Fee Balance</fullName>
            </value>
            <value>
                <fullName>Write Off</fullName>
            </value>
            <value>
                <fullName>Write Off Fee Balance</fullName>
            </value>
            <value>
                <fullName>Overpayment Refund</fullName>
            </value>
            <value>
                <fullName>Initial Balance</fullName>
            </value>
            <value>
                <fullName>Refund</fullName>
            </value>
            <value>
                <fullName>Reversal</fullName>
            </value>
            <value>
                <fullName>Deferred Interest Write Off</fullName>
            </value>
            <value>
                <fullName>Collection on Write-Off</fullName>
            </value>
            <value>
                <fullName>Renewal Fee Payoff</fullName>
            </value>
            <value>
                <fullName>Interest Charge</fullName>
            </value>
            <value>
                <fullName>Reserve Request</fullName>
            </value>
            <value>
                <fullName>Payment From Reserve</fullName>
            </value>
            <value>
                <fullName>Refund from Reserve</fullName>
            </value>
            <value>
                <fullName>Adjustment</fullName>
            </value>
            <value>
                <fullName>Consulting Fee</fullName>
            </value>
            <value>
                <fullName>Additional Principal Payment</fullName>
            </value>
            <value>
                <fullName>Starting Draw Reserve Balance</fullName>
            </value>
            <value>
                <fullName>Extension Fee</fullName>
            </value>
            <value>
                <fullName>Maturity Default</fullName>
            </value>
            <value>
                <fullName>Payoff</fullName>
            </value>
            <value>
                <fullName>Origination Fee</fullName>
            </value>
            <value>
                <fullName>Recovery</fullName>
            </value>
            <value>
                <fullName>Unwind</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/cmbls__Payment__c/fields/cmbls__Transaction_Amount__c.field-meta.xml
<CustomField>
    <fullName>cmbls__Transaction_Amount__c</fullName>
    <label>Transaction Amount</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/cmbls__Payment__c/fields/cmbls__Transaction_Type__c.field-meta.xml
<CustomField>
    <fullName>cmbls__Transaction_Type__c</fullName>
    <description>This field indicates wether if it is a Fee or a Payment, and should be displayed in the page detail layout.</description>
    <inlineHelpText>This field indicates wether if it is a Fee or a Payment, and should be displayed in the page detail layout.</inlineHelpText>
    <label>Transaction Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Fee</fullName>
            </value>
            <value>
                <fullName>Payment</fullName>
            </value>
            <value>
                <fullName>Adjustment</fullName>
            </value>
            <value>
                <fullName>Distribution</fullName>
            </value>
            <value>
                <fullName>Fee Collection</fullName>
            </value>
            <value>
                <fullName>Reserve</fullName>
            </value>
            <value>
                <fullName>Interest</fullName>
            </value>
            <value>
                <fullName>Draw</fullName>
            </value>
            <value>
                <fullName>Draw Reserve</fullName>
            </value>
            <value>
                <fullName>Deferred Fee</fullName>
            </value>
            <value>
                <fullName>Lender Reimbursement</fullName>
            </value>
            <value>
                <fullName>Discount</fullName>
            </value>
            <value>
                <fullName>Payoff</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/cmbls__Payment__c/fields/Payment__c.field-meta.xml
<CustomField>
    <fullName>Payment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Rescheduled From</label>
    <referenceTo>cmbls__Payment__c</referenceTo>
    <relationshipLabel>Payments (Payment)</relationshipLabel>
    <relationshipName>Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/cmbls__Repayment__c/cmbls__Repayment__c.object-meta.xml
<CustomObject>
    <label>Repayment</label>
    <nameField>
        <displayFormat>RPMT-{0000000}</displayFormat>
        <label>Repayment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Repayments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/cmbls__Repayment__c/fields/cmbls__ACH_Processor__c.field-meta.xml
<CustomField>
    <fullName>cmbls__ACH_Processor__c</fullName>
    <description>The name of the processor being used</description>
    <inlineHelpText>The name of the processor being used</inlineHelpText>
    <label>ACH Processor</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Wells Fargo - NF Collections</fullName>
            </value>
            <value>
                <fullName>Wells Fargo - NFAS2 Collections</fullName>
            </value>
            <value>
                <fullName>Wells Fargo - NFSPV1 Collections</fullName>
            </value>
            <value>
                <fullName>Wells Fargo - NFSPV2 Collections</fullName>
            </value>
            <value>
                <fullName>Wells Fargo - NFAS3 Collections</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/cmbls__Repayment__c/fields/cmbls__Status__c.field-meta.xml
<CustomField>
    <fullName>cmbls__Status__c</fullName>
    <description>Active, pause, complete, and new</description>
    <inlineHelpText>Active, pause, complete, and new</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Temporary Pause</fullName>
            </value>
            <value>
                <fullName>Pause</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Write Off</fullName>
            </value>
            <value>
                <fullName>Recovery</fullName>
            </value>
            <value>
                <fullName>Unwind</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/ReschedulePaymentTest.cls
/**
 * ReschedulePaymentTest class
 * @author CloudMyBiz (r)
 * @date 3/24/2022
 * @description
 * @group 
 */

@IsTest
private class ReschedulePaymentTest{
    
    @TestSetup static void setupMethod(){
        Test.startTest();
        Account acc = TestDataFactory.createAccount();
        insert acc;
    
        cmbls__Repayment__c repayment = TestDataFactory.createRepayment(acc.Id);
        insert repayment;
    
        delete [SELECT Id FROM cmbls__Payment__c];
    
        insert new cmbls__Payment__c(
            cmbls__Repayment__c = repayment.Id,
            RecordTypeId = PaymentUtils.PAYMENT_RECORD_TYPE_CREDIT_ID,
            cmbls__Effective_Date__c = System.today().addDays(1),
            cmbls__Transaction_Type__c = PaymentUtils.PAYMENT_TRANSACTION_TYPE_PAYMENT,
            cmbls__Sub_Type__c = 'Adjustment',
            cmbls__Transaction_Amount__c = 4000,
            cmbls__Status__c = PaymentUtils.PAYMENT_STATUS_SCHEDULED,
            cmbls__Payment_Method__c = PaymentUtils.PAYMENT_METHOD_ACH,
            cmbls__ACH_Processor__c = 'ACH.com'
        );
        Test.stopTest();
    }

    @IsTest
    static void mainInvocableMethod(){
        cmbls__Repayment__c repayment = [SELECT Id, (SELECT Id FROM cmbls__Payments__r LIMIT 1) FROM cmbls__Repayment__c];
        ReschedulePayment.RescheduleRequest mainRequest = new ReschedulePayment.RescheduleRequest();
        mainRequest.paymentId = repayment.cmbls__Payments__r[0].Id;
        mainRequest.effectiveDate = System.today().addDays(10);
        mainRequest.notes = 'Test Notes';
    
        Test.startTest();
        ReschedulePayment.RescheduleResult[] results = ReschedulePayment.mainInvocableMethod(new ReschedulePayment.RescheduleRequest[]{mainRequest});
        System.assertEquals(1, results.size());
        System.assertEquals(true, results[0].success);
        Test.stopTest();
        
        cmbls__Payment__c newPayment = [SELECT Id, cmbls__Status__c, cmbls__Effective_Date__c, cmbls__Notes__c, cmbls__Repayment__c, Payment__c FROM cmbls__Payment__c WHERE Id != :repayment.cmbls__Payments__r[0].Id];
        System.assertEquals(PaymentUtils.PAYMENT_STATUS_SCHEDULED, newPayment.cmbls__Status__c);
        System.assertEquals(mainRequest.notes, newPayment.cmbls__Notes__c);
        System.assertEquals(repayment.Id, newPayment.cmbls__Repayment__c);
        System.assertEquals(mainRequest.effectiveDate, newPayment.cmbls__Effective_Date__c);
        System.assertEquals(repayment.cmbls__Payments__r[0].Id, newPayment.Payment__c);
        
        cmbls__Payment__c oldPayment = [SELECT Id, cmbls__Status__c, cmbls__Notes__c FROM cmbls__Payment__c WHERE Id = :repayment.cmbls__Payments__r[0].Id];
        System.assertEquals(PaymentUtils.PAYMENT_STATUS_CANCELED, oldPayment.cmbls__Status__c);
        System.assertEquals(mainRequest.notes, oldPayment.cmbls__Notes__c);
        
        String successMessage = String.format(ReschedulePayment.SUCCESS_MESSAGE, new String[]{oldPayment.Id, newPayment.Id});
        System.assertEquals(successMessage, results[0].output);
    }
    
    @IsTest
    static void mainInvocableMethodError(){
        cmbls__Repayment__c repayment = [SELECT Id, (SELECT Id FROM cmbls__Payments__r LIMIT 1) FROM cmbls__Repayment__c];
        ReschedulePayment.RescheduleRequest mainRequest = new ReschedulePayment.RescheduleRequest();
        mainRequest.paymentId = repayment.cmbls__Payments__r[0].Id;
        mainRequest.effectiveDate = System.today().addDays(10);
        mainRequest.notes = 'Test Notes';
        
        update new cmbls__Payment__c(Id = repayment.cmbls__Payments__r[0].Id, cmbls__Status__c = PaymentUtils.PAYMENT_STATUS_CANCELED);
    
        Test.startTest();
        ReschedulePayment.RescheduleResult[] results = ReschedulePayment.mainInvocableMethod(new ReschedulePayment.RescheduleRequest[]{mainRequest});
        System.assertEquals(1, results.size());
        System.assertEquals(false, results[0].success);
        Test.stopTest();
        
        System.assertEquals(1, [SELECT COUNT() FROM cmbls__Payment__c WHERE cmbls__Repayment__c = :repayment.Id]);
        cmbls__Payment__c oldPayment = [SELECT Id, cmbls__Status__c, Name, cmbls__Notes__c FROM cmbls__Payment__c WHERE Id = :repayment.cmbls__Payments__r[0].Id];
        System.assertEquals(PaymentUtils.PAYMENT_STATUS_CANCELED, oldPayment.cmbls__Status__c);
        System.assertEquals(null, oldPayment.cmbls__Notes__c);
    
        String outputMessage = String.format(ReschedulePayment.NOT_SCHEDULED_ERROR_MESSAGE, new String[]{oldPayment.Name, oldPayment.cmbls__Status__c});
        System.assertEquals(String.format(ReschedulePayment.ERROR_MESSAGE, new String[]{outputMessage}), results[0].output);
    }
}