unpackaged/main/default/objects/cmbls__GL_Transaction__c/cmbls__GL_Transaction__c.object-meta.xml
<CustomObject>
    <label>GL Transaction</label>
    <nameField>
        <label>GL Transaction Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GL Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/cmbls__GL_Transaction__c/fields/cmbls__Date__c.field-meta.xml
<CustomField>
    <fullName>cmbls__Date__c</fullName>
    <label>Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/cmbls__GP_Batch__c/cmbls__GP_Batch__c.object-meta.xml
<CustomObject>
    <label>GL Export</label>
    <nameField>
        <displayFormat>GL-{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GL Batches</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/cmbls__GP_Batch__c/fields/Batch_Related_Id__c.field-meta.xml
<CustomField>
    <fullName>Batch_Related_Id__c</fullName>
    <description>Id of Apex batchable context that helps to recover the record created by a specific batch.</description>
    <inlineHelpText>Id of Apex batchable context that helps to recover the record created by a specific batch.</inlineHelpText>
    <label>Batch Related Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/cmbls__GP_Batch__c/fields/cmbls__Status__c.field-meta.xml
<CustomField>
    <fullName>cmbls__Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Posted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/BatchCreateGLExportTest.cls
/**
 * BatchCreateGLExportTest class
 * @author CloudMyBiz (r)
 * @date 5/30/2023
 */

@IsTest
private class BatchCreateGLExportTest{
    
    @TestSetup static void setupMethod(){
        Test.startTest();
        insert new cmbls__GL_Transaction__c[]{
            new cmbls__GL_Transaction__c(cmbls__Date__c = System.today()),
            new cmbls__GL_Transaction__c(cmbls__Date__c = System.today()),
            new cmbls__GL_Transaction__c(cmbls__Date__c = System.today()),
            new cmbls__GL_Transaction__c(cmbls__Date__c = System.today())
        };
        
        Test.stopTest();
    }
    
    @IsTest
    static void behavior(){
        Test.startTest();
        Id jobId = Database.executeBatch(new BatchCreateGLExport());
        Test.stopTest();
        Assert.areEqual(1, [SELECT COUNT() FROM cmbls__GP_Batch__c WHERE Batch_Related_Id__c = :jobId AND cmbls__Status__c = 'Success']);
        Assert.areEqual(0, [SELECT COUNT() FROM cmbls__GL_Transaction__c WHERE cmbls__GP_Batch__c = NULL AND cmbls__Sent_to_GP__c = NULL]);
    }
    
    @IsTest
    static void schedule(){
        Test.startTest();
        String CRON_EXP = '0 0 23 * * ?';
        System.schedule('BatchCreateGLExport TEST', CRON_EXP, new BatchCreateGLExport());
        Test.stopTest();
    }
}