unpackaged/main/default/objects/cmbls__GL_Transaction__c/cmbls__GL_Transaction__c.object-meta.xml
<CustomObject>
    <label>GL Transaction</label>
    <nameField>
        <label>GL Transaction Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GL Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/cmbls__GP_Batch__c/cmbls__GP_Batch__c.object-meta.xml
<CustomObject>
    <label>GL Export</label>
    <nameField>
        <displayFormat>GL-{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>GL Batches</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/cmbls__GP_Batch__c/fields/Batch_Related_Id__c.field-meta.xml
<CustomField>
    <fullName>Batch_Related_Id__c</fullName>
    <description>Id of Apex batchable context that helps to recover the record created by a specific batch.</description>
    <inlineHelpText>Id of Apex batchable context that helps to recover the record created by a specific batch.</inlineHelpText>
    <label>Batch Related Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/cmbls__GP_Batch__c/fields/cmbls__Status__c.field-meta.xml
<CustomField>
    <fullName>cmbls__Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Posted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/BatchCreateGLExport.cls
/**
 * BatchCreateGLExport class
 * @author CloudMyBiz (r)
 * @date 5/30/2023
 */

global inherited sharing class BatchCreateGLExport implements Database.Batchable<SObject>, Schedulable{
    global Database.QueryLocator start(Database.BatchableContext bc){
        return Database.getQueryLocator([SELECT Id FROM cmbls__GL_Transaction__c WHERE cmbls__Sent_to_GP__c = NULL AND cmbls__GP_Batch__c = NULL]);
    }
    global void execute(Database.BatchableContext bc, List<cmbls__GL_Transaction__c> scope){
        cmbls__GP_Batch__c[] existingBatch = [SELECT Id FROM cmbls__GP_Batch__c WHERE Batch_Related_Id__c = :bc.getJobId()];
        cmbls__GP_Batch__c batch;
        if(existingBatch.isEmpty()){
            batch = new cmbls__GP_Batch__c(cmbls__Status__c = 'Success', Batch_Related_Id__c = bc.getJobId());
            insert batch;
        }else{
            batch = existingBatch[0];
        }
        
        for(cmbls__GL_Transaction__c item :scope){
            item.cmbls__GP_Batch__c = batch.Id;
            item.cmbls__Sent_to_GP__c = System.now();
        }
        update scope;
    }
    
    global void finish(Database.BatchableContext bc){}
    
    global void execute(SchedulableContext sc){
        Database.executeBatch(new BatchCreateGLExport());
    }

}