unpackaged/main/default/objects/Chart_of_Account__c/Chart_of_Account__c.object-meta.xml
<CustomObject>
    <label>Chart of Account</label>
    <nameField>
        <displayFormat>CA-{000000}</displayFormat>
        <label>Chart of Account Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Chart of Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Chart_of_Account_Key__c/Chart_of_Account_Key__c.object-meta.xml
<CustomObject>
    <label>Chart of Account Key</label>
    <nameField>
        <displayFormat>CAK-{00000}</displayFormat>
        <label>Chart of Account Key Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Chart of Accounts Key</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Chart_of_Account_Key__c/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Company</label>
    <referenceTo>cmbls__Fund__c</referenceTo>
    <relationshipLabel>Chart of Accounts Key</relationshipLabel>
    <relationshipName>Chart_of_Accounts_Key</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Chart_of_Account_Key__c/fields/Key__c.field-meta.xml
<CustomField>
    <fullName>Key__c</fullName>
    <label>Key</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>LOAN__c</fullName>
                <label>LOAN</label>
            </value>
            <value>
                <fullName>FRPSA__c</fullName>
                <label>FRPSA</label>
            </value>
            <value>
                <fullName>NFAS2__c</fullName>
                <label>NFAS2</label>
            </value>
            <value>
                <fullName>FRPS2__c</fullName>
                <label>FRPS2</label>
            </value>
            <value>
                <fullName>QBF__c</fullName>
                <label>QBF</label>
            </value>
            <value>
                <fullName>QBF_FRPSA__c</fullName>
                <label>QBF+FRPSA</label>
            </value>
            <value>
                <fullName>QBtoNF__c</fullName>
                <label>QBtoNF</label>
            </value>
            <value>
                <fullName>NFtoNFAS2__c</fullName>
                <label>NFtoNFAS2</label>
            </value>
            <value>
                <fullName>NFAS2toNF__c</fullName>
                <label>NFAS2toNF</label>
            </value>
            <value>
                <fullName>NFtoQB__c</fullName>
                <label>NFtoQB</label>
            </value>
            <value>
                <fullName>NFSPV1__c</fullName>
                <label>NFSPV1</label>
            </value>
            <value>
                <fullName>NFSPV1_FRPSA__c</fullName>
                <label>NFSPV1+FRPSA</label>
            </value>
            <value>
                <fullName>NFtoNFSPV1__c</fullName>
                <label>NFtoNFSPV1</label>
            </value>
            <value>
                <fullName>NFSPV1toNF__c</fullName>
                <label>NFSPV1toNF</label>
            </value>
            <value>
                <fullName>NFSPV2__c</fullName>
                <label>NFSPV2</label>
            </value>
            <value>
                <fullName>NFSPV2_FRPSA__c</fullName>
                <label>NFSPV2+FRPSA</label>
            </value>
            <value>
                <fullName>NFtoNFSPV2__c</fullName>
                <label>NFtoNFSPV2</label>
            </value>
            <value>
                <fullName>NFSPV2toNF__c</fullName>
                <label>NFSPV2toNF</label>
            </value>
            <value>
                <fullName>NFAS3__c</fullName>
                <label>NFAS3</label>
            </value>
            <value>
                <fullName>FRPS3__c</fullName>
                <label>FRPS3</label>
            </value>
            <value>
                <fullName>NFtoNFAS3__c</fullName>
                <label>NFtoNFAS3</label>
            </value>
            <value>
                <fullName>NFAS3toNF__c</fullName>
                <label>NFAS3toNF</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Chart_of_Account_Key__c/fields/Previous_Company__c.field-meta.xml
<CustomField>
    <fullName>Previous_Company__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Previous Company</label>
    <referenceTo>cmbls__Fund__c</referenceTo>
    <relationshipLabel>Chart of Accounts Key</relationshipLabel>
    <relationshipName>Chart_of_Accounts_Key2</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Chart_of_Account_Key__c/fields/Product_Type__c.field-meta.xml
<CustomField>
    <fullName>Product_Type__c</fullName>
    <label>Product Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Product_Type</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/globalValueSets/Product_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>FRPSA</fullName>
    </customValue>
    <customValue>
        <fullName>LOAN</fullName>
    </customValue>
    <masterLabel>Product Type</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/ChartOfAccountSelector.cls
/**
 * ChartOfAccountSelector class
 * @author CloudMyBiz (r)
 * @date 10/24/2022
 * @description Service Class. Interface between business logic and specific apex contexts such as Trigger Handlers, Controllers, Batch Classes, API etc.
 * Services generally include static methods that implement business logic. Exceptions are generally thrown for the caller to handle.
 * @group Services
 */
public inherited sharing class ChartOfAccountSelector{

    public static Chart_of_Account_Key__c[] getChartOfAccountKeys(){
        return [SELECT Id, Name, Key__c, Company__c, Product_Type__c, Previous_Company__c FROM Chart_of_Account_Key__c];
    }

    public static Chart_of_Account__c[] getChartOfAccounts(){
        List<String> fields = new List<String>(
            Chart_of_Account__c.sObjectType.getDescribe().fields.getMap().keySet()
        );
        return Database.query('SELECT ' + String.join(fields, ',') + ' FROM Chart_of_Account__c');
    }
}