unpackaged/main/default/objects/Data_Masking_Configuration__mdt/Data_Masking_Configuration__mdt.object-meta.xml
<CustomObject>
    <description>This custom Metadata is used to store object and field information which is used in batch which runs after sandbox refresh to mask data</description>
    <label>Data Masking Configuration</label>
    <pluralLabel>Data Masking Configurations</pluralLabel>
</CustomObject>

unpackaged/main/default/objects/Data_Masking_Configuration__mdt/fields/FieldName__c.field-meta.xml
<CustomField>
    <fullName>FieldName__c</fullName>
    <label>FieldName</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Data_Masking_Configuration__mdt/fields/MaskType__c.field-meta.xml
<CustomField>
    <fullName>MaskType__c</fullName>
    <label>MaskType</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Data_Masking_Configuration__mdt/fields/ObjectName__c.field-meta.xml
<CustomField>
    <fullName>ObjectName__c</fullName>
    <label>Object Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/SandboxPostRefreshTest.cls
/**
* ─────────────────────────────────────────────────────────────────────────────────────────────────
* TITLE: SandboxPostRefreshTest 
* DESCRIPTION:This class is test class of SandboxPostRefresh 
* @author         Supriya Gore
* @version        1.0
* @created        18/03/2025
* @mofidied       
* ────────────────────────────────────────────────────────────────────────────────────────────────   */

@isTest
private class SandboxPostRefreshTest {

    @isTest
    static void testRunApexClass() {
        Test.startTest();
        
        SandboxPostRefresh sandboxClass = new SandboxPostRefresh();
        
        sandboxClass.runApexClass(null);  // Passing null for context (or you could simulate SandboxContext if needed)

        Test.stopTest();

        // Verify that the metadata records exist
        List<Data_Masking_Configuration__mdt> metadataRecords = [SELECT ObjectName__c, FieldName__c, MaskType__c FROM Data_Masking_Configuration__mdt];
        for(Data_Masking_Configuration__mdt cm : metadataRecords){
            if(cm.FieldName__c == 'Email'){
                System.assertEquals('invalid', cm.MaskType__c, 'The masktype for email should be invalid');
            }
        }

    }
    
}