unpackaged/main/default/objects/Data_Masking_Configuration__mdt/Data_Masking_Configuration__mdt.object-meta.xml
<CustomObject>
    <description>This custom Metadata is used to store object and field information which is used in batch which runs after sandbox refresh to mask data</description>
    <label>Data Masking Configuration</label>
    <pluralLabel>Data Masking Configurations</pluralLabel>
</CustomObject>

unpackaged/main/default/objects/Data_Masking_Configuration__mdt/fields/FieldName__c.field-meta.xml
<CustomField>
    <fullName>FieldName__c</fullName>
    <label>FieldName</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Data_Masking_Configuration__mdt/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>true</defaultValue>
    <description>This checkbox will decide whether to consider field for data masking or not</description>
    <label>IsActive</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Data_Masking_Configuration__mdt/fields/MaskType__c.field-meta.xml
<CustomField>
    <fullName>MaskType__c</fullName>
    <label>MaskType</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Data_Masking_Configuration__mdt/fields/ObjectName__c.field-meta.xml
<CustomField>
    <fullName>ObjectName__c</fullName>
    <label>Object Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Data_Masking_Configuration__mdt/fields/QueryFilter__c.field-meta.xml
<CustomField>
    <fullName>QueryFilter__c</fullName>
    <label>QueryFilter</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/SandboxPostRefresh.cls
/**
* ─────────────────────────────────────────────────────────────────────────────────────────────────
* TITLE: SandboxPostRefresh
* DESCRIPTION:This class runs automatically after sandbox refresh and invokes data masking batch class
* @author         Supriya Gore
* @version        1.0
* @created        18/03/2025
* @mofidied       
* ────────────────────────────────────────────────────────────────────────────────────────────────   */
global class SandboxPostRefresh implements SandboxPostCopy {
//Below is the method of sandboxpostcopy interface which will invoke data masking batch after sandbox refresh
        global void runApexClass(SandboxContext context) {
            if(context!=null){
                System.debug(context.organizationId());
                System.debug(context.sandboxId());
                System.debug(context.sandboxName());
            }
            
            // Query all custom metadata records
            List<Data_Masking_Configuration__mdt> metadataRecords = [SELECT ObjectName__c, FieldName__c, MaskType__c,QueryFilter__c,IsActive__c FROM Data_Masking_Configuration__mdt where IsActive__c =true];
            
            // Create a map to store values with DeveloperName as the key
            Map<String, Map<String, String>> metadataMap = new Map<String, Map<String, String>>();
            Map<string,string> objectFilter = new Map<string,string>();
            // Iterate through the metadata records and add them to the map
            for (Data_Masking_Configuration__mdt record : metadataRecords) {
                // Create a sub-map to store the field values for each record
                Map<String, String> fieldValues = new Map<String, String>();
                //fieldValues.put(record.FieldName__c, record.MaskType__c);
                if(record.QueryFilter__c != null){
                    string filter = ' '+record.QueryFilter__c;
                    if(!objectFilter.containsKey(record.ObjectName__c)){
                        objectFilter.put(record.ObjectName__c,' '+filter);
                    }
                }
                // Add the sub-map to the main map with DeveloperName as the key
                if (!metadataMap.containsKey(record.ObjectName__c)) {
                    metadataMap.put(record.ObjectName__c, new Map<String, String>());
                }
                metadataMap.get(record.ObjectName__c).put(record.FieldName__c, record.MaskType__c);
            }
            For(String ObjectName: metadataMap.keySet()){
            string queryFilter ='';
            if(objectFilter.get(ObjectName)!=null)
            queryFilter = objectFilter.get(ObjectName);
                BatchToMaskData batch = new BatchToMaskData(ObjectName,metadataMap.get(ObjectName),queryFilter);  // Specify the object type
                Database.executeBatch(batch, 200);
            }
        }
    }