unpackaged/main/default/objects/cmbls__Fund__c/cmbls__Fund__c.object-meta.xml
<CustomObject>
    <label>Fund</label>
    <nameField>
        <label>Fund Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Funds</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/cmbls__Loan_Servicing_Settings__c/cmbls__Loan_Servicing_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Loan Servicing Settings</label>
</CustomObject>

unpackaged/main/default/objects/cmbls__Loan_Servicing_Settings__c/fields/National_Funding_Fund_Id__c.field-meta.xml
<CustomField>
    <fullName>National_Funding_Fund_Id__c</fullName>
    <inlineHelpText>National Funding’s ‘Fund’ record to transfer loans</inlineHelpText>
    <label>National Funding Fund Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/cmbls__Loan_Transfer__c/cmbls__Loan_Transfer__c.object-meta.xml
<CustomObject>
    <label>Loan Transfer</label>
    <nameField>
        <label>Loan Transfer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Loans Transfer</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/cmbls__Loan_Transfer__c/fields/Broker_Fee_Balance__c.field-meta.xml
<CustomField>
    <fullName>Broker_Fee_Balance__c</fullName>
    <label>Broker Fee Balance</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/cmbls__Loan_Transfer__c/fields/cmbls__Amount__c.field-meta.xml
<CustomField>
    <fullName>cmbls__Amount__c</fullName>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/cmbls__Loan_Transfer__c/fields/cmbls__New_Fund__c.field-meta.xml
<CustomField>
    <fullName>cmbls__New_Fund__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>New Fund</label>
    <referenceTo>cmbls__Fund__c</referenceTo>
    <relationshipLabel>Loan Transfers</relationshipLabel>
    <relationshipName>Loan_Transfers</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/cmbls__Loan_Transfer__c/fields/cmbls__Repayment__c.field-meta.xml
<CustomField>
    <fullName>cmbls__Repayment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Repayment</label>
    <referenceTo>cmbls__Repayment__c</referenceTo>
    <relationshipLabel>Loan Transfers</relationshipLabel>
    <relationshipName>Loan_Transfers</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/cmbls__Loan_Transfer__c/fields/cmbls__Unpaid_Accrued_Interest__c.field-meta.xml
<CustomField>
    <fullName>cmbls__Unpaid_Accrued_Interest__c</fullName>
    <inlineHelpText>Difference between Interest Accrued and Interest Paid</inlineHelpText>
    <label>Unpaid Accrued Interest</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/cmbls__Loan_Transfer__c/fields/Interest_Balance__c.field-meta.xml
<CustomField>
    <fullName>Interest_Balance__c</fullName>
    <label>Interest Balance</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/cmbls__Loan_Transfer__c/fields/Origination_Fee_Balance__c.field-meta.xml
<CustomField>
    <fullName>Origination_Fee_Balance__c</fullName>
    <label>Origination Fee Balance</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/cmbls__Loan_Transfer__c/fields/Principal_Balance__c.field-meta.xml
<CustomField>
    <fullName>Principal_Balance__c</fullName>
    <label>Principal Balance</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/cmbls__Queued_Event__c/cmbls__Queued_Event__c.object-meta.xml
<CustomObject>
    <label>Queued Event</label>
    <nameField>
        <displayFormat>QE-{0000}</displayFormat>
        <label>Queued Event Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Queued Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/cmbls__Queued_Event__c/fields/Canceled__c.field-meta.xml
<CustomField>
    <fullName>Canceled__c</fullName>
    <defaultValue>false</defaultValue>
    <description>The system will mark this field as checked if the conditions no longer applies</description>
    <inlineHelpText>The system will mark this field as checked if the conditions no longer applies</inlineHelpText>
    <label>Canceled</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/cmbls__Queued_Event__c/fields/Deleted_Record_Id__c.field-meta.xml
<CustomField>
    <fullName>Deleted_Record_Id__c</fullName>
    <defaultValue>false</defaultValue>
    <description>The system will mark this field as checked if the related record Id no longer exist</description>
    <inlineHelpText>The system will mark this field as checked if the related record Id no longer exist</inlineHelpText>
    <label>Deleted Record Id</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/cmbls__Repayment__c/cmbls__Repayment__c.object-meta.xml
<CustomObject>
    <label>Repayment</label>
    <nameField>
        <displayFormat>RPMT-{0000000}</displayFormat>
        <label>Repayment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Repayments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/cmbls__Repayment__c/fields/cmbls__Funding_Amount__c.field-meta.xml
<CustomField>
    <fullName>cmbls__Funding_Amount__c</fullName>
    <description>Amount that was put on the Contract</description>
    <inlineHelpText>Amount that was put on the Contract</inlineHelpText>
    <label>Funding Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/cmbls__Repayment__c/fields/cmbls__Loan_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>cmbls__Loan_Start_Date__c</fullName>
    <label>Loan Start Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/cmbls__Repayment__c/fields/cmbls__Primary_Fund__c.field-meta.xml
<CustomField>
    <fullName>cmbls__Primary_Fund__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Primary Fund</label>
    <referenceTo>cmbls__Fund__c</referenceTo>
    <relationshipLabel>Repayments</relationshipLabel>
    <relationshipName>Repayments</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/cmbls__Repayment__c/fields/cmbls__Status__c.field-meta.xml
<CustomField>
    <fullName>cmbls__Status__c</fullName>
    <description>Active, pause, complete, and new</description>
    <inlineHelpText>Active, pause, complete, and new</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Temporary Pause</fullName>
            </value>
            <value>
                <fullName>Pause</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Write Off</fullName>
            </value>
            <value>
                <fullName>Recovery</fullName>
            </value>
            <value>
                <fullName>Unwind</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/LoanTransfer.cls
public inherited sharing class LoanTransfer{
    public cmbls__Loan_Servicing_Settings__c settings = cmbls__Loan_Servicing_Settings__c.getInstance();
    private Map<Id, cmbls__Queued_Event__c> queuedEventsByRepayment;
    private cmbls__Repayment__c[] repayments;
    private Map<Id, Decimal> originationFeeExpensesByRepayment;
    private Map<Id, Decimal> expenseBrokerFeesByRepayment;
    private cmbls__Loan_Transfer__c[] loanTransfersToCreate;
    private cmbls__Debug_Log__c[] logs;
    private cmbls__Fund__c fundRecord;
    
    public LoanTransfer(cmbls__Queued_Event__c[] queuedEvents){
        this.queuedEventsByRepayment = new Map<Id, cmbls__Queued_Event__c>();
        for(cmbls__Queued_Event__c item :queuedEvents) this.queuedEventsByRepayment.put(item.cmbls__Record_Id__c, item);
        this.repayments = RepaymentSelector.getQuickBridgeFundedRecords(this.queuedEventsByRepayment.keySet());
        this.originationFeeExpensesByRepayment = ExpenseSelector.getSumOriginationFeeExpensesByRepayment(this.queuedEventsByRepayment.keySet());
        this.expenseBrokerFeesByRepayment = ExpenseSelector.getSumExpenseBrokerFeesByRepayment(this.queuedEventsByRepayment.keySet());
        this.fundRecord = RepaymentSelector.getTransferFundRecord(settings.National_Funding_Fund_Id__c);
        this.loanTransfersToCreate = new cmbls__Loan_Transfer__c[]{};
        this.logs = new cmbls__Debug_Log__c[]{};
    }
    
    public void processQueuedEvents(){
        
        for(cmbls__Repayment__c repayment :this.getRepaymentsToProcess()){
            Decimal principalBalance = NumberUtils.getDecimal(repayment.cmbls__Funding_Amount__c);
            Decimal originationFeeBalance = NumberUtils.getDecimal(originationFeeExpensesByRepayment.get(repayment.Id));
            Decimal brokerFeeBalance = NumberUtils.getDecimal(expenseBrokerFeesByRepayment.get(repayment.Id));
            this.loanTransfersToCreate.add(this.getRecord(repayment.Id, principalBalance, originationFeeBalance, brokerFeeBalance));
        }
        
        Integer index = 0;
        for(Database.SaveResult result :Database.insert(this.loanTransfersToCreate, false)){
            cmbls__Loan_Transfer__c record = this.loanTransfersToCreate[index];
            cmbls__Queued_Event__c queuedEvent = this.queuedEventsByRepayment.get(record.cmbls__Repayment__c);
            queuedEvent.cmbls__Date_Processed__c = System.now();
            queuedEvent.cmbls__Number_of_Attempts__c = NumberUtils.getDecimal(queuedEvent.cmbls__Number_of_Attempts__c) + 1;
            
            if(!result.isSuccess()){
                cmbls__Debug_Log__c log = UtilityTools.getDebugLogForDMLFailure(null, record, result);
                log.cmbls__Subject__c = String.format(RepaymentUtils.AUTOMATIC_TRANSFER_ERROR_SUBJECT, new String[]{record.cmbls__Repayment__c});
                log.cmbls__Description__c = RepaymentUtils.AUTOMATIC_TRANSFER_ERROR_DESCRIPTION;
                this.logs.add(log);
                
                queuedEvent.cmbls__Date_Processed__c = null;
            }
            index++;
        }
    }
    
    public void save(){
        Database.update(this.queuedEventsByRepayment.values());
        Database.insert(this.logs);
    }
    
    public cmbls__Repayment__c[] getRepaymentsToProcess(){
        Map<Id, cmbls__Repayment__c> repaymentMap = new Map<Id, cmbls__Repayment__c>(this.repayments);
        cmbls__Repayment__c[] repaymentsToProcess = new cmbls__Repayment__c[]{};
        for(Id repaymentId :this.queuedEventsByRepayment.keySet()){
            if(!repaymentMap.containsKey(repaymentId)){
                this.queuedEventsByRepayment.get(repaymentId).Deleted_Record_Id__c = true;
            }else{
                cmbls__Repayment__c repayment = repaymentMap.get(repaymentId);
                if(repayment.cmbls__Loan_Start_Date__c <= System.today()){
                    cmbls__Debug_Log__c log = UtilityTools.getDebugLogForDMLFailure(null, repayment, null);
                    log.cmbls__Subject__c = String.format(RepaymentUtils.AUTOMATIC_TRANSFER_ERROR_SUBJECT, new String[]{repayment.Id});
                    log.cmbls__Description__c = RepaymentUtils.AUTOMATIC_TRANSFER_ERROR_DESCRIPTION;
                    if(repayment.cmbls__Status__c == RepaymentUtils.STATUS_UNWIND){
                        this.queuedEventsByRepayment.get(repaymentId).Canceled__c = true;
                        log.cmbls__Log__c += '- Message: Invalid Repayment Status "' + repayment.cmbls__Status__c + '"';
                        this.logs.add(log);
                    }else if(String.isBlank(repayment.cmbls__Primary_Fund__c) || this.fundRecord == null){
                        log.cmbls__Log__c += '- Message: Missing Required Fields' +
                            '- Fields: \n' +
                            '--- cmbls__Primary_Fund__c = "' + repayment.cmbls__Primary_Fund__c + '"\n' +
                            '--- cmbls__New_Fund__c = "' + this.fundRecord?.Id + '"\n';
                        this.logs.add(log);
                    }else{
                        repaymentsToProcess.add(repayment);
                    }
                }
            }
        }
        return repaymentsToProcess;
    }
    
    public cmbls__Loan_Transfer__c getRecord(Id repaymentId, Decimal principalBalance, Decimal originationFeeBalance, Decimal brokerFeeBalance){
        return new cmbls__Loan_Transfer__c(
            cmbls__Loan_Transfer_Date__c = System.today(),
            cmbls__New_Fund__c = fundRecord.Id,
            Principal_Balance__c = principalBalance,
            Interest_Balance__c = 0,
            Origination_Fee_Balance__c = originationFeeBalance,
            cmbls__Indirect_Cost_Origination_Fee__c = originationFeeBalance,
            Broker_Fee_Balance__c = brokerFeeBalance,
            cmbls__Unpaid_Accrued_Interest__c = 0,
            cmbls__Amount__c = (principalBalance + brokerFeeBalance) - originationFeeBalance,
            cmbls__Type__c = RepaymentUtils.TRANSFER_TYPE_INTERNAL,
            cmbls__Repayment__c = repaymentId,
            cmbls__Unaccrued_Expense_Balances__c = 'Include in Loan Transfer'
        );
    }
}