unpackaged/main/default/objects/FPC_Funding_del__c/FPC_Funding_del__c.object-meta.xml
<CustomObject>
    <description>Table of lenders this deal is shopped to.</description>
    <label>Funding</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Funding ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Funding</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/FPC_Funding_del__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Funding</relationshipLabel>
    <relationshipName>Funding</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/FPC_Funding_del__c/fields/Send_Method__c.field-meta.xml
<CustomField>
    <fullName>Send_Method__c</fullName>
    <description>Indicates if Funding record will be submitted to lender manually or automatically via Syndication API webservice.</description>
    <label>Send Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Automated</fullName>
            </value>
            <value>
                <fullName>Manual</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/FPC_Funding_del__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status of funding</description>
    <inlineHelpText>Pick the funding status of the opportunity.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Older Approval</fullName>
            </value>
            <value>
                <fullName>Lender Pend Info</fullName>
            </value>
            <value>
                <fullName>Lender Approved</fullName>
            </value>
            <value>
                <fullName>Send to Lender</fullName>
            </value>
            <value>
                <fullName>Hold</fullName>
            </value>
            <value>
                <fullName>Not Eligible</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Withdrawn</fullName>
            </value>
            <value>
                <fullName>Auto Submitting</fullName>
            </value>
            <value>
                <fullName>Submission in Progress</fullName>
            </value>
            <value>
                <fullName>Referred</fullName>
            </value>
            <value>
                <fullName>Processing</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Closed - Won</fullName>
            </value>
            <value>
                <fullName>Closed - Lost</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/STSConfig__c/STSConfig__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>STSConfig</label>
</CustomObject>

unpackaged/main/default/objects/STSConfig__c/fields/Endpoint__c.field-meta.xml
<CustomField>
    <fullName>Endpoint__c</fullName>
    <label>Endpoint</label>
    <type>Url</type>
</CustomField>

unpackaged/main/default/objects/Syndication__c/Syndication__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Syndication</label>
</CustomObject>

unpackaged/main/default/classes/SyndicationOrchestratorTest.cls
/**
 * Created by oporter on 12/31/2018.
 */

@isTest
public with sharing class SyndicationOrchestratorTest {

    public static testMethod void testSuccess(){
        SingleRequestMockClass fakeResponse = new SingleRequestMockClass(204, 'Complete', 'test', null);
        Test.startTest();
        Opportunity opp = new Opportunity(StageName = 'test', CloseDate = Date.today(),Name = 'test');
        insert opp;
        FPC_Funding_del__c fundingRecord = new FPC_Funding_del__c(Opportunity__c = opp.Id);
        insert fundingRecord;
        List<Id> fundingRecordList = new List<Id>();
        fundingRecordList.add(fundingRecord.Id);
        Test.setMock(HttpCalloutMock.class, fakeResponse);
        SyndicationOrchestrator.authenticateAndPostSyndicationService('test', '123', 'test', fundingRecord.Id);
        Test.stopTest();
        system.assertEquals(fundingRecord.Status__c, null); //this will change depending on how we call the class from the PB
    }

    public static testMethod void testSynd(){
        STSConfig__c stsConfig = new STSConfig__c(Endpoint__c = 'test');
        insert stsConfig;
        Syndication__c syndicationCustomSetting = new Syndication__c(Endpoint__c = 'test', APIKey__c = '123456789');
        insert syndicationCustomSetting;
        SingleRequestMockClass fakeResponse = new SingleRequestMockClass(204, 'Complete', 'test', null);
        Test.startTest();
        Opportunity opp = new Opportunity(StageName = 'test', CloseDate = Date.today(),Name = 'test');
        insert opp;
        FPC_Funding_del__c fundingRecord = new FPC_Funding_del__c(Opportunity__c = opp.Id);
        insert fundingRecord;
        List<Id> fundingRecordList = new List<Id>();
        
        Test.setMock(HttpCalloutMock.class, fakeResponse);
        SyndicationOrchestrator.SyndicationRequestWrapper wrapper = new SyndicationOrchestrator.SyndicationRequestWrapper();
        wrapper.fundingId = fundingRecord.Id;
    	wrapper.brand = 'Quick Bridge'; 
        List<SyndicationOrchestrator.SyndicationRequestWrapper> requestList = new List<SyndicationOrchestrator.SyndicationRequestWrapper>{ wrapper };
        SyndicationOrchestrator.getSyndication(requestList);
        Test.stopTest();
        system.assertEquals(fundingRecord.Status__c, null); //this will change depending on how we call the class from the PB
    }

    public static testMethod void testError(){
        Opportunity opp = new Opportunity(StageName = 'test', CloseDate = Date.today(),Name = 'test');
        insert opp;
        FPC_Funding_del__c fundingRecord = new FPC_Funding_del__c(Opportunity__c = opp.Id);
        insert fundingRecord;
        SyndicationOrchestrator.updateFundingRecordError(401, 'Internal Error', fundingRecord.Id);
        system.assertEquals(null, fundingRecord.Status__c); //this will change depending on how we call the class from the PB
    }

    public static testMethod void testCallPB(){
        STSConfig__c stsConfig = new STSConfig__c(Endpoint__c = 'test');
        insert stsConfig;
        Syndication__c syndicationCustomSetting = new Syndication__c(Endpoint__c = 'test', APIKey__c = '123456789');
        insert syndicationCustomSetting;
        SingleRequestMockClass fakeResponse = new SingleRequestMockClass(204, 'Complete', 'test', null);
        Test.startTest();
        Opportunity opp = new Opportunity(StageName = 'test', CloseDate = Date.today(),Name = 'test');
        insert opp;
        FPC_Funding_del__c fundingRecord = new FPC_Funding_del__c(Opportunity__c = opp.Id);
        insert fundingRecord;
        List<Id> fundingRecordList = new List<Id>();
        fundingRecordList.add(fundingRecord.Id);
        Test.setMock(HttpCalloutMock.class, fakeResponse);
        fundingRecord.Status__c = 'Send to Lender';
        fundingRecord.Send_Method__c = 'Automated';
        update fundingRecord;
        Test.stopTest();
        system.assertEquals(fundingRecord.Status__c, 'Send to Lender');
    }
}