unpackaged/main/default/objects/FPC_Funding_del__c/FPC_Funding_del__c.object-meta.xml
<CustomObject>
    <description>Table of lenders this deal is shopped to.</description>
    <label>Funding</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Funding ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Funding</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/FPC_Funding_del__c/fields/Error_Message__c.field-meta.xml
<CustomField>
    <fullName>Error_Message__c</fullName>
    <label>Error Message</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/FPC_Funding_del__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status of funding</description>
    <inlineHelpText>Pick the funding status of the opportunity.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Older Approval</fullName>
            </value>
            <value>
                <fullName>Lender Pend Info</fullName>
            </value>
            <value>
                <fullName>Lender Approved</fullName>
            </value>
            <value>
                <fullName>Send to Lender</fullName>
            </value>
            <value>
                <fullName>Hold</fullName>
            </value>
            <value>
                <fullName>Not Eligible</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Withdrawn</fullName>
            </value>
            <value>
                <fullName>Auto Submitting</fullName>
            </value>
            <value>
                <fullName>Submission in Progress</fullName>
            </value>
            <value>
                <fullName>Referred</fullName>
            </value>
            <value>
                <fullName>Processing</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/HTTPCalloutConfiguration__mdt/HTTPCalloutConfiguration__mdt.object-meta.xml
<CustomObject>
    <label>HTTPCalloutConfiguration</label>
    <pluralLabel>HTTPCalloutConfigurations</pluralLabel>
</CustomObject>

unpackaged/main/default/objects/HTTPCalloutConfiguration__mdt/fields/APIKey__c.field-meta.xml
<CustomField>
    <fullName>APIKey__c</fullName>
    <label>APIKey</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/HTTPCalloutConfiguration__mdt/fields/Endpoint__c.field-meta.xml
<CustomField>
    <fullName>Endpoint__c</fullName>
    <label>Endpoint</label>
    <type>Url</type>
</CustomField>

unpackaged/main/default/classes/SyndicationOrchestrator.cls
/*
* Created by oporter on 12/28/18
* ─────────────────────────────────────────────────────────────────────────────────────────────────
* TITLE: SyndicationOrchestrator
* DESCRIPTION: When NF does not approve a deal, we send the deal to Syndication. This class is the interfaction between us and the other provider APIS.
*
* ─────────────────────────────────────────────────────────────────────────────────────────────────
* @author         Olivia Porter       <oporter@nationalfunding.com>
* @modifiedBy     Olivia Porter       <oporter@nationalfunding.com>
* @maintainedBy   Olivia Porter       <oporter@nationalfunding.com>
* @version        1.0
* @created        2018-12.28
* @modified
* ─────────────────────────────────────────────────────────────────────────────────────────────────
* v1              test@nationalfunding.com
* 0000-00-00      Explanation of the change.  Multiple lines can be used to explain the change, but
*                 each line should be indented till left aligned with the previous description text.
* v2			  
*2025-05-02		  Update getSyndication method regarding SPR-122.Fetches the Syndication configuration based on the brand.
*
*/

public with sharing class SyndicationOrchestrator {

    @InvocableMethod
    public static void getSyndication(List<SyndicationRequestWrapper> requests) {
        HTTPCalloutConfiguration__mdt stsConfig = HTTPCalloutConfiguration__mdt.getInstance('STS');
         Map<String, HTTPCalloutConfiguration__mdt> syndicationConfigMap = new Map<String, HTTPCalloutConfiguration__mdt>{
            'Quick Bridge' => HTTPCalloutConfiguration__mdt.getInstance('Syndication_QB'),
            'Default'      => HTTPCalloutConfiguration__mdt.getInstance('Syndication')
        };
        
        for (SyndicationRequestWrapper request : requests) {
            Id fundingId = request.fundingId;
            HTTPCalloutConfiguration__mdt syndicateConfig = syndicationConfigMap.containsKey(request.brand) ? syndicationConfigMap.get(request.brand) : syndicationConfigMap.get('Default');
            authenticateAndPostSyndicationService(stsConfig.Endpoint__c, syndicateConfig.APIKey__c, syndicateConfig.Endpoint__c, fundingId);        
    	}
    }

    public static String authorize(String stsEndpoint, String apikey){
        HttpRequest httpRequest = new HttpRequest();
        httpRequest.setMethod('POST');
        httpRequest.setEndpoint(stsEndpoint);
        httpRequest.setHeader('Content-Type', 'application/json');
        httpRequest.setBody('"' + apikey + '"');
        Http http = new Http();
        HttpResponse response = http.send(httpRequest);
        if (!WebHelper.isSuccessStatus(response)) {
            throw new GenericException('There has been an error calling the STS service.');
        }
        String securityToken = response.getBody();
        system.debug('security token:: ' + securityToken);
        String tokenizerAuthentication = 'token ' + securityToken;
        return tokenizerAuthentication;
    }

    @Future(callout=true)
    public static void authenticateAndPostSyndicationService(String stsEndpoint, String apikey, String syndicationEndpoint, Id fundingId){
        String authorization = authorize(stsEndpoint, apikey);
        HttpRequest synHttpRequest = new HttpRequest();
        synHttpRequest.setMethod('POST');
        synHttpRequest.setEndpoint(syndicationEndpoint);
        synHttpRequest.setHeader('Authorization', authorization);
        synHttpRequest.setHeader('Content-Type', 'application/json');
        synHttpRequest.setBody('{"FundingId":"' + fundingId + '"}');
        Http http = new Http();
        HttpResponse response = http.send(synHttpRequest);
        system.debug('response:: ' + response);
        system.debug('response:: ' + response.getBody());
        if (!WebHelper.isSuccessStatus(response)) {
            updateFundingRecordError(response.getStatusCode(), response.getStatus(), fundingId);
        }
    }

    public static void updateFundingRecordError(Integer statusCode, String status, Id fundingId){
        NFLogger.logError('SyndicationOrchestrator', 'There has been an issue with Funding Record(s): ' + fundingId, status);
        FPC_Funding_del__c fundingRecord = new FPC_Funding_del__c(Id = fundingId, Status__c = 'Error', Error_Message__c = status);
        update fundingRecord;
    }
    
    public class SyndicationRequestWrapper {
        @InvocableVariable(required=true)
        public Id fundingId;
    
        @InvocableVariable(required=true)
        public String brand;
    }
}