unpackaged/main/default/objects/cmbls__Invoice__c/cmbls__Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <displayFormat>INV-{0000}</displayFormat>
        <label>Invoice #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/cmbls__Invoice__c/fields/cmbls__Repayment__c.field-meta.xml
<CustomField>
    <fullName>cmbls__Repayment__c</fullName>
    <label>Repayment</label>
    <referenceTo>cmbls__Repayment__c</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/cmbls__Invoice__c/fields/Omit_From_FUNAS_Auto_Generation__c.field-meta.xml
<CustomField>
    <fullName>Omit_From_FUNAS_Auto_Generation__c</fullName>
    <formula>OR(
    cmbls__Total__c &lt;= 0,
				cmbls__Total_Fees__c = cmbls__Total__c
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Omit From FUNAS Auto Generation</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/cmbls__Repayment__c/cmbls__Repayment__c.object-meta.xml
<CustomObject>
    <label>Repayment</label>
    <nameField>
        <displayFormat>RPMT-{0000000}</displayFormat>
        <label>Repayment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Repayments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/cmbls__Repayment__c/fields/cmbls__First_Payment_Date__c.field-meta.xml
<CustomField>
    <fullName>cmbls__First_Payment_Date__c</fullName>
    <label>First Payment Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/cmbls__Repayment__c/fields/cmbls__Funded_Date__c.field-meta.xml
<CustomField>
    <fullName>cmbls__Funded_Date__c</fullName>
    <inlineHelpText>This will be used to indicate the funded date for the original deal</inlineHelpText>
    <label>Funded Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/cmbls__Repayment__c/fields/cmbls__Funding_Amount__c.field-meta.xml
<CustomField>
    <fullName>cmbls__Funding_Amount__c</fullName>
    <description>Amount that was put on the Contract</description>
    <inlineHelpText>Amount that was put on the Contract</inlineHelpText>
    <label>Funding Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/cmbls__Repayment__c/fields/cmbls__Maturity_Date__c.field-meta.xml
<CustomField>
    <fullName>cmbls__Maturity_Date__c</fullName>
    <inlineHelpText>Maturity Date for Loan</inlineHelpText>
    <label>Current Maturity Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/cmbls__Repayment__c/fields/cmbls__Payment_Amount__c.field-meta.xml
<CustomField>
    <fullName>cmbls__Payment_Amount__c</fullName>
    <description>Amount of incremental payments</description>
    <inlineHelpText>Amount of incremental payments</inlineHelpText>
    <label>Installment Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/cmbls__Repayment__c/fields/FUNAS_Execution_Result__c.field-meta.xml
<CustomField>
    <fullName>FUNAS_Execution_Result__c</fullName>
    <label>FUNAS Execution Result</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/cmbls__Repayment__c/fields/Generate_FUNAS_Amortization_Schedule__c.field-meta.xml
<CustomField>
    <fullName>Generate_FUNAS_Amortization_Schedule__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If checked, a batch job will pull the record and it will run Funas Amortization.</description>
    <inlineHelpText>If checked, a batch job will pull the record and it will run Funas Amortization.</inlineHelpText>
    <label>Generate FUNAS Amortization Schedule</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/cmbls__Repayment__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Repayments (Opportunity)</relationshipLabel>
    <relationshipName>Repayments</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/BatchGenerateFunasAmortizationTest.cls
/**
 * BatchGenerateFunasAmortizationTest class
 * @author CloudMyBiz (r)
 * @date 17/06/2022
 * @description
 * @group 
 */

@IsTest
private class BatchGenerateFunasAmortizationTest {

    @TestSetup static void setupMethod() {
        Test.startTest();
        Account acc = TestDataFactory.createAccount();
        insert acc;

        Opportunity opp = TestDataFactory.createOpportunity(acc.Id);
        insert opp;

        cmbls__Repayment__c repayment = TestDataFactory.createRepayment(acc.Id);
        repayment.cmbls__Current_Interest_Rate__c = 10;
        repayment.cmbls__Initial_Payment_Amount__c = 1000;
        repayment.cmbls__Interest_Accrual_Frequency__c = Constant.INTEREST_ACCRUAL_FREQUENCY_MONTHLY;
        repayment.Generate_FUNAS_Amortization_Schedule__c = true;
        repayment.cmbls__First_Payment_Date__c = Date.today().addMonths(-2);
        repayment.cmbls__Funded_Date__c = Date.today().addMonths(-3);
        repayment.cmbls__Payment_Amount__c = 1000;
        repayment.cmbls__Funding_Amount__c = 10000;
        repayment.Opportunity__c = opp.Id;
        insert repayment;

        cmbls__Invoice__c invoice = TestDataFactory.createInvoice(repayment.Id, Date.today());
        insert invoice;

        cmbls__Invoice_Line_Item__c invoiceLineItem = TestDataFactory.createInvoiceLineItem(1000, Date.today(), invoice.Id);
        insert invoiceLineItem;

        Test.stopTest();
    }

    @IsTest static void monthlyAmortization() {
        Test.startTest();
        Database.executeBatch(new BatchGenerateFunasAmortization());
        Test.stopTest();

        cmbls__Repayment__c repayment = [SELECT Id, Generate_FUNAS_Amortization_Schedule__c, FUNAS_Execution_Result__c, cmbls__Maturity_Date__c FROM cmbls__Repayment__c];
        System.assertEquals(false, repayment.Generate_FUNAS_Amortization_Schedule__c);
        System.assertNotEquals(null, repayment.FUNAS_Execution_Result__c);
        System.assert(repayment.FUNAS_Execution_Result__c.contains('successfully'));
        System.assertNotEquals(null, repayment.cmbls__Maturity_Date__c);
        System.assert([SELECT COUNT() FROM cmbls__Amortization_Schedule__c WHERE cmbls__Repayment__c =: repayment.Id] > 0);
    }

    @IsTest static void weeklyAmortization() {
        cmbls__Repayment__c repayment = [SELECT Id, Generate_FUNAS_Amortization_Schedule__c, FUNAS_Execution_Result__c, cmbls__Maturity_Date__c FROM cmbls__Repayment__c];
        repayment.cmbls__Interest_Accrual_Frequency__c = Constant.INTEREST_ACCRUAL_FREQUENCY_MONTHLY;
        update repayment;

        Test.startTest();
        new BatchGenerateFunasAmortization().execute(null);
        Test.stopTest();

        repayment = [SELECT Generate_FUNAS_Amortization_Schedule__c, FUNAS_Execution_Result__c, cmbls__Maturity_Date__c FROM cmbls__Repayment__c WHERE Id = :repayment.Id];
        System.assertEquals(false, repayment.Generate_FUNAS_Amortization_Schedule__c);
        System.assertNotEquals(null, repayment.FUNAS_Execution_Result__c);
        System.assert(repayment.FUNAS_Execution_Result__c.contains('successfully'));
        System.assertNotEquals(null, repayment.cmbls__Maturity_Date__c);
        System.assert([SELECT COUNT() FROM cmbls__Amortization_Schedule__c WHERE cmbls__Repayment__c =: repayment.Id] > 0);
    }
    
    @IsTest static void omittedInvoice() {
        cmbls__Repayment__c repayment = [SELECT Id, Generate_FUNAS_Amortization_Schedule__c, FUNAS_Execution_Result__c, cmbls__Maturity_Date__c FROM cmbls__Repayment__c];
        cmbls__Invoice_Line_Item__c lineItem = [SELECT Id, cmbls__Invoice__c FROM cmbls__Invoice_Line_Item__c WHERE cmbls__Invoice__r.cmbls__Repayment__c = :repayment.Id];
        lineItem.cmbls__Type__c = 'Fee';
        update lineItem;
        
        System.assertEquals(1, [SELECT COUNT() FROM cmbls__Invoice__c WHERE Omit_From_FUNAS_Auto_Generation__c = TRUE AND Id = :lineItem.cmbls__Invoice__c]);
    }
    
    @IsTest static void dtos() {
        FunasDTO.FunasLineItem funasLineItem = new FunasDTO.FunasLineItem();
        funasLineItem.amount = 10;
        funasLineItem.balance   = 10;
        funasLineItem.asDate = 10;
        funasLineItem.interest = 10;
        funasLineItem.lineNumber = 10;
        funasLineItem.lineType = 10;
        funasLineItem.paymentAmount = 10;
        funasLineItem.principal = 10;
        funasLineItem.rate = 10;
        funasLineItem.settled = 10;

        FunasCallableAdapter fca = FunasCallableAdapter.getController();
        fca.call('calculate', new Map<String, Object>{});
        fca.call('calculate', new Account());
    }
}